
create index CECRED.TBCC_GRUPO_ECONOMICO_IX1 on CECRED.TBCC_GRUPO_ECONOMICO (CDCOOPER, NRDCONTA);
 
create index CECRED.TBCC_GRUPO_ECONOMICO_INTEG_IX2 on CECRED.TBCC_GRUPO_ECONOMICO (NRDCONTA, DTEXCLUSAO, CDCOOPER);

create index CECRED.TBCC_GRUPO_ECONOMICO_INTEG_IX3 on CECRED.TBCC_GRUPO_ECONOMICO (CDCOOPER, DTEXCLUSAO, IDGRUPO);