BEGIN
  	INSERT INTO CECRED.MENUMOBILE (MENUMOBILEID, MENUPAIID, NOME, SEQUENCIA, HABILITADO, AUTORIZACAO, VERSAOMINIMAAPP, VERSAOMAXIMAAPP)
	VALUES (1051, 1021, 'Limites Pix para Empresas', 1, 1, 1, '2.55.0', NULL);
COMMIT;
END;