BEGIN
  FOR RW_CONTAS IN (SELECT
            DISTINCT
            L.IDLIMITE_COOPERADO,
            L.IDTIPO_LIMITE,
            L.IDPERIODO,
            CASE
              WHEN L.IDPERIODO = 1
              THEN C.VLLIMTED
              WHEN L.IDPERIODO = 2
              THEN 1000
            END AS VLLIMITE
            FROM CECRED.CRAPSNH C
            INNER JOIN PIX.TBPIX_LIMITE_COOPERADO L ON 
                L.CDCOOPER = C.CDCOOPER AND L.NRDCONTA = C.NRDCONTA AND L.IDSEQTTL = C.IDSEQTTL
            WHERE L.IDTIPO_LIMITE = 4 AND L.VLLIMITE = 0
            AND C.TPDSENHA = 1 AND C.CDSITSNH = 1) LOOP  
  
    UPDATE PIX.TBPIX_LIMITE_COOPERADO SET VLLIMITE = RW_CONTAS.VLLIMITE WHERE IDLIMITE_COOPERADO = RW_CONTAS.IDLIMITE_COOPERADO
    AND VLLIMITE = 0;
   
    COMMIT;  
  END LOOP;
END;
