BEGIN		
	UPDATE CRAPACA
	   SET LSTPARAM = LSTPARAM || ', pr_cdbloqueio_origem'
	 WHERE NMPROCED = 'CREDITO.alterarBloqueioDebito'
	   AND NMDEACAO = 'ALTERA_BLOQ_DEBITO_OP_CREDITO';
	 
    COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
END;
/
