BEGIN    
  UPDATE CRAPACA
     SET LSTPARAM = LSTPARAM || ', pr_cdoperad'
   WHERE NMPROCED = 'CREDITO.obterBloqueioDebito'
     AND NMDEACAO = 'CONSULTA_BLOQ_DEBITO_OP_CREDITO';
   
    COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
END;
/
