BEGIN

  declare

  vr_nrctrcrd crawcrd.nrctrcrd%TYPE;
  vr_nrseqcrd crawcrd.nrseqcrd%TYPE;

  begin
  
   vr_nrctrcrd := fn_sequence('CRAPMAT','NRCTRCRD', 2);
   vr_nrseqcrd := CCRD0003.fn_sequence_nrseqcrd(2);

   insert into cecred.crawcrd
    (nrdconta,
    nrcrcard,
    nrcctitg,
    nrcpftit,
    vllimcrd,
    flgctitg,
    dtmvtolt,
    nmextttl,
    flgprcrd,
    tpdpagto,
    flgdebcc,
    tpenvcrd,
    vlsalari,
    dddebito,
    cdlimcrd,
    tpcartao,
    dtnasccr,
    nrdoccrd,
    nmtitcrd,
    nrctrcrd,
    cdadmcrd,
    cdcooper,
    nrseqcrd,
    dtpropos,
    dtsolici,
    flgdebit,
    cdgraupr,
    insitcrd,
    dtlibera,
    insitdec)
  values  (851477,       
    '5156010078140134',   
    7563239498641,    
    06042206931,     
    10000,      
    3,        
    trunc(sysdate),   
    'LUANA DE ESPINDOLA',  
    1,      
    3,    
    0,   
    1,   
    1,    
    22,    
    44,     
    2,    
    to_date('26/01/1988','dd/mm/yyyy'),
    '04812291312',     
    'LUANA DE ESPINDOLA',   
    vr_nrctrcrd,   
    13,      
    2,      
    vr_nrseqcrd,     
    to_date('29/08/2023','dd/mm/rrrr'), 
    to_date('29/08/2023','dd/mm/rrrr'), 
    1,         
    5,       
    6,       
    null,   
    8     
    );

   insert into cecred.crapcrd
    (cdcooper,
    nrdconta,
    nrcrcard,
    nrcpftit,
    nmtitcrd,
    dddebito,
    cdlimcrd,
    dtvalida,
    nrctrcrd,
    cdmotivo,
    nrprotoc,
    cdadmcrd,
    tpcartao,
    dtcancel,
    flgdebit,
    flgprovi)
  values  (2,     
    851477,       
    '5156010078140134',  
    06042206931,    
    'LUANA DE ESPINDOLA', 
    22,      
    44,     
    NULL,    
    vr_nrctrcrd,   
    0,  
    0,       
    13,     
    2,     
    NULL,  
    1,   
    0      
    );

   vr_nrctrcrd := fn_sequence('CRAPMAT','NRCTRCRD', 2);
   vr_nrseqcrd := CCRD0003.fn_sequence_nrseqcrd(2);

   insert into cecred.crawcrd
    (nrdconta,
    nrcrcard,
    nrcctitg,
    nrcpftit,
    vllimcrd,
    flgctitg,
    dtmvtolt,
    nmextttl,
    flgprcrd,
    tpdpagto,
    flgdebcc,
    tpenvcrd,
    vlsalari,
    dddebito,
    cdlimcrd,
    tpcartao,
    dtnasccr,
    nrdoccrd,
    nmtitcrd,
    nrctrcrd,
    cdadmcrd,
    cdcooper,
    nrseqcrd,
    dtpropos,
    dtsolici,
    flgdebit,
    cdgraupr,
    insitcrd,
    dtlibera,
    insitdec)
  values  (13860003,       
    '5474080307800928',   
    7563239864798,    
    63244047904,     
    10000,      
    3,        
    trunc(sysdate),   
    'ELIANE AP DE ABREU',  
    1,      
    3,    
    0,   
    0,   
    2375,    
    19,    
    44,     
    2,    
    to_date('24/12/1966','dd/mm/yyyy'),
    '41049855',     
    'ELIANE AP DE ABREU',   
    vr_nrctrcrd,   
    15,      
    1,      
    vr_nrseqcrd,     
    to_date('29/08/2023','dd/mm/rrrr'), 
    to_date('29/08/2023','dd/mm/rrrr'), 
    1,         
    5,       
    3,       
    null,   
    1     
    );

   insert into cecred.crapcrd
    (cdcooper,
    nrdconta,
    nrcrcard,
    nrcpftit,
    nmtitcrd,
    dddebito,
    cdlimcrd,
    dtvalida,
    nrctrcrd,
    cdmotivo,
    nrprotoc,
    cdadmcrd,
    tpcartao,
    dtcancel,
    flgdebit,
    flgprovi)
  values  (1,     
    13860003,       
    '5474080307800928',  
    63244047904,    
    'ELIANE AP DE ABREU', 
    19,      
    44,     
    NULL,    
    vr_nrctrcrd,   
    0,  
    0,       
    15,     
    2,     
    NULL,  
    1,   
    0      
    );

   commit;    

  end;

END;
