CREATE OR REPLACE TRIGGER CECRED.TRG_CC_PREJUIZO_ID
  BEFORE INSERT
  ON TBCC_PREJUIZO
  FOR EACH ROW
  BEGIN
    SELECT CECRED.SEQ_CC_PREJUIZO_ID.NEXTVAL
    INTO :NEW.idprejuizo
    FROM DUAL;

    EXCEPTION WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20100,'ERRO GERACAO SEQ_CC_PREJUIZO_ID!');
  END;
