DECLARE
BEGIN
INSERT INTO TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
VALUES ('INSITIMOVEL', '8', 'Efetivado sem registro');
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    RAISE_application_error(-20500, SQLERRM);
    ROLLBACK;
END;
