BEGIN
  UPDATE CECRED.TBEPR_CDC_USUARIO_VINCULO SET IDCOOPERADO_CDC = 31002 WHERE IDCOOPERADO_CDC = 18011 AND IDUSUARIO IN (17602, 17603);
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
END;