BEGIN

UPDATE TBGEN_NOTIF_MANUAL_PRM
SET CDSITUACAO_MENSAGEM = 3
WHERE CDMENSAGEM IN (SELECT CDMENSAGEM FROM tbgen_notif_msg_cadastro
WHERE DSTITULO_MENSAGEM = 'Vai viajar nas férias?')
AND CDSITUACAO_MENSAGEM = 1;



COMMIT;



END;                        
