begin

UPDATE	crapprm p
SET	p.DSVLRPRM	= '14/12/2021#2'
WHERE	p.CDACESSO	IN
	('CTRL_CRPS663_EXEC',
	'CTRL_CRPS688_EXEC',
	'CTRL_DEBBAN_EXEC',
	'CTRL_DEBNET_EXEC',
	'CTRL_DEBNET_PRIORI_EXEC',
	'CTRL_DEBSIC_EXEC',
	'CTRL_DEBSIC_PRIORI_EXEC',
	'CTRL_DEBUNITAR_EXEC',
	'CTRL_JOBAGERCEL_EXEC',
	'CTRL_CRPS674_EXEC')
AND	p.cdcooper	= 1;

commit;

end;