begin

insert into tbcred_pronampe_retremessa (NRREMESSA, NRREGISTRO, TPREGISTRO, CDRETORNO, DTPROCESSAMENTO, IDCONTRATO, VLFINANCIADO, DTRECUPERACAO, VLRECUPERADO, DTCANCELAMENTO, DTDEVOLUCAO, CDPENDENCIAOP, CDSITUACAOOP, DTULTSALDOOP, DTVENCIMENTOOP, DTINIPENDENCIAOP, CDENCERRAMENTOOP, DTENCERRAMENTOOP, CDIMPUGNACAOOP, DTIMPUGNACAOOP, CDMOVIMENTACAOFI, DTMOVIMENTACAOFI, DTFATOGERADORFI, VLNOMIFATOGERFI, VLATUALMONETARFI, VLISSQNFI, VLLIQUIDOMOVFI, NRCAUSADORMOVFI)
values (70, 41, '03', '0', to_date('14-12-2021 11:28:00', 'dd-mm-yyyy hh24:mi:ss'), 3790885, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into tbcred_pronampe_retremessa (NRREMESSA, NRREGISTRO, TPREGISTRO, CDRETORNO, DTPROCESSAMENTO, IDCONTRATO, VLFINANCIADO, DTRECUPERACAO, VLRECUPERADO, DTCANCELAMENTO, DTDEVOLUCAO, CDPENDENCIAOP, CDSITUACAOOP, DTULTSALDOOP, DTVENCIMENTOOP, DTINIPENDENCIAOP, CDENCERRAMENTOOP, DTENCERRAMENTOOP, CDIMPUGNACAOOP, DTIMPUGNACAOOP, CDMOVIMENTACAOFI, DTMOVIMENTACAOFI, DTFATOGERADORFI, VLNOMIFATOGERFI, VLATUALMONETARFI, VLISSQNFI, VLLIQUIDOMOVFI, NRCAUSADORMOVFI)
values (70, 42, '03', '0', to_date('14-12-2021 11:28:00', 'dd-mm-yyyy hh24:mi:ss'), 3790886, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into tbcred_pronampe_retremessa (NRREMESSA, NRREGISTRO, TPREGISTRO, CDRETORNO, DTPROCESSAMENTO, IDCONTRATO, VLFINANCIADO, DTRECUPERACAO, VLRECUPERADO, DTCANCELAMENTO, DTDEVOLUCAO, CDPENDENCIAOP, CDSITUACAOOP, DTULTSALDOOP, DTVENCIMENTOOP, DTINIPENDENCIAOP, CDENCERRAMENTOOP, DTENCERRAMENTOOP, CDIMPUGNACAOOP, DTIMPUGNACAOOP, CDMOVIMENTACAOFI, DTMOVIMENTACAOFI, DTFATOGERADORFI, VLNOMIFATOGERFI, VLATUALMONETARFI, VLISSQNFI, VLLIQUIDOMOVFI, NRCAUSADORMOVFI)
values (70, 43, '03', '100', to_date('14-12-2021 11:28:00', 'dd-mm-yyyy hh24:mi:ss'), 3790887, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into tbcred_pronampe_retremessa (NRREMESSA, NRREGISTRO, TPREGISTRO, CDRETORNO, DTPROCESSAMENTO, IDCONTRATO, VLFINANCIADO, DTRECUPERACAO, VLRECUPERADO, DTCANCELAMENTO, DTDEVOLUCAO, CDPENDENCIAOP, CDSITUACAOOP, DTULTSALDOOP, DTVENCIMENTOOP, DTINIPENDENCIAOP, CDENCERRAMENTOOP, DTENCERRAMENTOOP, CDIMPUGNACAOOP, DTIMPUGNACAOOP, CDMOVIMENTACAOFI, DTMOVIMENTACAOFI, DTFATOGERADORFI, VLNOMIFATOGERFI, VLATUALMONETARFI, VLISSQNFI, VLLIQUIDOMOVFI, NRCAUSADORMOVFI)
values (70, 44, '03', '110', to_date('14-12-2021 11:28:00', 'dd-mm-yyyy hh24:mi:ss'), 3790888, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into tbcred_pronampe_retremessa (NRREMESSA, NRREGISTRO, TPREGISTRO, CDRETORNO, DTPROCESSAMENTO, IDCONTRATO, VLFINANCIADO, DTRECUPERACAO, VLRECUPERADO, DTCANCELAMENTO, DTDEVOLUCAO, CDPENDENCIAOP, CDSITUACAOOP, DTULTSALDOOP, DTVENCIMENTOOP, DTINIPENDENCIAOP, CDENCERRAMENTOOP, DTENCERRAMENTOOP, CDIMPUGNACAOOP, DTIMPUGNACAOOP, CDMOVIMENTACAOFI, DTMOVIMENTACAOFI, DTFATOGERADORFI, VLNOMIFATOGERFI, VLATUALMONETARFI, VLISSQNFI, VLLIQUIDOMOVFI, NRCAUSADORMOVFI)
values (70, 45, '03', '158', to_date('14-12-2021 11:28:00', 'dd-mm-yyyy hh24:mi:ss'), 3790889, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into tbcred_pronampe_retremessa (NRREMESSA, NRREGISTRO, TPREGISTRO, CDRETORNO, DTPROCESSAMENTO, IDCONTRATO, VLFINANCIADO, DTRECUPERACAO, VLRECUPERADO, DTCANCELAMENTO, DTDEVOLUCAO, CDPENDENCIAOP, CDSITUACAOOP, DTULTSALDOOP, DTVENCIMENTOOP, DTINIPENDENCIAOP, CDENCERRAMENTOOP, DTENCERRAMENTOOP, CDIMPUGNACAOOP, DTIMPUGNACAOOP, CDMOVIMENTACAOFI, DTMOVIMENTACAOFI, DTFATOGERADORFI, VLNOMIFATOGERFI, VLATUALMONETARFI, VLISSQNFI, VLLIQUIDOMOVFI, NRCAUSADORMOVFI)
values (70, 46, '03', '245', to_date('14-12-2021 11:28:00', 'dd-mm-yyyy hh24:mi:ss'), 3790890, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

commit;
end;
