BEGIN

DELETE FROM TBINSS_AGENDAMENTO_GPS GPS WHERE INSITUACAO = 0 AND DTDEBITO >= '14/01/2022' AND DTDEBITO < '18/01/2022';

DELETE FROM CRAPLAU WHERE DTMVTOPG >= '14/01/2022' AND DTMVTOPG < '18/01/2022' AND CDHISTOR = 540 and INSITLAU = 1;

DELETE FROM CRAPLGP WHERE ROWID IN (
 SELECT LGP.ROWID
  FROM TBINSS_AGENDAMENTO_GPS GPS 
 INNER JOIN CRAPLAU LAU ON LAU.CDCOOPER = GPS.CDCOOPER AND LAU.NRDCONTA = GPS.NRDCONTA AND LAU.NRSEQAGP = GPS.NRSEQAGP
 INNER JOIN CRAPLGP LGP ON LGP.CDCOOPER = GPS.CDCOOPER AND LGP.NRCTAPAG = GPS.NRDCONTA AND LGP.NRDOLOTE = 11900 AND LGP.NRSEQDIG = LAU.NRDOCMTO AND LGP.NRSEQAGP = GPS.NRSEQAGP
 WHERE GPS.INSITUACAO = 0 AND GPS.DTDEBITO >= '14/01/2022' AND GPS.DTDEBITO < '18/01/2022');

commit;
END;
