insert into menumobile (MENUMOBILEID, MENUPAIID, NOME, SEQUENCIA, HABILITADO, AUTORIZACAO, VERSAOMINIMAAPP, VERSAOMAXIMAAPP)
values (1026, 30, 'Seguros', 1, 1, 1, '2.38.0', null);
COMMIT;

insert into menumobile (MENUMOBILEID, MENUPAIID, NOME, SEQUENCIA, HABILITADO, AUTORIZACAO, VERSAOMINIMAAPP, VERSAOMAXIMAAPP)
values (1027, 1026, 'Fazer uma simulação', 1, 1, 1, '2.38.0', null);
COMMIT;

insert into menumobile (MENUMOBILEID, MENUPAIID, NOME, SEQUENCIA, HABILITADO, AUTORIZACAO, VERSAOMINIMAAPP, VERSAOMAXIMAAPP)
values (1028, 1027, 'Seguro Residencial', 1, 1, 1, '2.38.0', null);
COMMIT;

insert into menumobile (MENUMOBILEID, MENUPAIID, NOME, SEQUENCIA, HABILITADO, AUTORIZACAO, VERSAOMINIMAAPP, VERSAOMAXIMAAPP)
values (1034, 1026, 'Canais de contato', 1, 1, 1, '2.38.0', null);
COMMIT;
