BEGIN
  DELETE CECRED.CRAPDIR WHERE CDCOOPER = 11 AND DTMVTOLT > TO_DATE('01/12/2023','DD/MM/YYYY');
  DELETE CECRED.CRAPSDA WHERE CDCOOPER = 11 AND DTMVTOLT >= TO_DATE('29/12/2023','DD/MM/YYYY');
  DELETE TBGEN_BATCH_PARALELO WHERE CDCOOPER = 11 AND CDPROGRA = 'CRPS001' AND DTMVTOLT = TO_DATE('29/12/2023','DD/MM/YYYY');
  DELETE CECRED.CRAPNEG WHERE CDCOOPER = 11;

  COMMIT;
END;