-- US591909 - Script para modificar CPF, CNPJ, Data Nascimento e número da conta
UPDATE AUTORIZADOR.PROPOSTA_CLIENTE pc 
	SET pc.CONTA_DEBITO = TRUNC(TO_NUMBER(DBMS_RANDOM.VALUE * POWER(9,9)))

UPDATE FOUNDATION.PESSOA p 
	SET P.DOCUMENTO = TRUNC(TO_NUMBER(DBMS_RANDOM.VALUE * POWER(14,10))),
        P.DATA_NASCIMENTO = (P.DATA_NASCIMENTO + TRUNC(TO_NUMBER(DBMS_RANDOM.VALUE * POWER(2,5)))