BEGIN

  UPDATE CECRED.TBCRD_FATURA
     SET INSITUACAO = 4
   WHERE CDCOOPER = 1
     AND NRDCONTA = 6738583
     AND INSITUACAO = 1;

  DELETE CECRED.TBCRD_CONTA_CARTAO
   WHERE ROWID = 'AAATD9ABWAACg0LABO';

  UPDATE CECRED.CRAWCRD
     SET NRCCTITG = 0
   WHERE ROWID = 'AA9ojCAIRAAH2goAAV';

  DELETE CECRED.TBCRD_CONTA_CARTAO
   WHERE ROWID = 'AAATD9ABVAAEY/YADd';

  UPDATE CECRED.CRAWCRD
     SET NRCCTITG = 0
   WHERE ROWID = 'AA9ojCAIOAAMWKRAAl';

  UPDATE CECRED.CRAWCRD
     SET NRCCTITG = 0
   WHERE ROWID = 'AA9ojCAIPAAOLOcAAg';

  DELETE CECRED.TBCRD_CONTA_CARTAO
   WHERE ROWID = 'AAATD9ABUAACI0iACH';

  DELETE CECRED.TBCRD_CONTA_CARTAO
   WHERE ROWID = 'AAATD9ABVAAEY9/ADE';

  UPDATE CECRED.CRAWCRD
     SET NRCCTITG = 0
   WHERE ROWID = 'AA9ojCAINAAM4GvAAc';

  DELETE CECRED.TBCRD_CONTA_CARTAO
   WHERE ROWID = 'AAATD9ABTAAEjMBABl';

  DELETE CECRED.TBCRD_CONTA_CARTAO
   WHERE ROWID = 'AAATD9ABTAAEjMBABp';

  DELETE CECRED.TBCRD_CONTA_CARTAO
   WHERE ROWID = 'AAATD9ABTAAEjMBABq';

  DELETE CECRED.TBCRD_CONTA_CARTAO
   WHERE ROWID = 'AAATD9ABTAAEjMBACI';

  DELETE CECRED.TBCRD_CONTA_CARTAO
   WHERE ROWID = 'AAATD9ABTAAEjJIADy';

  DELETE CECRED.TBCRD_CONTA_CARTAO
   WHERE ROWID = 'AAATD9ABWAABZxGABY';

  DELETE CECRED.TBCRD_CONTA_CARTAO
   WHERE ROWID = 'AAATD9ABVAAAX/DABI';

  DELETE CECRED.TBCRD_LIMITE_ATUALIZA
   WHERE ROWID = 'AACMtDABVAAFlgpABz';
   
  DELETE CECRED.TBCRD_LIMITE_ATUALIZA
   WHERE ROWID = 'AACMtDABWAAAtI8ABy';

  DELETE CECRED.TBCRD_CONTA_CARTAO
   WHERE ROWID = 'AAATD9ABWAAAMdwAE6';

  UPDATE CECRED.CRAWCRD
     SET NRCCTITG = 0
   WHERE ROWID = 'AA9ojCAILAALNCOAAW';

  COMMIT;

END;
