BEGIN

    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('01', '01', 'duplicatas');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('01', '02', 'cheques');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('01', '03', 'fat. cartão cred.');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('01', '04', 'apl. renda fixa');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('01', '05', 'apl. renda var.');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('01', '06', 'ações e debêntures');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('01', '07', 'tributos e rec. orc.');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('01', '08', 'dir. alugueis');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('01', '99', 'notas promissórias');

    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('02', '01', 'duplicatas');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('02', '02', 'cheques');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('02', '03', 'fat. cartão cred.');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('02', '04', 'apl. renda fixa');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('02', '05', 'apl. renda var.');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('02', '06', 'ações e debêntures');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('02', '07', 'tributos e rec. orc.');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('02', '08', 'dir. alugueis');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('02', '09', 'dep. Titulos');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('02', '10', 'depositos');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('02', '99', 'notas promissórias');

    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('03', '21', 'prod. Agro c/ warrant');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('03', '22', 'prod. Agro s/ warrant');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('03', '23', 'equipamentos');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('03', '24', 'veículos');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('03', '25', 'imóveis');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('03', '50', 'civil');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('03', '99', 'outros');

    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('04', '23', 'equipamentos');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('04', '24', 'veículos');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('04', '26', 'imóveis residenciais');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('04', '27', 'outros imóveis');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('04', '28', 'bens e direitos');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('04', '99', 'outros');

    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('05', '62', 'outros graus');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('05', '63', 'primeiro grau - imóveis res.');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('05', '64', 'primeiro grau - outros');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('05', '65', 'Primeiro Grau - bens e direitos');

    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('06', '71', 'federal');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('06', '72', 'estadual ou distrital ');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('06', '73', 'municipal');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('06', '74', 'garantia prestadaTN / BC');

    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('07', '99', 'outras');

    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('08', '81', 'seguro rural');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('08', '82', 'Proagro');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('08', '83', 'SBCE');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('08', '84', 'FCVS');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('08', '85', 'apólices de créd. a exp.');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('08', '86', 'fundo garantidor / de aval');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('08', '87', 'CCR');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('08', '88', 'FGPC');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('08', '89', 'FGTS');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('08', '90', 'FGI');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('08', '99', 'outros seguros e assemelhados');

    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('09', '01', 'pessoa física');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('09', '02', 'pessoa jurídica');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('09', '03', 'pessoa física no exterior');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('09', '04', 'pessoa jurídica no exterior');

    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('10', '01', 'Veículos automotores');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('10', '02', 'Outros bens');

    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('11', '01', 'Mitigadoras');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('11', '02', 'Não Mitigadoras');

    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('12', '01', 'Entidades Multilaterais de Desenvolvimento');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('12', '02', 'garantia fundos');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('12', '03', 'garantia FGPC');
    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('12', '04', 'garantia fundos');

    INSERT INTO CREDITO.TBCRED_BNDES_ANEXO (CDDOMINIO, CDSUB_DOMINIO, DSANEXO) VALUES ('13', '01', 'acordos');

    COMMIT;

END;