BEGIN

INSERT INTO CECRED.CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR)
VALUES ('BUSCA_CONTRATOS_PRESTAMISTA_PJ', 'SEGU0004', 'PC_BUSCA_CONTRATOS_PJ', 'pr_nrdconta,pr_nrctremp,pr_nrregist,pr_nriniseq',(SELECT NRSEQRDR FROM CECRED.CRAPRDR WHERE NMPROGRA = 'SEGU0004'));

COMMIT;
END;
