BEGIN

INSERT INTO CECRED.CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR)
VALUES ('CALCULAR_SEGURO_PRESTAMISTA_PJ', 'SEGU0004', 'PC_CALCULAR_SEGURO_PRESTAMISTA_PJ', 'pr_cdcooper,pr_nmsocio,pr_dtnascsoc',(SELECT NRSEQRDR FROM CECRED.CRAPRDR WHERE NMPROGRA = 'SEGU0004'));

COMMIT;
END;
