DECLARE
BEGIN

	INSERT INTO CREDITO.TBCRED_REPASSADOR_PRODUTO
		(CDPRODUTO_REPASSE
		,IDREPASSADOR_CREDITO
		,NMPRODUTO_REPASSE)
	VALUES
		(22500
		,(SELECT IDREPASSADOR_CREDITO
			 FROM CREDITO.TBCRED_REPASSADOR_CREDITO
			WHERE NMREPASSADOR = 'BNDES')
		,'FINAME');

	INSERT INTO CREDITO.TBCRED_REPASSADOR_SUBPRODUTO
		(IDREPASSADOR_PRODUTO
		,DSLINHA_REPASSE
		,CDCONDICAO_OPERACIONAL
		,DSCONDICAO_OPERACIONAL)
	VALUES
		((SELECT IDREPASSADOR_PRODUTO
			 FROM CREDITO.TBCRED_REPASSADOR_PRODUTO
			WHERE NMPRODUTO_REPASSE = 'FINAME')
		,'BK Aquisição e Comercialização'
		,393
		,'PO2020/01');

	INSERT INTO CREDITO.TBCRED_REPASSADOR_SUBPRODUTO
		(IDREPASSADOR_PRODUTO
		,DSLINHA_REPASSE
		,CDCONDICAO_OPERACIONAL
		,DSCONDICAO_OPERACIONAL)
	VALUES
		((SELECT IDREPASSADOR_PRODUTO
			 FROM CREDITO.TBCRED_REPASSADOR_PRODUTO
			WHERE NMPRODUTO_REPASSE = 'FINAME')
		,'Máquinas 4.0'
		,393
		,'PO2020/01');

	INSERT INTO CREDITO.TBCRED_REPASSADOR_SUBPRODUTO
		(IDREPASSADOR_PRODUTO
		,DSLINHA_REPASSE
		,CDCONDICAO_OPERACIONAL
		,DSCONDICAO_OPERACIONAL)
	VALUES
		((SELECT IDREPASSADOR_PRODUTO
			 FROM CREDITO.TBCRED_REPASSADOR_PRODUTO
			WHERE NMPRODUTO_REPASSE = 'FINAME')
		,'Baixo Carbono'
		,393
		,'PO2020/01');

	COMMIT;

EXCEPTION
	WHEN OTHERS THEN
		RAISE_APPLICATION_ERROR(-25001, SQLERRM);
END;