/*
31/05/2019 - Controla o envio do arquivo de impressão de cheques para a gráfica - Renato Cordeiro - AMcom
*/
BEGIN

  EXECUTE IMMEDIATE 'ALTER SESSION SET 
  nls_calendar = ''GREGORIAN''
  nls_comp = ''BINARY''
  nls_date_format = ''DD-MON-RR''
  nls_date_language = ''AMERICAN''
  nls_iso_currency = ''AMERICA''
  nls_language = ''AMERICAN''
  nls_length_semantics = ''BYTE''
  nls_nchar_conv_excp = ''FALSE''
  nls_numeric_characters = ''.,''
  nls= ''BINARY''
  nls_territory = ''AMERICA''
  nls_time_format = ''HH.MI.SSXFF AM''
  nls_time_tz_format = ''HH.MI.SSXFF AM TZR''
  nls_timestamp_format = ''DD-MON-RR HH.MI.SSXFF AM''
  nls_timestamp_tz_format = ''DD-MON-RR HH.MI.SSXFF AM TZR'''; 
    
  sys.dbms_scheduler.create_job(
    job_name        => 'CECRED.JBCHQ_ENVIO_GRAFICA',
    job_type        => 'PLSQL_BLOCK',
    job_action      => 
'declare
   CURSOR cr_tbchq_seguranca_cheque IS
     SELECT distinct a.cdcooper cdcooper
       FROM tbchq_seguranca_cheque a
       WHERE a.idstatus_atualizacao_hsm = 2
         AND NOT EXISTS (SELECT 1 
                           FROM tbchq_seguranca_cheque b
                          WHERE b.idstatus_atualizacao_hsm = 0 OR b.idstatus_atualizacao_hsm = 1)
       ORDER BY a.cdcooper;

   vr_stprogra                 BINARY_INTEGER;
   vr_infimsol                 BINARY_INTEGER;
   vr_cdcritic                 crapcri.cdcritic%TYPE;
   vr_dscritic                 crapcri.dscritic%TYPE;
   
   rw_tbchq_seguranca_cheque   cr_tbchq_seguranca_cheque%ROWTYPE;
       
BEGIN
   OPEN cr_tbchq_seguranca_cheque;
   FETCH cr_tbchq_seguranca_cheque INTO rw_tbchq_seguranca_cheque;
   IF cr_tbchq_seguranca_cheque%FOUND THEN
      cheq0003.pc_gera_arq_grafica_cheque(pr_cdcooper => rw_tbchq_seguranca_cheque.cdcooper, 
                                          pr_flgresta => 0, 
                                          pr_stprogra => vr_stprogra, 
                                          pr_infimsol => vr_infimsol, 
                                          pr_cdcritic => vr_cdcritic, 
                                          pr_dscritic => vr_dscritic);
      -- executa o JOB
      IF nvl(vr_cdcritic,0) <> 0 or vr_dscritic IS NOT NULL THEN
         raise_application_error(-20001, vr_dscritic);
      END IF;

   ELSE
      -- controla re-execução mais á frente
      NULL;  
   
   END IF;
   
   CLOSE cr_tbchq_seguranca_cheque;
   
END;',
    start_date      => TO_TIMESTAMP_TZ(to_date('10/06/2019' ,'DD/MM/RRRR')||' 07:00 America/Sao_Paulo','DD/MM/RRRR HH24:MI TZR'),
    repeat_interval => 'Freq=DAILY;ByDay=Mon,Tue,Wed,Thu,Fri;BYHOUR=07, 08, 09, 10, 11, 12, 13, 14, 15, 16, 17;BYMINUTE=05;BYSECOND=0',
    end_date        => to_date(null),
    job_class       => 'DEFAULT_JOB_CLASS',
    enabled         => TRUE,
    auto_drop       => TRUE,
    comments        => 'Rodar rotina de envio de arquivo de impressão de cheques para a gráfica.'||
                       ' Esta execução complementa a execução prévia na diária do pc_crps408 e da atualização '||
                       ' do código de segurança via HSM (SOA/Dinamo)');

END;
/
