UPDATE TBCONSOR_SEGMENTO SET CDSEGMENTO = 1 WHERE ID = 1;
UPDATE TBCONSOR_SEGMENTO SET CDSEGMENTO = 2 WHERE ID = 2;
UPDATE TBCONSOR_SEGMENTO SET CDSEGMENTO = 3 WHERE ID = 3;
UPDATE TBCONSOR_SEGMENTO SET CDSEGMENTO = 8 WHERE ID = 4;
UPDATE TBCONSOR_SEGMENTO SET CDSEGMENTO = 5 WHERE ID = 5;
UPDATE TBCONSOR_SEGMENTO SET CDSEGMENTO = 6 WHERE ID = 6;
UPDATE TBCONSOR_SEGMENTO SET CDSEGMENTO = 7 WHERE ID = 7;
UPDATE TBCONSOR_SEGMENTO SET CDSEGMENTO = 4 WHERE ID = 8;
commit;
/