BEGIN
  UPDATE craptel 
  SET lsopptel = 'ACESSO,CONSULTA STATUS RECUP,ALTERAR CONTRATO,CONSULTAR REMESSA,CONSULTAR INF DIARIO,CANCELAMENTO CONTRATO,CONSULTAR STATUS CRED,LIB CRED/LIQUIDACAO'
  WHERE nmdatela = 'PRONAM';
  
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
END;
