BEGIN

DROP TRIGGER CREDITO.TBCRED_CARGA_PREAPROV_DET_IDREGISTRO;

DROP TRIGGER CREDITO.TBCRED_CARGA_PREAPROV_IDCARGA;

DROP TRIGGER CREDITO.TBCRED_PREAPROV_DET_IDREGISTRO;

DROP TRIGGER CREDITO.TBCRED_PREAPROV_LOG_IDLOG;

END;