declare

    conta_13582933_4605658 clob := '<?xml version="1.0"?>
<Root>
  <convenioCredito>
    <cooperativa>
      <codigo>1</codigo>
    </cooperativa>
    <numeroContrato>69</numeroContrato>
  </convenioCredito>
  <configuracaoCredito>
    <diasCarencia>45</diasCarencia>
    <financiaIOF>true</financiaIOF>
    <financiaTarifa>true</financiaTarifa>
  </configuracaoCredito>
  <propostaContratoCredito>
    <CETPercentAoAno>12.98</CETPercentAoAno>
    <dataPrimeiraParcela>2021-12-01</dataPrimeiraParcela>
    <produto>
      <codigo>162</codigo>
    </produto>
    <quantidadeParcelas>96</quantidadeParcelas>
    <taxaJurosRemuneratorios>1.01</taxaJurosRemuneratorios>
    <taxaJurosRemuneratoriosAnual>12.82</taxaJurosRemuneratoriosAnual>
    <tipoLiberacao>
      <codigo>6</codigo>
    </tipoLiberacao>
    <tipoLiquidacao>
      <codigo>4</codigo>
    </tipoLiquidacao>
    <tributoIOFValor>77.22</tributoIOFValor>
    <valor>15821.12</valor>
    <valorBase>15743.90</valorBase>
    <dataProposta>2021-11-05T08:16:16</dataProposta>
    <emitente>
      <dataNascOuConstituicao>1997-02-21T00:00:00</dataNascOuConstituicao>
      <identificadorReceitaFederal>9701846974</identificadorReceitaFederal>
      <razaoSocialOuNome>VANDIR DA SILVA</razaoSocialOuNome>
      <nacionalidade>
        <codigo>42</codigo>
      </nacionalidade>
      <tipo>
        <codigo>1</codigo>
      </tipo>
      <contaCorrente>
        <agencia>
          <codigo>101</codigo>
        </agencia>
        <banco>
          <codigo>85</codigo>
        </banco>
        <codigoConta>8079625</codigoConta>
        <cooperativa>
          <codigo>1</codigo>
        </cooperativa>
      </contaCorrente>
      <numeroTitularidade>1</numeroTitularidade>
      <pessoaContatoEndereco>
        <CEP>89135000</CEP>
        <cidade>
          <descricao>APIUNA</descricao>
        </cidade>
        <nomeBairro>RIBEIRAO CARVALHO</nomeBairro>
        <numeroLogradouro>4313</numeroLogradouro>
        <tipoEndereco>
          <codigo>13</codigo>
        </tipoEndereco>
        <tipoENomeLogradouro>RUA ESTRADA GERAL RI</tipoENomeLogradouro>
        <UF>SC</UF>
      </pessoaContatoEndereco>
    </emitente>
    <identificadorProposta>4366220</identificadorProposta>
    <statusProposta>
      <codigo>26</codigo>
    </statusProposta>
  </propostaContratoCredito>
  <pessoaDocumento>
    <identificador>6697806</identificador>
    <tipo>
      <sigla>CI</sigla>
    </tipo>
  </pessoaDocumento>
  <pessoaFisicaOcupacao>
    <naturezaOcupacao>
      <codigo>6</codigo>
    </naturezaOcupacao>
  </pessoaFisicaOcupacao>
  <pessoaFisicaDetalhamento>
    <estadoCivil>
      <codigo>4</codigo>
    </estadoCivil>
    <sexo>
      <codigo>1</codigo>
    </sexo>
  </pessoaFisicaDetalhamento>
  <pessoaFisicaRendimento>
    <identificadorRegistroFuncionario>0</identificadorRegistroFuncionario>
  </pessoaFisicaRendimento>
  <remuneracaoColaborador>
    <empregador>
      <identificadorReceitaFederal>79373767000116</identificadorReceitaFederal>
      <razaoSocialOuNome>PREFEITURA MUNIPAL DE APIUNA</razaoSocialOuNome>
    </empregador>
  </remuneracaoColaborador>
  <beneficio/>
  <listaPessoasEndereco>
    <pessoaEndereco>
      <parametroConsignado>
        <tipoPessoaEndereco>EMPREGADOR</tipoPessoaEndereco>
      </parametroConsignado>
      <pessoaContatoEndereco>
        <CEP>89135000</CEP>
        <cidade>
          <descricao>APIUNA</descricao>
        </cidade>
        <nomeBairro>CENTRO</nomeBairro>
        <numeroLogradouro>204</numeroLogradouro>
        <tipoENomeLogradouro>RUA QUINTINO BOCAIUVA</tipoENomeLogradouro>
        <UF>SC</UF>
      </pessoaContatoEndereco>
    </pessoaEndereco>
  </listaPessoasEndereco>
  <parcela>
    <valor>259.48</valor>
  </parcela>
  <tarifa>
    <valor>0.0</valor>
  </tarifa>
  <inadimplencia>
    <despesasCartorarias>0.0</despesasCartorarias>
  </inadimplencia>
  <posicao>
    <produtoCategoria>
      <codigo>32</codigo>
    </produtoCategoria>
    <saldo>13361.60</saldo>
  </posicao>
  <usuarioDominioCecred>
    <codigo/>
  </usuarioDominioCecred>
  <parametroConsignado>
    <codigoFisTabelaJuros>1</codigoFisTabelaJuros>
    <indicadorContaPrincipal>true</indicadorContaPrincipal>
    <naturalidade>RIO DO SUL</naturalidade>
    <dataCalculoLegado>2021-10-17T00:00:00</dataCalculoLegado>
  </parametroConsignado>
</Root>
';

conta_13582933_4605327 clob := '<?xml version="1.0" encoding="WINDOWS1252"?>
<Root>
	<convenioCredito>
		<cooperativa>
			<codigo>1</codigo>
		</cooperativa>
		<numeroContrato>6502</numeroContrato>
	</convenioCredito>
	<configuracaoCredito>
		<financiaIOF>false</financiaIOF>
		<financiaTarifa>false</financiaTarifa>
		<diasCarencia>41</diasCarencia>
	</configuracaoCredito>
	<propostaContratoCredito>
		<CETPercentAoAno>11.09</CETPercentAoAno>
		<dataPrimeiraParcela>20211201</dataPrimeiraParcela>
		<produto>
			<codigo>162</codigo>
		</produto>
		<quantidadeParcelas>111</quantidadeParcelas>
		<taxaJurosRemuneratorios>0.88</taxaJurosRemuneratorios>
		<taxaJurosRemuneratoriosAnual>11.09</taxaJurosRemuneratoriosAnual>
		<tipoLiberacao>
			<codigo>6</codigo>
		</tipoLiberacao>
		<tipoLiquidacao>
			<codigo>4</codigo>
		</tipoLiquidacao>
		<tributoIOFValor>0.0</tributoIOFValor>
		<valor>49146.78</valor>
		<valorBase>49146.78</valorBase>
		<dataProposta>2021-11-05T08:16:16</dataProposta>
		<emitente>
			<dataNascOuConstituicao>19760313T00:00:00</dataNascOuConstituicao>
			<identificadorReceitaFederal>1850874930</identificadorReceitaFederal>
			<razaoSocialOuNome>VILMA APARECIDA GOUVEA CAETANO</razaoSocialOuNome>
			<nacionalidade>
				<codigo>42</codigo>
			</nacionalidade>
			<tipo>
				<codigo>1</codigo>
			</tipo>
			<contaCorrente>
				<agencia>
					<codigo>101</codigo>
				</agencia>
				<banco>
					<codigo>85</codigo>
				</banco>
				<codigoConta>13582933</codigoConta>
				<cooperativa>
					<codigo>1</codigo>
				</cooperativa>
			</contaCorrente>
			<numeroTitularidade>1</numeroTitularidade>
			<pessoaContatoEndereco>
				<CEP>83323125</CEP>
				<cidade>
					<descricao>PINHAIS</descricao>
				</cidade>
				<nomeBairro>ESTANCIA PINHAIS</nomeBairro>
				<numeroLogradouro>12863</numeroLogradouro>
				<tipoEndereco>
					<codigo>13</codigo>
				</tipoEndereco>
				<tipoENomeLogradouro>RODOVIA JOAO LEOPOLD</tipoENomeLogradouro>
				<UF>PR</UF>
			</pessoaContatoEndereco>
		</emitente>
		<identificadorProposta>4605327</identificadorProposta>
		<statusProposta>
			<codigo>26</codigo>
		</statusProposta>
	</propostaContratoCredito>
	<pessoaDocumento>
		<identificador>63073547</identificador>
		<tipo>
			<sigla>CI</sigla>
		</tipo>
	</pessoaDocumento>
	<pessoaFisicaOcupacao>
		<naturezaOcupacao>
			<codigo>6</codigo>
		</naturezaOcupacao>
	</pessoaFisicaOcupacao>
	<pessoaFisicaDetalhamento>
		<estadoCivil>
			<codigo>4</codigo>
		</estadoCivil>
		<sexo>
			<codigo>2</codigo>
		</sexo>
	</pessoaFisicaDetalhamento>
	<pessoaFisicaRendimento>
		<identificadorRegistroFuncionario>1318800</identificadorRegistroFuncionario>
	</pessoaFisicaRendimento>
	<remuneracaoColaborador>
		<empregador>
			<identificadorReceitaFederal>95423000000100</identificadorReceitaFederal>
			<razaoSocialOuNome>MUNICIPIO DE PINHAIS</razaoSocialOuNome>
		</empregador>
	</remuneracaoColaborador>
	<beneficio/>
	<listaPessoasEndereco>
		<pessoaEndereco>
			<parametroConsignado>
				<tipoPessoaEndereco>EMPREGADOR</tipoPessoaEndereco>
			</parametroConsignado>
			<pessoaContatoEndereco>
				<CEP>83323400</CEP>
				<cidade>
					<descricao>PINHAIS</descricao>
				</cidade>
				<nomeBairro>CENTRO</nomeBairro>
				<numeroLogradouro>536</numeroLogradouro>
				<tipoENomeLogradouro>RUA WANDA DOS SANTOS MALLMANN</tipoENomeLogradouro>
				<UF>PR</UF>
			</pessoaContatoEndereco>
		</pessoaEndereco>
	</listaPessoasEndereco>
	<parcela>
		<valor>697.70</valor>
	</parcela>
	<tarifa>
		<valor>0.0</valor>
	</tarifa>
	<inadimplencia>
		<despesasCartorarias>0.0</despesasCartorarias>
	</inadimplencia>
	<posicao>
		<produtoCategoria>
			<codigo>32</codigo>
		</produtoCategoria>
		<saldo>49146.78</saldo>
	</posicao>
	<usuarioDominioCecred>
		<codigo/>
	</usuarioDominioCecred>
	<parametroConsignado>
		<codigoFisTabelaJuros>1</codigoFisTabelaJuros>
		<indicadorContaPrincipal>true</indicadorContaPrincipal>
		<naturalidade>CURITIBA</naturalidade>
		<dataCalculoLegado>20211021T00:00:00</dataCalculoLegado>
	</parametroConsignado>
</Root>';

conta_8060266_4604992 clob := '<?xml version="1.0" encoding="WINDOWS1252"?>
<Root>
	<convenioCredito>
		<cooperativa>
			<codigo>1</codigo>
		</cooperativa>
		<numeroContrato>8387</numeroContrato>
	</convenioCredito>
	<configuracaoCredito>
		<financiaIOF>false</financiaIOF>
		<financiaTarifa>false</financiaTarifa>
		<diasCarencia>44</diasCarencia>
	</configuracaoCredito>
	<propostaContratoCredito>
		<CETPercentAoAno>11.09</CETPercentAoAno>
		<dataPrimeiraParcela>20211205</dataPrimeiraParcela>
		<produto>
			<codigo>162</codigo>
		</produto>
		<quantidadeParcelas>81</quantidadeParcelas>
		<taxaJurosRemuneratorios>0.88</taxaJurosRemuneratorios>
		<taxaJurosRemuneratoriosAnual>11.09</taxaJurosRemuneratoriosAnual>
		<tipoLiberacao>
			<codigo>6</codigo>
		</tipoLiberacao>
		<tipoLiquidacao>
			<codigo>4</codigo>
		</tipoLiquidacao>
		<tributoIOFValor>0.0</tributoIOFValor>
		<valor>48489.32</valor>
		<valorBase>48489.32</valorBase>
		<dataProposta>2021-11-05T08:16:16</dataProposta>
		<emitente>
			<dataNascOuConstituicao>19840709T00:00:00</dataNascOuConstituicao>
			<identificadorReceitaFederal>4051652939</identificadorReceitaFederal>
			<razaoSocialOuNome>CARLA TATIANA RADUENZ GEISLER</razaoSocialOuNome>
			<nacionalidade>
				<codigo>42</codigo>
			</nacionalidade>
			<tipo>
				<codigo>1</codigo>
			</tipo>
			<contaCorrente>
				<agencia>
					<codigo>101</codigo>
				</agencia>
				<banco>
					<codigo>85</codigo>
				</banco>
				<codigoConta>8060266</codigoConta>
				<cooperativa>
					<codigo>1</codigo>
				</cooperativa>
			</contaCorrente>
			<numeroTitularidade>1</numeroTitularidade>
			<pessoaContatoEndereco>
				<CEP>89120000</CEP>
				<cidade>
					<descricao>TIMBO</descricao>
				</cidade>
				<nomeBairro>QUINTINO</nomeBairro>
				<numeroLogradouro>269</numeroLogradouro>
				<tipoEndereco>
					<codigo>13</codigo>
				</tipoEndereco>
				<tipoENomeLogradouro>RUA BOTUVERA</tipoENomeLogradouro>
				<UF>SC</UF>
			</pessoaContatoEndereco>
		</emitente>
		<identificadorProposta>4604992</identificadorProposta>
		<statusProposta>
			<codigo>26</codigo>
		</statusProposta>
	</propostaContratoCredito>
	<pessoaDocumento>
		<identificador>4527168</identificador>
		<tipo>
			<sigla>CI</sigla>
		</tipo>
	</pessoaDocumento>
	<pessoaFisicaOcupacao>
		<naturezaOcupacao>
			<codigo>6</codigo>
		</naturezaOcupacao>
	</pessoaFisicaOcupacao>
	<pessoaFisicaDetalhamento>
		<estadoCivil>
			<codigo>4</codigo>
		</estadoCivil>
		<sexo>
			<codigo>1</codigo>
		</sexo>
	</pessoaFisicaDetalhamento>
	<pessoaFisicaRendimento>
		<identificadorRegistroFuncionario>8060266</identificadorRegistroFuncionario>
	</pessoaFisicaRendimento>
	<remuneracaoColaborador>
		<empregador>
			<identificadorReceitaFederal>5278562000115</identificadorReceitaFederal>
			<razaoSocialOuNome>SERVICO AUTONOMO MUN ICIPAL DE AGUA</razaoSocialOuNome>
		</empregador>
	</remuneracaoColaborador>
	<beneficio/>
	<listaPessoasEndereco>
		<pessoaEndereco>
			<parametroConsignado>
				<tipoPessoaEndereco>EMPREGADOR</tipoPessoaEndereco>
			</parametroConsignado>
			<pessoaContatoEndereco>
				<CEP>89120000</CEP>
				<cidade>
					<descricao>TIMBO</descricao>
				</cidade>
				<nomeBairro>CENTRO</nomeBairro>
				<numeroLogradouro>56</numeroLogradouro>
				<tipoENomeLogradouro>R DUQUE DE CAXIAS</tipoENomeLogradouro>
				<UF>SC</UF>
			</pessoaContatoEndereco>
		</pessoaEndereco>
	</listaPessoasEndereco>
	<parcela>
		<valor>843.08</valor>
	</parcela>
	<tarifa>
		<valor>0.0</valor>
	</tarifa>
	<inadimplencia>
		<despesasCartorarias>0.0</despesasCartorarias>
	</inadimplencia>
	<posicao>
		<produtoCategoria>
			<codigo>32</codigo>
		</produtoCategoria>
		<saldo>48489.32</saldo>
	</posicao>
	<usuarioDominioCecred>
		<codigo/>
	</usuarioDominioCecred>
	<parametroConsignado>
		<codigoFisTabelaJuros>1</codigoFisTabelaJuros>
		<indicadorContaPrincipal>true</indicadorContaPrincipal>
		<naturalidade>POMERODE</naturalidade>
		<dataCalculoLegado>20211022T00:00:00</dataCalculoLegado>
	</parametroConsignado>
</Root>';

conta_8060266_4605029 clob := '<?xml version="1.0" encoding="WINDOWS1252"?>
<Root>
	<convenioCredito>
		<cooperativa>
			<codigo>1</codigo>
		</cooperativa>
		<numeroContrato>8387</numeroContrato>
	</convenioCredito>
	<configuracaoCredito>
		<financiaIOF>false</financiaIOF>
		<financiaTarifa>false</financiaTarifa>
		<diasCarencia>44</diasCarencia>
	</configuracaoCredito>
	<propostaContratoCredito>
		<CETPercentAoAno>11.09</CETPercentAoAno>
		<dataPrimeiraParcela>20211205</dataPrimeiraParcela>
		<produto>
			<codigo>162</codigo>
		</produto>
		<quantidadeParcelas>80</quantidadeParcelas>
		<taxaJurosRemuneratorios>0.88</taxaJurosRemuneratorios>
		<taxaJurosRemuneratoriosAnual>11.09</taxaJurosRemuneratoriosAnual>
		<tipoLiberacao>
			<codigo>6</codigo>
		</tipoLiberacao>
		<tipoLiquidacao>
			<codigo>4</codigo>
		</tipoLiquidacao>
		<tributoIOFValor>0.0</tributoIOFValor>
		<valor>36433.52</valor>
		<valorBase>36433.52</valorBase>
		<dataProposta>2021-11-05T08:16:16</dataProposta>
		<emitente>
			<dataNascOuConstituicao>19840709T00:00:00</dataNascOuConstituicao>
			<identificadorReceitaFederal>4051652939</identificadorReceitaFederal>
			<razaoSocialOuNome>CARLA TATIANA RADUENZ GEISLER</razaoSocialOuNome>
			<nacionalidade>
				<codigo>42</codigo>
			</nacionalidade>
			<tipo>
				<codigo>1</codigo>
			</tipo>
			<contaCorrente>
				<agencia>
					<codigo>101</codigo>
				</agencia>
				<banco>
					<codigo>85</codigo>
				</banco>
				<codigoConta>8060266</codigoConta>
				<cooperativa>
					<codigo>1</codigo>
				</cooperativa>
			</contaCorrente>
			<numeroTitularidade>1</numeroTitularidade>
			<pessoaContatoEndereco>
				<CEP>89120000</CEP>
				<cidade>
					<descricao>TIMBO</descricao>
				</cidade>
				<nomeBairro>QUINTINO</nomeBairro>
				<numeroLogradouro>269</numeroLogradouro>
				<tipoEndereco>
					<codigo>13</codigo>
				</tipoEndereco>
				<tipoENomeLogradouro>RUA BOTUVERA</tipoENomeLogradouro>
				<UF>SC</UF>
			</pessoaContatoEndereco>
		</emitente>
		<identificadorProposta>4605029</identificadorProposta>
		<statusProposta>
			<codigo>26</codigo>
		</statusProposta>
	</propostaContratoCredito>
	<pessoaDocumento>
		<identificador>4527168</identificador>
		<tipo>
			<sigla>CI</sigla>
		</tipo>
	</pessoaDocumento>
	<pessoaFisicaOcupacao>
		<naturezaOcupacao>
			<codigo>6</codigo>
		</naturezaOcupacao>
	</pessoaFisicaOcupacao>
	<pessoaFisicaDetalhamento>
		<estadoCivil>
			<codigo>4</codigo>
		</estadoCivil>
		<sexo>
			<codigo>1</codigo>
		</sexo>
	</pessoaFisicaDetalhamento>
	<pessoaFisicaRendimento>
		<identificadorRegistroFuncionario>8060266</identificadorRegistroFuncionario>
	</pessoaFisicaRendimento>
	<remuneracaoColaborador>
		<empregador>
			<identificadorReceitaFederal>5278562000115</identificadorReceitaFederal>
			<razaoSocialOuNome>SERVICO AUTONOMO MUN ICIPAL DE AGUA</razaoSocialOuNome>
		</empregador>
	</remuneracaoColaborador>
	<beneficio/>
	<listaPessoasEndereco>
		<pessoaEndereco>
			<parametroConsignado>
				<tipoPessoaEndereco>EMPREGADOR</tipoPessoaEndereco>
			</parametroConsignado>
			<pessoaContatoEndereco>
				<CEP>89120000</CEP>
				<cidade>
					<descricao>TIMBO</descricao>
				</cidade>
				<nomeBairro>CENTRO</nomeBairro>
				<numeroLogradouro>56</numeroLogradouro>
				<tipoENomeLogradouro>R DUQUE DE CAXIAS</tipoENomeLogradouro>
				<UF>SC</UF>
			</pessoaContatoEndereco>
		</pessoaEndereco>
	</listaPessoasEndereco>
	<parcela>
		<valor>638.91</valor>
	</parcela>
	<tarifa>
		<valor>0.0</valor>
	</tarifa>
	<inadimplencia>
		<despesasCartorarias>0.0</despesasCartorarias>
	</inadimplencia>
	<posicao>
		<produtoCategoria>
			<codigo>32</codigo>
		</produtoCategoria>
		<saldo>36433.52</saldo>
	</posicao>
	<usuarioDominioCecred>
		<codigo/>
	</usuarioDominioCecred>
	<parametroConsignado>
		<codigoFisTabelaJuros>1</codigoFisTabelaJuros>
		<indicadorContaPrincipal>true</indicadorContaPrincipal>
		<naturalidade>POMERODE</naturalidade>
		<dataCalculoLegado>20211022T00:00:00</dataCalculoLegado>
	</parametroConsignado>
</Root>';

conta_13584715_4606375 clob := '<?xml version="1.0" encoding="WINDOWS1252"?>
<Root>
	<convenioCredito>
		<cooperativa>
			<codigo>1</codigo>
		</cooperativa>
		<numeroContrato>6502</numeroContrato>
	</convenioCredito>
	<configuracaoCredito>
		<financiaIOF>false</financiaIOF>
		<financiaTarifa>false</financiaTarifa>
		<diasCarencia>33</diasCarencia>
	</configuracaoCredito>
	<propostaContratoCredito>
		<CETPercentAoAno>11.08</CETPercentAoAno>
		<dataPrimeiraParcela>20211201</dataPrimeiraParcela>
		<produto>
			<codigo>162</codigo>
		</produto>
		<quantidadeParcelas>117</quantidadeParcelas>
		<taxaJurosRemuneratorios>0.88</taxaJurosRemuneratorios>
		<taxaJurosRemuneratoriosAnual>11.09</taxaJurosRemuneratoriosAnual>
		<tipoLiberacao>
			<codigo>6</codigo>
		</tipoLiberacao>
		<tipoLiquidacao>
			<codigo>4</codigo>
		</tipoLiquidacao>
		<tributoIOFValor>0.0</tributoIOFValor>
		<valor>19950.96</valor>
		<valorBase>19950.96</valorBase>
		<dataProposta>2021-11-05T08:16:16</dataProposta>
		<emitente>
			<dataNascOuConstituicao>19781029T00:00:00</dataNascOuConstituicao>
			<identificadorReceitaFederal>831376961</identificadorReceitaFederal>
			<razaoSocialOuNome>GILVANA ALVES BUENO</razaoSocialOuNome>
			<nacionalidade>
				<codigo>42</codigo>
			</nacionalidade>
			<tipo>
				<codigo>1</codigo>
			</tipo>
			<contaCorrente>
				<agencia>
					<codigo>101</codigo>
				</agencia>
				<banco>
					<codigo>85</codigo>
				</banco>
				<codigoConta>13584715</codigoConta>
				<cooperativa>
					<codigo>1</codigo>
				</cooperativa>
			</contaCorrente>
			<numeroTitularidade>1</numeroTitularidade>
			<pessoaContatoEndereco>
				<CEP>83325290</CEP>
				<cidade>
					<descricao>PINHAIS</descricao>
				</cidade>
				<nomeBairro>ALTO TARUMA</nomeBairro>
				<numeroLogradouro>430</numeroLogradouro>
				<tipoEndereco>
					<codigo>13</codigo>
				</tipoEndereco>
				<tipoENomeLogradouro>RUA EUGENIA RIBAS</tipoENomeLogradouro>
				<UF>PR</UF>
			</pessoaContatoEndereco>
		</emitente>
		<identificadorProposta>4606375</identificadorProposta>
		<statusProposta>
			<codigo>26</codigo>
		</statusProposta>
	</propostaContratoCredito>
	<pessoaDocumento>
		<identificador>62355425</identificador>
		<tipo>
			<sigla>CI</sigla>
		</tipo>
	</pessoaDocumento>
	<pessoaFisicaOcupacao>
		<naturezaOcupacao>
			<codigo>6</codigo>
		</naturezaOcupacao>
	</pessoaFisicaOcupacao>
	<pessoaFisicaDetalhamento>
		<estadoCivil>
			<codigo>4</codigo>
		</estadoCivil>
		<sexo>
			<codigo>1</codigo>
		</sexo>
	</pessoaFisicaDetalhamento>
	<pessoaFisicaRendimento>
		<identificadorRegistroFuncionario>0</identificadorRegistroFuncionario>
	</pessoaFisicaRendimento>
	<remuneracaoColaborador>
		<empregador>
			<identificadorReceitaFederal>95423000000100</identificadorReceitaFederal>
			<razaoSocialOuNome>MUNICIPIO DE PINHAIS</razaoSocialOuNome>
		</empregador>
	</remuneracaoColaborador>
	<beneficio/>
	<listaPessoasEndereco>
		<pessoaEndereco>
			<parametroConsignado>
				<tipoPessoaEndereco>EMPREGADOR</tipoPessoaEndereco>
			</parametroConsignado>
			<pessoaContatoEndereco>
				<CEP>83323400</CEP>
				<cidade>
					<descricao>PINHAIS</descricao>
				</cidade>
				<nomeBairro>CENTRO</nomeBairro>
				<numeroLogradouro>536</numeroLogradouro>
				<tipoENomeLogradouro>RUA WANDA DOS SANTOS MALLMANN</tipoENomeLogradouro>
				<UF>PR</UF>
			</pessoaContatoEndereco>
		</pessoaEndereco>
	</listaPessoasEndereco>
	<parcela>
		<valor>274.04</valor>
	</parcela>
	<tarifa>
		<valor>0.0</valor>
	</tarifa>
	<inadimplencia>
		<despesasCartorarias>0.0</despesasCartorarias>
	</inadimplencia>
	<posicao>
		<produtoCategoria>
			<codigo>32</codigo>
		</produtoCategoria>
		<saldo>19950.96</saldo>
	</posicao>
	<usuarioDominioCecred>
		<codigo/>
	</usuarioDominioCecred>
	<parametroConsignado>
		<codigoFisTabelaJuros>1</codigoFisTabelaJuros>
		<indicadorContaPrincipal>true</indicadorContaPrincipal>
		<naturalidade>MARECHAL CANDIDO RON</naturalidade>
		<dataCalculoLegado>20211029T00:00:00</dataCalculoLegado>
	</parametroConsignado>
</Root>';

conta_13581155_4644042 clob := '<?xml version="1.0" encoding="WINDOWS1252"?>
<Root>
	<convenioCredito>
		<cooperativa>
			<codigo>1</codigo>
		</cooperativa>
		<numeroContrato>6502</numeroContrato>
	</convenioCredito>
	<configuracaoCredito>
		<financiaIOF>false</financiaIOF>
		<financiaTarifa>false</financiaTarifa>
		<diasCarencia>34</diasCarencia>
	</configuracaoCredito>
	<propostaContratoCredito>
		<CETPercentAoAno>11.09</CETPercentAoAno>
		<dataPrimeiraParcela>20211201</dataPrimeiraParcela>
		<produto>
			<codigo>162</codigo>
		</produto>
		<quantidadeParcelas>94</quantidadeParcelas>
		<taxaJurosRemuneratorios>0.88</taxaJurosRemuneratorios>
		<taxaJurosRemuneratoriosAnual>11.09</taxaJurosRemuneratoriosAnual>
		<tipoLiberacao>
			<codigo>6</codigo>
		</tipoLiberacao>
		<tipoLiquidacao>
			<codigo>4</codigo>
		</tipoLiquidacao>
		<tributoIOFValor>0.0</tributoIOFValor>
		<valor>2777.40</valor>
		<valorBase>2777.40</valorBase>
		<dataProposta>2021-11-05T08:16:16</dataProposta>
		<emitente>
			<dataNascOuConstituicao>19660926T00:00:00</dataNascOuConstituicao>
			<identificadorReceitaFederal>61042951934</identificadorReceitaFederal>
			<razaoSocialOuNome>JOSE DE JESUS ASSUNCAO FILHO</razaoSocialOuNome>
			<nacionalidade>
				<codigo>42</codigo>
			</nacionalidade>
			<tipo>
				<codigo>1</codigo>
			</tipo>
			<contaCorrente>
				<agencia>
					<codigo>101</codigo>
				</agencia>
				<banco>
					<codigo>85</codigo>
				</banco>
				<codigoConta>13581155</codigoConta>
				<cooperativa>
					<codigo>1</codigo>
				</cooperativa>
			</contaCorrente>
			<numeroTitularidade>1</numeroTitularidade>
			<pessoaContatoEndereco>
				<CEP>83322160</CEP>
				<cidade>
					<descricao>PINHAIS</descricao>
				</cidade>
				<nomeBairro>WEISSOPOLIS</nomeBairro>
				<numeroLogradouro>1527</numeroLogradouro>
				<tipoEndereco>
					<codigo>13</codigo>
				</tipoEndereco>
				<tipoENomeLogradouro>RUA RIO IGUACU</tipoENomeLogradouro>
				<UF>PR</UF>
			</pessoaContatoEndereco>
		</emitente>
		<identificadorProposta>4644042</identificadorProposta>
		<statusProposta>
			<codigo>26</codigo>
		</statusProposta>
	</propostaContratoCredito>
	<pessoaDocumento>
		<identificador>43791796</identificador>
		<tipo>
			<sigla>CI</sigla>
		</tipo>
	</pessoaDocumento>
	<pessoaFisicaOcupacao>
		<naturezaOcupacao>
			<codigo>6</codigo>
		</naturezaOcupacao>
	</pessoaFisicaOcupacao>
	<pessoaFisicaDetalhamento>
		<estadoCivil>
			<codigo>4</codigo>
		</estadoCivil>
		<sexo>
			<codigo>1</codigo>
		</sexo>
	</pessoaFisicaDetalhamento>
	<pessoaFisicaRendimento>
		<identificadorRegistroFuncionario>0</identificadorRegistroFuncionario>
	</pessoaFisicaRendimento>
	<remuneracaoColaborador>
		<empregador>
			<identificadorReceitaFederal>95423000000100</identificadorReceitaFederal>
			<razaoSocialOuNome>MUNICIPIO DE PINHAIS</razaoSocialOuNome>
		</empregador>
	</remuneracaoColaborador>
	<beneficio/>
	<listaPessoasEndereco>
		<pessoaEndereco>
			<parametroConsignado>
				<tipoPessoaEndereco>EMPREGADOR</tipoPessoaEndereco>
			</parametroConsignado>
			<pessoaContatoEndereco>
				<CEP>83323400</CEP>
				<cidade>
					<descricao>PINHAIS</descricao>
				</cidade>
				<nomeBairro>CENTRO</nomeBairro>
				<numeroLogradouro>536</numeroLogradouro>
				<tipoENomeLogradouro>RUA WANDA DOS SANTOS MALLMANN</tipoENomeLogradouro>
				<UF>PR</UF>
			</pessoaContatoEndereco>
		</pessoaEndereco>
	</listaPessoasEndereco>
	<parcela>
		<valor>43.61</valor>
	</parcela>
	<tarifa>
		<valor>0.0</valor>
	</tarifa>
	<inadimplencia>
		<despesasCartorarias>0.0</despesasCartorarias>
	</inadimplencia>
	<posicao>
		<produtoCategoria>
			<codigo>32</codigo>
		</produtoCategoria>
		<saldo>2777.40</saldo>
	</posicao>
	<usuarioDominioCecred>
		<codigo/>
	</usuarioDominioCecred>
	<parametroConsignado>
		<codigoFisTabelaJuros>1</codigoFisTabelaJuros>
		<indicadorContaPrincipal>true</indicadorContaPrincipal>
		<naturalidade>ASSAI</naturalidade>
		<dataCalculoLegado>20211028T00:00:00</dataCalculoLegado>
	</parametroConsignado>
</Root>';

conta_13520563_4639950 clob := '<?xml version="1.0" encoding="WINDOWS1252"?>
<Root>
	<convenioCredito>
		<cooperativa>
			<codigo>1</codigo>
		</cooperativa>
		<numeroContrato>6502</numeroContrato>
	</convenioCredito>
	<configuracaoCredito>
		<financiaIOF>false</financiaIOF>
		<financiaTarifa>false</financiaTarifa>
		<diasCarencia>34</diasCarencia>
	</configuracaoCredito>
	<propostaContratoCredito>
		<CETPercentAoAno>11.09</CETPercentAoAno>
		<dataPrimeiraParcela>20211201</dataPrimeiraParcela>
		<produto>
			<codigo>162</codigo>
		</produto>
		<quantidadeParcelas>48</quantidadeParcelas>
		<taxaJurosRemuneratorios>0.88</taxaJurosRemuneratorios>
		<taxaJurosRemuneratoriosAnual>11.09</taxaJurosRemuneratoriosAnual>
		<tipoLiberacao>
			<codigo>6</codigo>
		</tipoLiberacao>
		<tipoLiquidacao>
			<codigo>4</codigo>
		</tipoLiquidacao>
		<tributoIOFValor>0.0</tributoIOFValor>
		<valor>28339.16</valor>
		<valorBase>28339.16</valorBase>
		<dataProposta>2021-11-05T08:16:16</dataProposta>
		<emitente>
			<dataNascOuConstituicao>19760216T00:00:00</dataNascOuConstituicao>
			<identificadorReceitaFederal>97827827934</identificadorReceitaFederal>
			<razaoSocialOuNome>ALEXANDRE MAGALHAES FANHA</razaoSocialOuNome>
			<nacionalidade>
				<codigo>42</codigo>
			</nacionalidade>
			<tipo>
				<codigo>1</codigo>
			</tipo>
			<contaCorrente>
				<agencia>
					<codigo>101</codigo>
				</agencia>
				<banco>
					<codigo>85</codigo>
				</banco>
				<codigoConta>13520563</codigoConta>
				<cooperativa>
					<codigo>1</codigo>
				</cooperativa>
			</contaCorrente>
			<numeroTitularidade>1</numeroTitularidade>
			<pessoaContatoEndereco>
				<CEP>83325370</CEP>
				<cidade>
					<descricao>PINHAIS</descricao>
				</cidade>
				<nomeBairro>ALTO TARUMA</nomeBairro>
				<numeroLogradouro>282</numeroLogradouro>
				<tipoEndereco>
					<codigo>13</codigo>
				</tipoEndereco>
				<tipoENomeLogradouro>RUA GUAIRA</tipoENomeLogradouro>
				<UF>PR</UF>
			</pessoaContatoEndereco>
		</emitente>
		<identificadorProposta>4639950</identificadorProposta>
		<statusProposta>
			<codigo>26</codigo>
		</statusProposta>
	</propostaContratoCredito>
	<pessoaDocumento>
		<identificador>00553789846</identificador>
		<tipo>
			<sigla>CI</sigla>
		</tipo>
	</pessoaDocumento>
	<pessoaFisicaOcupacao>
		<naturezaOcupacao>
			<codigo>6</codigo>
		</naturezaOcupacao>
	</pessoaFisicaOcupacao>
	<pessoaFisicaDetalhamento>
		<estadoCivil>
			<codigo>4</codigo>
		</estadoCivil>
		<sexo>
			<codigo>1</codigo>
		</sexo>
	</pessoaFisicaDetalhamento>
	<pessoaFisicaRendimento>
		<identificadorRegistroFuncionario>0</identificadorRegistroFuncionario>
	</pessoaFisicaRendimento>
	<remuneracaoColaborador>
		<empregador>
			<identificadorReceitaFederal>95423000000100</identificadorReceitaFederal>
			<razaoSocialOuNome>MUNICIPIO DE PINHAIS</razaoSocialOuNome>
		</empregador>
	</remuneracaoColaborador>
	<beneficio/>
	<listaPessoasEndereco>
		<pessoaEndereco>
			<parametroConsignado>
				<tipoPessoaEndereco>EMPREGADOR</tipoPessoaEndereco>
			</parametroConsignado>
			<pessoaContatoEndereco>
				<CEP>83323400</CEP>
				<cidade>
					<descricao>PINHAIS</descricao>
				</cidade>
				<nomeBairro>CENTRO</nomeBairro>
				<numeroLogradouro>536</numeroLogradouro>
				<tipoENomeLogradouro>RUA WANDA DOS SANTOS MALLMANN</tipoENomeLogradouro>
				<UF>PR</UF>
			</pessoaContatoEndereco>
		</pessoaEndereco>
	</listaPessoasEndereco>
	<parcela>
		<valor>727.25</valor>
	</parcela>
	<tarifa>
		<valor>0.0</valor>
	</tarifa>
	<inadimplencia>
		<despesasCartorarias>0.0</despesasCartorarias>
	</inadimplencia>
	<posicao>
		<produtoCategoria>
			<codigo>32</codigo>
		</produtoCategoria>
		<saldo>28339.16</saldo>
	</posicao>
	<usuarioDominioCecred>
		<codigo/>
	</usuarioDominioCecred>
	<parametroConsignado>
		<codigoFisTabelaJuros>1</codigoFisTabelaJuros>
		<indicadorContaPrincipal>true</indicadorContaPrincipal>
		<naturalidade>CURITIBA</naturalidade>
		<dataCalculoLegado>20211028T00:00:00</dataCalculoLegado>
	</parametroConsignado>
</Root>';

begin

    insert into tbgen_evento_soa (CDCOOPER, NRDCONTA, NRCTRPRP, TPEVENTO, TPRODUTO_EVENTO, TPOPERACAO, DHOPERACAO, DSPROCESSAMENTO, DSSTATUS, DHEVENTO, DSERRO, NRTENTATIVAS, DSCONTEUDO_REQUISICAO)
    values (1, 13582933, 4605658, 'EFETIVA_PROPOSTA', 'CONSIGNADO', 'INSERT', sysdate, null, null, null, null, null, conta_13582933_4605658);

    insert into tbgen_evento_soa (CDCOOPER, NRDCONTA, NRCTRPRP, TPEVENTO, TPRODUTO_EVENTO, TPOPERACAO, DHOPERACAO, DSPROCESSAMENTO, DSSTATUS, DHEVENTO, DSERRO, NRTENTATIVAS, DSCONTEUDO_REQUISICAO)
    values (1, 13582933, 4605327, 'EFETIVA_PROPOSTA', 'CONSIGNADO', 'INSERT', sysdate, null, null, null, null, null, conta_13582933_4605327);

    insert into tbgen_evento_soa (CDCOOPER, NRDCONTA, NRCTRPRP, TPEVENTO, TPRODUTO_EVENTO, TPOPERACAO, DHOPERACAO, DSPROCESSAMENTO, DSSTATUS, DHEVENTO, DSERRO, NRTENTATIVAS, DSCONTEUDO_REQUISICAO)
    values (1, 8060266, 4604992, 'EFETIVA_PROPOSTA', 'CONSIGNADO', 'INSERT', sysdate, null, null, null, null, null, conta_8060266_4604992);
	
    insert into tbgen_evento_soa (CDCOOPER, NRDCONTA, NRCTRPRP, TPEVENTO, TPRODUTO_EVENTO, TPOPERACAO, DHOPERACAO, DSPROCESSAMENTO, DSSTATUS, DHEVENTO, DSERRO, NRTENTATIVAS, DSCONTEUDO_REQUISICAO)
    values (1, 8060266, 4605029, 'EFETIVA_PROPOSTA', 'CONSIGNADO', 'INSERT', sysdate, null, null, null, null, null, conta_8060266_4605029);

    insert into tbgen_evento_soa (CDCOOPER, NRDCONTA, NRCTRPRP, TPEVENTO, TPRODUTO_EVENTO, TPOPERACAO, DHOPERACAO, DSPROCESSAMENTO, DSSTATUS, DHEVENTO, DSERRO, NRTENTATIVAS, DSCONTEUDO_REQUISICAO)
    values (1, 13584715, 4606375, 'EFETIVA_PROPOSTA', 'CONSIGNADO', 'INSERT', sysdate, null, null, null, null, null, conta_13584715_4606375);

    insert into tbgen_evento_soa (CDCOOPER, NRDCONTA, NRCTRPRP, TPEVENTO, TPRODUTO_EVENTO, TPOPERACAO, DHOPERACAO, DSPROCESSAMENTO, DSSTATUS, DHEVENTO, DSERRO, NRTENTATIVAS, DSCONTEUDO_REQUISICAO)
    values (1, 13581155, 4644042, 'EFETIVA_PROPOSTA', 'CONSIGNADO', 'INSERT', sysdate, null, null, null, null, null, conta_13581155_4644042);

    insert into tbgen_evento_soa (CDCOOPER, NRDCONTA, NRCTRPRP, TPEVENTO, TPRODUTO_EVENTO, TPOPERACAO, DHOPERACAO, DSPROCESSAMENTO, DSSTATUS, DHEVENTO, DSERRO, NRTENTATIVAS, DSCONTEUDO_REQUISICAO)
    values (1, 13520563, 4639950, 'EFETIVA_PROPOSTA', 'CONSIGNADO', 'INSERT', sysdate, null, null, null, null, null, conta_13520563_4639950);

    commit;
    
EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;


end; 
