begin
    delete from CREDITO.TBCRED_PRONAMPE_REJEICAO;
	
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('0','Dados válidos');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('1','Dado inválido no campo TIPO DO REGISTRO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('2','Dado inválido no campo IDENTIFICADOR DA OPERAÇÃO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('3','Dado inválido no campo NÚMERO DA AGÊNCIA');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('4','A data de formalização não pode ser futura');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('5','Dado inválido no campo CPF-CNPJ DO MUTUÁRIO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('6','Dado inválido no campo FINALIDADE DO CRÉDITO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('7','Dado inválido no campo MODALIDADE DO CRÉDITO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('8','Dado inválido no campo DATA DA FORMALIZAÇÃO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('9','Dado inválido no campo DATA PREVISTA DA PRIMEIRA LIBERAÇÃO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('10','Dado inválido no campo VALOR PREVISTO DA PRIMEIRA LIBERAÇÃO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('11','Dado inválido no campo TIPO DE PESSOA DO MUTUÁRIO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('12','Dado inválido no campo DATA DE VENCIMENTO DA OPERAÇÃO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('13','Dado inválido no campo VALOR DA OPERAÇÃO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('14','Dado inválido no campo PERCENTUAL DE GARANTIA');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('15','Dado inválido no campo NOVO IDENTIFICADOR DA OPERAÇÃO ');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('16','Faturamento superior ao máximo permitido');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('17','Dado inválido no campo SALDO DEVEDOR');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('18','A data do cancelamento não pode ser anterior a outro evento já informado');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('19','O saldo de capital não pode ser maior que o valor da operação');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('21','Dado inválido no campo VALOR FINANCIADO ADICIONAL');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('22','Dado inválido no campo DATA DO SALDO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('23','Dado inválido no campo SALDO DE CAPITAL EM NORMALIDADE');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('24','Dado inválido no campo SALDO DE CAPITAL EM ATRASO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('25','Dado inválido no campo NÍVEL DE RISCO DA OPERAÇÃO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('26','Dado inválido no campo DATA DA LIQUIDAÇÃO DA OPERAÇÃO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('27','Dado inválido no campo DATA DE INÍCIO DA INADIMPLÊNCIA');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('28','Dado inválido no campo DATA DA SOLICITAÇÃO DE HONRA');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('29','Dado inválido no campo DATA DA RECUPERAÇÃO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('30','Dado inválido no campo VALOR RECUPERADO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('31','As datas informadas estão fora de uma ordem lógica entre si');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('32','Informou data futura em campo que exige data passada');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('33','Informou data passada em campo que exige data futura');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('34','Operação já cadastrada');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('35','Evento informado após o prazo limite');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('36','Procedimento não permitido para mutuário com operação honrada pelo Fundo Garantidor');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('37','Excedeu o valor máximo que pode ser garantido ao mutuário');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('38','Excedeu o valor máximo que pode ser garantido ao Agente Financeiro');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('39','Excedeu o valor máximo que pode ser garantido pelo Fundo');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('40','Dados informados resultam em CCG igual a zero');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('41','Operação não cadastrada');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('42','Nenhuma alteração em relação aos dados já cadastrados');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('44','O Agente Financeiro excedeu seu índice máximo de valores honrados');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('45','Já foi informado saldo com data mais recente que esta');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('46','Informou saldo em normalidade para operação vencida');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('48','A data de início da inadimplência não pode ser anterior à data de formalização');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('50','Não foi localizada a recuperação de valor honrado com os dados informados');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('51','Procedimento não permitido para operação na situação NORMALIDADE');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('52','Procedimento não permitido para operação na situação ATRASADA');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('53','Procedimento não permitido para operação na situação CANCELADA PELO AGENTE COM DEVOL CCG');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('54','Procedimento não permitido para operação na situação ENCERRADA PELO ADMINISTRADOR');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('55','Procedimento não permitido para operação na situação HONRADA');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('56','Procedimento não permitido para operação na situação LIQUIDADA APÓS A HONRA DA GARANTIA');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('57','Procedimento não permitido para operação na situação LIQUIDADA SEM HONRA DA GARANTIA');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('58','Dado inválido no campo SALDO BASE PARA CÁLCULO DO VALOR HONRADO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('59','A data de início da inadimplência não confere com as informações de saldo anteriores');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('60','Período de inadimplência menor que o mínimo exigido');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('61','Período de inadimplência maior que o máximo permitido');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('62','Dado inválido no campo CÓDIGO IBGE DO MUNICÍPIO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('64','Dado inválido no campo TIPO DE PÚBLICO ALVO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('65','Dado inválido no campo FATURAMENTO BRUTO ANUAL');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('66','Dado inválido no campo DATA DA LIBERAÇÃO OU ACP');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('67','Dado inválido no campo VALOR DA LIBERAÇÃO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('68','Dado inválido no campo VALOR DA CCG');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('69','Dado inválido no campo SALDO DE ENCARGOS EM NORMALIDADE');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('70','Dado inválido no campo SALDO DE ENCARGOS EM ATRASO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('72','A data do saldo não pode ser anterior à primeira liberação de crédito');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('88','Dado inválido no campo DATA DO CANCELAMENTO DA OPERAÇÃO ');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('92','Valor garantido maior que o máximo permitido para a finalidade INVESTIMENTO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('93','Valor Garantido maior que o máximo permitido para a finalidade CAPITAL DE GIRO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('94','Percentual de garantia menor que o mínimo exigido para a finalidade INVESTIMENTO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('95','Percentual de garantia menor que o mínimo exigido para a finalidade CAPITAL DE GIRO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('96','Percentual de garantia maior que o máximo permitido para a finalidade INVESTIMENTO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('97','Percentual de garantia maior que o máximo permitido para a finalidade CAPITAL DE GIRO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('100','Dado inválido no campo DATA DA ALTERAÇÃO DA OPERAÇÃO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('103','O valor liberado somado com as liberações anteriores não pode superar o valor da operação');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('104','A CCG informada não confere com a CCG calculada pelo Administrador');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('107','Dado inválido no campo DATA DA RECUPERAÇÃO A CANCELAR');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('108','Procedimento não permitido para operação na situação IMPUGNADA');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('109','A data de liquidação não pode ser menor que a data do último saldo informado');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('110','Código de público alvo não permitido');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('113','Dado inválido no campo DATA DA REATIVAÇÃO DA OPERAÇÃO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('114','Dado inválido no campo DATA DA DEVOLUÇÃO DO VALOR HONRADO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('116','A data da devolução não pode ser anterior à data da honra da garantia');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('117','Procedimento não permitido para operação na situação FORMALIZADA');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('119','Procedimento não permitido para operação na situação CANCELADA PELO AGENTE SEM DEVOL CCG');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('120','O valor liberado não pode ser maior que o valor da operação');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('121','Agente Financeiro não habilitado a operar com este Fundo Garantidor na data do evento');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('122','A data da liberação de crédito ou ACP não pode ser maior que a data de vencim. da operação');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('123','A data da formalização não pode ser menor que a data de vencimento da operação');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('124','O valor da operação não pode ser menor que o seu saldo devedor');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('125','Dado inválido no campo DATA DO CANCELAMENTO DA RECUPERAÇÃO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('126','Dado inválido no campo VALOR DA RECUPERAÇÃO A CANCELAR');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('127','A data da alteração não pode ser futura');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('128','Procedimento não permitido para operação com pendência');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('129','CPF/CNPJ inválido junto à Receita Federal do Brasil');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('130','Não deve ser cobrada CCG nesta liberação de crédito/ACP');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('131','Dado inválido no campo TIPO DE CRONOGRAMA DE AMORTIZAÇÃO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('132','Dado inválido no campo CONDIÇÃO ESPECIAL DA OPERAÇÃO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('133','Dado inválido no campo DATA PREVISTA DE VENCIMENTO DA OPERAÇÃO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('134','A data de vencimento não pode ser alterada em operação com cronograma do tipo independente');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('135','Não permitido cronograma INDEPENDENTE para a modalidade/finalidade de crédito da operação');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('136','A data da liberação de crédito ou ACP não pode ser anterior à data de formaliz. da oper.');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('137','A data da liberação do crédito ou ACP não pode ser futura');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('138','A data da reativação não pode ser anterior à data de liquidação da operação');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('139','A data da reativação não pode ser posterior à data de vencimento da operação');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('140','Dado inválido no campo DATA DO DESPACHO EXTERNO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('142','Modalidade de crédito incompatível com a condição especial');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('143','Procedimento não permitido para operação na situação PARCELADA APÓS A HONRA DA GARANTIA');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('144','Dado inválido no campo DATA DO PARCELAMENTO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('145','Dado inválido no campo VALOR DO SALDO PARCELADO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('146','Dado inválido no campo DATA DE VENCIMENTO DO PARCELAMENTO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('147','A data do parcelamento não pode ser anterior à data da honra da garantia');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('148','A data do parcelamento não pode ser futura');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('149','O saldo parcelado difere do saldo honrado a recuperar na data do parcelamento');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('150','A data de vencimento do parcelamento não pode ser anterior à data do parcelamento');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('151','Prazo de parcelamento maior que o máximo permitido');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('152','Dado inválido no campo FONTE DE RECURSOS');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('153','Dado inválido no campo PROGRAMA DE CRÉDITO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('154','Prazo da operação maior que o máximo permitido ');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('155','O código de público alvo é incompatível com a condição especial');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('156','Data em dia não útil');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('157','O saldo não pode ser zero na enésima liberação em operação da modalidade CRÉDITO FIXO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('158','A data do saldo deve ser o último dia do mês');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('159','A data do saldo não pode ser futura');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('160','A data da solicitação de honra não pode ser futura');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('161','A data do cancelamento não pode ser futura');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('162','A data da liquidação não pode ser futura');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('163','A data da reativação não pode ser futura');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('164','Tipo de condição especial não permitido nessa data de formalização');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('165','Tipo de condição especial não permitido nessa data de despacho externo');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('166','Saldo base incompatível com saldos anteriores da operação, conforme metodologia de cálculo');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('167','A data da alteração não pode ser anterior à data da formalização');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('168','O saldo devedor somado com o valor liberado não pode ser maior que o valor da operação');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('169','A data desta liberação de crédito/ACP não pode ser anterior à ultima informada');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('170','A data da liberação de crédito/ACP não pode ser anterior à data do despacho externo');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('171','A data do cancelamento não pode ser futura');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('172','Procedimento não permitido para mutuário com operação LIQUIDADA PÓS-HONRA COM ABATIMENTO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('173','Procedimento não permitido para mutuário com operação CEDIDA PÓS-HONRA COM DESÁGIO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('174','Dado inválido no campo VALOR DO ABATIMENTO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('175','Dado inválido no campo TIPO DE ABATIMENTO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('176','Procedimento não permitido para operação na situação LIQUIDADA PÓS-HONRA COM ABATIMENTO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('177','Procedimento não permitido para operação na situação CEDIDA PÓS-HONRA COM DESÁGIO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('178','Já existe operação formalizada com o identificador da operação substituta');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('179','A data da recuperação deve ser dia útil');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('180','A data da recuperação não pode ser anterior à data de solicitação da honra');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('181','A data da recuperação não pode ser futura');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('183','O valor do abatimento é compatível com o tipo de abatimento');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('184','Não cumpriu o prazo mínimo desde a solicitação de honra para conceder abatimento');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('185','Não cumpriu o prazo mínimo desde a solicitação de honra para fazer cessão com deságio');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('187','A recuperação a cancelar não foi a última informada');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('188','O saldo base informado resulta em valor honrado igual a zero');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('189','O código de público alvo é incompatível com o tipo de pessoa');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('190','Dados informados na remessa divergem dos informados na pré-validação');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('192','Esta operação já foi pré-validada com reserva');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('193','Procedimento não permitido para mutuário com operação PARCELADA POS-HONRA');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('194','A operação original não foi liquidada');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('195','A data do cancelamento não pode ser anterior à data da recuperação a cancelar');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('196','Procedimento não permitido para operação que foi liquidada para novacao de divida');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('197','Código do tipo de formalização inválido');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('199','Não foi localizada a operação liquidada para a novação da divida');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('200','O valor recuperado junto com o abatimento está abaixo do mínimo exigido');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('202','A data do abatimento não pode ser anterior a uma recuperação ou abatimento já informado');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('203','A data do abatimento não pode ser futura');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('204','A data do abatimento não pode ser anterior à data da honra da garantia');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('205','O prazo entre o início da inadimplência e a data do abatimento é menor que o permitido');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('206','Prazo entre os abatimentos e menor que o permitido');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('207','Já foi processado evento anterior que utilizou este número de reserva');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('208','A reserva expirou por decurso de prazo');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('209','A reserva foi cancelada pelo Agente Financeiro');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('210','Número de reserva não localizado');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('211','Dado invalido no campo NUMERO DA RESERVA ');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('212','abatimento acima do percentual máximo permitido');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('213','O valor do abatimento não corresponde ao saldo honrado a recuperar');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('214','O valor do abatimento não pode ser maior nem igual ao saldo honrado');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('215','Dado invalido no campo DATA DO ABATIMENTO');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('216','O prazo entre a honra da garantia e o abatimento é menor que o permitido');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('217','Este tipo de evento não estava habilitado na data informada');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('218','Já foi processado evento de abatimento após a recuperação a cancelar');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('219','Não é permitido aumentar o valor da operação de novação');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('220','É proibida mais de uma liberação de crédito em operação do tipo "novação de dívida"');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('221','Prazo da operação menor que o mínimo permitido');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('222','Operação formalizada fora do período permitido');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('223','O valor da operação não pode ser alterado');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('224','A alteração da data de vencimento deve ser feita pelo evento 10');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('225','O valor liberado não pode ser zero');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('226','Empresa com mais de 1 ano de fundação deve informar faturamento maior que zero');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('227','Excedeu o valor máximo que pode ser financiado com base no faturamento do mutuário');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('228','Excedeu o valor máximo que pode ser financiado pelo Agente com a garantia desse Fundo');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('229','Tipo de evento não habilitado para este Fundo Garantidor');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('230','Excedeu o valor máximo que pode ser financiado a empresa com menos de 1 ano');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('231','Excedeu o valor máximo que pode ser financiado a cada mutuário');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('232','Excedeu o valor máximo que pode ser honrado pelo Fundo');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('233','Faturamento bruto anual inválido junto à RFB');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('234','Operação não cadastrada no SCR do BACEN');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('235','O faturamento informado anteriormente ainda está pendente de validação pela RFB');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('236','O faturamento informado anteriormente foi validado pela RFB');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('237','Operação pendente de validação no SCR do BACEN');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('240','Tipo de Programa de Crédito não permitido para esta operação');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('241','Alteração de vencimento não permitida para esta operação');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('242','O prazo adicional, em relação à operação original, é maior que o permitido');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('243','Solicitação de honra não permitida para o período em que a operação foi formalizada');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('244','O código de público alvo é incompatível com o faturamento');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('245','Não permitido para operação formalizada em ano anterior');
	insert into CREDITO.TBCRED_PRONAMPE_REJEICAO (cdrejeicao, dsrejeicao) values ('999','Registro rejeitado por outro motivo (consulte o Administrador do Fundo)');

	commit;
exception
    when OTHERS then
	  rollback;
end;