BEGIN
  INSERT 
    INTO CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR)
   VALUES ('PROCESSA_LIBERACAO', 'TELA_PRONAM', 'pc_processa_liberacao_web', 'pr_contratos', 2304);
COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
END;  