BEGIN
  UPDATE CRAPTEL
     SET CDOPPTEL = CDOPPTEL||',L'
        ,LSOPPTEL = LSOPPTEL||',LIB CRED/LIQUIDACAO'
   WHERE NMDATELA = 'PRONAM';
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
END;         