DECLARE


BEGIN
-- Inserção dos parametros de horário 72000 -> 20:00 79200 -> 22:00 Não existe processo de compensação de pagamento e transferencia interna após às 22:00;
  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '72000 79200', 1);  

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '72000 79200', 2);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '72000 79200', 3);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '72000 79200', 4);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '72000 79200', 5);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '72000 79200', 6);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '72000 79200', 7);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '72000 79200', 8);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '72000 79200', 9);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '72000 79200', 10);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '72000 79200', 11);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '72000 79200', 12);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '72000 79200', 13);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '72000 79200', 14);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '72000 79200', 15);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '72000 79200', 16);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '72000 79200', 17);
  
  COMMIT;    
  
EXCEPTION WHEN OTHERS THEN
  ROLLBACK;
END;
