DECLARE
  vr_idcampo cecred.tbgen_layout.IDLAYOUT%TYPE;
BEGIN

  DELETE FROM cecred.tbgen_layout_programa c 
    WHERE EXISTS (SELECT 1 FROM cecred.tbgen_layout l WHERE l.idlayout = c.idlayout AND l.nmlayout = 'GFGF270R');
  DELETE FROM cecred.tbgen_layout_campo c 
    WHERE EXISTS (SELECT 1 FROM cecred.tbgen_layout l WHERE l.idlayout = c.idlayout AND l.nmlayout = 'GFGF270R');
  DELETE FROM cecred.tbgen_layout l WHERE l.nmlayout = 'GFGF270R';

  SELECT MAX(IDLAYOUT)+1 INTO vr_idcampo FROM cecred.tbgen_layout;

  -- Insere o novo layout
  INSERT INTO cecred.tbgen_layout (IDLAYOUT, NMLAYOUT, DSLAYOUT, DSDELIMITADOR, DSOBSERVACAO)
  VALUES (vr_idcampo, 'GFGF270R', 'Pronampe - Informativo Diario', null, 'Info. Diario');

  -- Insere nome do programa para rastreabilidade
    INSERT INTO cecred.tbgen_layout_programa (IDLAYOUT, CDPROGRA)
    VALUES (vr_idcampo, 'incluirPronampeGFGF270R');

  -- Header
  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, 'H', 1, 'NRSEQUENCIAL', 'N', null, 1, 7, null, 'NUMERO SEQUENCIAL REMESSA', '0000001');

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, 'H', 2, 'CDTIPOREG', 'N', null, 8, 2, null, 'TIPO DE REGISTRO', null);

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, 'H', 3, 'NMARQUIVO', 'T', null, 10, 8, null, 'NOME DO ARQUIVO RETORNO', null);

  -- 98 - DETALHE (SALDO HONRADO A RECUPERAR)
  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '98', 1, 'TPREGISTRO', 'N', null, 8, 2, null, 'TIPO DE REGISTRO', '98');

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '98', 2, 'IDCONTRATO', 'T', null, 10, 20, null, 'CODIGO IDENTIFICADOR DA OPERACAO DE CREDITO', null);

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '98', 3, 'DTVALIDSALDO', 'D', 'RRRRMMDD', 30, 8, null, 'DATA DE VALIDADE DO SALDO PARA COBRANCA', null);

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '98', 4, 'VLSALDOHONRA', 'N', null, 38, 17, 2, 'VALOR DO SALDO HONRADO A RECUPERAR', null);

  -- 91 - DETALHE (REMESSA PENDENTE DE MOVIMENTACAO FINANCEIRA)
  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '91', 1, 'TPREGISTRO', 'N', null, 8, 2, null, 'TIPO DE REGISTRO', '91');

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '91', 2, 'NRSEQREMESSA', 'N', null, 10, 4, null, 'SEQUENCIAL DO ARQUIVO DE REMESSA', null);

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '91', 3, 'VLAMOVIMENTAR', 'N', null, 14, 17, 2, 'VALOR A SER MOVIMENTADO', null);

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '91', 4, 'CDPENDENCIA', 'N', null, 31, 1, null, 'TIPO DE PENDENCIA', null);

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '91', 5, 'DTVLAMOVIMENTAR', 'D', 'RRRRMMDD', 32, 8, null, 'DATA DE VALIDADE DO VALOR A SER MOVIMENTADO', null);

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '91', 6, 'VLARETERISSQN', 'N', null, 40, 17, 2, 'VALOR A SER RETIRO PARA RECOLHIMENTO DO ISSQN', null);

  -- 96 - DETALHE (SITUACAO PATRIMONIAL)
  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '96', 1, 'TPREGISTRO', 'N', null, 8, 2, null, 'TIPO DE REGISTRO', '96');

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '96', 2, 'VLBASECALC', 'N', null, 10, 17, 2, 'BASE DE CALCULO LIMITE FGO', null);

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '96', 3, 'VLLIMFGO', 'N', null, 44, 17, 2, 'LIMITE MAXIMO CARTEIRA FGO', null);

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '96', 4, 'VLLIMAGENTE', 'N', null, 61, 17, 2, 'LIMITE MAXIMO CARTEIRA AGENTE', null);

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '96', 5, 'VLCMPRMFGO', 'N', null, 78, 17, 2, 'VALOR COMPROMETIDO FGO', null);

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '96', 6, 'VLCOMPRMAGENTE', 'N', null, 95, 17, 2, 'VALOR COMPROMETIDO AGENTE', null);

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '96', 7, 'DTSITPATRIMO', 'D', 'RRRRMMDD', 117, 8, null, 'DATA SITUACAO PATRIMONIAL', null);

  -- Trailer

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, 'T', 1, 'CDTIPOREG', 'N', nuLL, 8, 2, null, 'TIPO DE REGISTRO', 99);
  
  COMMIT;  
END;
