DECLARE
  vr_idcampo cecred.tbgen_layout.IDLAYOUT%TYPE;
BEGIN

  DELETE FROM cecred.tbgen_layout_programa c 
    WHERE EXISTS (SELECT 1 FROM cecred.tbgen_layout l WHERE l.idlayout = c.idlayout AND l.nmlayout = 'GFGF450R');
  DELETE FROM cecred.tbgen_layout_campo c 
    WHERE EXISTS (SELECT 1 FROM cecred.tbgen_layout l WHERE l.idlayout = c.idlayout AND l.nmlayout = 'GFGF450R');
  DELETE FROM cecred.tbgen_layout l WHERE l.nmlayout = 'GFGF450R';

  SELECT MAX(IDLAYOUT)+1 INTO vr_idcampo FROM cecred.tbgen_layout;

  -- Insere o novo layout
  INSERT INTO cecred.tbgen_layout (IDLAYOUT, NMLAYOUT, DSLAYOUT, DSDELIMITADOR, DSOBSERVACAO)
  VALUES (vr_idcampo, 'GFGF450R', 'Pronampe - Movimentacao Financeira', null, '4º Retorno');

  -- Insere nome do programa para rastreabilidade
    INSERT INTO cecred.tbgen_layout_programa (IDLAYOUT, CDPROGRA)
    VALUES (vr_idcampo, 'incluirPronampeGFGF450R');

  -- Header
  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, 'H', 1, 'NRSEQUENCIAL', 'N', null, 1, 7, null, 'NUMERO SEQUENCIAL REMESSA', '0000001');

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, 'H', 2, 'CDTIPOREG', 'N', null, 8, 2, null, 'TIPO DE REGISTRO', null);

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, 'H', 3, 'NMARQUIVO', 'T', null, 10, 8, null, 'NOME DO ARQUIVO RETORNO', null);

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, 'H', 4, 'NRSEQREMESSA', 'N', null, 32, 4, null, 'SEQUENCIAL DO ARQUIVO DE REMESSA', null);

  -- 97 - Detalhe da situacao da operacao
  
  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '97', 1, 'TPREGISTRO', 'N', null, 8, 2, null, 'TIPO DE REGISTRO', '97');

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '97', 2, 'IDCONTRATO', 'T', null, 10, 20, null, 'CODIGO IDENTIFICADOR DA OPERACAO DE CREDITO', null);
  
  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '97', 3, 'CDMOVIMENTACAO', 'N', null, 30, 2, null, 'TIPO DE MOVIMENTACAO FINANCEIRA', null);
 
  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '97', 4, 'DTMOVIMENTACAO', 'D', 'RRRRMMDD', 32, 8, null, 'DATA DA MOVIMENTACAO FINANCEIRA', null);

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '97', 5, 'DTFATOGERADOR', 'D', 'RRRRMMDD', 40, 8, null, 'DATA DO FATO GERADOR DA MOVIMENTACAO', null);

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '97', 6, 'VLNOMIFATOGERADOR', 'N', null, 48, 17, 2, 'VALOR NOMINAL DA DATA DO FATO GERADOR', null);

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '97', 7, 'VLATUALIZACAOMONET', 'N', null, 65, 17, 2, 'VALOR DA ATUALIZACAO MONETARIA', null);

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '97', 8, 'VLISSQN', 'N', null, 82, 17, 2, 'VALOR DO ISSQN', null);

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '97', 9, 'VLLIQUIDO', 'N', null, 99, 17, 2, 'VALOR LIQUIDO MOVIMENTADO', null);

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '97', 10, 'NRCAUSADORMOV', 'N', null, 116, 7, null, 'NUMERO SEQUENCIAL CAUSADOR DA MOVIMENTACAO', null);
  
  -- Trailer

  INSERT INTO cecred.tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, 'T', 1, 'CDTIPOREG', 'N', nuLL, 8, 2, null, 'TIPO DE REGISTRO', 99);
  
  COMMIT;  
END;
