BEGIN
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','0','Ativo');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','1','Liquidação Antecipada');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','2','Sinistro');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','3','Retomada');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','4','Término por outros');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','5','Dação');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','6','Término por revenda');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','7','Saldo Zerado');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','8','Término Prazo');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','9','Arrematação por Terceiros');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','10','Término por Cessão');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','20','Término por Cancelamento Administrativo');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','21','Término por Recomercialização');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','22','Término por Subrogação');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','23','Término por Transferência');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','24','Término por Transf. De Parte Ideal');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','25','Término por Transf. Em Sinistro Parc.');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','26','Término por Consolidacao de Hipoteca');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','27','Término por Novação c/ 70% Desc.');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','28','Termino por Novação c/ 30% Desc.');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','29','Término por Rescisão Contratual');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','30','Término por Renegociação');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','31','Término por Permuta');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','32','Término por Integr. da Fase de Poupança');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','33','Término por Renovação');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','34','Término por Retrocessão');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','35','Término por Consolidação');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','70','Cancelamento de Acordo Avançado');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','91','Liquidação com Recurso do PSH');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','94','Liquidação de Futura Aquisição');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','95','Contrato em fase de construção');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','96','Contratos com Séries');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','97','Contrato em Cobrança');
insert into tbgen_dominio_campo(nmdominio,cddominio,dscodigo) values ('STATUSCONTRATOPROGNUM','98','Excluído');   
COMMIT;
EXCEPTION
 WHEN OTHERS THEN
  ROLLBACK;
END;
