begin  
  UPDATE CECRED.TBCC_LANCAMENTOS_PENDENTES SET
    IDSITUACAO = 'M'
  WHERE IDTRANSACAO = 46725522
    AND IDSITUACAO <> 'P';
  
  commit;

  EXCEPTION
  WHEN OTHERS THEN
  ROLLBACK;
end;