BEGIN

delete from CREDITO.TBCRED_CARGA_PREAPROV;

delete from CREDITO.TBCRED_CARGA_PREAPROV_DET;

delete from CREDITO.TBCRED_PREAPROV;

delete from CREDITO.TBCRED_PREAPROV_DET;
    
  COMMIT;
  
  EXCEPTION
    WHEN OTHERS THEN
     ROLLBACK;
END;
       