begin
insert into TBSEG_PARAMETROS_PRST(IDSEQPAR,CDCOOPER,TPPESSOA,CDSEGURA,TPDPAGTO,MODALIDA,QTPARCEL,PIEDIAS ,PIEPARCE,PIELIMIT,PIETAXA ,IFTTDIAS,IFTTPARC,IFTTLIMI,IFTTTAXA,LMPSELEG,TPCUSTEI,VLCOMISS,TPADESAO,LIMITDPS,VIGENCIA,APOLICO ,ENDERFTP,LOGINFTP,SENHAFTP,FLGELEPF,FLGINDEN,IDADEDPS,PAGSEGU ,SEQARQU ,APOLINC)values( TBSEG_PARAMETROS_PRST_seq.nextval,  1, 0, 514, 0, 0, 240, 30, 5 , 10000, 0.19, 30 , 5, 10000, 0, 0, 0, 0.3, 0, 2000000, '31-10-2022', '0000000077001060', 'filetransfer.icatuseguros.com.br', 'Producao-Ailos', '@Ailos2019@', 0, 0, 66, 0.01755, 3056, '0000000077001006' );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 1, 18, 65, 0.033, 0.033 );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 1, 66, 80, 0.072, 0.072 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 1, 18, 65, 40000, 3000000);
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 1, 66, 70, 40000, 500000 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 1, 71, 75, 40000, 100000 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 1, 76, 80, 40000, 50000 );

insert into TBSEG_PARAMETROS_PRST(IDSEQPAR,CDCOOPER,TPPESSOA,CDSEGURA,TPDPAGTO,MODALIDA,QTPARCEL,PIEDIAS ,PIEPARCE,PIELIMIT,PIETAXA ,IFTTDIAS,IFTTPARC,IFTTLIMI,IFTTTAXA,LMPSELEG,TPCUSTEI,VLCOMISS,TPADESAO,LIMITDPS,VIGENCIA,APOLICO ,ENDERFTP,LOGINFTP,SENHAFTP,FLGELEPF,FLGINDEN,IDADEDPS,PAGSEGU ,SEQARQU ,APOLINC)values( TBSEG_PARAMETROS_PRST_seq.nextval,  2, 0, 514, 0, 0, 240, 30, 5 , 10000, 0.19, 30 , 5, 10000, 0, 0, 0, 0.3, 0, 2000000, '31-10-2022', '0000000077001060', 'filetransfer.icatuseguros.com.br', 'Producao-Ailos', '@Ailos2019@', 0, 0, 66, 0.01755, 3056, '0000000077001006' );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 2, 18, 65, 0.033, 0.033 );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 2, 66, 80, 0.072, 0.072 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 2, 18, 65, 0.1, 3000000);
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 2, 66, 70, 0.1, 500000 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 2, 71, 75, 0.1, 100000 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 2, 76, 80, 0.1, 50000 );
                                                                                                                                                                                                                                                                                                                               
insert into TBSEG_PARAMETROS_PRST(IDSEQPAR,CDCOOPER,TPPESSOA,CDSEGURA,TPDPAGTO,MODALIDA,QTPARCEL,PIEDIAS ,PIEPARCE,PIELIMIT,PIETAXA ,IFTTDIAS,IFTTPARC,IFTTLIMI,IFTTTAXA,LMPSELEG,TPCUSTEI,VLCOMISS,TPADESAO,LIMITDPS,VIGENCIA,APOLICO ,ENDERFTP,LOGINFTP,SENHAFTP,FLGELEPF,FLGINDEN,IDADEDPS,PAGSEGU ,SEQARQU ,APOLINC)values( TBSEG_PARAMETROS_PRST_seq.nextval,  3, 0, 514, 0, 0, 240, 30, 5 , 10000, 0.19, 30 , 5, 10000, 0, 0, 0, 0.3, 0, 2000000, '31-10-2022', '0000000077001060', 'filetransfer.icatuseguros.com.br', 'Producao-Ailos', '@Ailos2019@', 0, 0, 66, 0.01755, 3056, '0000000077001006' );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 3, 18, 65, 0.033, 0.033 );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 3, 66, 80, 0.072, 0.072 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 3, 18, 65, 10000, 3000000);
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 3, 66, 70, 10000, 500000 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 3, 71, 75, 10000, 100000 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 3, 76, 80, 10000, 50000 );
                                                                                                                                                                                                                                                                                                                               
insert into TBSEG_PARAMETROS_PRST(IDSEQPAR,CDCOOPER,TPPESSOA,CDSEGURA,TPDPAGTO,MODALIDA,QTPARCEL,PIEDIAS ,PIEPARCE,PIELIMIT,PIETAXA ,IFTTDIAS,IFTTPARC,IFTTLIMI,IFTTTAXA,LMPSELEG,TPCUSTEI,VLCOMISS,TPADESAO,LIMITDPS,VIGENCIA,APOLICO ,ENDERFTP,LOGINFTP,SENHAFTP,FLGELEPF,FLGINDEN,IDADEDPS,PAGSEGU ,SEQARQU ,APOLINC)values( TBSEG_PARAMETROS_PRST_seq.nextval,  4, 0, 514, 0, 0, 240, 30, 5 , 10000, 0.19, 30 , 5, 10000, 0, 0, 0, 0.3, 0, 2000000, '31-10-2022', '0000000077001060', 'filetransfer.icatuseguros.com.br', 'Producao-Ailos', '@Ailos2019@', 0, 0, 66, 0.01755, 3056, '0000000077001006' );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 4, 18, 65, 0.033, 0.033 );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 4, 66, 80, 0.072, 0.072 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 4, 18, 65, 0.1, 3000000);
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 4, 66, 70, 0.1, 500000 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 4, 71, 75, 0.1, 100000 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 4, 76, 80, 0.1, 50000 );
                                                                                                                                                                                                                                                                                                                               
insert into TBSEG_PARAMETROS_PRST(IDSEQPAR,CDCOOPER,TPPESSOA,CDSEGURA,TPDPAGTO,MODALIDA,QTPARCEL,PIEDIAS ,PIEPARCE,PIELIMIT,PIETAXA ,IFTTDIAS,IFTTPARC,IFTTLIMI,IFTTTAXA,LMPSELEG,TPCUSTEI,VLCOMISS,TPADESAO,LIMITDPS,VIGENCIA,APOLICO ,ENDERFTP,LOGINFTP,SENHAFTP,FLGELEPF,FLGINDEN,IDADEDPS,PAGSEGU ,SEQARQU ,APOLINC)values( TBSEG_PARAMETROS_PRST_seq.nextval,  5, 0, 514, 0, 0, 240, 30, 5 , 10000, 0.19, 30 , 5, 10000, 0, 0, 0, 0.3, 0, 2000000, '31-10-2022', '0000000077001060', 'filetransfer.icatuseguros.com.br', 'Producao-Ailos', '@Ailos2019@', 0, 0, 66, 0.01755, 3056, '0000000077001006' );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 5, 18, 65, 0.033, 0.033 );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 5, 66, 80, 0.072, 0.072 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 5, 18, 65, 0.1, 3000000);
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 5, 66, 70, 0.1, 500000 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 5, 71, 75, 0.1, 100000 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 5, 76, 80, 0.1, 50000 );
                                                                                                                                                                                                                                                                                                                               
insert into TBSEG_PARAMETROS_PRST(IDSEQPAR,CDCOOPER,TPPESSOA,CDSEGURA,TPDPAGTO,MODALIDA,QTPARCEL,PIEDIAS ,PIEPARCE,PIELIMIT,PIETAXA ,IFTTDIAS,IFTTPARC,IFTTLIMI,IFTTTAXA,LMPSELEG,TPCUSTEI,VLCOMISS,TPADESAO,LIMITDPS,VIGENCIA,APOLICO ,ENDERFTP,LOGINFTP,SENHAFTP,FLGELEPF,FLGINDEN,IDADEDPS,PAGSEGU ,SEQARQU ,APOLINC)values( TBSEG_PARAMETROS_PRST_seq.nextval,  6, 0, 514, 0, 0, 240, 30, 5 , 10000, 0.19, 30 , 5, 10000, 0, 0, 0, 0.3, 0, 2000000, '31-10-2022', '0000000077001060', 'filetransfer.icatuseguros.com.br', 'Producao-Ailos', '@Ailos2019@', 0, 0, 66, 0.01755, 3056, '0000000077001006' );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 6, 18, 65, 0.033, 0.033 );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 6, 66, 80, 0.072, 0.072 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 6, 18, 65, 0.1, 3000000);
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 6, 66, 70, 0.1, 500000 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 6, 71, 75, 0.1, 100000 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 6, 76, 80, 0.1, 50000 );
                                                                                                                                                                                                                                                                                                                               
insert into TBSEG_PARAMETROS_PRST(IDSEQPAR,CDCOOPER,TPPESSOA,CDSEGURA,TPDPAGTO,MODALIDA,QTPARCEL,PIEDIAS ,PIEPARCE,PIELIMIT,PIETAXA ,IFTTDIAS,IFTTPARC,IFTTLIMI,IFTTTAXA,LMPSELEG,TPCUSTEI,VLCOMISS,TPADESAO,LIMITDPS,VIGENCIA,APOLICO ,ENDERFTP,LOGINFTP,SENHAFTP,FLGELEPF,FLGINDEN,IDADEDPS,PAGSEGU ,SEQARQU ,APOLINC)values( TBSEG_PARAMETROS_PRST_seq.nextval,  7, 0, 514, 0, 0, 240, 30, 5 , 10000, 0.19, 30 , 5, 10000, 0, 0, 0, 0.3, 0, 2000000, '31-10-2022', '0000000077001060', 'filetransfer.icatuseguros.com.br', 'Producao-Ailos', '@Ailos2019@', 0, 0, 66, 0.01755, 3056, '0000000077001006' );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 7, 18, 65, 0.033, 0.033 );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 7, 66, 80, 0.072, 0.072 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 7, 18, 65, 0.1, 3000000);
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 7, 66, 70, 0.1, 500000 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 7, 71, 75, 0.1, 100000 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 7, 76, 80, 0.1, 50000 );
                                                                                                                                                                                                                                                                                                                               
insert into TBSEG_PARAMETROS_PRST(IDSEQPAR,CDCOOPER,TPPESSOA,CDSEGURA,TPDPAGTO,MODALIDA,QTPARCEL,PIEDIAS ,PIEPARCE,PIELIMIT,PIETAXA ,IFTTDIAS,IFTTPARC,IFTTLIMI,IFTTTAXA,LMPSELEG,TPCUSTEI,VLCOMISS,TPADESAO,LIMITDPS,VIGENCIA,APOLICO ,ENDERFTP,LOGINFTP,SENHAFTP,FLGELEPF,FLGINDEN,IDADEDPS,PAGSEGU ,SEQARQU ,APOLINC)values( TBSEG_PARAMETROS_PRST_seq.nextval,  8, 0, 514, 0, 0, 240, 30, 5 , 10000, 0.19, 30 , 5, 10000, 0, 0, 0, 0.3, 0, 2000000, '31-10-2022', '0000000077001060', 'filetransfer.icatuseguros.com.br', 'Producao-Ailos', '@Ailos2019@', 0, 0, 66, 0.01755, 3056, '0000000077001006' );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 8, 18, 65, 0.033, 0.033 );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 8, 66, 80, 0.072, 0.072 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 8, 18, 65, 0.1, 3000000);
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 8, 66, 70, 0.1, 500000 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 8, 71, 75, 0.1, 100000 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 8, 76, 80, 0.1, 50000 );
                                                                                                                                                                                                                                                                                                                               
insert into TBSEG_PARAMETROS_PRST(IDSEQPAR,CDCOOPER,TPPESSOA,CDSEGURA,TPDPAGTO,MODALIDA,QTPARCEL,PIEDIAS ,PIEPARCE,PIELIMIT,PIETAXA ,IFTTDIAS,IFTTPARC,IFTTLIMI,IFTTTAXA,LMPSELEG,TPCUSTEI,VLCOMISS,TPADESAO,LIMITDPS,VIGENCIA,APOLICO ,ENDERFTP,LOGINFTP,SENHAFTP,FLGELEPF,FLGINDEN,IDADEDPS,PAGSEGU ,SEQARQU ,APOLINC)values( TBSEG_PARAMETROS_PRST_seq.nextval,  9, 0, 514, 0, 0, 240, 30, 5 , 10000, 0.19, 30 , 5, 10000, 0, 0, 0, 0.3, 0, 2000000, '31-10-2022', '0000000077001060', 'filetransfer.icatuseguros.com.br', 'Producao-Ailos', '@Ailos2019@', 0, 0, 66, 0.01755, 3056, '0000000077001006' );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 9, 18, 65, 0.033, 0.033 );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 9, 66, 80, 0.072, 0.072 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 9, 18, 65, 0.1, 3000000);
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 9, 66, 70, 0.1, 500000 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 9, 71, 75, 0.1, 100000 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 9, 76, 80, 0.1, 50000 );
                                                                                                                                                                                                                                                                                                                               
insert into TBSEG_PARAMETROS_PRST(IDSEQPAR,CDCOOPER,TPPESSOA,CDSEGURA,TPDPAGTO,MODALIDA,QTPARCEL,PIEDIAS ,PIEPARCE,PIELIMIT,PIETAXA ,IFTTDIAS,IFTTPARC,IFTTLIMI,IFTTTAXA,LMPSELEG,TPCUSTEI,VLCOMISS,TPADESAO,LIMITDPS,VIGENCIA,APOLICO ,ENDERFTP,LOGINFTP,SENHAFTP,FLGELEPF,FLGINDEN,IDADEDPS,PAGSEGU ,SEQARQU ,APOLINC)values( 2, 10, 0, 514, 0, 0, 240, 30, 5 , 10000, 0.19, 30 , 5, 10000, 0, 0, 0, 0.3, 0, 2000000, '31-10-2022', '0000000077001060', 'filetransfer.icatuseguros.com.br', 'Producao-Ailos', '@Ailos2019@', 0, 0, 66, 0.01755, 3056, '0000000077001006' );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 10, 18, 65, 0.033, 0.033 );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 10, 66, 80, 0.072, 0.072 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 10, 18, 65, 0.1, 3000000);
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 10, 66, 70, 0.1, 500000 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 10, 71, 75, 0.1, 100000 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 10, 76, 80, 0.1, 50000 );
                                                                                                                                                                                                                                                                                                                               
insert into TBSEG_PARAMETROS_PRST(IDSEQPAR,CDCOOPER,TPPESSOA,CDSEGURA,TPDPAGTO,MODALIDA,QTPARCEL,PIEDIAS ,PIEPARCE,PIELIMIT,PIETAXA ,IFTTDIAS,IFTTPARC,IFTTLIMI,IFTTTAXA,LMPSELEG,TPCUSTEI,VLCOMISS,TPADESAO,LIMITDPS,VIGENCIA,APOLICO ,ENDERFTP,LOGINFTP,SENHAFTP,FLGELEPF,FLGINDEN,IDADEDPS,PAGSEGU ,SEQARQU ,APOLINC)values( 2, 11, 0, 514, 0, 0, 240, 30, 5 , 10000, 0.19, 30 , 5, 10000, 0, 0, 0, 0.3, 0, 2000000, '31-10-2022', '0000000077001060', 'filetransfer.icatuseguros.com.br', 'Producao-Ailos', '@Ailos2019@', 0, 0, 66, 0.01755, 3056, '0000000077001006' );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 11, 18, 65, 0.033, 0.033 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 11, 66, 80, 0.072, 0.072 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 11, 18, 65, 0.1, 3000000);                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 11, 66, 70, 0.1, 500000 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 11, 71, 75, 0.1, 100000 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 11, 76, 80, 0.1, 50000 );                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                               
insert into TBSEG_PARAMETROS_PRST(IDSEQPAR,CDCOOPER,TPPESSOA,CDSEGURA,TPDPAGTO,MODALIDA,QTPARCEL,PIEDIAS ,PIEPARCE,PIELIMIT,PIETAXA ,IFTTDIAS,IFTTPARC,IFTTLIMI,IFTTTAXA,LMPSELEG,TPCUSTEI,VLCOMISS,TPADESAO,LIMITDPS,VIGENCIA,APOLICO ,ENDERFTP,LOGINFTP,SENHAFTP,FLGELEPF,FLGINDEN,IDADEDPS,PAGSEGU ,SEQARQU ,APOLINC)values( 2, 12, 0, 514, 0, 0, 240, 30, 5 , 10000, 0.19, 30 , 5, 10000, 0, 0, 0, 0.3, 0, 2000000, '31-10-2022', '0000000077001060', 'filetransfer.icatuseguros.com.br', 'Producao-Ailos', '@Ailos2019@', 0, 0, 66, 0.01755, 3056, '0000000077001006' );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 12, 18, 65, 0.033, 0.033 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 12, 66, 80, 0.072, 0.072 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 12, 18, 65, 0.1, 3000000);                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 12, 66, 70, 0.1, 500000 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 12, 71, 75, 0.1, 100000 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 12, 76, 80, 0.1, 50000 );                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                               
insert into TBSEG_PARAMETROS_PRST(IDSEQPAR,CDCOOPER,TPPESSOA,CDSEGURA,TPDPAGTO,MODALIDA,QTPARCEL,PIEDIAS ,PIEPARCE,PIELIMIT,PIETAXA ,IFTTDIAS,IFTTPARC,IFTTLIMI,IFTTTAXA,LMPSELEG,TPCUSTEI,VLCOMISS,TPADESAO,LIMITDPS,VIGENCIA,APOLICO ,ENDERFTP,LOGINFTP,SENHAFTP,FLGELEPF,FLGINDEN,IDADEDPS,PAGSEGU ,SEQARQU ,APOLINC)values( 2, 13, 0, 514, 0, 0, 240, 30, 5 , 10000, 0.19, 30 , 5, 10000, 0, 0, 0, 0.3, 0, 2000000, '31-10-2022', '0000000077001060', 'filetransfer.icatuseguros.com.br', 'Producao-Ailos', '@Ailos2019@', 0, 0, 66, 0.01755, 3056, '0000000077001006' );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 13, 18, 65, 0.033, 0.033 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 13, 66, 80, 0.072, 0.072 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 13, 18, 65, 0.1, 3000000);                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 13, 66, 70, 0.1, 500000 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 13, 71, 75, 0.1, 100000 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 13, 76, 80, 0.1, 50000 );                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                               
insert into TBSEG_PARAMETROS_PRST(IDSEQPAR,CDCOOPER,TPPESSOA,CDSEGURA,TPDPAGTO,MODALIDA,QTPARCEL,PIEDIAS ,PIEPARCE,PIELIMIT,PIETAXA ,IFTTDIAS,IFTTPARC,IFTTLIMI,IFTTTAXA,LMPSELEG,TPCUSTEI,VLCOMISS,TPADESAO,LIMITDPS,VIGENCIA,APOLICO ,ENDERFTP,LOGINFTP,SENHAFTP,FLGELEPF,FLGINDEN,IDADEDPS,PAGSEGU ,SEQARQU ,APOLINC)values( 2, 14, 0, 514, 0, 0, 240, 30, 5 , 10000, 0.19, 30 , 5, 10000, 0, 0, 0, 0.3, 0, 2000000, '31-10-2022', '0000000077001060', 'filetransfer.icatuseguros.com.br', 'Producao-Ailos', '@Ailos2019@', 0, 0, 66, 0.01755, 3056, '0000000077001006' );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 14, 18, 65, 0.033, 0.033 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 14, 66, 80, 0.072, 0.072 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 14, 18, 65, 0.1, 3000000);                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 14, 66, 70, 0.1, 500000 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 14, 71, 75, 0.1, 100000 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 14, 76, 80, 0.1, 50000 );                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                               
insert into TBSEG_PARAMETROS_PRST(IDSEQPAR,CDCOOPER,TPPESSOA,CDSEGURA,TPDPAGTO,MODALIDA,QTPARCEL,PIEDIAS ,PIEPARCE,PIELIMIT,PIETAXA ,IFTTDIAS,IFTTPARC,IFTTLIMI,IFTTTAXA,LMPSELEG,TPCUSTEI,VLCOMISS,TPADESAO,LIMITDPS,VIGENCIA,APOLICO ,ENDERFTP,LOGINFTP,SENHAFTP,FLGELEPF,FLGINDEN,IDADEDPS,PAGSEGU ,SEQARQU ,APOLINC)values( 2, 15, 0, 514, 0, 0, 240, 30, 5 , 10000, 0.19, 30 , 5, 10000, 0, 0, 0, 0.3, 0, 2000000, '31-10-2022', '0000000077001060', 'filetransfer.icatuseguros.com.br', 'Producao-Ailos', '@Ailos2019@', 0, 0, 66, 0.01755, 3056, '0000000077001006' );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 15, 18, 65, 0.033, 0.033 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 15, 66, 80, 0.072, 0.072 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 15, 18, 65, 0.1, 3000000);                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 15, 66, 70, 0.1, 500000 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 15, 71, 75, 0.1, 100000 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 15, 76, 80, 0.1, 50000 );                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                               
insert into TBSEG_PARAMETROS_PRST(IDSEQPAR,CDCOOPER,TPPESSOA,CDSEGURA,TPDPAGTO,MODALIDA,QTPARCEL,PIEDIAS ,PIEPARCE,PIELIMIT,PIETAXA ,IFTTDIAS,IFTTPARC,IFTTLIMI,IFTTTAXA,LMPSELEG,TPCUSTEI,VLCOMISS,TPADESAO,LIMITDPS,VIGENCIA,APOLICO ,ENDERFTP,LOGINFTP,SENHAFTP,FLGELEPF,FLGINDEN,IDADEDPS,PAGSEGU ,SEQARQU ,APOLINC)values( 2, 16, 0, 514, 0, 0, 240, 30, 5 , 10000, 0.19, 30 , 5, 10000, 0, 0, 0, 0.3, 0, 2000000, '31-10-2022', '0000000077001060', 'filetransfer.icatuseguros.com.br', 'Producao-Ailos', '@Ailos2019@', 0, 0, 66, 0.01755, 3056, '0000000077001006' );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 16, 18, 65, 0.033, 0.033 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 16, 66, 80, 0.072, 0.072 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 16, 18, 65, 20000, 3000000);                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 16, 66, 70, 20000, 500000 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 16, 71, 75, 20000, 100000 );                                                                                                                                                                                                 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 16, 76, 80, 20000, 50000 );                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                               
insert into TBSEG_PARAMETROS_PRST(IDSEQPAR,CDCOOPER,TPPESSOA,CDSEGURA,TPDPAGTO,MODALIDA,QTPARCEL,PIEDIAS ,PIEPARCE,PIELIMIT,PIETAXA ,IFTTDIAS,IFTTPARC,IFTTLIMI,IFTTTAXA,LMPSELEG,TPCUSTEI,VLCOMISS,TPADESAO,LIMITDPS,VIGENCIA,APOLICO ,ENDERFTP,LOGINFTP,SENHAFTP,FLGELEPF,FLGINDEN,IDADEDPS,PAGSEGU ,SEQARQU ,APOLINC)values( 2, 17, 0, 514, 0, 0, 240, 30, 5 , 10000, 0.19, 30 , 5, 10000, 0, 0, 0, 0.3, 0, 2000000, '31-10-2022', '0000000077001060', 'filetransfer.icatuseguros.com.br', 'Producao-Ailos', '@Ailos2019@', 0, 0, 66, 0.01755, 3056, '0000000077001006' );
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 17, 18, 65, 0.033, 0.033 ); 
insert into TBSEG_PARAM_PRST_TAX_COB ( IDSEQPAR, GBIDAMIN, GBIDAMAX, GBSEGMIN, GBSEGMAX ) values ( 17, 66, 80, 0.072, 0.072 );
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 17, 18, 65, 0.1, 3000000); 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 17, 66, 70, 0.1, 500000 ); 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 17, 71, 75, 0.1, 100000 ); 
insert into TBSEG_PARAM_PRST_CAP_SEG ( IDSEQPAR, IDADEMIN, IDADEMAX, CAPITMIN, CAPITMAX ) values ( 17, 76, 80, 0.1, 50000 ); 

commit;
end;