BEGIN
create or replace view pix.tbpix_parametros_gerais as
select "CDCOOPER","FLPRODUTO_ATIVO","QTMAXIMA_CHAVES_PF","QTMAXIMA_CHAVES_PJ","QTDIAS_CHAVE_DESATIVACAO","VLMAXIMO_TRANSACAO_PF","VLMAXIMO_TRANSACAO_PJ","HRINICIO_TRANSACOES","HRFINAL_TRANSACOES","FLAGENDAMENTO_ATIVO","QTMAXRECORRENCIAS_AGENDAMENTO","HRINICIO_AGENDAMENTO","HRFINAL_AGENDAMENTO","HRINTERVALO_AGENDAMENTO","HRLEMBRETE_AGENDAMENTO","FLPROCESSAR_AGENDAMENTO","VLDIU_SAQTRO_COOPER","VLNOT_SAQTRO_COOPER","VLNOT_SAQTRO_TRAN_COOPER","VLDIU_SAQTRO_TRAN_COOPER" from "PIX"."TBPIX_PARAMETROS_GERAIS$";
comment on column PIX.TBPIX_PARAMETROS_GERAIS.HRLEMBRETE_AGENDAMENTO is 'Configuração do horário de execução do job de lembrete de agendamentos.';
comment on column PIX.TBPIX_PARAMETROS_GERAIS.FLPROCESSAR_AGENDAMENTO is 'Identifica se o processamento de agendamentos está ativo neste canal';
    COMMIT;

EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;

END;


