BEGIN

  INSERT INTO cecred.crapstf(DTMVTOLT,NRTERFIN,VLDSDINI,VLDSDFIN,CDCOOPER) VALUES (to_date('28-10-2022', 'dd-mm-yyyy'),328,0,0,1);
  INSERT INTO cecred.crapstf(DTMVTOLT,NRTERFIN,VLDSDINI,VLDSDFIN,CDCOOPER) VALUES (to_date('14-09-2022', 'dd-mm-yyyy'),280,0,0,1);
  
  COMMIT;

END;
