BEGIN
  DELETE FROM cecred.CRAPEBN WHERE cdcooper = 14 and nrdconta = 92002 and nrctremp = 2626056;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20500, SQLERRM);
END;