BEGIN

  DELETE
  FROM   CECRED.CRAPRTO
  WHERE  CDPRODUT = 1
  AND    NRTABELA = 4
  AND    CDOPERAC = 'I'
  AND    CDRETORN >= 301;
  
  DELETE
  FROM   CECRED.CRAPRTO
  WHERE  CDPRODUT = 1
  AND    NRTABELA = 3
  AND    CDOPERAC = 'C'
  AND    CDRETORN in (55,999);
  
  DELETE
  FROM   CECRED.CRAPRTO
  WHERE  CDPRODUT = 1
  AND    NRTABELA = 3
  AND    CDOPERAC = 'Q'
  AND    CDRETORN in (85,999);
  
  DELETE
  FROM   CECRED.CRAPRTO
  WHERE  CDPRODUT = 1
  AND    NRTABELA = 1
  AND    CDOPERAC = 'O'
  AND    CDRETORN in (35,40,41,42,999);
  
  COMMIT;

END;