/* RITM0086922 */
INSERT INTO crappat (CDPARTAR, NMPARTAR, TPDEDADO, CDPRODUT) VALUES (86, 'ISENTA PRIMEIRA TARIFA LIMITE ESPECIAL', 1, 0);
--
INSERT INTO crapbat (CDBATTAR, NMIDENTI, CDPROGRA, TPCADAST, CDCADAST) VALUES ('ISENTARLIM', 'ISENTA TARIFA LIMITE', ' ', 2, 86);
--
INSERT INTO crappco (CDPARTAR, CDCOOPER, DSCONTEU) VALUES (86, 1, '1');
--
INSERT INTO crappco (CDPARTAR, CDCOOPER, DSCONTEU) VALUES (86, 2, '0');
--
INSERT INTO crappco (CDPARTAR, CDCOOPER, DSCONTEU) VALUES (86, 3, '0');
--
INSERT INTO crappco (CDPARTAR, CDCOOPER, DSCONTEU) VALUES (86, 4, '0');
--
INSERT INTO crappco (CDPARTAR, CDCOOPER, DSCONTEU) VALUES (86, 5, '0');
--
INSERT INTO crappco (CDPARTAR, CDCOOPER, DSCONTEU) VALUES (86, 6, '0');
--
INSERT INTO crappco (CDPARTAR, CDCOOPER, DSCONTEU) VALUES (86, 7, '0');
--
INSERT INTO crappco (CDPARTAR, CDCOOPER, DSCONTEU) VALUES (86, 8, '0');
--
INSERT INTO crappco (CDPARTAR, CDCOOPER, DSCONTEU) VALUES (86, 9, '0');
--
INSERT INTO crappco (CDPARTAR, CDCOOPER, DSCONTEU) VALUES (86, 10, '0');
--
INSERT INTO crappco (CDPARTAR, CDCOOPER, DSCONTEU) VALUES (86, 11, '0');
--
INSERT INTO crappco (CDPARTAR, CDCOOPER, DSCONTEU) VALUES (86, 12, '0');
--
INSERT INTO crappco (CDPARTAR, CDCOOPER, DSCONTEU) VALUES (86, 13, '0');
--
INSERT INTO crappco (CDPARTAR, CDCOOPER, DSCONTEU) VALUES (86, 14, '0');
--
INSERT INTO crappco (CDPARTAR, CDCOOPER, DSCONTEU) VALUES (86, 15, '0');
--
INSERT INTO crappco (CDPARTAR, CDCOOPER, DSCONTEU) VALUES (86, 16, '0');
--
INSERT INTO crappco (CDPARTAR, CDCOOPER, DSCONTEU) VALUES (86, 17, '0');
--
COMMIT;