/* RITM0086922 */
INSERT INTO crappat (CDPARTAR, NMPARTAR, TPDEDADO, CDPRODUT) VALUES (86, 'ISENTA PRIMEIRA TARIFA LIMITE ESPECIAL', 1, 0);
--
INSERT INTO crapbat (CDBATTAR, NMIDENTI, CDPROGRA, TPCADAST, CDCADAST) VALUES ('ISENTARLIM', 'ISENTA TARIFA LIMITE', ' ', 2, 86);
--
UPDATE crappco SET cdpartar = 86 WHERE cdpartar = 85;
--
COMMIT;