
insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI)
values (789, 1, 1, 'EXTRADO DE TED', 5, ' ', '80col', 0, 1, 'Online', 1, 1, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI)
values (789, 1, 1, 'EXTRADO DE TED', 5, ' ', '80col', 0, 2, 'Online', 1, 1, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI)
values (789, 1, 1, 'EXTRADO DE TED', 5, ' ', '80col', 0, 3, 'Online', 1, 1, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI)
values (789, 1, 1, 'EXTRADO DE TED', 5, ' ', '80col', 0, 4, 'Online', 1, 1, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI)
values (789, 1, 1, 'EXTRADO DE TED', 5, ' ', '80col', 0, 5, 'Online', 1, 1, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI)
values (789, 1, 1, 'EXTRADO DE TED', 5, ' ', '80col', 0, 6, 'Online', 1, 1, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI)
values (789, 1, 1, 'EXTRADO DE TED', 5, ' ', '80col', 0, 7, 'Online', 1, 1, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI)
values (789, 1, 1, 'EXTRADO DE TED', 5, ' ', '80col', 0, 8, 'Online', 1, 1, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI)
values (789, 1, 1, 'EXTRADO DE TED', 5, ' ', '80col', 0, 9, 'Online', 1, 1, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI)
values (789, 1, 1, 'EXTRADO DE TED', 5, ' ', '80col', 0, 10, 'Online', 1, 1, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI)
values (789, 1, 1, 'EXTRADO DE TED', 5, ' ', '80col', 0, 11, 'Online', 1, 1, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI)
values (789, 1, 1, 'EXTRADO DE TED', 5, ' ', '80col', 0, 12, 'Online', 1, 1, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI)
values (789, 1, 1, 'EXTRADO DE TED', 5, ' ', '80col', 0, 13, 'Online', 1, 1, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI)
values (789, 1, 1, 'EXTRADO DE TED', 5, ' ', '80col', 0, 14, 'Online', 1, 1, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI)
values (789, 1, 1, 'EXTRADO DE TED', 5, ' ', '80col', 0, 16, 'Online', 1, 1, 1, ' ', null, null);

