BEGIN

  declare

  vr_nrctrcrd crawcrd.nrctrcrd%TYPE;
  vr_nrseqcrd crawcrd.nrseqcrd%TYPE;

  begin

  vr_nrctrcrd := fn_sequence('CRAPMAT','NRCTRCRD', 2);
  vr_nrseqcrd := CCRD0003.fn_sequence_nrseqcrd(2);

  insert into cecred.crawcrd
    (nrdconta,
    nrcrcard,
    nrcctitg,
    nrcpftit,
    vllimcrd,
    flgctitg,
    dtmvtolt,
    nmextttl,
    flgprcrd,
    tpdpagto,
    flgdebcc,
    tpenvcrd,
    vlsalari,
    dddebito,
    cdlimcrd,
    tpcartao,
    dtnasccr,
    nrdoccrd,
    nmtitcrd,
    nrctrcrd,
    cdadmcrd,
    cdcooper,
    nrseqcrd,
    dtpropos,
    dtsolici,
    flgdebit,
    cdgraupr,
    insitcrd,
    dtlibera,
    insitdec)
  values  (13163426,       
    '5127077306365813',   
    7563239788757,    
    9199720981,     
    310000,      
    3,        
    trunc(sysdate),   
    'DAMARIS DE A SILVA',  
    1,      
    1,    
    1,   
    0,   
    0,    
    11,    
    0,     
    2,    
    to_date('26/05/1992','dd/mm/yyyy'),
    '0',     
    'CARTAO PROVISORIO',   
    vr_nrctrcrd,   
    18,      
    1,      
    vr_nrseqcrd,     
    to_date('21/09/2022','dd/mm/rrrr'), 
    to_date('21/09/2022','dd/mm/rrrr'), 
    1,         
    5,       
    6,       
    trunc(sysdate),   
    2     
    );

  insert into cecred.crapcrd
    (cdcooper,
    nrdconta,
    nrcrcard,
    nrcpftit,
    nmtitcrd,
    dddebito,
    cdlimcrd,
    dtvalida,
    nrctrcrd,
    cdmotivo,
    nrprotoc,
    cdadmcrd,
    tpcartao,
    dtcancel,
    flgdebit,
    flgprovi)
  values  (1,     
    13163426,       
    '5127077306365813',  
    9199720981,    
    'CARTAO PROVISORIO', 
    11,      
    0,     
    NULL,    
    vr_nrctrcrd,   
    0,  
    0,       
    18,     
    2,     
    NULL,  
    1,   
    0      
    );

    commit;    

  vr_nrctrcrd := fn_sequence('CRAPMAT','NRCTRCRD', 2);
  vr_nrseqcrd := CCRD0003.fn_sequence_nrseqcrd(2);

  insert into cecred.crawcrd
    (nrdconta,
    nrcrcard,
    nrcctitg,
    nrcpftit,
    vllimcrd,
    flgctitg,
    dtmvtolt,
    nmextttl,
    flgprcrd,
    tpdpagto,
    flgdebcc,
    tpenvcrd,
    vlsalari,
    dddebito,
    cdlimcrd,
    tpcartao,
    dtnasccr,
    nrdoccrd,
    nmtitcrd,
    nrctrcrd,
    cdadmcrd,
    cdcooper,
    nrseqcrd,
    dtpropos,
    dtsolici,
    flgdebit,
    cdgraupr,
    insitcrd,
    dtlibera,
    insitdec)
  values  (13163426,       
    '5127077306365805',   
    7563239788757,    
    9199720981,     
    310000,      
    3,        
    trunc(sysdate),   
    'DAMARIS DE A SILVA',  
    1,      
    1,    
    1,   
    0,   
    0,    
    11,    
    0,     
    2,    
    to_date('26/05/1992','dd/mm/yyyy'),
    '0',     
    'CARTAO PROVISORIO',   
    vr_nrctrcrd,   
    18,      
    1,      
    vr_nrseqcrd,     
    to_date('21/09/2022','dd/mm/rrrr'), 
    to_date('21/09/2022','dd/mm/rrrr'), 
    1,         
    5,       
    4,       
    trunc(sysdate),   
    2     
    );

  insert into cecred.crapcrd
    (cdcooper,
    nrdconta,
    nrcrcard,
    nrcpftit,
    nmtitcrd,
    dddebito,
    cdlimcrd,
    dtvalida,
    nrctrcrd,
    cdmotivo,
    nrprotoc,
    cdadmcrd,
    tpcartao,
    dtcancel,
    flgdebit,
    flgprovi)
  values  (1,     
    13163426,       
    '5127077306365805',  
    9199720981,    
    'CARTAO PROVISORIO', 
    11,      
    0,     
    NULL,    
    vr_nrctrcrd,   
    0,  
    0,       
    18,     
    2,     
    NULL,  
    1,   
    0      
    );

  commit;    

  end;

END;
