BEGIN

  UPDATE crapprm SET DSVLRPRM = 2 WHERE NMSISTEM = 'CRED' AND CDCOOPER = 1 AND CDACESSO = 'COOP_PILOTO_LCI';
  UPDATE crapprm SET DSVLRPRM = 2 WHERE NMSISTEM = 'CRED' AND CDCOOPER = 2 AND CDACESSO = 'COOP_PILOTO_LCI';
  UPDATE crapprm SET DSVLRPRM = 2 WHERE NMSISTEM = 'CRED' AND CDCOOPER = 3 AND CDACESSO = 'COOP_PILOTO_LCI';
  UPDATE crapprm SET DSVLRPRM = 2 WHERE NMSISTEM = 'CRED' AND CDCOOPER = 5 AND CDACESSO = 'COOP_PILOTO_LCI';
  UPDATE crapprm SET DSVLRPRM = 2 WHERE NMSISTEM = 'CRED' AND CDCOOPER = 6 AND CDACESSO = 'COOP_PILOTO_LCI';
  UPDATE crapprm SET DSVLRPRM = 2 WHERE NMSISTEM = 'CRED' AND CDCOOPER = 7 AND CDACESSO = 'COOP_PILOTO_LCI';
  UPDATE crapprm SET DSVLRPRM = 2 WHERE NMSISTEM = 'CRED' AND CDCOOPER = 8 AND CDACESSO = 'COOP_PILOTO_LCI';
  UPDATE crapprm SET DSVLRPRM = 2 WHERE NMSISTEM = 'CRED' AND CDCOOPER = 9 AND CDACESSO = 'COOP_PILOTO_LCI';
  UPDATE crapprm SET DSVLRPRM = 2 WHERE NMSISTEM = 'CRED' AND CDCOOPER = 10 AND CDACESSO = 'COOP_PILOTO_LCI';
  UPDATE crapprm SET DSVLRPRM = 2 WHERE NMSISTEM = 'CRED' AND CDCOOPER = 11 AND CDACESSO = 'COOP_PILOTO_LCI';
  UPDATE crapprm SET DSVLRPRM = 2 WHERE NMSISTEM = 'CRED' AND CDCOOPER = 12 AND CDACESSO = 'COOP_PILOTO_LCI';
  UPDATE crapprm SET DSVLRPRM = 2 WHERE NMSISTEM = 'CRED' AND CDCOOPER = 13 AND CDACESSO = 'COOP_PILOTO_LCI';
  UPDATE crapprm SET DSVLRPRM = 2 WHERE NMSISTEM = 'CRED' AND CDCOOPER = 14 AND CDACESSO = 'COOP_PILOTO_LCI';
  UPDATE crapprm SET DSVLRPRM = 2 WHERE NMSISTEM = 'CRED' AND CDCOOPER = 16 AND CDACESSO = 'COOP_PILOTO_LCI';
 
  COMMIT;
 
EXCEPTION

  WHEN OTHERS THEN
    ROLLBACK;

END;
