CREATE OR REPLACE TRIGGER CECRED.TRG_CRAPRDR_NRSEQRDR
  BEFORE INSERT ON craprdr
  FOR EACH ROW
BEGIN
  -- Buscar sequencia para PK da tabela caso nao foi passada
  IF :new.nrseqrdr IS NULL THEN
    :NEW.NRSEQRDR := SEQRDR_NRSEQRDR.NEXTVAL;
  END IF;
END TRG_CRAPRDR_NRSEQRDR;
/

