CREATE OR REPLACE TRIGGER CECRED.TRG_CRAPGSG_PROGRESS_RECID
BEFORE INSERT ON CRAPGSG

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := CRAPGSG_SEQ.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20100,'ERRO GERACAO SEQUENCE PROGRESS_RECID - TABELA CRAPGSG!');

END;
/

