CREATE OR REPLACE TRIGGER CECRED.TRG_tbcrd_fatura_PRG_RECID
BEFORE INSERT ON CECRED.tbcrd_fatura

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := tbcrd_fatura_seq.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20100,'ERRO GERACAO SEQUENCE PROGRESS_RECID - TABELA tbcrd_fatura!');

END;
/

