CREATE OR REPLACE TRIGGER CECRED.TRG_CRAPAUT_PROGRESS_RECID
BEFORE INSERT ON CRAPAUT

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := CRAPAUT_SEQ.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20100,'ERRO GERACAO SEQUENCE PROGRESS_RECID - TABELA CRAPAUT!');

END;
/

