CREATE OR REPLACE TRIGGER CECRED.TRG_CRAPDRM_PROGRESS_RECID
BEFORE INSERT ON CRAPDRM

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := CRAPDRM_SEQ.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20100,'ERRO GERACAO SEQUENCE PROGRESS_RECID - TABELA CRAPDRM!');

END;
/

