CREATE OR REPLACE TRIGGER CECRED."TRG_OPER_DIARIAS_PROG_RECID"
BEFORE INSERT ON TBCC_OPERACOES_DIARIAS

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := TBCC_OPERACOES_DIARIAS_SEQ.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20100,'ERRO GERACAO SEQUENCE PROGRESS_RECID - TABELA TBCC_OPERACOES_DIARIAS_SEQ!');

END;
/

