CREATE OR REPLACE TRIGGER CECRED.TRG_inss_agend_gps_PROG_RECID
BEFORE INSERT ON tbinss_agendamento_gps

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := tbinss_agendamento_gps_SEQ.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20100,'ERRO GERACAO SEQUENCE PROGRESS_RECID - TABELA tbinss_agendamento_gps!');

END;
/

