CREATE OR REPLACE TRIGGER CECRED.TRG_CRAPGER_PROGRESS_RECID
BEFORE INSERT ON CRAPGER

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := CRAPGER_SEQ.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20100,'ERRO GERACAO SEQUENCE PROGRESS_RECID - TABELA CRAPGER!');

END;
/

