CREATE OR REPLACE TRIGGER CECRED.TRG_CRAPCOL_PROGRESS_RECID
BEFORE INSERT ON CRAPCOL

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := CRAPCOL_SEQ.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20100,'ERRO GERACAO SEQUENCE PROGRESS_RECID - TABELA CRAPCOL!');

END;
/

