CREATE OR REPLACE TRIGGER CECRED.TRG_CRAPCFP_PROGRESS_RECID
BEFORE INSERT ON CRAPCFP

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := CRAPCFP_SEQ.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20000,'ERRO GERACAO SEQUENCE PROGRESS_RECID - TABELA CRAPCFP!');

END;
/

