CREATE OR REPLACE TRIGGER CECRED.TRG_CRAPDDA_NRSEQDDA
BEFORE INSERT ON CRAPDDA
FOR EACH ROW
BEGIN
  -- Buscar sequencia para PK da tabela caso não foi passada
  IF :new.nrseqdda IS NULL THEN
    SELECT CRAPDDA_NRSEQDDA.NEXTVAL INTO :NEW.NRSEQDDA FROM DUAL;
  END IF;
END;
/

