CREATE OR REPLACE TRIGGER CECRED.TRG_CRAPCDR_PROGRESS_RECID
BEFORE INSERT ON cecred.CRAPCDR

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := cecred.CRAPCDR_SEQ.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20100,'ERRO GERACAO sequence CECRED.PROGRESS_RECID - TABELA CRAPCDR!');

END;
/

