CREATE OR REPLACE TRIGGER CECRED.TRG_CRAPSLE_NRSEQSOL
BEFORE INSERT ON CRAPSLE
FOR EACH ROW
BEGIN
  -- Buscar sequencia para PK da tabela caso não foi passada
  IF :new.nrseqsol IS NULL THEN
    SELECT CRAPSLE_NRSEQSOL.NEXTVAL INTO :NEW.NRSEQSOL FROM DUAL;
  END IF;
END;
/

