CREATE OR REPLACE TRIGGER CECRED.TRG_TBGEN_LAYOUT_CAMPO
BEFORE INSERT ON CECRED.tbgen_layout_campo
FOR EACH ROW
BEGIN
IF :NEW.IDCAMPO_LAYOUT IS NULL THEN
:NEW.IDCAMPO_LAYOUT := SEQ_IDCAMPO_LAYOUT.NEXTVAL;
END IF;
EXCEPTION
WHEN OTHERS THEN
RAISE_APPLICATION_ERROR(-20100,'ERRO GERACAO SEQUENCE IDLAYOUT - TABELA tbgen_layout_campo!');
END;
/

