CREATE OR REPLACE TRIGGER CECRED.TRG_CRAPIPC_PROGRESS_RECID
BEFORE INSERT ON CRAPIPC

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := CRAPIPC_SEQ.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20100,'ERRO GERACAO SEQUENCE PROGRESS_RECID - TABELA CRAPIPC!');

END;
/

