CREATE OR REPLACE TRIGGER CECRED.TRG_CRAPCEM_PROGRESS_RECID
BEFORE INSERT ON CRAPCEM

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := CRAPCEM_SEQ.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20100,'ERRO GERACAO SEQUENCE PROGRESS_RECID - TABELA CRAPCEM!');

END;
/

