CREATE OR REPLACE TRIGGER CECRED.TRG_CRAPALT_PROGRESS_RECID
BEFORE INSERT ON CRAPALT

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := CRAPALT_SEQ.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20100,'ERRO GERACAO SEQUENCE PROGRESS_RECID - TABELA CRAPALT!');

END;
/

