CREATE OR REPLACE TRIGGER CECRED.TRG_CRAPBCX_PROGRESS_RECID
BEFORE INSERT ON CRAPBCX

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := CRAPBCX_SEQ.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20100,'ERRO GERACAO SEQUENCE PROGRESS_RECID - TABELA CRAPBCX!');

END;
/

