CREATE OR REPLACE TRIGGER CECRED.TRG_CRAPRLI_PROGRESS_RECID
BEFORE INSERT ON CECRED.CRAPRLI

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := CRAPRLI_SEQ.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20100,'ERRO GERACAO sequence CECRED.PROGRESS_RECID - TABELA CRAPRLI!');

END;
/

