CREATE OR REPLACE TRIGGER CECRED.TRG_CRAPCYC_PROGRESS_RECID
BEFORE INSERT ON CRAPCYC

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := CRAPCYC_SEQ.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20100,'ERRO GERACAO SEQUENCE PROGRESS_RECID - TABELA CRAPCYC!');

END;
/

