CREATE OR REPLACE TRIGGER CECRED.TRG_TBHISTOR_CARTOES_SOA
BEFORE INSERT ON CECRED.TBHISTOR_CARTOES_SOA

FOR EACH ROW

BEGIN
  SELECT CECRED.SEQ_TBHISTOR_CARTOES_SOA.NEXTVAL
    INTO :NEW.IDALTERACAO
    FROM DUAL;
EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20100,'ERRO GERACAO SEQUENCE IDALTERACAO - TABELA TBHISTOR_CARTOES_SOA!');
END;
/