CREATE OR REPLACE TRIGGER CECRED.TRGDOMIC_LIQTRANS_ARQUIVO_ID
  BEFORE INSERT ON CECRED.TBDOMIC_LIQTRANS_ARQUIVO
  FOR EACH ROW
BEGIN
    SELECT CECRED.SEQDOMIC_LIQTRANS_ARQUIVO_ID.NEXTVAL
    INTO :NEW.idarquivo
    FROM DUAL;
END;
