CREATE OR REPLACE TRIGGER CECRED.TRGDOMIC_LIQTRANS_LANCTO_ID
  BEFORE INSERT ON CECRED.TBDOMIC_LIQTRANS_LANCTO
  FOR EACH ROW
BEGIN
    SELECT CECRED.SEQDOMIC_LIQTRANS_LANCTO_ID.NEXTVAL
    INTO :NEW.idlancto
    FROM DUAL;
END;
