create trigger CECRED.TRGDOMIC_MENSAGEM_LIQ_LTR_STR
before insert on CECRED.TBDOMIC_MENSAGEM_LIQ_LTR_STR
for each row
BEGIN
  SELECT CECRED.SEQDOMIC_MENS_LIQ_LTR_STR_ID.NEXTVAL
  INTO :NEW.idmensagem
  FROM DUAL;
END;