create trigger CECRED.TRGDOMIC_MENSAGEM_LIQUID_ID
before insert on CECRED.TBDOMIC_MENSAGEM_LIQUIDACAO
for each row
BEGIN
  SELECT CECRED.SEQDOMIC_MENSAGEM_LIQUID_ID.NEXTVAL
  INTO :NEW.idmensagem
  FROM DUAL;
END;