create trigger CECRED.TRGDOMIC_MOTIVO_ERRO_ID
before insert on CECRED.TBDOMIC_MOTIVO_ERRO
for each row
BEGIN
  SELECT CECRED.SEQDOMIC_MOTIVO_ERRO_ID.NEXTVAL
  INTO :NEW.IDMOTIVOERRO
  FROM DUAL;
END;