create trigger CECRED.TRGDOMIC_MENSAGEM_LIQUIDACAO_ID
befor insert on CECRED.TBDOMIC_MENSAGEM_LIQUIDACAO
for each row
BEGIN
  SELECT CECRED.SEQDOMIC_MENSAGEM_LIQUIDACAO_ID.NEXTVAL
  INTO :NEW.idmensagem
  FROM DUAL;
END;