create trigger CECRED.TRGDOMIC_LIQTRANS_MENS_LTR_STR
before insert on CECRED.TBDOMIC_LIQTRANS_MENS_LTR_STR
for each row
BEGIN
  SELECT CECRED.SEQDOMIC_LIQ_MENS_LTR_STR_ID.NEXTVAL
  INTO :NEW.idmensagem
  FROM DUAL;
END;
/