create trigger CECRED.TRGDOMIC_LIQTRANS_MENSAGEM_SLC
before insert on CECRED.TBDOMIC_LIQTRANS_MENSAGEM_SLC
for each row
BEGIN
  SELECT CECRED.SEQDOMIC_LIQ_MENSAGEM_SLC_ID.NEXTVAL
  INTO :NEW.idmensagem
  FROM DUAL;
END;
/