-- Cargas dos dominios da lista de poderes
INSERT INTO TBCC_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
VALUES ('LISTAPODERES', '1', 'Emitir Cheques');

INSERT INTO TBCC_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
VALUES ('LISTAPODERES', '2', 'Endossar Cheques');

INSERT INTO TBCC_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
VALUES ('LISTAPODERES', '3', 'Autorizar Debitos');

INSERT INTO TBCC_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
VALUES ('LISTAPODERES', '4', 'Requisitar Taloes');

INSERT INTO TBCC_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
VALUES ('LISTAPODERES', '5', 'Assinar Contratos de Emprst/Financ');

INSERT INTO TBCC_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
VALUES ('LISTAPODERES', '6', 'Substabelecer');

INSERT INTO TBCC_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
VALUES ('LISTAPODERES', '7', 'Receber');

INSERT INTO TBCC_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
VALUES ('LISTAPODERES', '8', 'Passar Recibo');

INSERT INTO TBCC_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
VALUES ('LISTAPODERES', '9', 'Outros Poderes');

INSERT INTO TBCC_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
VALUES ('LISTAPODERES', '10', 'Assinar Operacao Autoatendimento');

