insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('INSITUACAO_RATING', '0', 'Não Enviado');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('INSITUACAO_RATING', '1', 'Em Análise');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('INSITUACAO_RATING', '2', 'Analisado');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('INSITUACAO_RATING', '3', 'Vencido');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('INSITUACAO_RATING', '4', 'Efetivado');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('INSITUACAO_RATING', '5', 'Efetivo Vencido');


insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('INORIGEM_RATING', '1', 'MOTOR');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('INORIGEM_RATING', '2', 'ESTEIRA');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('INORIGEM_RATING', '3', 'REGRA AIMARO');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('INORIGEM_RATING', '4', 'CONTINGÊNCIA');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('INORIGEM_RATING', '5', 'HERDADO DO LIMITE');


insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('CDMODALI', '1901', 'LIMITE DE CREDITO NÃO UTILIZADO');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('CDMODALI', '201', 'LIMITE DE CREDITO UTILIZADO');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('CDMODALI', '101', 'ADIANTAMENTO A DEPOSITANTE');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('CDMODALI', '301', 'DESCONTO DE TÍTULO');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('CDMODALI', '302', 'DESCONTO DE CHEQUE');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('CDMODALI', '499', 'FINANCIAMENTO');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('CDMODALI', '299', 'EMPRÉSTIMO');


INSERT INTO tbgen_dominio_campo (nmdominio, cddominio, dscodigo)
    VALUES ('INBIRO_IBRATAN',1,'Biro BOA VISTA (BVS)');
    
INSERT INTO tbgen_dominio_campo (nmdominio, cddominio, dscodigo)
    VALUES ('INBIRO_IBRATAN',2,'Biro SERASA');


insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
     values ('INMODELO_IBRATAN', '1', 'Cálculo Aimaro');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
     values ('INMODELO_IBRATAN', '2', 'Cálculo Ibratan');


insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('TPCTRATO', '1', 'Limite de Crédito');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('TPCTRATO', '2', 'Limite de Desconto de Cheque');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('TPCTRATO', '3', 'Limite de Desconto de Título');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('TPCTRATO', '68', 'Pré-Aprovado');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('TPCTRATO', '90', 'Empréstimos/Financiamentos');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('TPCTRATO', '91', 'Borderôs de descontos de Títulos');

insert into TBGEN_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO)
values ('TPCTRATO', '92', 'Borderôs de descontos de Cheques');

COMMIT;
  