CREATE table TBCRD_PREAPROV_EXCLUSOES (
SKCARGA NUMBER(10) NOT NULL,
CDCOOPER NUMBER(3) NOT NULL,
TPPESSOA NUMBER(1) NOT NULL,
NRCPFCNPJBASE NUMBER(14) NOT NULL,
CDEXCLUSAO NUMBER(10) NOT NULL,
DSEXCLUSAO VARCHAR2(255) NOT NULL
);

COMMENT ON TABLE TBCRD_PREAPROV_EXCLUSOES IS
'Armazena as exclusoes dos cooperados que nao possuem pre-aprovado de cartoes de credito.';

COMMENT ON COLUMN TBCRD_PREAPROV_EXCLUSOES.SKCARGA IS
'Chave artificial de identificacao da carga';

COMMENT ON COLUMN TBCRD_PREAPROV_EXCLUSOES.CDCOOPER IS
'Codigo da cooperativa';

COMMENT ON COLUMN TBCRD_PREAPROV_EXCLUSOES.TPPESSOA IS
'Identificacao do tipo de pessoa (1=PF, 2=PJ)';

COMMENT ON COLUMN TBCRD_PREAPROV_EXCLUSOES.NRCPFCNPJBASE IS
'Numero do cpf ou cnpj base ao qual o limite potencial pertence';

COMMENT ON COLUMN TBCRD_PREAPROV_EXCLUSOES.CDEXCLUSAO IS
'Codigo da exclusao do cooperado';

COMMENT ON COLUMN TBCRD_PREAPROV_EXCLUSOES.DSEXCLUSAO IS
'Descricao da exclusao do cooperado';

ALTER TABLE TBCRD_PREAPROV_EXCLUSOES
ADD CONSTRAINT TBCRD_PREAPROV_EXCLUSOES_PK PRIMARY KEY ( SKCARGA, CDCOOPER );

ALTER TABLE TBCRD_PREAPROV_EXCLUSOES
ADD CONSTRAINT TBCRD_PREAPROV_EXCLUSOES_UK UNIQUE (SKCARGA, CDCOOPER, TPPESSOA, NRCPFCNPJBASE, CDEXCLUSAO);

ALTER TABLE TBCRD_PREAPROV_EXCLUSOES ADD CONSTRAINT TBCRD_PREAPROV_EXCLUSOES_FK FOREIGN KEY (SKCARGA, CDCOOPER)
REFERENCES TBCRD_PREAPROV_CARGA(SKCARGA, CDCOOPER);   
  
  

