-- Carga para os de/para do status da crawcrd para os status do canais 

BEGIN
INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO)
VALUES ('STATUSCRDCANAIS', '101', 'Aguardando Autorização
', 0);

INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO)
VALUES ('STATUSCRDCANAIS', '102', 'Aguardando Aprovação
', 0);

INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO)
VALUES ('STATUSCRDCANAIS', '103', 'Aguardando Entrega
', 0);

COMMIT;
END ;