DECLARE    

BEGIN

    INSERT INTO CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR)
	VALUES ('BUSCA_LIMITES_OPERACIONAIS', 'CCRD0009', 'pccrd_buscar_limites_ope', 'pr_cdcooperativa', (SELECT NRSEQRDR FROM craprdr WHERE nmprogra = 'CCRD0009'));
    COMMIT;

	
END;
