CREATE TABLE TBCRD_PREAPROV_RECUSA (
    IDRECUSADO       NUMBER(10)    NOT NULL,
    IDLIMITE         NUMBER(10)    NOT NULL,
    SKCARGA          NUMBER(10)    NOT NULL,
    CDCOOPER         NUMBER(3)     NOT NULL,
    TPPESSOA         NUMBER(1)     NOT NULL,
    NRCPFCNPJ        NUMBER(14)    NOT NULL,    
	NRDCONTA         NUMBER(10)    NOT NULL,
	CDOPERAD         VARCHAR2(10)    NOT NULL,
    CDDOMINIO        NUMBER(10)    NOT NULL,
    DTRECUSA         DATE          NOT NULL
);

COMMENT ON TABLE TBCRD_PREAPROV_RECUSA IS 
	'Tabela de motivo de recusa de limite preaprovado pelo cooperado';

COMMENT ON COLUMN TBCRD_PREAPROV_RECUSA.IDRECUSADO IS
    'Chave artificial de identificacao da recusa';

COMMENT ON COLUMN TBCRD_PREAPROV_RECUSA.IDLIMITE IS
    'Chave artificial de identificacao do limite';

COMMENT ON COLUMN TBCRD_PREAPROV_RECUSA.SKCARGA IS
    'Chave artificial de identificacao da carga';

COMMENT ON COLUMN TBCRD_PREAPROV_RECUSA.CDCOOPER IS
    'CÃ³digo da cooperativa';

COMMENT ON COLUMN TBCRD_PREAPROV_RECUSA.TPPESSOA IS
    'Identificacao do tipo de pessoa (1 = PF, 2 = PJ)';

COMMENT ON COLUMN TBCRD_PREAPROV_RECUSA.NRCPFCNPJ IS
    'Numero do CPF ou CNPJ base ao qual o limite potencial pertence';

COMMENT ON COLUMN TBCRD_PREAPROV_RECUSA.NRDCONTA IS
    'Numero da conta';

COMMENT ON COLUMN TBCRD_PREAPROV_RECUSA.CDOPERAD IS
    'Codigo do Operador';

COMMENT ON COLUMN TBCRD_PREAPROV_RECUSA.CDDOMINIO IS
    'Codigo do motivo da exclusao, relacionado a tabela tbcrd_dominio_campo';

COMMENT ON COLUMN TBCRD_PREAPROV_RECUSA.DTRECUSA IS
    'Data de recusa';

ALTER TABLE TBCRD_PREAPROV_RECUSA ADD CONSTRAINT TBCRD_PREAPROV_RECUSA_PK PRIMARY KEY ( IDRECUSADO, CDCOOPER, NRDCONTA );

ALTER TABLE TBCRD_PREAPROV_RECUSA ADD CONSTRAINT TBCRD_PREAPROV_RECUSA_FK FOREIGN KEY (IDLIMITE, SKCARGA, CDCOOPER, TPPESSOA, NRCPFCNPJ)
  REFERENCES TBCRD_PREAPROV_LIMITE(IDLIMITE, SKCARGA, CDCOOPER, TPPESSOA, NRCPFCNPJ); 
