UPDATE CRAPTTL
   SET DSNATURA = 'EMBU'
 WHERE DSNATURA = 'EMBU DAS ARTES';

UPDATE CRAPMUN
   SET DSCIDADE = 'EMBU'
 WHERE DSCIDADE = 'EMBU DAS ARTES';

UPDATE CRAPNAT
   SET DSNATURA = 'EMBU'
 WHERE DSNATURA = 'EMBU DAS ARTES';
   
   
 
-- Efetuar commit 
COMMIT;
