BEGIN
  EXECUTE IMMEDIATE 'ALTER TRIGGER CECRED.TRG_TBCADAST_PESSOA_EMAIL_ATLZ DISABLE';
	UPDATE TBCADAST_PESSOA_EMAIL
	SET INSITUACAO = 1 --ATIVO
	WHERE INSITUACAO IS NULL;
  COMMIT;
  EXECUTE IMMEDIATE 'ALTER TRIGGER CECRED.TRG_TBCADAST_PESSOA_EMAIL_ATLZ ENABLE';
END;
