

UPDATE CRAPTTL
   SET DSNATURA = 'EMBU DAS ARTES'
 WHERE DSNATURA = 'EMBU';

UPDATE CRAPMUN
   SET DSCIDADE = 'EMBU DAS ARTES'
 WHERE DSCIDADE = 'EMBU';

UPDATE CRAPNAT
   SET DSNATURA = 'EMBU DAS ARTES'
 WHERE DSNATURA = 'EMBU';
   
 
-- Efetuar commit 
COMMIT;
