BEGIN
  insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.01.01.001',upper(gene0007.fn_caract_acento('Pagamentos de boletos diversos, convênios, DAS, DARF e GPS; ')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.01.01.002',upper(gene0007.fn_caract_acento('Saque')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.01.01.003',upper(gene0007.fn_caract_acento('Depósito')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.01.01.004',upper(gene0007.fn_caract_acento('Recarga Telefônica')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.01.01.005',upper(gene0007.fn_caract_acento('Transferência (para o Sistema CECRED e TEDs);')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.01.01.006',upper(gene0007.fn_caract_acento('Contratação de crédito pré-aprovado;')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.01.01.007',upper(gene0007.fn_caract_acento('Consulta de saldo, extrato')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.01.01.008',upper(gene0007.fn_caract_acento('Investimento (aplicação e resgate);')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.02.01.001',upper(gene0007.fn_caract_acento('Pagamentos de boletos diversos, convênios, DAS, DARF e GPS; ')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.02.01.002',upper(gene0007.fn_caract_acento('Saque')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.02.01.003',upper(gene0007.fn_caract_acento('Depósito')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.02.01.004',upper(gene0007.fn_caract_acento('Recarga Telefônica')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.02.01.005',upper(gene0007.fn_caract_acento('Transferência (para o Sistema CECRED e TEDs);')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.02.01.006',upper(gene0007.fn_caract_acento('Investimento (aplicação e resgate);')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.03.01.001',upper(gene0007.fn_caract_acento('Consulta de saldo, extrato')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.03.01.002',upper(gene0007.fn_caract_acento('Pagamentos de boletos diversos, convênios, DAS, DARF e GPS; ')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.03.01.003',upper(gene0007.fn_caract_acento('Pagamento DDA - Débito Direto Autorizado')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.03.01.004',upper(gene0007.fn_caract_acento('Débito automático;')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.03.01.005',upper(gene0007.fn_caract_acento('Transferência (para o Sistema CECRED e TEDs);')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.03.01.006',upper(gene0007.fn_caract_acento('Contratação de crédito pré-aprovado;')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.03.01.007',upper(gene0007.fn_caract_acento('Solicitação de empréstimo; ')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.03.01.008',upper(gene0007.fn_caract_acento('Investimento (aplicação e resgate);')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.03.01.009',upper(gene0007.fn_caract_acento('Pagamento de parcelas e liquidação de contratos de empréstimos (Price Pré-Fixado)')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.03.01.010',upper(gene0007.fn_caract_acento('Recarga de Celular')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.04.01.001',upper(gene0007.fn_caract_acento('Login por leitor de digital ou reconhecimento facial')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.04.01.002',upper(gene0007.fn_caract_acento('Primeiro acesso a Conta Online;')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.04.01.003',upper(gene0007.fn_caract_acento('Consulta de saldo, extrato, agendamento, comprovante, empréstimo e lançamentos futuros;')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.04.01.004',upper(gene0007.fn_caract_acento('Pagamentos de boletos diversos, convênios, DAS, DARF e GPS; ')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.04.01.005',upper(gene0007.fn_caract_acento('Pagamento DDA - Débito Direto Autorizado')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.04.01.006',upper(gene0007.fn_caract_acento('Débito automático;')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.04.01.007',upper(gene0007.fn_caract_acento('Transferência (para o Sistema CECRED e TEDs);')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.04.01.008',upper(gene0007.fn_caract_acento('Contratação de crédito pré-aprovado;')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.04.01.009',upper(gene0007.fn_caract_acento('Solicitação de empréstimo; ')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.04.01.010',upper(gene0007.fn_caract_acento('Investimento (aplicação e resgate);')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.04.01.011',upper(gene0007.fn_caract_acento('Pagamento de parcelas e liquidação de contratos de empréstimos (Price Pré-Fixado)')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.04.01.012',upper(gene0007.fn_caract_acento('Recarga de Celular')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.05.01.001',upper(gene0007.fn_caract_acento('Depósito a Prazo')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.05.01.002',upper(gene0007.fn_caract_acento('Deposito a Vista')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.05.01.003',upper(gene0007.fn_caract_acento('Cota Capital ')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.06.01.001',upper(gene0007.fn_caract_acento('Admissão de Sócios e Abertura de Conta')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.06.01.002',upper(gene0007.fn_caract_acento('​Desligamento de Sócios e Encerramento de Conta​')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.07.01.001',upper(gene0007.fn_caract_acento('Protesto de Títulos ')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.07.01.002',upper(gene0007.fn_caract_acento('Negativação de boletos')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.07.01.003',upper(gene0007.fn_caract_acento('Emissão de Boletos ')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.07.01.004',upper(gene0007.fn_caract_acento('Adesão a Cobrança ')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.07.01.005',upper(gene0007.fn_caract_acento('Cobrança Registrada')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.07.01.006',upper(gene0007.fn_caract_acento('Recebimento de pagamentos')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.08.01.001',upper(gene0007.fn_caract_acento('Depósito de cheques da cooperativa (sr)')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.08.01.002',upper(gene0007.fn_caract_acento('Depósito de cheques de terceiros (nr)')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.08.01.003',upper(gene0007.fn_caract_acento('Custódia de Cheques')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.08.01.004',upper(gene0007.fn_caract_acento('Pagamento de cheques')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.08.01.005',upper(gene0007.fn_caract_acento('Sustação de pagamento de cheques')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.08.01.006',upper(gene0007.fn_caract_acento('Devolução de Cheques de terceiros')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.08.01.007',upper(gene0007.fn_caract_acento('Cancelamento da folha do talonário')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.08.01.008',upper(gene0007.fn_caract_acento('Cancelamento utilização do Produto')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.08.01.009',upper(gene0007.fn_caract_acento('Talonário de cheques')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.09.01.001',upper(gene0007.fn_caract_acento('Consorcio Auto')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.09.01.002',upper(gene0007.fn_caract_acento('Consorcio Imóvel')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.09.01.003',upper(gene0007.fn_caract_acento('Consorcio Moto')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.09.01.004',upper(gene0007.fn_caract_acento('Consorcio Pesados')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.09.01.005',upper(gene0007.fn_caract_acento('Consorcio Serviços')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.09.01.006',upper(gene0007.fn_caract_acento('Lance')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.10.01.001',upper(gene0007.fn_caract_acento('Cartões Cielo')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.10.01.002',upper(gene0007.fn_caract_acento('Cartões Sipag')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.10.01.003',upper(gene0007.fn_caract_acento('Cartões Rede')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.11.01.001',upper(gene0007.fn_caract_acento('Folha de Pagamento')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.11.01.002',upper(gene0007.fn_caract_acento('Pagamentos de títulos e faturas')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.11.01.003',upper(gene0007.fn_caract_acento('Débito direto autorizado (DDA)')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.11.01.004',upper(gene0007.fn_caract_acento('Recarga de Celular')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.11.01.005',upper(gene0007.fn_caract_acento('Pagamento de boletos por arquivo')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.12.01.001',upper(gene0007.fn_caract_acento('Admissão de Cooperado')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.12.01.002',upper(gene0007.fn_caract_acento('Demissão de Cooperado')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.13.01.001',upper(gene0007.fn_caract_acento('Operações de Crédito - Empréstimo')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.13.01.002',upper(gene0007.fn_caract_acento('Propostas')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.13.01.003',upper(gene0007.fn_caract_acento('Crédito Pré-aprovado')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.13.01.004',upper(gene0007.fn_caract_acento('CDC')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.13.01.005',upper(gene0007.fn_caract_acento('Renovação Limite de crédito')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.13.01.006',upper(gene0007.fn_caract_acento('Desconto de Títulos')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.13.01.007',upper(gene0007.fn_caract_acento('Desconto de Cheques')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.13.01.008',upper(gene0007.fn_caract_acento('Crédito de repasse')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.13.01.009',upper(gene0007.fn_caract_acento('Crédito consignado')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.13.01.010',upper(gene0007.fn_caract_acento('Prazo Médio de Liberação')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.14.01.001',upper(gene0007.fn_caract_acento('Aplicação')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.14.01.002',upper(gene0007.fn_caract_acento('Resgate')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.14.01.003',upper(gene0007.fn_caract_acento('RDC Pós - Fixado')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.14.01.004',upper(gene0007.fn_caract_acento('RDC Pré - Fixado')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.14.01.005',upper(gene0007.fn_caract_acento('Popança programada')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.14.01.006',upper(gene0007.fn_caract_acento('Cota Capital ')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.15.01.001',upper(gene0007.fn_caract_acento('Seguro Empresarial e Vida em Grupo')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.15.01.002',upper(gene0007.fn_caract_acento('Seguro Automóvel')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.15.01.003',upper(gene0007.fn_caract_acento('Seguro Residencial')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.15.01.004',upper(gene0007.fn_caract_acento('Seguro Prestamista')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.15.01.005',upper(gene0007.fn_caract_acento('Seguro Vida Individual (CHUBB)')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.15.01.006',upper(gene0007.fn_caract_acento('Seguro AP (Acidentes Pessoais) - Estagiário e Vida Exclusiva (PREVISUL)')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.16.01.001',upper(gene0007.fn_caract_acento('Crédito em Conta Corrente')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.16.01.002',upper(gene0007.fn_caract_acento('Transmissão de Arquivos ')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.16.01.003',upper(gene0007.fn_caract_acento('Atualização Prova de Vida')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.17.01.001',upper(gene0007.fn_caract_acento('Contratação')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.17.01.002',upper(gene0007.fn_caract_acento('Portabilidade')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.17.01.003',upper(gene0007.fn_caract_acento('Resgates')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.17.01.004',upper(gene0007.fn_caract_acento('Aportes')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.17.01.005',upper(gene0007.fn_caract_acento('Sinistros')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.18.01.001',upper(gene0007.fn_caract_acento('Suprimento')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.18.01.002',upper(gene0007.fn_caract_acento('Recolhimento')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.19.01.001',upper(gene0007.fn_caract_acento('Parceiro Comercial - Sicredi')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.19.01.002',upper(gene0007.fn_caract_acento('Parceiro Comercial - Sicoob')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.19.01.003',upper(gene0007.fn_caract_acento('Devolução de Cheques')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.19.01.004',upper(gene0007.fn_caract_acento('Depósito de cheque ')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.19.01.005',upper(gene0007.fn_caract_acento('Pagamento de boletos')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.19.01.006',upper(gene0007.fn_caract_acento('Compensação de Títulos')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.19.01.007',upper(gene0007.fn_caract_acento('Inclusão CCF')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.19.01.008',upper(gene0007.fn_caract_acento('Exclusão CCF')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.20.01.001',upper(gene0007.fn_caract_acento('BNDES')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.20.01.002',upper(gene0007.fn_caract_acento('BRDE')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.20.01.003',upper(gene0007.fn_caract_acento('Caixa Econômica')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.20.01.004',upper(gene0007.fn_caract_acento('Bradesco')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.21.01.001',upper(gene0007.fn_caract_acento('Fluxo financeiro')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.21.01.002',upper(gene0007.fn_caract_acento('Investimentos')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.21.01.003',upper(gene0007.fn_caract_acento('Fundos de reserva')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.21.01.004',upper(gene0007.fn_caract_acento('Conciliação bancária')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.22.01.001',upper(gene0007.fn_caract_acento('Pagamento obrigatório de remessa de boletos e DOCs')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.22.01.002',upper(gene0007.fn_caract_acento('Pagamento obrigatório de remessa de cheques')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.22.01.003',upper(gene0007.fn_caract_acento('Requisições de Cooperados - TED e TEC')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.22.01.004',upper(gene0007.fn_caract_acento('Conciliação diária do SPB')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.22.01.005',upper(gene0007.fn_caract_acento('Requisições Internas ')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.22.01.006',upper(gene0007.fn_caract_acento('Despesas em geral do SPB')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.22.01.007',upper(gene0007.fn_caract_acento('Ressarcimento  de TIB')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.22.01.008',upper(gene0007.fn_caract_acento('Adequação normativa')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.22.01.009',upper(gene0007.fn_caract_acento('Cadastro e manutenção de usuários e limites')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.23.01.001',upper(gene0007.fn_caract_acento('Cobrança PA fixa')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.23.01.002',upper(gene0007.fn_caract_acento('Gestão processual de crédito')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.23.01.003',upper(gene0007.fn_caract_acento('Cobrança Extrajudicial ')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.23.01.004',upper(gene0007.fn_caract_acento('Análise e envio da cobrança judicial')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.23.01.005',upper(gene0007.fn_caract_acento('Acordos')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.23.01.006',upper(gene0007.fn_caract_acento('Notificação de cobrança')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.23.01.007',upper(gene0007.fn_caract_acento('Prestação de contas pela assessoria de cobrança')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.24.01.001',upper(gene0007.fn_caract_acento('Assessoria Jurídica')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.24.01.002',upper(gene0007.fn_caract_acento('Contencioso')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.24.01.003',upper(gene0007.fn_caract_acento('Circularizações')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.24.01.004',upper(gene0007.fn_caract_acento('Tratamento de ordem Judicial')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.24.01.005',upper(gene0007.fn_caract_acento('RDR')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.24.01.006',upper(gene0007.fn_caract_acento('Analise Jurídica de Contratos Firmados pela Ailos')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.24.01.007',upper(gene0007.fn_caract_acento('Societário')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.24.01.009',upper(gene0007.fn_caract_acento('Gestão de Contratos')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.25.01.001',upper(gene0007.fn_caract_acento('Pagamentos')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.25.01.002',upper(gene0007.fn_caract_acento('Repasse e cobrança de convênios')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.25.01.003',upper(gene0007.fn_caract_acento('Prestação de contas de despesas de viagem')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.26.01.001',upper(gene0007.fn_caract_acento('Controles de CDBs')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.26.01.002',upper(gene0007.fn_caract_acento('Centralização de controle de impostos Federais e Municipais')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.26.01.003',upper(gene0007.fn_caract_acento('Obrigações acessórias Federais e Municipais')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.27.01.001',upper(gene0007.fn_caract_acento('DigiDoc')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.28.01.001',upper(gene0007.fn_caract_acento('Gestão de Fornecedores')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.28.01.002',upper(gene0007.fn_caract_acento('Requisição de Compras')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.28.01.003',upper(gene0007.fn_caract_acento('Cotação e pedido de compras')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.28.01.004',upper(gene0007.fn_caract_acento('Gestão de contratação de serviços de terceiros')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.29.01.001',upper(gene0007.fn_caract_acento('Orçamento Central')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.29.01.002',upper(gene0007.fn_caract_acento('Orçamento Filiadas')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.30.01.001',upper(gene0007.fn_caract_acento('Conciliações diárias - Filiadas e Central')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.30.01.002',upper(gene0007.fn_caract_acento('Fechamento mensal Filiadas e Central')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.30.01.003',upper(gene0007.fn_caract_acento('Demonstrações Contábeis')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.30.01.004',upper(gene0007.fn_caract_acento('Criação e manutenção de históricos')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.30.01.005',upper(gene0007.fn_caract_acento('Registro e movimentação de imobilizado')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.30.01.006',upper(gene0007.fn_caract_acento('Inventário de bens imobilizado')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.30.01.007',upper(gene0007.fn_caract_acento('Bens não de uso próprio')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.31.01.001',upper(gene0007.fn_caract_acento('Folha de Pagamento')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.31.01.002',upper(gene0007.fn_caract_acento('Admissão')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.31.01.003',upper(gene0007.fn_caract_acento('Rescisão')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.32.01.001',upper(gene0007.fn_caract_acento('Criação de campanha')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.32.01.002',upper(gene0007.fn_caract_acento('Assessoria')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.32.01.003',upper(gene0007.fn_caract_acento('Desenvolvimento do release')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.33.01.001',upper(gene0007.fn_caract_acento('Desenvolvimento de campanhas')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.34.01.001',upper(gene0007.fn_caract_acento('Telecom')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.34.01.002',upper(gene0007.fn_caract_acento('Sistemas de Informação')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.34.01.003',upper(gene0007.fn_caract_acento('Infraestrutura')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.34.01.004',upper(gene0007.fn_caract_acento('Arquitetura Coorporativa')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.34.01.005',upper(gene0007.fn_caract_acento('Segurança da Informação')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.34.01.006',upper(gene0007.fn_caract_acento('Atendimento ao Usuário')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.35.01.001',upper(gene0007.fn_caract_acento('Mapeamento de Processos')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.35.01.002',upper(gene0007.fn_caract_acento('Análise e melhoria de processos')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.35.01.003',upper(gene0007.fn_caract_acento('Gestão e publicação de conteúdo normativo e de processos')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.35.01.004',upper(gene0007.fn_caract_acento('Escopo funcional de projetos')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.35.01.005',upper(gene0007.fn_caract_acento('Automatização de processos')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.36.01.001',upper(gene0007.fn_caract_acento('Projetos')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.36.01.002',upper(gene0007.fn_caract_acento('Melhorias')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.37.01.001',upper(gene0007.fn_caract_acento('Abertura de Cooperativa ')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.37.01.002',upper(gene0007.fn_caract_acento('Abertura de Posto de Atendimento')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.38.01.001',upper(gene0007.fn_caract_acento('Progrid')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.38.01.002',upper(gene0007.fn_caract_acento('Comitê Educativo')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.38.01.003',upper(gene0007.fn_caract_acento('SOA')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.38.01.004',upper(gene0007.fn_caract_acento('Eventos Assembleares')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.39.01.001',upper(gene0007.fn_caract_acento('Sede Administrativa')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.39.01.002',upper(gene0007.fn_caract_acento('PA')));
insert into tbcontab_prm_produto_servico(cdproduto_servico, dsproduto_servico) values ('P.39.01.003',upper(gene0007.fn_caract_acento('Estacionamento')));

  COMMIT;
END;