BEGIN
  UPDATE tbcontab_prm_risco_slip t
     SET t.idativo = 'N';
  
  --R.01
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.01.01.001',upper(gene0007.fn_caract_acento('Diferença de caixa/tesouraria não registrada ou comunicada a alçada competente '))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Diferença de caixa/tesouraria não registrada ou comunicada a alçada competente ')), idativo = 'S' where cdrisco_operacional = 'RO.01.01.001'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.01.01.002',upper(gene0007.fn_caract_acento('Utilização de cartão/talonário do cooperado - em arquivo da cooperativa'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Utilização de cartão/talonário do cooperado - em arquivo da cooperativa')), idativo = 'S' where cdrisco_operacional = 'RO.01.01.002'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.01.01.003',upper(gene0007.fn_caract_acento('Apropriação de cheques que cooperado entrega para desconto ou custódia'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Apropriação de cheques que cooperado entrega para desconto ou custódia')), idativo = 'S' where cdrisco_operacional = 'RO.01.01.003'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.01.01.004',upper(gene0007.fn_caract_acento('Apropriação de valores do cooperado '))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Apropriação de valores do cooperado ')), idativo = 'S' where cdrisco_operacional = 'RO.01.01.004'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.01.01.005',upper(gene0007.fn_caract_acento('Apropriação de valores da cooperativa'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Apropriação de valores da cooperativa')), idativo = 'S' where cdrisco_operacional = 'RO.01.01.005'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.01.01.006',upper(gene0007.fn_caract_acento('Estorno indevido com apropriação do valor'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Estorno indevido com apropriação do valor')), idativo = 'S' where cdrisco_operacional = 'RO.01.01.006'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.01.01.007',upper(gene0007.fn_caract_acento('Registro de fatos financeiro em favorecimento próprio '))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Registro de fatos financeiro em favorecimento próprio ')), idativo = 'S' where cdrisco_operacional = 'RO.01.01.007'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.01.01.008',upper(gene0007.fn_caract_acento('Pagamento de contas pessoais utilizando-se de recursos da conta corrente de cooperados'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Pagamento de contas pessoais utilizando-se de recursos da conta corrente de cooperados')), idativo = 'S' where cdrisco_operacional = 'RO.01.01.008'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.01.02.001',upper(gene0007.fn_caract_acento('Aceitação de garantias falsas '))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Aceitação de garantias falsas ')), idativo = 'S' where cdrisco_operacional = 'RO.01.02.001'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.01.02.002',upper(gene0007.fn_caract_acento('Falsificação de assinatura'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Falsificação de assinatura')), idativo = 'S' where cdrisco_operacional = 'RO.01.02.002'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.01.02.003',upper(gene0007.fn_caract_acento('Falsificação/Adulteração de documentos cooperado'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Falsificação/Adulteração de documentos cooperado')), idativo = 'S' where cdrisco_operacional = 'RO.01.02.003'; end;
  
  --R.02
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.02.01.001',upper(gene0007.fn_caract_acento('Assalto/Furto ao posto de atendimento com perda de valores'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Assalto/Furto ao posto de atendimento com perda de valores')), idativo = 'S' where cdrisco_operacional = 'RO.02.01.001'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.02.01.002',upper(gene0007.fn_caract_acento('Explosão de caixa eletrônico com perda de valores'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Explosão de caixa eletrônico com perda de valores')), idativo = 'S' where cdrisco_operacional = 'RO.02.01.002'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.02.01.003',upper(gene0007.fn_caract_acento('Extorsão mediante sequestro.'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Extorsão mediante sequestro.')), idativo = 'S' where cdrisco_operacional = 'RO.02.01.003'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.02.01.004',upper(gene0007.fn_caract_acento('Furto de pertence do cooperado e/ou colaborador nas dependências da cooperativa'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Furto de pertence do cooperado e/ou colaborador nas dependências da cooperativa')), idativo = 'S' where cdrisco_operacional = 'RO.02.01.004'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.02.02.001',upper(gene0007.fn_caract_acento('Falsidade ideológica.'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Falsidade ideológica.')), idativo = 'S' where cdrisco_operacional = 'RO.02.02.001'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.02.02.002',upper(gene0007.fn_caract_acento('Fraude Cobrança bancária - Emissão de boletos falsos'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Fraude Cobrança bancária - Emissão de boletos falsos')), idativo = 'S' where cdrisco_operacional = 'RO.02.02.002'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.02.02.003',upper(gene0007.fn_caract_acento('Fraude em operação de crédito (devedor/fiador)'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Fraude em operação de crédito (devedor/fiador)')), idativo = 'S' where cdrisco_operacional = 'RO.02.02.003'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.02.02.004',upper(gene0007.fn_caract_acento('Fraude com cheques '))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Fraude com cheques ')), idativo = 'S' where cdrisco_operacional = 'RO.02.02.004'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.02.03.001',upper(gene0007.fn_caract_acento('Fraude conta Online'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Fraude conta Online')), idativo = 'S' where cdrisco_operacional = 'RO.02.03.001'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.02.03.002',upper(gene0007.fn_caract_acento('Fraude cartão de crédito/Debito'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Fraude cartão de crédito/Debito')), idativo = 'S' where cdrisco_operacional = 'RO.02.03.002'; end;
  
  --R.03
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.03.01.001',upper(gene0007.fn_caract_acento('Descumprimento da legislação trabalhista'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Descumprimento da legislação trabalhista')), idativo = 'S' where cdrisco_operacional = 'RO.03.01.001'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.03.01.002',upper(gene0007.fn_caract_acento('Responsabilidade solidária - Empresa Terceira'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Responsabilidade solidária - Empresa Terceira')), idativo = 'S' where cdrisco_operacional = 'RO.03.01.002'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.03.01.003',upper(gene0007.fn_caract_acento('Vinculo empregatício - Terceiro'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Vinculo empregatício - Terceiro')), idativo = 'S' where cdrisco_operacional = 'RO.03.01.003'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.03.01.004',upper(gene0007.fn_caract_acento('Equiparação bancária'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Equiparação bancária')), idativo = 'S' where cdrisco_operacional = 'RO.03.01.004'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.03.01.005',upper(gene0007.fn_caract_acento('Transporte de valores por colaborador da cooperativa'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Transporte de valores por colaborador da cooperativa')), idativo = 'S' where cdrisco_operacional = 'RO.03.01.005'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.03.01.006',upper(gene0007.fn_caract_acento('Solicitação de vinculo trabalhista de terceiros '))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Solicitação de vinculo trabalhista de terceiros ')), idativo = 'S' where cdrisco_operacional = 'RO.03.01.006'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.03.02.001',upper(gene0007.fn_caract_acento('Ambiente de Trabalho em desacordo com a legislação'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Ambiente de Trabalho em desacordo com a legislação')), idativo = 'S' where cdrisco_operacional = 'RO.03.02.001'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.03.02.002',upper(gene0007.fn_caract_acento('Indisponibilidade de EPI´s / EPC´s'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Indisponibilidade de EPI´s / EPC´s')), idativo = 'S' where cdrisco_operacional = 'RO.03.02.002'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.03.02.003',upper(gene0007.fn_caract_acento('Acidente trabalhista  - Colaborador da Cooperativa'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Acidente trabalhista  - Colaborador da Cooperativa')), idativo = 'S' where cdrisco_operacional = 'RO.03.02.003'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.03.02.004',upper(gene0007.fn_caract_acento('Acidente trabalhista  - Colaborador de empresa terceira'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Acidente trabalhista  - Colaborador de empresa terceira')), idativo = 'S' where cdrisco_operacional = 'RO.03.02.004'; end;
  
  --R.04
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.01.001',upper(gene0007.fn_caract_acento('Inutilização de cartão de crédito/ débito com defeito'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Inutilização de cartão de crédito/ débito com defeito')), idativo = 'S' where cdrisco_operacional = 'RO.04.01.001'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.01.002',upper(gene0007.fn_caract_acento('Indisponibilidade/ Instabilidade no sistema do parceiro'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Indisponibilidade/ Instabilidade no sistema do parceiro')), idativo = 'S' where cdrisco_operacional = 'RO.04.01.002'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.01.003',upper(gene0007.fn_caract_acento('Pagamento ao Cooperado de Benefício do INSS sem repasse'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Pagamento ao Cooperado de Benefício do INSS sem repasse')), idativo = 'S' where cdrisco_operacional = 'RO.04.01.003'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.01.004',upper(gene0007.fn_caract_acento('Pagamento de Benefício de INSS duplicado'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Pagamento de Benefício de INSS duplicado')), idativo = 'S' where cdrisco_operacional = 'RO.04.01.004'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.01.005',upper(gene0007.fn_caract_acento('Antecipação de Benefício do INSS por Falha na validação da Prova de Vida do INSS '))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Antecipação de Benefício do INSS por Falha na validação da Prova de Vida do INSS ')), idativo = 'S' where cdrisco_operacional = 'RO.04.01.005'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.01.006',upper(gene0007.fn_caract_acento('Ressarcimento ao Cooperado por Falha na liquidação de convênios'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Ressarcimento ao Cooperado por Falha na liquidação de convênios')), idativo = 'S' where cdrisco_operacional = 'RO.04.01.006'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.01.007',upper(gene0007.fn_caract_acento('Falha na comunicação do arquivo de compensação'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Falha na comunicação do arquivo de compensação')), idativo = 'S' where cdrisco_operacional = 'RO.04.01.007'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.001',upper(gene0007.fn_caract_acento('Falhas em Produtos e/ou Serviços'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Falhas em Produtos e/ou Serviços')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.001'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.002',upper(gene0007.fn_caract_acento('Acidente com cooperado nas dependências da cooperativa '))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Acidente com cooperado nas dependências da cooperativa ')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.002'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.003',upper(gene0007.fn_caract_acento('Descumprimento de acordo firmado com o cooperado'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Descumprimento de acordo firmado com o cooperado')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.003'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.004',upper(gene0007.fn_caract_acento('Abatimentos/ Descontos em operação de crédito'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Abatimentos/ Descontos em operação de crédito')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.004'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.005',upper(gene0007.fn_caract_acento('Abono saldo de conta corrente negativa (Recuperação de Crédito)'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Abono saldo de conta corrente negativa (Recuperação de Crédito)')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.005'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.006',upper(gene0007.fn_caract_acento('Abono saldo de conta corrente em adto a depositante (Recuperação de Crédito)'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Abono saldo de conta corrente em adto a depositante (Recuperação de Crédito)')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.006'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.007',upper(gene0007.fn_caract_acento('Antecipação do crédito de contestação do cartão de crédito'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Antecipação do crédito de contestação do cartão de crédito')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.007'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.008',upper(gene0007.fn_caract_acento('Pagamento em duplicidade '))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Pagamento em duplicidade ')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.008'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.009',upper(gene0007.fn_caract_acento('Abono de taxas e tarifas '))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Abono de taxas e tarifas ')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.009'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.010',upper(gene0007.fn_caract_acento('Abono de anuidade do cartão de crédito'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Abono de anuidade do cartão de crédito')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.010'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.011',upper(gene0007.fn_caract_acento('Abono na cobrança de Juros '))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Abono na cobrança de Juros ')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.011'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.012',upper(gene0007.fn_caract_acento('Abono por emissão de 2° via de cartão'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Abono por emissão de 2° via de cartão')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.012'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.013',upper(gene0007.fn_caract_acento('Cobrança Indevida '))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Cobrança Indevida ')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.013'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.014',upper(gene0007.fn_caract_acento('Cobrança Indevida ou duplicidade em produtos e/ou serviços'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Cobrança Indevida ou duplicidade em produtos e/ou serviços')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.014'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.015',upper(gene0007.fn_caract_acento('Inscrição/manutenção Indevida nos órgãos de proteção ao crédito'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Inscrição/manutenção Indevida nos órgãos de proteção ao crédito')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.015'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.016',upper(gene0007.fn_caract_acento('Quebra de sigilo bancário'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Quebra de sigilo bancário')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.016'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.017',upper(gene0007.fn_caract_acento('Cobrança Vexatória (exposição do cooperado)'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Cobrança Vexatória (exposição do cooperado)')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.017'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.018',upper(gene0007.fn_caract_acento('Cobrança por SMS - (perturbação)'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Cobrança por SMS - (perturbação)')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.018'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.019',upper(gene0007.fn_caract_acento('Protesto Indevido'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Protesto Indevido')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.019'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.020',upper(gene0007.fn_caract_acento('Débito de Verba Salarial acima do limite de 30%'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Débito de Verba Salarial acima do limite de 30%')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.020'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.021',upper(gene0007.fn_caract_acento('Débito de Verba Salarial para pagamento de empréstimo em atraso'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Débito de Verba Salarial para pagamento de empréstimo em atraso')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.021'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.022',upper(gene0007.fn_caract_acento('Débito de Verba Salarial para pagamento de limite de crédito'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Débito de Verba Salarial para pagamento de limite de crédito')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.022'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.023',upper(gene0007.fn_caract_acento('Débito Indevido na Conta '))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Débito Indevido na Conta ')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.023'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.024',upper(gene0007.fn_caract_acento('Desapropriação - Alienação de Imóvel'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Desapropriação - Alienação de Imóvel')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.024'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.025',upper(gene0007.fn_caract_acento('Encerramento irregular da conta'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Encerramento irregular da conta')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.025'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.026',upper(gene0007.fn_caract_acento('Bloqueio indevido de conta corrente '))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Bloqueio indevido de conta corrente ')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.026'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.027',upper(gene0007.fn_caract_acento('Falha ne processo do cancelamento indevido de produtos ou serviços'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Falha ne processo do cancelamento indevido de produtos ou serviços')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.027'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.028',upper(gene0007.fn_caract_acento('Redução de limites de operações de crédito'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Redução de limites de operações de crédito')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.028'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.029',upper(gene0007.fn_caract_acento('Benfeitoria em imóvel alienado'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Benfeitoria em imóvel alienado')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.029'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.030',upper(gene0007.fn_caract_acento('Falha ao colher assinaturas em documentos ou contratos'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Falha ao colher assinaturas em documentos ou contratos')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.030'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.031',upper(gene0007.fn_caract_acento('Extravio de Documentos / dossiê / processos'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Extravio de Documentos / dossiê / processos')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.031'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.032',upper(gene0007.fn_caract_acento('Tutela de urgência para rescisão de contrato, restituição de valores pagos'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Tutela de urgência para rescisão de contrato, restituição de valores pagos')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.032'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.033',upper(gene0007.fn_caract_acento('Revisão de cláusulas contratuais'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Revisão de cláusulas contratuais')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.033'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.04.02.034',upper(gene0007.fn_caract_acento('Reintegração de posse'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Reintegração de posse')), idativo = 'S' where cdrisco_operacional = 'RO.04.02.034'; end;
  
  --R.05
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.05.01.001',upper(gene0007.fn_caract_acento('Danos causados por desastres naturais'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Danos causados por desastres naturais')), idativo = 'S' where cdrisco_operacional = 'RO.05.01.001'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.05.01.002',upper(gene0007.fn_caract_acento('Destruição/vandalismo e arrombamento causando danos a ativos da cooperativa'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Destruição/vandalismo e arrombamento causando danos a ativos da cooperativa')), idativo = 'S' where cdrisco_operacional = 'RO.05.01.002'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.05.01.003',upper(gene0007.fn_caract_acento('Incêndio'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Incêndio')), idativo = 'S' where cdrisco_operacional = 'RO.05.01.003'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.05.01.004',upper(gene0007.fn_caract_acento('Danos a equipamentos da cooperativa'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Danos a equipamentos da cooperativa')), idativo = 'S' where cdrisco_operacional = 'RO.05.01.004'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.05.02.001',upper(gene0007.fn_caract_acento('Danos a veículos locados ou de colaboradores a serviço da cooperativa'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Danos a veículos locados ou de colaboradores a serviço da cooperativa')), idativo = 'S' where cdrisco_operacional = 'RO.05.02.001'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.05.02.002',upper(gene0007.fn_caract_acento('Danos a bens de cooperados nas dependências da cooperativa'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Danos a bens de cooperados nas dependências da cooperativa')), idativo = 'S' where cdrisco_operacional = 'RO.05.02.002'; end;
  
  --R.06
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.06.01.001',upper(gene0007.fn_caract_acento('Greves de empregados'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Greves de empregados')), idativo = 'S' where cdrisco_operacional = 'RO.06.01.001'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.06.01.002',upper(gene0007.fn_caract_acento('Invasão das instalações do cooperativa ou imediações.'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Invasão das instalações do cooperativa ou imediações.')), idativo = 'S' where cdrisco_operacional = 'RO.06.01.002'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.06.02.001',upper(gene0007.fn_caract_acento('Interrupção dos serviços de transporte, energia e telecomunicações.'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Interrupção dos serviços de transporte, energia e telecomunicações.')), idativo = 'S' where cdrisco_operacional = 'RO.06.02.001'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.06.02.002',upper(gene0007.fn_caract_acento('Greve nos serviços públicos.'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Greve nos serviços públicos.')), idativo = 'S' where cdrisco_operacional = 'RO.06.02.002'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.06.03.001',upper(gene0007.fn_caract_acento('Distúrbios ou manifestações políticas e sociais'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Distúrbios ou manifestações políticas e sociais')), idativo = 'S' where cdrisco_operacional = 'RO.06.03.001'; end;
  
  --R.07
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.07.01.001',upper(gene0007.fn_caract_acento('Sobrecarga de sistemas de processamento de dados (lentidão)'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Sobrecarga de sistemas de processamento de dados (lentidão)')), idativo = 'S' where cdrisco_operacional = 'RO.07.01.001'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.07.01.002',upper(gene0007.fn_caract_acento('Falha em sistema operacional'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Falha em sistema operacional')), idativo = 'S' where cdrisco_operacional = 'RO.07.01.002'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.07.01.003',upper(gene0007.fn_caract_acento('Falha em infraestrutura (hardware)'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Falha em infraestrutura (hardware)')), idativo = 'S' where cdrisco_operacional = 'RO.07.01.003'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.07.01.004',upper(gene0007.fn_caract_acento('Falha em comunicação de dados (link)'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Falha em comunicação de dados (link)')), idativo = 'S' where cdrisco_operacional = 'RO.07.01.004'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.07.01.005',upper(gene0007.fn_caract_acento('Falha no serviço de canais de relacionamento (caixa online, conta online, mobile, TA)'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Falha no serviço de canais de relacionamento (caixa online, conta online, mobile, TA)')), idativo = 'S' where cdrisco_operacional = 'RO.07.01.005'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.07.01.006',upper(gene0007.fn_caract_acento('Falta de backup'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Falta de backup')), idativo = 'S' where cdrisco_operacional = 'RO.07.01.006'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.07.01.007',upper(gene0007.fn_caract_acento('Falha em sistema terceiro (parceiros de negócio)'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Falha em sistema terceiro (parceiros de negócio)')), idativo = 'S' where cdrisco_operacional = 'RO.07.01.007'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.07.01.008',upper(gene0007.fn_caract_acento('Erro na liberação de projeto/ melhoria'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Erro na liberação de projeto/ melhoria')), idativo = 'S' where cdrisco_operacional = 'RO.07.01.008'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.07.01.009',upper(gene0007.fn_caract_acento('Erro no processamento da Gabine JD (Ted, Tec, Boletos)'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Erro no processamento da Gabine JD (Ted, Tec, Boletos)')), idativo = 'S' where cdrisco_operacional = 'RO.07.01.009'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.07.01.010',upper(gene0007.fn_caract_acento('Falha na execução do processamento noturno (processo Batch) '))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Falha na execução do processamento noturno (processo Batch) ')), idativo = 'S' where cdrisco_operacional = 'RO.07.01.010'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.07.02.001',upper(gene0007.fn_caract_acento('Uso indevido de senhas e user ID.'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Uso indevido de senhas e user ID.')), idativo = 'S' where cdrisco_operacional = 'RO.07.02.001'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.07.02.002',upper(gene0007.fn_caract_acento('Acessos não-seletivos (funções críticas liberadas sem critério). '))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Acessos não-seletivos (funções críticas liberadas sem critério). ')), idativo = 'S' where cdrisco_operacional = 'RO.07.02.002'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.07.02.003',upper(gene0007.fn_caract_acento('Ausência de cancelamento de user ID e senhas.'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Ausência de cancelamento de user ID e senhas.')), idativo = 'S' where cdrisco_operacional = 'RO.07.02.003'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.07.03.001',upper(gene0007.fn_caract_acento('Atividades de hackers.'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Atividades de hackers.')), idativo = 'S' where cdrisco_operacional = 'RO.07.03.001'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.07.03.002',upper(gene0007.fn_caract_acento('Roubo de informação com perda monetária.'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Roubo de informação com perda monetária.')), idativo = 'S' where cdrisco_operacional = 'RO.07.03.002'; end;

  --R.08
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.001',upper(gene0007.fn_caract_acento('Erro no cancelamento de produtos ou serviços'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Erro no cancelamento de produtos ou serviços')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.001'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.002',upper(gene0007.fn_caract_acento('Estorno falha na informação da comercialização de produtos '))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Estorno falha na informação da comercialização de produtos ')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.002'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.003',upper(gene0007.fn_caract_acento('Resgate de aplicação antes do prazo de carência'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Resgate de aplicação antes do prazo de carência')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.003'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.004',upper(gene0007.fn_caract_acento('Erro na formalização taxa de juros de contratos'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Erro na formalização taxa de juros de contratos')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.004'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.005',upper(gene0007.fn_caract_acento('Pagamento de boleto em duplicidade'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Pagamento de boleto em duplicidade')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.005'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.006',upper(gene0007.fn_caract_acento('Pagamento de boleto com valor divergente'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Pagamento de boleto com valor divergente')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.006'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.007',upper(gene0007.fn_caract_acento('Erro na compensação de cheques'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Erro na compensação de cheques')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.007'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.008',upper(gene0007.fn_caract_acento('Erro na liquidação de operações de crédito'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Erro na liquidação de operações de crédito')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.008'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.009',upper(gene0007.fn_caract_acento('Erro ao realizar débitos na conta de cooperados'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Erro ao realizar débitos na conta de cooperados')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.009'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.010',upper(gene0007.fn_caract_acento('Diferença de caixa'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Diferença de caixa')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.010'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.011',upper(gene0007.fn_caract_acento('Depósito na conta corrente incorreta'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Depósito na conta corrente incorreta')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.011'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.012',upper(gene0007.fn_caract_acento('Saque da conta corrente incorreta'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Saque da conta corrente incorreta')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.012'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.013',upper(gene0007.fn_caract_acento('Entrega de talonário para cooperado incorreto'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Entrega de talonário para cooperado incorreto')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.013'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.014',upper(gene0007.fn_caract_acento('Troca de cassetes no TAA'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Troca de cassetes no TAA')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.014'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.015',upper(gene0007.fn_caract_acento('Entrega de cartão para cooperado errado'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Entrega de cartão para cooperado errado')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.015'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.016',upper(gene0007.fn_caract_acento('Recebimento de cédulas suspeitas'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Recebimento de cédulas suspeitas')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.016'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.017',upper(gene0007.fn_caract_acento('Erro em lançamentos notas fiscais'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Erro em lançamentos notas fiscais')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.017'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.018',upper(gene0007.fn_caract_acento('Multa/juros por não pagamento obrigações '))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Multa/juros por não pagamento obrigações ')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.018'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.019',upper(gene0007.fn_caract_acento('Multa por descumprimento de cotas PCD'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Multa por descumprimento de cotas PCD')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.019'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.020',upper(gene0007.fn_caract_acento('Encerramento de conta corrente sem cancelar produtos com débitos futuros'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Encerramento de conta corrente sem cancelar produtos com débitos futuros')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.020'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.021',upper(gene0007.fn_caract_acento('Envio de numerário a menor para empresa de transporte de valores'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Envio de numerário a menor para empresa de transporte de valores')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.021'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.022',upper(gene0007.fn_caract_acento('Falha na homologação de novos produtos e melhoria de processos'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Falha na homologação de novos produtos e melhoria de processos')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.022'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.023',upper(gene0007.fn_caract_acento('Devolução Indevida de cheque'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Devolução Indevida de cheque')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.023'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.024',upper(gene0007.fn_caract_acento('Pagamento de cheque sem saldo em conta'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Pagamento de cheque sem saldo em conta')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.024'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.025',upper(gene0007.fn_caract_acento('Emissão de TED fora da grade de hora '))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Emissão de TED fora da grade de hora ')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.025'; end;
  begin insert into tbcontab_prm_risco_slip(cdrisco_operacional, dsrisco_operacional) values ('RO.08.01.026',upper(gene0007.fn_caract_acento('Multa por rescisão contratual'))); exception when dup_val_on_index then update tbcontab_prm_risco_slip set dsrisco_operacional = upper(gene0007.fn_caract_acento('Multa por rescisão contratual')), idativo = 'S' where cdrisco_operacional = 'RO.08.01.026'; end;
  
  COMMIT;
END;