CREATE TABLE TBCRD_PREAPROV_HISTCARGA (
	IDHISTCOOPER     NUMBER(10)    NOT NULL,
    CDCOOPER         NUMBER(3)     NOT NULL,
    SKCARGA          NUMBER(10)    NOT NULL,
    CDOPERAD         VARCHAR2(10)    NOT NULL,
    INACAO           NUMBER(1)     NOT NULL,
    DTACAO           DATE          NOT NULL
);

COMMENT ON TABLE TBCRD_PREAPROV_HISTCARGA IS 
	'Tabela de historico de bloqueio da carga e quem efetuou';

COMMENT ON COLUMN TBCRD_PREAPROV_HISTCARGA.IDHISTCOOPER IS
    'Chave artificial de identificacao do historico';

COMMENT ON COLUMN TBCRD_PREAPROV_HISTCARGA.CDCOOPER IS
    'Codigo da cooperativa';

COMMENT ON COLUMN TBCRD_PREAPROV_HISTCARGA.SKCARGA IS
    'Chave artificial de identificacao da carga';

COMMENT ON COLUMN TBCRD_PREAPROV_HISTCARGA.CDOPERAD IS
    'Codigo do operador';

COMMENT ON COLUMN TBCRD_PREAPROV_HISTCARGA.INACAO IS
    'Acao que a carga sofreu. 1 = desbloqueio, 2 = bloqueio';

COMMENT ON COLUMN TBCRD_PREAPROV_HISTCARGA.DTACAO IS
    'Data que ocorreu a acao';

ALTER TABLE TBCRD_PREAPROV_HISTCARGA ADD CONSTRAINT TBCRD_PREAPROV_HISTCARGA_PK PRIMARY KEY ( IDHISTCOOPER, CDCOOPER );
