DECLARE

  CURSOR CR_CRAPCRD IS
    SELECT *
      FROM CRAPCRD
     WHERE CDADMCRD = 0;
  
  VR_CDADMCRD CRAPCRD.CDADMCRD%TYPE;

BEGIN
  -- Ajustes solicitados no INC0049411
  -- Registro 01
  BEGIN
    UPDATE CRAWCRD
       SET CDLIMCRD = 20
     WHERE CDCOOPER = 1
       AND NRDCONTA = 7407440
       AND NRCRCARD = 6042034014412130;

    UPDATE CRAPCRD
       SET CDADMCRD = 11
          ,CDLIMCRD = 20
     WHERE CDCOOPER = 1
       AND NRDCONTA = 7407440
       AND NRCRCARD = 6042034014412130;
  EXCEPTION
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('Erro na atualização. Coop.: 1 - Conta: 7407440 - Cartão: 6042034014412130');
  END;
  
  -- Registro 02
  BEGIN
    UPDATE CRAWCRD
       SET CDLIMCRD = 20
          ,DTCANCEL = '30/10/2019'
          ,INSITCRD = 6
     WHERE CDCOOPER = 1
       AND NRDCONTA = 6098169
       AND NRCRCARD = 6042034013283862;

    UPDATE CRAPCRD
       SET CDADMCRD = 11
          ,CDLIMCRD = 20
          ,DTCANCEL = '30/10/2019'
     WHERE CDCOOPER = 1
       AND NRDCONTA = 6098169
       AND NRCRCARD = 6042034013283862;
  EXCEPTION
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('Erro na atualização. Coop.: 1 - Conta: 6098169 - Cartão: 6042034013283862');
  END;
  
  -- Efetuado varredura na base para correção de cartões sem administradora
  FOR RW_CRAPCRD IN CR_CRAPCRD LOOP
    VR_CDADMCRD := 0;
    
    BEGIN
      SELECT CDADMCRD
        INTO VR_CDADMCRD
        FROM CRAWCRD
       WHERE CDCOOPER = RW_CRAPCRD.CDCOOPER
         AND NRDCONTA = RW_CRAPCRD.NRDCONTA
         AND NRCRCARD = RW_CRAPCRD.NRCRCARD;
    EXCEPTION
      WHEN OTHERS THEN
        CONTINUE;
    END;
    
    BEGIN
      UPDATE CRAPCRD
         SET CDADMCRD = VR_CDADMCRD
       WHERE CDCOOPER = RW_CRAPCRD.CDCOOPER
         AND NRDCONTA = RW_CRAPCRD.NRDCONTA
         AND NRCRCARD = RW_CRAPCRD.NRCRCARD
         AND CDADMCRD = 0;
    EXCEPTION
      WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erro na atualização. Coop.: '||RW_CRAPCRD.CDCOOPER||' - Conta: '||RW_CRAPCRD.NRDCONTA||' - Cartão: '||RW_CRAPCRD.NRCRCARD);
    END;

  END LOOP;
  
  COMMIT;
  
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erro - '||SQLERRM);
END;
