BEGIN
  INSERT INTO crapprm (nmsistem,
                       cdcooper,
                       cdacesso,
                       dstexprm,
                       dsvlrprm)
    VALUES ('CRED', 3, 'HABILITA_LOG_CARTAO', 'Habilita LOG Cartão via trigger - TBCRD_LOG_CARTAO (1 - Ativado / 2 - Desativado)', 0);

  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO)  VALUES ('OPERACAO_ADM_CDACAO', '1', 'Ignorar', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO)  VALUES ('OPERACAO_ADM_CDACAO', '2', 'Criticar', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO)  VALUES ('OPERACAO_ADM_CDACAO', '3', 'Alterar Situação', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO)  VALUES ('OPERACAO_ADM_CDACAO', '4', 'Expurgar', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '0', 'BLOQUEIO DE EMISSÃO', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '1', 'OPERATIVO', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '2', 'REPOSTO POR ERRO FABRICAÇÃO', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '3', 'COMPROMETIDO', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '4', 'BLOQUEIO PREVENTIVO',1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '5', 'PERÍODO DE UTILIZAÇÃO EXCEDIDO P/ CARTÕES PROVISÓRIOS', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '6', 'EXTRAVIADO', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '8', 'VENCIDO', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '9', 'DEVOLVIDO E DESTRUIDO', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '10', 'REPOSTO', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '11', 'POSSIVEL RISCO/BLOQ PRVENTIVO CARTAO NÃO PRESENTE', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '13', 'POSSIVEL FR /  BLOQ PREVENTIVO TOTAL', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '14', 'ROUBADO', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '15', 'PERDIDO', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '16', 'FRAUDE      ', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '17', 'ANUL. A PEDIDO ENTIDADE', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '18', 'ANUL. A PEDIDO PORTADOR', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '25', 'FRAUDE CARTAO NÃO PRESENTE', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '27', 'PERÍODO DE UTILIZAÇÃO EXCEDIDO P/ TEMP CARTÕES PROVISÓRIOS', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '28', 'BLOQUEIO PREVENTIVO EMISSOR',1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '95', 'BLOQUEIO PARCIAL', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '96', 'BLOQUEIO', 1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO) values ('OPERACAO_ADM_SITUACAO', '97', 'CANCELAMENTO DEFINIIVO', 1);


  COMMIT;
END;