INSERT INTO crapprm VALUES ('CRED',1,'COBTIT_BLQ_EMI_CONSEC','Bloqueio de emissão consecutiva de boleto de desconto de título','30;5',null);
INSERT INTO crapprm VALUES ('CRED',1,'COBTIT_BLQ_RESG_CC','Bloqueio de resgate de debitos c/c (crps171 e crps474)','N',null);
INSERT INTO crapprm VALUES ('CRED',1,'COBTIT_INSTR_LINHA_1','Mensagem de informação do boleto - linha 1','contrato ref a conta: #conta#',null);
INSERT INTO crapprm VALUES ('CRED',1,'COBTIT_INSTR_LINHA_2','Mensagem de informação do boleto - linha 2','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',1,'COBTIT_INSTR_LINHA_3','Mensagem de informação do boleto - linha 3','este pagamento nao altera as condicoes contratadas',null);
INSERT INTO crapprm VALUES ('CRED',1,'COBTIT_INSTR_LINHA_4','Mensagem de informação do boleto - linha 4','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',1,'COBTIT_NRCONVEN','Numero do convenio de cobranca de desconto de título','970106',null);
INSERT INTO crapprm VALUES ('CRED',1,'COBTIT_NRDCONTA_BNF','Numero da conta do beneficiario de desconto de título','850004',null);
INSERT INTO crapprm VALUES ('CRED',1,'COBTIT_PRZ_BX_VENCTO','Prazo de baixa de vencimento do boleto de desconto de título','0',null);
INSERT INTO crapprm VALUES ('CRED',1,'COBTIT_PRZ_MAX_VENCTO','Prazo maximo de vencimento do boleto de desconto de título','4',null);
INSERT INTO crapprm VALUES ('CRED',1,'COBTIT_QTD_MAX_BOL_EPR','Quantidade maxima de boletos de desconto de título para um contrato','10',null);
INSERT INTO crapprm VALUES ('CRED',1,'COBTIT_TXT_SMS','Texto SMS','Prezado(a),linha digitavel do boleto solicitado #LinhaDigitavel#. Duvidas pelo telefone (47) 3231-1700.',null);
INSERT INTO crapprm VALUES ('CRED',1,'COBTIT_VLR_MIN','Valor minimo do boleto para COBTIT','50,00',null);
INSERT INTO crapprm VALUES ('CRED',1,'COBTIT_TXT_EMAIL','','Bom dia, Esta mensagem refere-se ao boleto emitido pela #cooperativa# para o cooperado: Nome: #pagador# E-mail: #email# Boleto em anexo. Duvidas, entrar em contato no telefone (47) 3231-1700',null);
INSERT INTO crapprm VALUES ('CRED',1,'COBTIT_DSC_MAX_PREJU','Desconto maximo pagamento contrato prejuizo','60,00',null);
INSERT INTO crapprm VALUES ('CRED',2,'COBTIT_TXT_SMS','Texto SMS','Prezado(a),linha digitavel do boleto solicitado #LinhaDigitavel#. Duvidas pelo telefone (47) 3231-1700.',null);
INSERT INTO crapprm VALUES ('CRED',2,'COBTIT_VLR_MIN','Valor minimo do boleto para COBTIT','50,00',null);
INSERT INTO crapprm VALUES ('CRED',2,'COBTIT_BLQ_EMI_CONSEC','Bloqueio de emissão consecutiva de boleto de desconto de título','30;5',null);
INSERT INTO crapprm VALUES ('CRED',2,'COBTIT_BLQ_RESG_CC','Bloqueio de resgate de debitos c/c (crps171 e crps474)','N',null);
INSERT INTO crapprm VALUES ('CRED',2,'COBTIT_INSTR_LINHA_1','Mensagem de informação do boleto - linha 1','contrato ref a conta: #conta#',null);
INSERT INTO crapprm VALUES ('CRED',2,'COBTIT_INSTR_LINHA_2','Mensagem de informação do boleto - linha 2','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',2,'COBTIT_INSTR_LINHA_3','Mensagem de informação do boleto - linha 3','este pagamento nao altera as condicoes contratadas',null);
INSERT INTO crapprm VALUES ('CRED',2,'COBTIT_INSTR_LINHA_4','Mensagem de informação do boleto - linha 4','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',2,'COBTIT_NRCONVEN','Numero do convenio de cobranca de desconto de título','970106',null);
INSERT INTO crapprm VALUES ('CRED',2,'COBTIT_NRDCONTA_BNF','Numero da conta do beneficiario de desconto de título','850004',null);
INSERT INTO crapprm VALUES ('CRED',2,'COBTIT_PRZ_BX_VENCTO','Prazo de baixa de vencimento do boleto de desconto de título','0',null);
INSERT INTO crapprm VALUES ('CRED',2,'COBTIT_PRZ_MAX_VENCTO','Prazo maximo de vencimento do boleto de desconto de título','4',null);
INSERT INTO crapprm VALUES ('CRED',2,'COBTIT_QTD_MAX_BOL_EPR','Quantidade maxima de boletos de desconto de título para um contrato','10',null);
INSERT INTO crapprm VALUES ('CRED',2,'COBTIT_TXT_EMAIL','','Bom dia, Esta mensagem refere-se ao boleto emitido pela #cooperativa# para o cooperado: Nome: #pagador# E-mail: #email# Boleto em anexo. Duvidas, entrar em contato no telefone (47) 3231-1700',null);
INSERT INTO crapprm VALUES ('CRED',2,'COBTIT_DSC_MAX_PREJU','Desconto maximo pagamento contrato prejuizo','60,00',null);
INSERT INTO crapprm VALUES ('CRED',3,'COBTIT_BLQ_EMI_CONSEC','Bloqueio de emissão consecutiva de boleto de desconto de título','30;3',null);
INSERT INTO crapprm VALUES ('CRED',3,'COBTIT_BLQ_RESG_CC','Bloqueio de resgate de debitos c/c (crps171 e crps474)','N',null);
INSERT INTO crapprm VALUES ('CRED',3,'COBTIT_INSTR_LINHA_1','Mensagem de informação do boleto - linha 1','contrato ref a conta: #conta#',null);
INSERT INTO crapprm VALUES ('CRED',3,'COBTIT_INSTR_LINHA_2','Mensagem de informação do boleto - linha 2','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',3,'COBTIT_INSTR_LINHA_3','Mensagem de informação do boleto - linha 3','este pagamento nao altera as condicoes contratadas',null);
INSERT INTO crapprm VALUES ('CRED',3,'COBTIT_INSTR_LINHA_4','Mensagem de informação do boleto - linha 4','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',3,'COBTIT_NRCONVEN','Numero do convenio de cobranca de desconto de título','970106',null);
INSERT INTO crapprm VALUES ('CRED',3,'COBTIT_NRDCONTA_BNF','Numero da conta do beneficiario de desconto de título','850004',null);
INSERT INTO crapprm VALUES ('CRED',3,'COBTIT_PRZ_BX_VENCTO','Prazo de baixa de vencimento do boleto de desconto de título','0',null);
INSERT INTO crapprm VALUES ('CRED',3,'COBTIT_PRZ_MAX_VENCTO','Prazo maximo de vencimento do boleto de desconto de título','2',null);
INSERT INTO crapprm VALUES ('CRED',3,'COBTIT_QTD_MAX_BOL_EPR','Quantidade maxima de boletos de desconto de título para um contrato','5',null);
INSERT INTO crapprm VALUES ('CRED',3,'COBTIT_TXT_SMS','Texto SMS','Prezado(a),linha digitavel do boleto solicitado #LinhaDigitavel#. Duvidas pelo telefone (47) 3231-1700.',null);
INSERT INTO crapprm VALUES ('CRED',3,'COBTIT_VLR_MIN','Valor minimo do boleto para COBTIT','50,00',null);
INSERT INTO crapprm VALUES ('CRED',4,'COBTIT_BLQ_EMI_CONSEC','Bloqueio de emissão consecutiva de boleto de desconto de título','30;3',null);
INSERT INTO crapprm VALUES ('CRED',4,'COBTIT_BLQ_RESG_CC','Bloqueio de resgate de debitos c/c (crps171 e crps474)','N',null);
INSERT INTO crapprm VALUES ('CRED',4,'COBTIT_INSTR_LINHA_1','Mensagem de informação do boleto - linha 1','contrato ref a conta: #conta#',null);
INSERT INTO crapprm VALUES ('CRED',4,'COBTIT_INSTR_LINHA_2','Mensagem de informação do boleto - linha 2','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',4,'COBTIT_INSTR_LINHA_3','Mensagem de informação do boleto - linha 3','este pagamento nao altera as condicoes contratadas',null);
INSERT INTO crapprm VALUES ('CRED',4,'COBTIT_INSTR_LINHA_4','Mensagem de informação do boleto - linha 4','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',4,'COBTIT_NRCONVEN','Numero do convenio de cobranca de desconto de título','970106',null);
INSERT INTO crapprm VALUES ('CRED',4,'COBTIT_NRDCONTA_BNF','Numero da conta do beneficiario de desconto de título','850004',null);
INSERT INTO crapprm VALUES ('CRED',4,'COBTIT_PRZ_BX_VENCTO','Prazo de baixa de vencimento do boleto de desconto de título','0',null);
INSERT INTO crapprm VALUES ('CRED',4,'COBTIT_PRZ_MAX_VENCTO','Prazo maximo de vencimento do boleto de desconto de título','2',null);
INSERT INTO crapprm VALUES ('CRED',4,'COBTIT_QTD_MAX_BOL_EPR','Quantidade maxima de boletos de desconto de título para um contrato','5',null);
INSERT INTO crapprm VALUES ('CRED',4,'COBTIT_TXT_SMS','Texto SMS','Prezado(a),linha digitavel do boleto solicitado #LinhaDigitavel#. Duvidas pelo telefone (47) 3231-1700.',null);
INSERT INTO crapprm VALUES ('CRED',4,'COBTIT_VLR_MIN','Valor minimo do boleto para COBTIT','50,00',null);
INSERT INTO crapprm VALUES ('CRED',5,'COBTIT_BLQ_EMI_CONSEC','Bloqueio de emissão consecutiva de boleto de desconto de título','30;5',null);
INSERT INTO crapprm VALUES ('CRED',5,'COBTIT_BLQ_RESG_CC','Bloqueio de resgate de debitos c/c (crps171 e crps474)','N',null);
INSERT INTO crapprm VALUES ('CRED',5,'COBTIT_INSTR_LINHA_1','Mensagem de informação do boleto - linha 1','contrato ref a conta: #conta#',null);
INSERT INTO crapprm VALUES ('CRED',5,'COBTIT_INSTR_LINHA_2','Mensagem de informação do boleto - linha 2','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',5,'COBTIT_INSTR_LINHA_3','Mensagem de informação do boleto - linha 3','este pagamento nao altera as condicoes contratadas',null);
INSERT INTO crapprm VALUES ('CRED',5,'COBTIT_INSTR_LINHA_4','Mensagem de informação do boleto - linha 4','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',5,'COBTIT_NRCONVEN','Numero do convenio de cobranca de desconto de título','970106',null);
INSERT INTO crapprm VALUES ('CRED',5,'COBTIT_NRDCONTA_BNF','Numero da conta do beneficiario de desconto de título','850004',null);
INSERT INTO crapprm VALUES ('CRED',5,'COBTIT_PRZ_BX_VENCTO','Prazo de baixa de vencimento do boleto de desconto de título','0',null);
INSERT INTO crapprm VALUES ('CRED',5,'COBTIT_PRZ_MAX_VENCTO','Prazo maximo de vencimento do boleto de desconto de título','4',null);
INSERT INTO crapprm VALUES ('CRED',5,'COBTIT_QTD_MAX_BOL_EPR','Quantidade maxima de boletos de desconto de título para um contrato','10',null);
INSERT INTO crapprm VALUES ('CRED',5,'COBTIT_TXT_SMS','Texto SMS','Prezado(a),linha digitavel do boleto solicitado #LinhaDigitavel#. Duvidas pelo telefone (47) 3231-1700.',null);
INSERT INTO crapprm VALUES ('CRED',5,'COBTIT_VLR_MIN','Valor minimo do boleto para COBTIT','50,00',null);
INSERT INTO crapprm VALUES ('CRED',5,'COBTIT_TXT_EMAIL','','Bom dia, Esta mensagem refere-se ao boleto emitido pela #cooperativa# para o cooperado: Nome: #pagador# E-mail: #email# Boleto em anexo. Duvidas, entrar em contato no telefone (47) 3231-1700',null);
INSERT INTO crapprm VALUES ('CRED',5,'COBTIT_DSC_MAX_PREJU','Desconto maximo pagamento contrato prejuizo','60,00',null);
INSERT INTO crapprm VALUES ('CRED',6,'COBTIT_BLQ_RESG_CC','Bloqueio de resgate de debitos c/c (crps171 e crps474)','N',null);
INSERT INTO crapprm VALUES ('CRED',6,'COBTIT_INSTR_LINHA_1','Mensagem de informação do boleto - linha 1','contrato ref a conta: #conta#',null);
INSERT INTO crapprm VALUES ('CRED',6,'COBTIT_BLQ_EMI_CONSEC','Bloqueio de emissão consecutiva de boleto de desconto de título','30;5',null);
INSERT INTO crapprm VALUES ('CRED',6,'COBTIT_INSTR_LINHA_2','Mensagem de informação do boleto - linha 2','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',6,'COBTIT_INSTR_LINHA_3','Mensagem de informação do boleto - linha 3','este pagamento nao altera as condicoes contratadas',null);
INSERT INTO crapprm VALUES ('CRED',6,'COBTIT_INSTR_LINHA_4','Mensagem de informação do boleto - linha 4','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',6,'COBTIT_NRCONVEN','Numero do convenio de cobranca de desconto de título','970106',null);
INSERT INTO crapprm VALUES ('CRED',6,'COBTIT_NRDCONTA_BNF','Numero da conta do beneficiario de desconto de título','850004',null);
INSERT INTO crapprm VALUES ('CRED',6,'COBTIT_PRZ_BX_VENCTO','Prazo de baixa de vencimento do boleto de desconto de título','0',null);
INSERT INTO crapprm VALUES ('CRED',6,'COBTIT_PRZ_MAX_VENCTO','Prazo maximo de vencimento do boleto de desconto de título','4',null);
INSERT INTO crapprm VALUES ('CRED',6,'COBTIT_QTD_MAX_BOL_EPR','Quantidade maxima de boletos de desconto de título para um contrato','10',null);
INSERT INTO crapprm VALUES ('CRED',6,'COBTIT_TXT_SMS','Texto SMS','Prezado(a),linha digitavel do boleto solicitado #LinhaDigitavel#. Duvidas pelo telefone (47) 3231-1700.',null);
INSERT INTO crapprm VALUES ('CRED',6,'COBTIT_VLR_MIN','Valor minimo do boleto para COBTIT','50,00',null);
INSERT INTO crapprm VALUES ('CRED',6,'COBTIT_TXT_EMAIL','','Bom dia, Esta mensagem refere-se ao boleto emitido pela #cooperativa# para o cooperado: Nome: #pagador# E-mail: #email# Boleto em anexo. Duvidas, entrar em contato no telefone (47) 3231-1700',null);
INSERT INTO crapprm VALUES ('CRED',6,'COBTIT_DSC_MAX_PREJU','Desconto maximo pagamento contrato prejuizo','60,00',null);
INSERT INTO crapprm VALUES ('CRED',7,'COBTIT_BLQ_EMI_CONSEC','Bloqueio de emissão consecutiva de boleto de desconto de título','30;5',null);
INSERT INTO crapprm VALUES ('CRED',7,'COBTIT_BLQ_RESG_CC','Bloqueio de resgate de debitos c/c (crps171 e crps474)','N',null);
INSERT INTO crapprm VALUES ('CRED',7,'COBTIT_INSTR_LINHA_1','Mensagem de informação do boleto - linha 1','contrato ref a conta: #conta#',null);
INSERT INTO crapprm VALUES ('CRED',7,'COBTIT_INSTR_LINHA_2','Mensagem de informação do boleto - linha 2','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',7,'COBTIT_INSTR_LINHA_3','Mensagem de informação do boleto - linha 3','este pagamento nao altera as condicoes contratadas',null);
INSERT INTO crapprm VALUES ('CRED',7,'COBTIT_INSTR_LINHA_4','Mensagem de informação do boleto - linha 4','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',7,'COBTIT_NRCONVEN','Numero do convenio de cobranca de desconto de título','970106',null);
INSERT INTO crapprm VALUES ('CRED',7,'COBTIT_NRDCONTA_BNF','Numero da conta do beneficiario de desconto de título','850004',null);
INSERT INTO crapprm VALUES ('CRED',7,'COBTIT_PRZ_BX_VENCTO','Prazo de baixa de vencimento do boleto de desconto de título','0',null);
INSERT INTO crapprm VALUES ('CRED',7,'COBTIT_PRZ_MAX_VENCTO','Prazo maximo de vencimento do boleto de desconto de título','4',null);
INSERT INTO crapprm VALUES ('CRED',7,'COBTIT_QTD_MAX_BOL_EPR','Quantidade maxima de boletos de desconto de título para um contrato','10',null);
INSERT INTO crapprm VALUES ('CRED',7,'COBTIT_TXT_SMS','Texto SMS','Prezado(a),linha digitavel do boleto solicitado #LinhaDigitavel#. Duvidas pelo telefone (47) 3231-1700.',null);
INSERT INTO crapprm VALUES ('CRED',7,'COBTIT_VLR_MIN','Valor minimo do boleto para COBTIT','50,00',null);
INSERT INTO crapprm VALUES ('CRED',7,'COBTIT_TXT_EMAIL','','Bom dia, Esta mensagem refere-se ao boleto emitido pela #cooperativa# para o cooperado: Nome: #pagador# E-mail: #email# Boleto em anexo. Duvidas, entrar em contato no telefone (47) 3231-1700',null);
INSERT INTO crapprm VALUES ('CRED',7,'COBTIT_DSC_MAX_PREJU','Desconto maximo pagamento contrato prejuizo','60,00',null);
INSERT INTO crapprm VALUES ('CRED',8,'COBTIT_BLQ_EMI_CONSEC','Bloqueio de emissão consecutiva de boleto de desconto de título','30;5',null);
INSERT INTO crapprm VALUES ('CRED',8,'COBTIT_BLQ_RESG_CC','Bloqueio de resgate de debitos c/c (crps171 e crps474)','N',null);
INSERT INTO crapprm VALUES ('CRED',8,'COBTIT_INSTR_LINHA_1','Mensagem de informação do boleto - linha 1','contrato ref a conta: #conta#',null);
INSERT INTO crapprm VALUES ('CRED',8,'COBTIT_INSTR_LINHA_2','Mensagem de informação do boleto - linha 2','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',8,'COBTIT_INSTR_LINHA_3','Mensagem de informação do boleto - linha 3','este pagamento nao altera as condicoes contratadas',null);
INSERT INTO crapprm VALUES ('CRED',8,'COBTIT_INSTR_LINHA_4','Mensagem de informação do boleto - linha 4','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',8,'COBTIT_NRCONVEN','Numero do convenio de cobranca de desconto de título','970106',null);
INSERT INTO crapprm VALUES ('CRED',8,'COBTIT_NRDCONTA_BNF','Numero da conta do beneficiario de desconto de título','850004',null);
INSERT INTO crapprm VALUES ('CRED',8,'COBTIT_PRZ_BX_VENCTO','Prazo de baixa de vencimento do boleto de desconto de título','0',null);
INSERT INTO crapprm VALUES ('CRED',8,'COBTIT_PRZ_MAX_VENCTO','Prazo maximo de vencimento do boleto de desconto de título','4',null);
INSERT INTO crapprm VALUES ('CRED',8,'COBTIT_QTD_MAX_BOL_EPR','Quantidade maxima de boletos de desconto de título para um contrato','10',null);
INSERT INTO crapprm VALUES ('CRED',8,'COBTIT_TXT_SMS','Texto SMS','Prezado(a),linha digitavel do boleto solicitado #LinhaDigitavel#. Duvidas pelo telefone (47) 3231-1700.',null);
INSERT INTO crapprm VALUES ('CRED',8,'COBTIT_VLR_MIN','Valor minimo do boleto para COBTIT','50,00',null);
INSERT INTO crapprm VALUES ('CRED',8,'COBTIT_TXT_EMAIL','','Bom dia, Esta mensagem refere-se ao boleto emitido pela #cooperativa# para o cooperado: Nome: #pagador# E-mail: #email# Boleto em anexo. Duvidas, entrar em contato no telefone (47) 3231-1700',null);
INSERT INTO crapprm VALUES ('CRED',8,'COBTIT_DSC_MAX_PREJU','Desconto maximo pagamento contrato prejuizo','60,00',null);
INSERT INTO crapprm VALUES ('CRED',9,'COBTIT_BLQ_EMI_CONSEC','Bloqueio de emissão consecutiva de boleto de desconto de título','30;5',null);
INSERT INTO crapprm VALUES ('CRED',9,'COBTIT_BLQ_RESG_CC','Bloqueio de resgate de debitos c/c (crps171 e crps474)','N',null);
INSERT INTO crapprm VALUES ('CRED',9,'COBTIT_INSTR_LINHA_1','Mensagem de informação do boleto - linha 1','contrato ref a conta: #conta#',null);
INSERT INTO crapprm VALUES ('CRED',9,'COBTIT_INSTR_LINHA_2','Mensagem de informação do boleto - linha 2','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',9,'COBTIT_INSTR_LINHA_3','Mensagem de informação do boleto - linha 3','este pagamento nao altera as condicoes contratadas',null);
INSERT INTO crapprm VALUES ('CRED',9,'COBTIT_INSTR_LINHA_4','Mensagem de informação do boleto - linha 4','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',9,'COBTIT_NRCONVEN','Numero do convenio de cobranca de desconto de título','970106',null);
INSERT INTO crapprm VALUES ('CRED',9,'COBTIT_NRDCONTA_BNF','Numero da conta do beneficiario de desconto de título','850004',null);
INSERT INTO crapprm VALUES ('CRED',9,'COBTIT_PRZ_BX_VENCTO','Prazo de baixa de vencimento do boleto de desconto de título','0',null);
INSERT INTO crapprm VALUES ('CRED',9,'COBTIT_PRZ_MAX_VENCTO','Prazo maximo de vencimento do boleto de desconto de título','4',null);
INSERT INTO crapprm VALUES ('CRED',9,'COBTIT_QTD_MAX_BOL_EPR','Quantidade maxima de boletos de desconto de título para um contrato','10',null);
INSERT INTO crapprm VALUES ('CRED',9,'COBTIT_TXT_SMS','Texto SMS','Prezado(a),linha digitavel do boleto solicitado #LinhaDigitavel#. Duvidas pelo telefone (47) 3231-1700.',null);
INSERT INTO crapprm VALUES ('CRED',9,'COBTIT_VLR_MIN','Valor minimo do boleto para COBTIT','50,00',null);
INSERT INTO crapprm VALUES ('CRED',9,'COBTIT_TXT_EMAIL','','Bom dia, Esta mensagem refere-se ao boleto emitido pela #cooperativa# para o cooperado: Nome: #pagador# E-mail: #email# Boleto em anexo. Duvidas, entrar em contato no telefone (47) 3231-1700',null);
INSERT INTO crapprm VALUES ('CRED',9,'COBTIT_DSC_MAX_PREJU','Desconto maximo pagamento contrato prejuizo','60,00',null);
INSERT INTO crapprm VALUES ('CRED',10,'COBTIT_BLQ_EMI_CONSEC','Bloqueio de emissão consecutiva de boleto de desconto de título','30;5',null);
INSERT INTO crapprm VALUES ('CRED',10,'COBTIT_BLQ_RESG_CC','Bloqueio de resgate de debitos c/c (crps171 e crps474)','N',null);
INSERT INTO crapprm VALUES ('CRED',10,'COBTIT_INSTR_LINHA_1','Mensagem de informação do boleto - linha 1','contrato ref a conta: #conta#',null);
INSERT INTO crapprm VALUES ('CRED',10,'COBTIT_INSTR_LINHA_2','Mensagem de informação do boleto - linha 2','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',10,'COBTIT_INSTR_LINHA_3','Mensagem de informação do boleto - linha 3','este pagamento nao altera as condicoes contratadas',null);
INSERT INTO crapprm VALUES ('CRED',10,'COBTIT_INSTR_LINHA_4','Mensagem de informação do boleto - linha 4','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',10,'COBTIT_NRCONVEN','Numero do convenio de cobranca de desconto de título','970106',null);
INSERT INTO crapprm VALUES ('CRED',10,'COBTIT_NRDCONTA_BNF','Numero da conta do beneficiario de desconto de título','850004',null);
INSERT INTO crapprm VALUES ('CRED',10,'COBTIT_PRZ_BX_VENCTO','Prazo de baixa de vencimento do boleto de desconto de título','0',null);
INSERT INTO crapprm VALUES ('CRED',10,'COBTIT_PRZ_MAX_VENCTO','Prazo maximo de vencimento do boleto de desconto de título','4',null);
INSERT INTO crapprm VALUES ('CRED',10,'COBTIT_QTD_MAX_BOL_EPR','Quantidade maxima de boletos de desconto de título para um contrato','10',null);
INSERT INTO crapprm VALUES ('CRED',10,'COBTIT_TXT_SMS','Texto SMS','Prezado(a),linha digitavel do boleto solicitado #LinhaDigitavel#. Duvidas pelo telefone (47) 3231-1700.',null);
INSERT INTO crapprm VALUES ('CRED',10,'COBTIT_VLR_MIN','Valor minimo do boleto para COBTIT','50,00',null);
INSERT INTO crapprm VALUES ('CRED',10,'COBTIT_TXT_EMAIL','','Bom dia, Esta mensagem refere-se ao boleto emitido pela #cooperativa# para o cooperado: Nome: #pagador# E-mail: #email# Boleto em anexo. Duvidas, entrar em contato no telefone (47) 3231-1700',null);
INSERT INTO crapprm VALUES ('CRED',10,'COBTIT_DSC_MAX_PREJU','Desconto maximo pagamento contrato prejuizo','60,00',null);
INSERT INTO crapprm VALUES ('CRED',11,'COBTIT_BLQ_EMI_CONSEC','Bloqueio de emissão consecutiva de boleto de desconto de título','30;5',null);
INSERT INTO crapprm VALUES ('CRED',11,'COBTIT_BLQ_RESG_CC','Bloqueio de resgate de debitos c/c (crps171 e crps474)','N',null);
INSERT INTO crapprm VALUES ('CRED',11,'COBTIT_INSTR_LINHA_1','Mensagem de informação do boleto - linha 1','contrato ref a conta: #conta#',null);
INSERT INTO crapprm VALUES ('CRED',11,'COBTIT_INSTR_LINHA_2','Mensagem de informação do boleto - linha 2','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',11,'COBTIT_INSTR_LINHA_3','Mensagem de informação do boleto - linha 3','este pagamento nao altera as condicoes contratadas',null);
INSERT INTO crapprm VALUES ('CRED',11,'COBTIT_INSTR_LINHA_4','Mensagem de informação do boleto - linha 4','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',11,'COBTIT_NRCONVEN','Numero do convenio de cobranca de desconto de título','970106',null);
INSERT INTO crapprm VALUES ('CRED',11,'COBTIT_NRDCONTA_BNF','Numero da conta do beneficiario de desconto de título','850004',null);
INSERT INTO crapprm VALUES ('CRED',11,'COBTIT_PRZ_BX_VENCTO','Prazo de baixa de vencimento do boleto de desconto de título','0',null);
INSERT INTO crapprm VALUES ('CRED',11,'COBTIT_PRZ_MAX_VENCTO','Prazo maximo de vencimento do boleto de desconto de título','4',null);
INSERT INTO crapprm VALUES ('CRED',11,'COBTIT_QTD_MAX_BOL_EPR','Quantidade maxima de boletos de desconto de título para um contrato','10',null);
INSERT INTO crapprm VALUES ('CRED',11,'COBTIT_TXT_SMS','Texto SMS','Prezado(a),linha digitavel do boleto solicitado #LinhaDigitavel#. Duvidas pelo telefone (47) 3231-1700.',null);
INSERT INTO crapprm VALUES ('CRED',11,'COBTIT_VLR_MIN','Valor minimo do boleto para COBTIT','50,00',null);
INSERT INTO crapprm VALUES ('CRED',11,'COBTIT_TXT_EMAIL','','Bom dia, Esta mensagem refere-se ao boleto emitido pela #cooperativa# para o cooperado: Nome: #pagador# E-mail: #email# Boleto em anexo. Duvidas, entrar em contato no telefone (47) 3231-1700',null);
INSERT INTO crapprm VALUES ('CRED',11,'COBTIT_DSC_MAX_PREJU','Desconto maximo pagamento contrato prejuizo','60,00',null);
INSERT INTO crapprm VALUES ('CRED',12,'COBTIT_BLQ_EMI_CONSEC','Bloqueio de emissão consecutiva de boleto de desconto de título','30;5',null);
INSERT INTO crapprm VALUES ('CRED',12,'COBTIT_BLQ_RESG_CC','Bloqueio de resgate de debitos c/c (crps171 e crps474)','N',null);
INSERT INTO crapprm VALUES ('CRED',12,'COBTIT_INSTR_LINHA_1','Mensagem de informação do boleto - linha 1','contrato ref a conta: #conta#',null);
INSERT INTO crapprm VALUES ('CRED',12,'COBTIT_INSTR_LINHA_2','Mensagem de informação do boleto - linha 2','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',12,'COBTIT_INSTR_LINHA_3','Mensagem de informação do boleto - linha 3','este pagamento nao altera as condicoes contratadas',null);
INSERT INTO crapprm VALUES ('CRED',12,'COBTIT_INSTR_LINHA_4','Mensagem de informação do boleto - linha 4','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',12,'COBTIT_NRCONVEN','Numero do convenio de cobranca de desconto de título','970106',null);
INSERT INTO crapprm VALUES ('CRED',12,'COBTIT_NRDCONTA_BNF','Numero da conta do beneficiario de desconto de título','850004',null);
INSERT INTO crapprm VALUES ('CRED',12,'COBTIT_PRZ_BX_VENCTO','Prazo de baixa de vencimento do boleto de desconto de título','0',null);
INSERT INTO crapprm VALUES ('CRED',12,'COBTIT_PRZ_MAX_VENCTO','Prazo maximo de vencimento do boleto de desconto de título','4',null);
INSERT INTO crapprm VALUES ('CRED',12,'COBTIT_QTD_MAX_BOL_EPR','Quantidade maxima de boletos de desconto de título para um contrato','10',null);
INSERT INTO crapprm VALUES ('CRED',12,'COBTIT_TXT_SMS','Texto SMS','Prezado(a),linha digitavel do boleto solicitado #LinhaDigitavel#. Duvidas pelo telefone (47) 3231-1700.',null);
INSERT INTO crapprm VALUES ('CRED',12,'COBTIT_VLR_MIN','Valor minimo do boleto para COBTIT','50,00',null);
INSERT INTO crapprm VALUES ('CRED',12,'COBTIT_TXT_EMAIL','','Bom dia, Esta mensagem refere-se ao boleto emitido pela #cooperativa# para o cooperado: Nome: #pagador# E-mail: #email# Boleto em anexo. Duvidas, entrar em contato no telefone (47) 3231-1700',null);
INSERT INTO crapprm VALUES ('CRED',12,'COBTIT_DSC_MAX_PREJU','Desconto maximo pagamento contrato prejuizo','60,00',null);
INSERT INTO crapprm VALUES ('CRED',13,'COBTIT_BLQ_EMI_CONSEC','Bloqueio de emissão consecutiva de boleto de desconto de título','30;5',null);
INSERT INTO crapprm VALUES ('CRED',13,'COBTIT_BLQ_RESG_CC','Bloqueio de resgate de debitos c/c (crps171 e crps474)','N',null);
INSERT INTO crapprm VALUES ('CRED',13,'COBTIT_INSTR_LINHA_1','Mensagem de informação do boleto - linha 1','contrato ref a conta: #conta#',null);
INSERT INTO crapprm VALUES ('CRED',13,'COBTIT_INSTR_LINHA_2','Mensagem de informação do boleto - linha 2','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',13,'COBTIT_INSTR_LINHA_3','Mensagem de informação do boleto - linha 3','este pagamento nao altera as condicoes contratadas',null);
INSERT INTO crapprm VALUES ('CRED',13,'COBTIT_INSTR_LINHA_4','Mensagem de informação do boleto - linha 4','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',13,'COBTIT_NRCONVEN','Numero do convenio de cobranca de desconto de título','970106',null);
INSERT INTO crapprm VALUES ('CRED',13,'COBTIT_NRDCONTA_BNF','Numero da conta do beneficiario de desconto de título','850004',null);
INSERT INTO crapprm VALUES ('CRED',13,'COBTIT_PRZ_BX_VENCTO','Prazo de baixa de vencimento do boleto de desconto de título','0',null);
INSERT INTO crapprm VALUES ('CRED',13,'COBTIT_PRZ_MAX_VENCTO','Prazo maximo de vencimento do boleto de desconto de título','4',null);
INSERT INTO crapprm VALUES ('CRED',13,'COBTIT_QTD_MAX_BOL_EPR','Quantidade maxima de boletos de desconto de título para um contrato','10',null);
INSERT INTO crapprm VALUES ('CRED',13,'COBTIT_TXT_SMS','Texto SMS','Prezado(a),linha digitavel do boleto solicitado #LinhaDigitavel#. Duvidas pelo telefone (47) 3231-1700.',null);
INSERT INTO crapprm VALUES ('CRED',13,'COBTIT_VLR_MIN','Valor minimo do boleto para COBTIT','50,00',null);
INSERT INTO crapprm VALUES ('CRED',13,'COBTIT_TXT_EMAIL','','Bom dia, Esta mensagem refere-se ao boleto emitido pela #cooperativa# para o cooperado: Nome: #pagador# E-mail: #email# Boleto em anexo. Duvidas, entrar em contato no telefone (47) 3231-1700',null);
INSERT INTO crapprm VALUES ('CRED',13,'COBTIT_DSC_MAX_PREJU','Desconto maximo pagamento contrato prejuizo','60,00',null);
INSERT INTO crapprm VALUES ('CRED',14,'COBTIT_TXT_EMAIL','','Bom dia, Esta mensagem refere-se ao boleto emitido pela #cooperativa# para o cooperado: Nome: #pagador# E-mail: #email# Boleto em anexo. Duvidas, entrar em contato no telefone (47) 3231-1700',null);
INSERT INTO crapprm VALUES ('CRED',14,'COBTIT_BLQ_EMI_CONSEC','Bloqueio de emissão consecutiva de boleto de desconto de título','30;5',null);
INSERT INTO crapprm VALUES ('CRED',14,'COBTIT_BLQ_RESG_CC','Bloqueio de resgate de debitos c/c (crps171 e crps474)','N',null);
INSERT INTO crapprm VALUES ('CRED',14,'COBTIT_INSTR_LINHA_1','Mensagem de informação do boleto - linha 1','contrato ref a conta: #conta#',null);
INSERT INTO crapprm VALUES ('CRED',14,'COBTIT_INSTR_LINHA_2','Mensagem de informação do boleto - linha 2','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',14,'COBTIT_INSTR_LINHA_3','Mensagem de informação do boleto - linha 3','este pagamento nao altera as condicoes contratadas',null);
INSERT INTO crapprm VALUES ('CRED',14,'COBTIT_INSTR_LINHA_4','Mensagem de informação do boleto - linha 4','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',14,'COBTIT_NRCONVEN','Numero do convenio de cobranca de desconto de título','970106',null);
INSERT INTO crapprm VALUES ('CRED',14,'COBTIT_NRDCONTA_BNF','Numero da conta do beneficiario de desconto de título','850004',null);
INSERT INTO crapprm VALUES ('CRED',14,'COBTIT_PRZ_BX_VENCTO','Prazo de baixa de vencimento do boleto de desconto de título','0',null);
INSERT INTO crapprm VALUES ('CRED',14,'COBTIT_PRZ_MAX_VENCTO','Prazo maximo de vencimento do boleto de desconto de título','4',null);
INSERT INTO crapprm VALUES ('CRED',14,'COBTIT_QTD_MAX_BOL_EPR','Quantidade maxima de boletos de desconto de título para um contrato','10',null);
INSERT INTO crapprm VALUES ('CRED',14,'COBTIT_TXT_SMS','Texto SMS','Prezado(a),linha digitavel do boleto solicitado #LinhaDigitavel#. Duvidas pelo telefone (47) 3231-1700.',null);
INSERT INTO crapprm VALUES ('CRED',14,'COBTIT_VLR_MIN','Valor minimo do boleto para COBTIT','50,00',null);
INSERT INTO crapprm VALUES ('CRED',14,'COBTIT_DSC_MAX_PREJU','Desconto maximo pagamento contrato prejuizo','60,00',null);
INSERT INTO crapprm VALUES ('CRED',15,'COBTIT_BLQ_EMI_CONSEC','Bloqueio de emissão consecutiva de boleto de desconto de título','30;3',null);
INSERT INTO crapprm VALUES ('CRED',15,'COBTIT_BLQ_RESG_CC','Bloqueio de resgate de debitos c/c (crps171 e crps474)','N',null);
INSERT INTO crapprm VALUES ('CRED',15,'COBTIT_INSTR_LINHA_1','Mensagem de informação do boleto - linha 1','contrato ref a conta: #conta#',null);
INSERT INTO crapprm VALUES ('CRED',15,'COBTIT_INSTR_LINHA_2','Mensagem de informação do boleto - linha 2','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',15,'COBTIT_INSTR_LINHA_3','Mensagem de informação do boleto - linha 3','este pagamento nao altera as condicoes contratadas',null);
INSERT INTO crapprm VALUES ('CRED',15,'COBTIT_INSTR_LINHA_4','Mensagem de informação do boleto - linha 4','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',15,'COBTIT_NRCONVEN','Numero do convenio de cobranca de desconto de título','970106',null);
INSERT INTO crapprm VALUES ('CRED',15,'COBTIT_NRDCONTA_BNF','Numero da conta do beneficiario de desconto de título','850004',null);
INSERT INTO crapprm VALUES ('CRED',15,'COBTIT_PRZ_BX_VENCTO','Prazo de baixa de vencimento do boleto de desconto de título','0',null);
INSERT INTO crapprm VALUES ('CRED',15,'COBTIT_PRZ_MAX_VENCTO','Prazo maximo de vencimento do boleto de desconto de título','2',null);
INSERT INTO crapprm VALUES ('CRED',15,'COBTIT_QTD_MAX_BOL_EPR','Quantidade maxima de boletos de desconto de título para um contrato','5',null);
INSERT INTO crapprm VALUES ('CRED',15,'COBTIT_TXT_SMS','Texto SMS','Prezado(a),linha digitavel do boleto solicitado #LinhaDigitavel#. Duvidas pelo telefone (47) 3231-1700.',null);
INSERT INTO crapprm VALUES ('CRED',15,'COBTIT_VLR_MIN','Valor minimo do boleto para COBTIT','50,00',null);
INSERT INTO crapprm VALUES ('CRED',16,'COBTIT_TXT_EMAIL','','Bom dia, Esta mensagem refere-se ao boleto emitido pela #cooperativa# para o cooperado: Nome: #pagador# E-mail: #email# Boleto em anexo. Duvidas, entrar em contato no telefone (47) 3231-1700',null);
INSERT INTO crapprm VALUES ('CRED',16,'COBTIT_BLQ_EMI_CONSEC','Bloqueio de emissão consecutiva de boleto de desconto de título','30;5',null);
INSERT INTO crapprm VALUES ('CRED',16,'COBTIT_BLQ_RESG_CC','Bloqueio de resgate de debitos c/c (crps171 e crps474)','N',null);
INSERT INTO crapprm VALUES ('CRED',16,'COBTIT_INSTR_LINHA_1','Mensagem de informação do boleto - linha 1','contrato ref a conta: #conta#',null);
INSERT INTO crapprm VALUES ('CRED',16,'COBTIT_INSTR_LINHA_2','Mensagem de informação do boleto - linha 2','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',16,'COBTIT_INSTR_LINHA_3','Mensagem de informação do boleto - linha 3','este pagamento nao altera as condicoes contratadas',null);
INSERT INTO crapprm VALUES ('CRED',16,'COBTIT_INSTR_LINHA_4','Mensagem de informação do boleto - linha 4','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',16,'COBTIT_NRCONVEN','Numero do convenio de cobranca de desconto de título','970106',null);
INSERT INTO crapprm VALUES ('CRED',16,'COBTIT_NRDCONTA_BNF','Numero da conta do beneficiario de desconto de título','850004',null);
INSERT INTO crapprm VALUES ('CRED',16,'COBTIT_PRZ_BX_VENCTO','Prazo de baixa de vencimento do boleto de desconto de título','0',null);
INSERT INTO crapprm VALUES ('CRED',16,'COBTIT_PRZ_MAX_VENCTO','Prazo maximo de vencimento do boleto de desconto de título','4',null);
INSERT INTO crapprm VALUES ('CRED',16,'COBTIT_QTD_MAX_BOL_EPR','Quantidade maxima de boletos de desconto de título para um contrato','10',null);
INSERT INTO crapprm VALUES ('CRED',16,'COBTIT_TXT_SMS','Texto SMS','Prezado(a),linha digitavel do boleto solicitado #LinhaDigitavel#. Duvidas pelo telefone (47) 3231-1700.',null);
INSERT INTO crapprm VALUES ('CRED',16,'COBTIT_VLR_MIN','Valor minimo do boleto para COBTIT','50,00',null);
INSERT INTO crapprm VALUES ('CRED',16,'COBTIT_DSC_MAX_PREJU','Desconto maximo pagamento contrato prejuizo','60,00',null);
INSERT INTO crapprm VALUES ('CRED',17,'COBTIT_TXT_EMAIL','','Bom dia, Esta mensagem refere-se ao boleto emitido pela #cooperativa# para o cooperado: Nome: #pagador# E-mail: #email# Boleto em anexo. Duvidas, entrar em contato no telefone (47) 3231-1700',null);
INSERT INTO crapprm VALUES ('CRED',17,'COBTIT_BLQ_EMI_CONSEC','Bloqueio de emissão consecutiva de boleto de desconto de título','30;3',null);
INSERT INTO crapprm VALUES ('CRED',17,'COBTIT_BLQ_RESG_CC','Bloqueio de resgate de debitos c/c (crps171 e crps474)','N',null);
INSERT INTO crapprm VALUES ('CRED',17,'COBTIT_INSTR_LINHA_1','Mensagem de informação do boleto - linha 1','contrato ref a conta: #conta#',null);
INSERT INTO crapprm VALUES ('CRED',17,'COBTIT_INSTR_LINHA_2','Mensagem de informação do boleto - linha 2','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',17,'COBTIT_INSTR_LINHA_3','Mensagem de informação do boleto - linha 3','este pagamento nao altera as condicoes contratadas',null);
INSERT INTO crapprm VALUES ('CRED',17,'COBTIT_INSTR_LINHA_4','Mensagem de informação do boleto - linha 4','restricao baixada com pagamento total do atraso',null);
INSERT INTO crapprm VALUES ('CRED',17,'COBTIT_NRCONVEN','Numero do convenio de cobranca de desconto de título','970106',null);
INSERT INTO crapprm VALUES ('CRED',17,'COBTIT_NRDCONTA_BNF','Numero da conta do beneficiario de desconto de título','850004',null);
INSERT INTO crapprm VALUES ('CRED',17,'COBTIT_PRZ_BX_VENCTO','Prazo de baixa de vencimento do boleto de desconto de título','0',null);
INSERT INTO crapprm VALUES ('CRED',17,'COBTIT_PRZ_MAX_VENCTO','Prazo maximo de vencimento do boleto de desconto de título','2',null);
INSERT INTO crapprm VALUES ('CRED',17,'COBTIT_QTD_MAX_BOL_EPR','Quantidade maxima de boletos de desconto de título para um contrato','5',null);
INSERT INTO crapprm VALUES ('CRED',17,'COBTIT_TXT_SMS','Texto SMS','Prezado(a),linha digitavel do boleto solicitado #LinhaDigitavel#. Duvidas pelo telefone (47) 3231-1700.',null);
INSERT INTO crapprm VALUES ('CRED',17,'COBTIT_VLR_MIN','Valor minimo do boleto para COBTIT','50,00',null);
