BEGIN

INSERT INTO CECRED.CRAPRDR (NMPROGRA,DTSOLICI)
VALUES ('SEGU0004',SYSDATE);

INSERT INTO CECRED.CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR)
VALUES ('BUSCA_CONTRATOS_PRESTAMISTA_PJ', 'SEGU0004', 'PC_BUSCA_CONTRATOS_PJ', 'pr_nrdconta,pr_nrctremp,pr_nrregist,pr_nriniseq',(SELECT NRSEQRDR FROM CECRED.CRAPRDR WHERE NMPROGRA = 'SEGU0004'));

INSERT INTO CECRED.CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR)
VALUES ('BUSCA_RESUMO_PRESTAMISTA_PJ', 'SEGU0004', 'PC_BUSCA_RESUMO_SEGURO_PJ', 'pr_cdcooper,pr_vlpremio,pr_nmsocio,pr_vlcobertura,pr_pecobertura,pr_totcobertura',(SELECT NRSEQRDR FROM CECRED.CRAPRDR WHERE NMPROGRA = 'SEGU0004'));

INSERT INTO CECRED.CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR)
VALUES ('BUSCA_SEGURO_PRESTAMISTA_PJ', 'SEGU0004', 'PC_BUSCA_SEGURO_PRESTAMISTA_PJ', 'pr_cdcooper,pr_nrdconta,pr_nrctremp',(SELECT NRSEQRDR FROM CECRED.CRAPRDR WHERE NMPROGRA = 'SEGU0004'));

INSERT INTO CECRED.CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR)
VALUES ('CALCULAR_SEGURO_PRESTAMISTA_PJ', 'SEGU0004', 'PC_CALCULAR_SEGURO_PRESTAMISTA_PJ', 'pr_cdcooper,pr_nrdconta,pr_nrctremp,pr_nmsocio,pr_nrcpfcgcsoc,pr_dtnascsoc,pr_dtadmsoc,pr_pesocio',(SELECT NRSEQRDR FROM CECRED.CRAPRDR WHERE NMPROGRA = 'SEGU0004'));

INSERT INTO CECRED.CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR)
VALUES ('CARREGA_SOCIOS_PRESTAMISTA_PJ', 'SEGU0004', 'PC_CARREGA_SOCIOS_PRESTAMISTA_PJ', 'pr_cdcooper,pr_nrdconta',(SELECT NRSEQRDR FROM CECRED.CRAPRDR WHERE NMPROGRA = 'SEGU0004'));

INSERT INTO CECRED.CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR)
VALUES ('CONSULTAR_SEGURO_PRESTAMISTA_PJ', 'SEGU0004', 'PC_CONSULTAR_SEGURO_PRESTAMISTA_PJ', 'pr_cdcooper,pr_nrdconta,pr_nrctrseg,pr_nrctremp',(SELECT NRSEQRDR FROM CECRED.CRAPRDR WHERE NMPROGRA = 'SEGU0004'));

INSERT INTO CECRED.CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR)
VALUES ('CRIA_SEGURO_PRESTAMISTA_PJ', 'SEGU0004', 'PC_CRIA_SEGURO_PRESTAMISTA_PJ', 'pr_cdcooper,pr_nrdconta,pr_nrctremp,pr_vlcapseg,pr_vlpremio,pr_nmrepresentante,pr_dscargo,pr_nrcpfcgcrep,pr_nmsocio,pr_nrcpfcgcsoc,pr_pesocio,pr_dtadmsoc,pr_dtnascsoc,pr_vlcobertura,pr_pecobertura, pr_flgsegma',(SELECT NRSEQRDR FROM CECRED.CRAPRDR WHERE NMPROGRA = 'SEGU0004'));

INSERT INTO CECRED.CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR)
VALUES ('EFETIVA_SEGURO_PRESTAMISTA_PJ', 'SEGU0004', 'PC_EFETIVA_SEGURO_PRESTAMISTA_PJ', 'pr_cdcooper,pr_nrdconta,pr_nrctremp',(SELECT NRSEQRDR FROM CECRED.CRAPRDR WHERE NMPROGRA = 'SEGU0004'));

INSERT INTO CECRED.CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR)
VALUES ('IMPRIME_PROPOSTA_PRESTAMISTA_PJ', 'SEGU0004', 'PC_IMP_PROPOSTA_SEG_PRES_PJ_WEB', 'pr_cdcooper,pr_nrdconta,pr_nrctrseg,pr_nrctremp',(SELECT NRSEQRDR FROM CECRED.CRAPRDR WHERE NMPROGRA = 'SEGU0004'));

INSERT INTO CECRED.CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR)
VALUES ('VALIDA_INCLUSAO_MANUAL_PJ', 'SEGU0004', 'PC_VALIDA_INCLUSAO_MANUAL_PJ', 'pr_cdcooper,pr_nrdconta',(SELECT NRSEQRDR FROM CECRED.CRAPRDR WHERE NMPROGRA = 'SEGU0004'));

COMMIT;
END;