begin
INSERT INTO cecred.crapsda (nrdconta, 
                dtmvtolt, 
                vlsddisp, 
                vlsdchsl, 
                vlsdbloq, 
                vlsdblpr, 
                vlsdblfp, 
                vlsdindi, 
                vllimcre, 
                cdcooper, 
                vlsdeved, 
                vldeschq, 
                vllimutl, 
                vladdutl, 
                vlsdrdca, 
                vlsdrdpp, 
                vllimdsc, 
                vlprepla, 
                vlprerpp, 
                vlcrdsal, 
                qtchqliq, 
                qtchqass, 
                dtdsdclq, 
                vltotpar, 
                vlopcdia, 
                vlavaliz, 
                vlavlatr, 
                qtdevolu, 
                vltotren, 
                vldestit, 
                vllimtit, 
                vlsdempr, 
                vlsdfina, 
                vlsrdc30, 
                vlsrdc60, 
                vlsrdcpr, 
                vlsrdcpo, 
                vlsdcota, 
                vlblqjud)
          SELECT nrdconta, 
              TO_DATE('09/07/2024','DD/MM/RRRR') , 
              vlsddisp, 
              vlsdchsl, 
              vlsdbloq, 
              vlsdblpr, 
              vlsdblfp, 
              vlsdindi, 
              vllimcre, 
              cdcooper, 
              vlsdeved, 
              vldeschq, 
              vllimutl, 
              vladdutl, 
              vlsdrdca, 
              vlsdrdpp, 
              vllimdsc, 
              vlprepla, 
              vlprerpp, 
              vlcrdsal, 
              qtchqliq, 
              qtchqass, 
              dtdsdclq, 
              vltotpar, 
              vlopcdia, 
              vlavaliz, 
              vlavlatr, 
              qtdevolu, 
              vltotren, 
              vldestit, 
              vllimtit, 
              vlsdempr, 
              vlsdfina, 
              vlsrdc30, 
              vlsrdc60, 
              vlsrdcpr, 
              vlsrdcpo, 
              vlsdcota, 
              vlblqjud
             FROM crapsda
             WHERE dtmvtolt = '09/05/2024'
                   AND cdcooper = 1
                   AND nrdconta = 99914492;

commit;
end;