DECLARE
  v_nrseqrdr NUMBER(10);
BEGIN

  DELETE crapaca a WHERE a.nmdeacao = 'CARREGA_PARAM_EXIBE_PREJU';

  DELETE CRAPRDR a WHERE a.NMPROGRA = 'TELA_PREJ';

  INSERT INTO CRAPRDR
    (NMPROGRA, DTSOLICI)
  VALUES
    ('TELA_PREJ', SYSDATE)
  RETURNING NRSEQRDR INTO v_nrseqrdr;

  INSERT INTO CRAPACA
    (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR)
  VALUES
    ('CARREGA_PARAM_EXIBE_PREJU'
    ,NULL
    ,'CREDITO.obterParametroPrejuzTopaz'
    ,NULL
    ,v_nrseqrdr);
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
END;
