BEGIN

  INSERT INTO cecred.crapstf(DTMVTOLT,NRTERFIN,VLDSDINI,VLDSDFIN,CDCOOPER) VALUES (to_date('15-03-2024', 'dd-mm-yyyy'),211,0,0,1);
  INSERT INTO cecred.crapstf(DTMVTOLT,NRTERFIN,VLDSDINI,VLDSDFIN,CDCOOPER) VALUES (to_date('15-03-2024', 'dd-mm-yyyy'),212,0,0,1);

  COMMIT;
END;