BEGIN

INSERT INTO CECRED.CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR)
VALUES ('VALIDA_INCLUSAO_MANUAL_PJ', 'SEGU0004', 'PC_VALIDA_SOCIOS_PJ', 'pr_cdcooper,pr_nrdconta',(SELECT NRSEQRDR FROM CECRED.CRAPRDR WHERE NMPROGRA = 'SEGU0004'));

COMMIT;
END;
