BEGIN
  UPDATE CECRED.tbepr_consignado_pagamento
   SET INSTATUS = 2
 WHERE CDCOOPER = 2
   AND NRDCONTA = 1069217
   AND NRCTREMP = 338555
   AND NRPAREPR = 2
   AND IDSEQUENCIA = 1180462;  
COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
END;       
