BEGIN
 UPDATE CRAPTAR T SET T.DSTARIFA = 'TARIFAS OPERAÇÕES GARANTIA IMÓVEIS'  WHERE T.CDTARIFA = 187;
 UPDATE CRAPTAR T SET T.DSTARIFA = 'TARIFAS OPERAÇÕES GARANTIA IMÓVEIS'  WHERE T.CDTARIFA = 188;
 COMMIT;
END;

