BEGIN
 UPDATE CECRED.CRAPTAR T SET T.DSTARIFA = 'TARIFA DE OPERAÇÃO COM IMÓVEL - PF'  WHERE T.CDTARIFA = 187;
 UPDATE CECRED.CRAPTAR T SET T.DSTARIFA = 'TARIFA DE OPERAÇÃO COM IMÓVEL - PJ'  WHERE T.CDTARIFA = 188;
 COMMIT;
END;
