INSERT INTO CECRED.CRAPPRM
  (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM)
VALUES
  ('CRED',
   '1',
   'QTD_GRUPOS_CRPS480',
   'Quantidade de grupos no paralelismo do CRPS480',
   300);

INSERT INTO CECRED.TBGEN_BATCH_PARAM
  (IDPARAMETRO, QTPARALELO, QTREG_TRANSACAO, CDCOOPER, CDPROGRAMA)
VALUES
  (100, 40, 0, 1, 'CRPS480');

CREATE SEQUENCE CECRED.SEQCAPT_CRAPLAP_NRSEQDIG
MINVALUE 1
MAXVALUE 999999999
START WITH 1
INCREMENT BY 1
CYCLE
CACHE 1000;

COMMIT;
