DECLARE
BEGIN
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2263
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2264
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2243
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2283
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2303
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2265
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2266
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2284
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2267
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2304
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2305
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2372
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2403
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2384
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2373
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2374
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2375
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2405
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2423
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2406
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2376
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2404
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2380
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2409
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2408
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2379
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2377
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2407
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2378
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2410
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2381
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2624
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2623
UPDATE CECRED.TBCALRIS_FORNECEDORES FORN SET FORN.DHALTERACAO = SYSDATE WHERE FORN.IDCALRIS_FORNECEDOR = 2643
COMMIT;
END;
/