CREATE OR REPLACE PROCEDURE CECRED.PC_OBTER_PARAMETRO_MLC(PR_ATIVO OUT CRAPCOB.DSVLRPRM%TYPE) IS

  CURSOR CR_CRAPPRM IS
    SELECT DSVLRPRM FROM CRAPPRM WHERE CDACESSO = 'MLC_ATIVO';
  RW_CRAPPRM CR_CRAPPRM%ROWTYPE;

BEGIN

  OPEN CR_CRAPPRM;
  FETCH CR_CRAPPRM
    INTO RW_CRAPPRM;
  CLOSE CR_CRAPPRM;

  PR_ATIVO := RW_CRAPPRM.DSVLRPRM;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20500, SQLERRM);
    ROLLBACK;
  
END PC_OBTER_PARAMETRO_MLC;
/
