BEGIN

  INSERT INTO crappat
    (CDPARTAR
    ,NMPARTAR
    ,TPDEDADO
    ,CDPRODUT)
  VALUES
    ((SELECT MAX(cdpartar) + 1 FROM crappat)
    ,'HISTORICOS_CRED_SFH'
    ,2
    ,0);

  INSERT INTO crappat
    (CDPARTAR
    ,NMPARTAR
    ,TPDEDADO
    ,CDPRODUT)
  VALUES
    ((SELECT MAX(cdpartar) + 1 FROM crappat)
    ,'HISTORICOS_CRED_SFI'
    ,2
    ,0);
        
  INSERT INTO crappco
    (CDPARTAR
    ,CDCOOPER
    ,DSCONTEU)
  VALUES
    ((SELECT a.cdpartar FROM CREDITO.crappat a WHERE a.nmpartar = 'HISTORICOS_CRED_SFH')
    ,3
    ,'VLPARCELA,3697/VLMORA,3696/VLMULTA,3695/VLTAXA_ADM_PF,3805/VLTAXA_ADM_PJ,3806/VLSEGURO_MPI,3808/VLSEGURO_DFI,3807/VLPARCELA_ESTORNO_FGTS,3746/VLSALDO_DEVEDOR_FGTS,3748/');

  INSERT INTO crappco
    (CDPARTAR
    ,CDCOOPER
    ,DSCONTEU)
  VALUES
    ((SELECT a.cdpartar FROM CREDITO.crappat a WHERE a.nmpartar = 'HISTORICOS_CRED_SFI')
    ,3
    ,'VLPARCELA,3700/VLMORA,3699/VLMULTA,3698/VLTAXA_ADM_PF,3805/VLTAXA_ADM_PJ,3806/VLSEGURO_MPI,3808/VLSEGURO_DFI,3807/VLPARCELA_ESTORNO_FGTS,3746/VLSALDO_DEVEDOR_FGTS,3748/');    
    
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERRO: ' || SQLERRM);
    ROLLBACK;
END;
