BEGIN
  INSERT INTO CECRED.CRAPPAT T (T.CDPARTAR, T.NMPARTAR, T.TPDEDADO, T.CDPRODUT) VALUES ((SELECT MAX(CDPARTAR) from CECRED.CRAPPAT) + 1,'PERCENTUAL MÁXIMO DE DESCONTO TARIFA PIX VAREJO',3,0);
  INSERT INTO CECRED.CRAPBAT T (T.CDBATTAR, T.NMIDENTI,T.TPCADAST, T.CDCADAST) VALUES ('PERDESTARPIX','PERCENTUAL MÁXIMO DE DESCONTO TARIFA PIX VAREJO',2, (SELECT MAX(CDPARTAR) from CECRED.CRAPPAT));
  
COMMIT;
END;
