insert into craptel (NMDATELA, NRMODULO, CDOPPTEL, TLDATELA, TLRESTEL, FLGTELDF, FLGTELBL, NMROTINA, LSOPPTEL, INACESSO, CDCOOPER, IDSISTEM, IDEVENTO, NRORDROT, NRDNIVEL, NMROTPAI, IDAMBTEL)
values ('ATENDA', 5, '@', 'TED Transf Arquivo', 'TED Transf Arquivo', 1, 1, 'TED_TRANSFERENCIAS_ARQ', 'ACESSO', 0, 1, 1, 0, 57, 1, ' ', 2);

insert into craptel (NMDATELA, NRMODULO, CDOPPTEL, TLDATELA, TLRESTEL, FLGTELDF, FLGTELBL, NMROTINA, LSOPPTEL, INACESSO, CDCOOPER, IDSISTEM, IDEVENTO, NRORDROT, NRDNIVEL, NMROTPAI, IDAMBTEL)
values ('ATENDA', 5, '@,X,I,H', 'TRANSFENCIA DE ARQUIVO TED', 'TED TRANSF ARQUIVO', 1, 1, 'TED TRANSF ARQUIVO', 'ACESSO,CANCELAMENTO,IMPRESSAO,HABILITACAO', 2, 1, 1, 0, 19, 1, ' ', 2);

insert into craptel (NMDATELA, NRMODULO, CDOPPTEL, TLDATELA, TLRESTEL, FLGTELDF, FLGTELBL, NMROTINA, LSOPPTEL, INACESSO, CDCOOPER, IDSISTEM, IDEVENTO, NRORDROT, NRDNIVEL, NMROTPAI, IDAMBTEL)
values ('ATENDA', 5, '@,X,I,H', 'TRANSFENCIA DE ARQUIVO TED', 'TED TRANSF ARQUIVO', 1, 1, 'TED TRANSF ARQUIVO', 'ACESSO,CANCELAMENTO,IMPRESSAO,HABILITACAO', 2, 2, 1, 0, 19, 1, ' ', 2);

insert into craptel (NMDATELA, NRMODULO, CDOPPTEL, TLDATELA, TLRESTEL, FLGTELDF, FLGTELBL, NMROTINA, LSOPPTEL, INACESSO, CDCOOPER, IDSISTEM, IDEVENTO, NRORDROT, NRDNIVEL, NMROTPAI, IDAMBTEL)
values ('ATENDA', 5, '@,X,I,H', 'TRANSFENCIA DE ARQUIVO TED', 'TED TRANSF ARQUIVO', 1, 1, 'TED TRANSF ARQUIVO', 'ACESSO,CANCELAMENTO,IMPRESSAO,HABILITACAO', 2, 5, 1, 0, 19, 1, ' ', 2);

insert into craptel (NMDATELA, NRMODULO, CDOPPTEL, TLDATELA, TLRESTEL, FLGTELDF, FLGTELBL, NMROTINA, LSOPPTEL, INACESSO, CDCOOPER, IDSISTEM, IDEVENTO, NRORDROT, NRDNIVEL, NMROTPAI, IDAMBTEL)
values ('ATENDA', 5, '@,X,I,H', 'TRANSFENCIA DE ARQUIVO TED', 'TED TRANSF ARQUIVO', 1, 1, 'TED TRANSF ARQUIVO', 'ACESSO,CANCELAMENTO,IMPRESSAO,HABILITACAO', 2, 6, 1, 0, 19, 1, ' ', 2);

insert into craptel (NMDATELA, NRMODULO, CDOPPTEL, TLDATELA, TLRESTEL, FLGTELDF, FLGTELBL, NMROTINA, LSOPPTEL, INACESSO, CDCOOPER, IDSISTEM, IDEVENTO, NRORDROT, NRDNIVEL, NMROTPAI, IDAMBTEL)
values ('ATENDA', 5, '@,X,I,H', 'TRANSFENCIA DE ARQUIVO TED', 'TED TRANSF ARQUIVO', 1, 1, 'TED TRANSF ARQUIVO', 'ACESSO,CANCELAMENTO,IMPRESSAO,HABILITACAO', 2, 7, 1, 0, 19, 1, ' ', 2);

insert into craptel (NMDATELA, NRMODULO, CDOPPTEL, TLDATELA, TLRESTEL, FLGTELDF, FLGTELBL, NMROTINA, LSOPPTEL, INACESSO, CDCOOPER, IDSISTEM, IDEVENTO, NRORDROT, NRDNIVEL, NMROTPAI, IDAMBTEL)
values ('ATENDA', 5, '@,X,I,H', 'TRANSFENCIA DE ARQUIVO TED', 'TED TRANSF ARQUIVO', 1, 1, 'TED TRANSF ARQUIVO', 'ACESSO,CANCELAMENTO,IMPRESSAO,HABILITACAO', 2, 8, 1, 0, 19, 1, ' ', 2);

insert into craptel (NMDATELA, NRMODULO, CDOPPTEL, TLDATELA, TLRESTEL, FLGTELDF, FLGTELBL, NMROTINA, LSOPPTEL, INACESSO, CDCOOPER, IDSISTEM, IDEVENTO, NRORDROT, NRDNIVEL, NMROTPAI, IDAMBTEL)
values ('ATENDA', 5, '@,X,I,H', 'TRANSFENCIA DE ARQUIVO TED', 'TED TRANSF ARQUIVO', 1, 1, 'TED TRANSF ARQUIVO', 'ACESSO,CANCELAMENTO,IMPRESSAO,HABILITACAO', 2, 9, 1, 0, 19, 1, ' ', 2);

insert into craptel (NMDATELA, NRMODULO, CDOPPTEL, TLDATELA, TLRESTEL, FLGTELDF, FLGTELBL, NMROTINA, LSOPPTEL, INACESSO, CDCOOPER, IDSISTEM, IDEVENTO, NRORDROT, NRDNIVEL, NMROTPAI, IDAMBTEL)
values ('ATENDA', 5, '@,X,I,H', 'TRANSFENCIA DE ARQUIVO TED', 'TED TRANSF ARQUIVO', 1, 1, 'TED TRANSF ARQUIVO', 'ACESSO,CANCELAMENTO,IMPRESSAO,HABILITACAO', 2, 10, 1, 0, 19, 1, ' ', 2);

insert into craptel (NMDATELA, NRMODULO, CDOPPTEL, TLDATELA, TLRESTEL, FLGTELDF, FLGTELBL, NMROTINA, LSOPPTEL, INACESSO, CDCOOPER, IDSISTEM, IDEVENTO, NRORDROT, NRDNIVEL, NMROTPAI, IDAMBTEL)
values ('ATENDA', 5, '@,X,I,H', 'TRANSFENCIA DE ARQUIVO TED', 'TED TRANSF ARQUIVO', 1, 1, 'TED TRANSF ARQUIVO', 'ACESSO,CANCELAMENTO,IMPRESSAO,HABILITACAO', 2, 11, 1, 0, 19, 1, ' ', 2);

insert into craptel (NMDATELA, NRMODULO, CDOPPTEL, TLDATELA, TLRESTEL, FLGTELDF, FLGTELBL, NMROTINA, LSOPPTEL, INACESSO, CDCOOPER, IDSISTEM, IDEVENTO, NRORDROT, NRDNIVEL, NMROTPAI, IDAMBTEL)
values ('ATENDA', 5, '@,X,I,H', 'TRANSFENCIA DE ARQUIVO TED', 'TED TRANSF ARQUIVO', 1, 1, 'TED TRANSF ARQUIVO', 'ACESSO,CANCELAMENTO,IMPRESSAO,HABILITACAO', 2, 12, 1, 0, 19, 1, ' ', 2);

insert into craptel (NMDATELA, NRMODULO, CDOPPTEL, TLDATELA, TLRESTEL, FLGTELDF, FLGTELBL, NMROTINA, LSOPPTEL, INACESSO, CDCOOPER, IDSISTEM, IDEVENTO, NRORDROT, NRDNIVEL, NMROTPAI, IDAMBTEL)
values ('ATENDA', 5, '@,X,I,H', 'TRANSFENCIA DE ARQUIVO TED', 'TED TRANSF ARQUIVO', 1, 1, 'TED TRANSF ARQUIVO', 'ACESSO,CANCELAMENTO,IMPRESSAO,HABILITACAO', 2, 13, 1, 0, 19, 1, ' ', 2);

insert into craptel (NMDATELA, NRMODULO, CDOPPTEL, TLDATELA, TLRESTEL, FLGTELDF, FLGTELBL, NMROTINA, LSOPPTEL, INACESSO, CDCOOPER, IDSISTEM, IDEVENTO, NRORDROT, NRDNIVEL, NMROTPAI, IDAMBTEL)
values ('ATENDA', 5, '@,X,I,H', 'TRANSFENCIA DE ARQUIVO TED', 'TED TRANSF ARQUIVO', 1, 1, 'TED TRANSF ARQUIVO', 'ACESSO,CANCELAMENTO,IMPRESSAO,HABILITACAO', 2, 14, 1, 0, 19, 1, ' ', 2);

insert into craptel (NMDATELA, NRMODULO, CDOPPTEL, TLDATELA, TLRESTEL, FLGTELDF, FLGTELBL, NMROTINA, LSOPPTEL, INACESSO, CDCOOPER, IDSISTEM, IDEVENTO, NRORDROT, NRDNIVEL, NMROTPAI, IDAMBTEL)
values ('ATENDA', 5, '@,X,I,H', 'TRANSFENCIA DE ARQUIVO TED', 'TED TRANSF ARQUIVO', 1, 1, 'TED TRANSF ARQUIVO', 'ACESSO,CANCELAMENTO,IMPRESSAO,HABILITACAO', 2, 16, 1, 0, 19, 1, ' ', 2);

insert into craptel (NMDATELA, NRMODULO, CDOPPTEL, TLDATELA, TLRESTEL, FLGTELDF, FLGTELBL, NMROTINA, LSOPPTEL, INACESSO, CDCOOPER, IDSISTEM, IDEVENTO, NRORDROT, NRDNIVEL, NMROTPAI, IDAMBTEL)
values ('ATENDA', 5, '@,X,I,H', 'TRANSFENCIA DE ARQUIVO TED', 'TED TRANSF ARQUIVO', 1, 1, 'TED TRANSF ARQUIVO', 'ACESSO,CANCELAMENTO,IMPRESSAO,HABILITACAO', 2, 17, 1, 0, 19, 1, ' ', 2);

insert into craptel (NMDATELA, NRMODULO, CDOPPTEL, TLDATELA, TLRESTEL, FLGTELDF, FLGTELBL, NMROTINA, LSOPPTEL, INACESSO, CDCOOPER, IDSISTEM, IDEVENTO, NRORDROT, NRDNIVEL, NMROTPAI, IDAMBTEL)
values ('ATENDA', 5, '@,X,I,H', 'TRANSFENCIA DE ARQUIVO TED', 'TED TRANSF ARQUIVO', 1, 1, 'TED TRANSF ARQUIVO', 'ACESSO,CANCELAMENTO,IMPRESSAO,HABILITACAO', 2, 3, 1, 0, 19, 1, ' ', 2);

commit;