insert into tbcc_produto (CDPRODUTO, DSPRODUTO, FLGITEM_SOA, FLGUTILIZA_INTERFACE_PADRAO, FLGENVIA_SMS, FLGCOBRA_TARIFA, IDFAIXA_VALOR, FLGPRODUTO_API)
values (49, 'TRANSFERENCIA POR ARQUIVO', 0, 0, 0, 0, 0, 0);

commit;

