Begin
    Insert into CRAPREL (CDRELATO, NRVIADEF, NMRELATO
    , NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER
    , PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,
    PROGRESS_RECID, CDFILREL, NRSEQPRI)
      
     Select r.CDRELATO, r.NRVIADEF, r.NMRELATO
    , r.NRMODULO, r.NMDESTIN, r.NMFORMUL, r.INDAUDIT, c.CDCOOPER
    , r.PERIODIC, r.TPRELATO, r.INIMPREL, r.INGERPDF, r.DSDEMAIL,
    r.PROGRESS_RECID, r.CDFILREL, r.NRSEQPRI
    from (  SELECT 818 CDRELATO, NRVIADEF, 'PRESTAMISTAS RECUSADOS MENSAL' NMRELATO
                      , NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER
                      , 'Mensal' PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL
                      , NULL PROGRESS_RECID, CDFILREL, NRSEQPRI
            FROM craprel  rel 
            WHERE cdrelato = 817 and  cdcooper = 1 ) R , crapcop c 
            where c.flgativo = 1 
    ;
  COMMIT;
   EXCEPTION 
     WHEN OTHERS THEN 
       ROLLBACK;
END;
