INSERT INTO CRAPPRM(NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES('CRED', 1 , 'HORA_EXPIRA_TRANSPENDPIX', 'Horário de expiração das transações pendentes de Pix', '23:00' );
/
INSERT INTO CRAPPRM(NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES('CRED', 2 , 'HORA_EXPIRA_TRANSPENDPIX', 'Horário de expiração das transações pendentes de Pix', '23:00' );
/
INSERT INTO CRAPPRM(NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES('CRED', 5 , 'HORA_EXPIRA_TRANSPENDPIX', 'Horário de expiração das transações pendentes de Pix', '23:00' );
/
INSERT INTO CRAPPRM(NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES('CRED', 6 , 'HORA_EXPIRA_TRANSPENDPIX', 'Horário de expiração das transações pendentes de Pix', '23:00' );
/
INSERT INTO CRAPPRM(NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES('CRED', 7 , 'HORA_EXPIRA_TRANSPENDPIX', 'Horário de expiração das transações pendentes de Pix', '23:00' );
/
INSERT INTO CRAPPRM(NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES('CRED', 8 , 'HORA_EXPIRA_TRANSPENDPIX', 'Horário de expiração das transações pendentes de Pix', '23:00' );
/
INSERT INTO CRAPPRM(NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES('CRED', 9 , 'HORA_EXPIRA_TRANSPENDPIX', 'Horário de expiração das transações pendentes de Pix', '23:00' );
/
INSERT INTO CRAPPRM(NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES('CRED', 10 , 'HORA_EXPIRA_TRANSPENDPIX', 'Horário de expiração das transações pendentes de Pix', '23:00' );
/
INSERT INTO CRAPPRM(NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES('CRED', 11 , 'HORA_EXPIRA_TRANSPENDPIX', 'Horário de expiração das transações pendentes de Pix', '23:00' );
/
INSERT INTO CRAPPRM(NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES('CRED', 12 , 'HORA_EXPIRA_TRANSPENDPIX', 'Horário de expiração das transações pendentes de Pix', '23:00' );
/
INSERT INTO CRAPPRM(NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES('CRED', 13 , 'HORA_EXPIRA_TRANSPENDPIX', 'Horário de expiração das transações pendentes de Pix', '23:00' );
/
INSERT INTO CRAPPRM(NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES('CRED', 14 , 'HORA_EXPIRA_TRANSPENDPIX', 'Horário de expiração das transações pendentes de Pix', '23:00' );
/
INSERT INTO CRAPPRM(NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES('CRED', 16 , 'HORA_EXPIRA_TRANSPENDPIX', 'Horário de expiração das transações pendentes de Pix', '23:00' );
/
