UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKwKAAU'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ96AAA'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAILAAMpU5AAD'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKCAAAF'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHl32AAV'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIOAAMYRwAA9'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKG3AA6'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKqvAAz'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKovABg'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ4WAAx'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ//AAB'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ41AAt'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKAFAA/'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKzrAAQ'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKAUAAY'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKydAAu'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADK0rAAJ'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKHfAAr'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKA1AAS'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ66AAN'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKC4AAb'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHlzqAA6'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAN9AACiJXAAN'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ6PAAE'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADK2aAAT'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ9jAAL'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKDPAAY'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ6dAAP'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKH8AAK'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKA/AA9'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ/DAAJ'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ+XABR'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKCaABF'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKvbAAS'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKGJAAB'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ6mAA4'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKHHAAR'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKzDAAa'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKC6ABQ'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ7HAAy'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKGNABY'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ+CAAz'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHl3OABP'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADK2WAAt'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ8GAAg'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ9yABM'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ+TAA4'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ8UAA0'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADK2+AAI'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ7BABG'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHlyAABG'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIOAAMYQ/AAH'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ5GAAu'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ/jABi'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ4xABH'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKx3AAy'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKyvAAr'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKFmAAb'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKvkABF'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADK3OAAJ'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADK07AAj'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIOAAMYL+ABR'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKDVAAD'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAITAAE/70AAo'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ7OAAy'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKF7AAP'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKHsABm'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAN8AAFyjUABV'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ46AAH'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKEDAAj'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKC6AAH'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIOAAMYQtAA9'; -- COOP 16
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKCqAAy'; -- COOP 16

UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKFeAAa'; -- COOP 6
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIOAAMYXSAAl'; -- COOP 6
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKDnAAC'; -- COOP 6
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKr+AAT'; -- COOP 6
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKB0AAt'; -- COOP 6
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ7nAAf'; -- COOP 6
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKrqAAU'; -- COOP 6
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKz3ABF'; -- COOP 6

UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKyqAAq'; -- COOP 12
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ/GAAM'; -- COOP 12
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKDWAAL'; -- COOP 12
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ/GAAL'; -- COOP 12
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKpWAAW'; -- COOP 12
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHl2EAA4'; -- COOP 12
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKHKABF'; -- COOP 12
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKwJAAU'; -- COOP 12
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIOAAMYWUAAa'; -- COOP 12
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKGXAAy'; -- COOP 12
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKGPAAa'; -- COOP 12
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKEbAAf'; -- COOP 12

UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ7cAAO'; -- COOP 10
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKEGAA8'; -- COOP 10
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ6XAA4'; -- COOP 10
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ7XAA5'; -- COOP 10
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHl4nAA+'; -- COOP 10
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKqbAAm'; -- COOP 10
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ6RAAk'; -- COOP 10
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKwTAAF'; -- COOP 10
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAN8AAFyeBAAx'; -- COOP 10
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIOAAMYRhAA+'; -- COOP 10
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIOAAMYI/AAp'; -- COOP 10
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ5nAAf'; -- COOP 10
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ//ABJ'; -- COOP 10
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKuUAAK'; -- COOP 10
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKvMAAf'; -- COOP 10
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMcAAF448AA9'; -- COOP 10
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIOAAMYJGAAN'; -- COOP 10
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIOAAMYQZAAt'; -- COOP 10
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ6qAAV'; -- COOP 10
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKBOAAb'; -- COOP 10

UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ9pABF'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKHEABB'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ4xABF'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ5tAAF'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ7FAAO'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKDMAAy'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKD2AAM'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKu4AAt'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ/jABY'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKsZAAC'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ9sAAz'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ94AA6'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAILAAMpS3AAA'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ7fAAV'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKpdAAK'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ7CAAB'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ7pAAj'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKwDAAF'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADK2uABd'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ5rAAn'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADK2mAA6'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKBEAAD'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKpAAAm'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ/HABg'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKAgABF'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ6KAAD'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKH/AAT'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKF1AA6'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ7BABE'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKGDAAh'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ/XABJ'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKEGABS'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKucAAy'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADK0CAAB'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKqeAA0'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKGWAAN'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKHLABb'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ9nAAr'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ4TAAA'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ/VAA5'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIOAAMYM7AAR'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKAPABE'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKB2AAL'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKvEAAV'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADK2BAAV'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIOAAMYVZAAu'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADK01AAk'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ8PAAV'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ65ABr'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKvnABQ'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ7SABM'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKv0AAQ'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKtIAAe'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKBAAAV'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ49AA4'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ6UAA8'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKtIAAd'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIOAAMYPcAAw'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ7+AAS'; -- COOP 11
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ4UAAd'; -- COOP 11

UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ7uAAY'; -- COOP 8
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAN8AAFyfnAAS'; -- COOP 8
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKFUAAH'; -- COOP 8

UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ/lAAS'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAABEuxAAQ'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKyoAAi'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKGNAA+'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ7NAAF'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHl7UABm'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIIAAPfp1AAi'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKEeAAT'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ93AAv'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKAjAAA'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ5sAAv'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ6+AAi'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ+3AA7'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ5+AAC'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ8KAAm'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKEBAAA'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ/zABH'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKEQAAc'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKEYABX'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHl7vABG'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ9nAAY'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHlyLAAq'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKFAAAa'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ70AAm'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHlzhAA1'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ5BAAY'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHl6RAAE'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMcAAF49HABW'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ8LAAH'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADK3eAAW'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHlyjAAW'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ7fAAK'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ8hAAJ'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKDnAAB'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKzLAAj'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKDmAA6'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ/PABu'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKw+AAG'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADK3dAAL'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIOAAMYKJAAw'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKDZAAC'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ++AAX'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHl+cAAY'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHl+cAAX'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHlyvABh'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAILAAMpSgAAp'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIOAAMYPWAAe'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKvEAAE'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHl90AAO'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ+UAAe'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKGVAAB'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHl2sABJ'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHl2sABH'; -- COOP 14
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADK1eAA4'; -- COOP 14

UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ76ABW'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHlyhAA6'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKCEAAK'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ93AAu'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIQAALLUxABL'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ8mAAM'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKobAAL'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ5uAAo'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKDGAAp'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADK3+AAI'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADK1OAAj'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAILAAMpeoAAE'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKq5ABA'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAITAAE/8mAA3'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAITAAE/8mAA7'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAITAAE/8mAA4'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAITAAE/8mAA5'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ/7AAR'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ8VAAL'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ6bAAg'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKsrAAJ'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKobAAE'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHl/lABM'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKBNAAQ'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ5FAAT'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHlzbAAE'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKA8AAN'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIOAAMYVkAAv'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ6JABS'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKGrAAa'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIOAAMYPGAAr'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKExAAQ'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHl1dABq'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKu8AA4'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKqdAAM'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKAIAAG'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ7eAAN'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKGsAAP'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKGsAAQ'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIOAAMYPCABP'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKCCAAw'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ8WAAP'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIOAAMYTHAAF'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHlxpACB'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADK3tAAR'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ+QABY'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKrUAA6'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKByAAs'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHly1AAa'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHly1AAZ'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ/KAAo'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKD8ABK'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHl3cAAF'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ/vAA9'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAADKwwAA3'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ4ZAA3'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHly1AAe'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHl0SAAC'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMeAAHl0SAAD'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKH6AAI'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKHHAAX'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ/aAAi'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAITAAE/8mAA6'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIKDmAAn'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAILAAMpahAAl'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAMdAAIJ5kAAD'; -- COOP 9
UPDATE crapbpr SET flgregim = 0 WHERE rowid = 'AAAS6GAIOAAMYTXAAF'; -- COOP 9

COMMIT;
