CREATE OR REPLACE TRIGGER PROGRID."TRG_CRAPAEP_PROGRESS_RECID"
BEFORE INSERT ON CRAPAEP

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := CRAPAEP_SEQ.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-25100,'ERRO GERACAO SEQUENCE PROGRESS_RECID - TABELA CRAPAEP!');

END;
/

