CREATE OR REPLACE TRIGGER PROGRID."TRG_CRAPHEP_PROGRESS_RECID"
BEFORE INSERT ON CRAPHEP

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := CRAPHEP_SEQ.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-25100,'ERRO GERACAO SEQUENCE PROGRESS_RECID - TABELA CRAPHEP!');

END;
/

