CREATE OR REPLACE TRIGGER PROGRID."TRG_CRAPCDI_PROGRESS_RECID"
BEFORE INSERT ON CRAPCDI

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := CRAPCDI_SEQ.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-25100,'ERRO GERACAO SEQUENCE PROGRESS_RECID - TABELA CRAPCDI!');

END;
/

