CREATE OR REPLACE TRIGGER PROGRID."TRG_CRAPIAP_PROGRESS_RECID"
BEFORE INSERT ON CRAPIAP

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := CRAPIAP_SEQ.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-25100,'ERRO GERACAO SEQUENCE PROGRESS_RECID - TABELA CRAPIAP!');

END;
/

