CREATE OR REPLACE TRIGGER PROGRID."TRG_CRAPREP_PROGRESS_RECID"
BEFORE INSERT ON CRAPREP

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := CRAPREP_SEQ.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-25100,'ERRO GERACAO SEQUENCE PROGRESS_RECID - TABELA CRAPREP!');

END;
/

