CREATE OR REPLACE TRIGGER PROGRID."TRG_CRAPEAP_PROGRESS_RECID"
BEFORE INSERT ON CRAPEAP

FOR EACH ROW

BEGIN

  IF :NEW.PROGRESS_RECID IS NULL THEN
    :NEW.PROGRESS_RECID := CRAPEAP_SEQ.NEXTVAL;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-25100,'ERRO GERACAO SEQUENCE PROGRESS_RECID - TABELA CRAPEAP!');

END;
/

