BEGIN   
UPDATE CRAWEPR
   SET CRAWEPR.CDLCREMP = 3000
      ,CRAWEPR.CDFINEMP = 64
 WHERE CRAWEPR.CDCOOPER = 2
   AND CRAWEPR.NRDCONTA = 1020749
   AND CRAWEPR.NRCTREMP = 352655;  
COMMIT;   
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
END; 
