begin
  update 
    juridico.tbjur_termos_adesao 
  set 
    dscompleta = '<center><p><strong>PROCURAÇÃO</strong></p></center><p><strong>Eu, #RAZAO_SOCIAL_CEDENTE# (conta administrada), outorgo poderes para #RAZAO_SOCIAL_ADM# (conta administradora), </strong>na qualidade de OPERADOR conforme definições previstas nas Cláusulas e Condições Gerais Aplicáveis à Conta Corrente do Sistema Ailos Pessoa Jurídica disponível no site da sua Cooperativa, para realizar as movimentações nesta conta, conforme os poderes que serão posteriormente liberados por mim.</p><p><strong>Com esta procuração, EU, #RAZAO_SOCIAL_CEDENTE# (conta administrada), estou ciente de que sou responsável:</strong></p><ul><li>pelos atos praticados pelo OPERADOR cadastrado.</li><li>pela inclusão e exclusão de operadores bem como a gestão de permissão de acesso, liberaçõees de poderes e limites concedidos, sendo que a COOPERATIVA não possui qualquer interferência neste processo.</li></ul><p><strong>Fique atento!</strong> Se sua conta exigir assinatura conjunta para as movimentações, o acesso do OPERADOR será liberado quando todos os responsáveis realizarem a aprovação. No entanto, o OPERADOR poderá sempre assinar isoladamente, ainda que a sua conta requeira assinatura conjunta.</p>',
    dsresumida = '<p><strong>PROCURAÇÃO</strong></p><p><strong>Eu, #RAZAO_SOCIAL_CEDENTE# (conta administrada), outorgo poderes para #RAZAO_SOCIAL_ADM# (conta administradora), </strong>na qualidade de OPERADOR conforme definições previstas nas Cláusulas e Condições Gerais Aplicáveis; Conta Corrente do Sistema Ailos Pessoa Jurídica disponível no site da sua Cooperativa, para realizar as movimentações nesta conta, conforme os poderes que serão posteriormente liberados por mim.</p><p><strong>Com esta procuração, EU, #RAZAO_SOCIAL_CEDENTE# (conta administrada), estou ciente de que sou responsável:</strong></p><ul><li>pelos atos praticados pelo OPERADOR cadastrado.</li><li>pela inclusão e exclusão de operadores bem como a gestão de permissão de acesso, liberações de poderes e limites concedidos, sendo que a COOPERATIVA não possui qualquer interferência neste processo.</li></ul><p><strong>Fique atento!</strong> Se sua conta exigir assinatura conjunta para as movimentações, o acesso do OPERADOR será liberado quando todos os responsáveis realizarem a aprovação. No entanto, o OPERADOR poderá sempre assinar isoladamente, ainda que a sua conta requeira assinatura conjunta.</p>'
  WHERE
    tptermo_adesao = 1;
  
  commit;
end;