BEGIN
  UPDATE CRAPACA SET LSTPARAM = REPLACE(LSTPARAM,'PR_VIGENCIA','PR_DTINIVIGENCIA') || ', PR_DTFIMVIGENCIA' WHERE NMPACKAG = 'TELA_SEGPRE' AND NMDEACAO = 'SEGPRE_ALTERAR';
  COMMIT;
EXCEPTION WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('12 ERRO: ' || SQLERRM);
  ROLLBACK;
END;
/
