CREATE TABLE TBCOBRAN_LOG_ARQUIVO_IEPTB
  (
    IDLOG_ARQUIVO      NUMBER (10) NOT NULL ,
    DHLOG_ARQUIVO      DATE NOT NULL ,
    NMARQUIVO_IEPTB    VARCHAR2 (50) NOT NULL ,
    DTGERACAO_ARQUIVO  DATE NOT NULL ,
    QTREGISTRO_ARQUIVO NUMBER (5) NOT NULL ,
    IDFORMA_PROCESSA   NUMBER (1) NOT NULL ,
    CDOPERADOR         VARCHAR2 (10) NOT NULL ,
    DSERRO_ARQUIVO     VARCHAR2 (2000),
    TPARQUIVO_IEPTB    NUMBER(1) NOT NULL,
    CDSITUACAO         NUMBER(1)
  ) ;
COMMENT ON COLUMN TBCOBRAN_LOG_ARQUIVO_IEPTB.IDLOG_ARQUIVO
IS
  'Indicado do log do arquivo.' ;
  COMMENT ON COLUMN TBCOBRAN_LOG_ARQUIVO_IEPTB.DHLOG_ARQUIVO
IS
  'Data e hora do registro do log.' ;
  COMMENT ON COLUMN TBCOBRAN_LOG_ARQUIVO_IEPTB.NMARQUIVO_IEPTB
IS
  'Nome do arquivo IEPTB gerado.' ;
  COMMENT ON COLUMN TBCOBRAN_LOG_ARQUIVO_IEPTB.DTGERACAO_ARQUIVO
IS
  'Data de movimento da geracao do arquivo.' ;
  COMMENT ON COLUMN TBCOBRAN_LOG_ARQUIVO_IEPTB.QTREGISTRO_ARQUIVO
IS
  'Quantidade de registros do arquivo.' ;
  COMMENT ON COLUMN TBCOBRAN_LOG_ARQUIVO_IEPTB.IDFORMA_PROCESSA
IS
  'Forma de processamento do arquivo (Dominio: FORMA_PROCESSA_ARQ_IEPTB).' ;
  COMMENT ON COLUMN TBCOBRAN_LOG_ARQUIVO_IEPTB.CDOPERADOR
IS
  'Codigo do operador que realizou o processamento do arquivo.' ;
  COMMENT ON COLUMN TBCOBRAN_LOG_ARQUIVO_IEPTB.DSERRO_ARQUIVO
IS
  'Descricao do erro na geracao do arquivo.' ;
  COMMENT ON COLUMN CECRED.TBCOBRAN_LOG_ARQUIVO_IEPTB.TPARQUIVO_IEPTB
IS 
  'Tipo do arquivo do log (Dominio: TIPO_ARQUIVO_IEPTB).';
  COMMENT ON COLUMN CECRED.TBCOBRAN_LOG_ARQUIVO_IEPTB.CDSITUACAO
IS 
  'Situacao do arquivo (1=Pendente / 2=Processado).';
  ALTER TABLE TBCOBRAN_LOG_ARQUIVO_IEPTB ADD CONSTRAINT TBCOBRAN_LOG_ARQUIVO_IEPTB_PK PRIMARY KEY ( IDLOG_ARQUIVO ) ;
  CREATE TABLE TBCOBRAN_LOG_ITEM_ARQ_IEPTB
    (
      IDLOG_ARQUIVO NUMBER (10) NOT NULL ,
      IDSEQ_BOLETO  NUMBER (5) NOT NULL ,
      CDCOOPER      NUMBER (10) ,
      CDBANDOC      NUMBER (5) ,
      NRDCTABB      NUMBER (10) ,
      NRCNVCOB      NUMBER (10) ,
      NRDCONTA      NUMBER (10) ,
      NRDOCMTO      NUMBER (10) ,
      VLTITULO      NUMBER (25,2)
    ) ;
  COMMENT ON COLUMN TBCOBRAN_LOG_ITEM_ARQ_IEPTB.IDLOG_ARQUIVO
IS
  'Indicado do log do arquivo.' ;
  COMMENT ON COLUMN TBCOBRAN_LOG_ITEM_ARQ_IEPTB.IDSEQ_BOLETO
IS
  'Indica o boleto enviado ou recebido no arquivo' ;
  COMMENT ON COLUMN TBCOBRAN_LOG_ITEM_ARQ_IEPTB.CDCOOPER
IS
  'Codigo que identifica a Cooperativa. ' ;
  COMMENT ON COLUMN TBCOBRAN_LOG_ITEM_ARQ_IEPTB.CDBANDOC
IS
  'Codigo do banco/caixa.' ;
  COMMENT ON COLUMN TBCOBRAN_LOG_ITEM_ARQ_IEPTB.NRDCTABB
IS
  'Numero da conta base no banco.' ;
  COMMENT ON COLUMN TBCOBRAN_LOG_ITEM_ARQ_IEPTB.NRCNVCOB
IS
  'Numero do convenio de cobranca.' ;
  COMMENT ON COLUMN TBCOBRAN_LOG_ITEM_ARQ_IEPTB.NRDCONTA
IS
  'Numero da conta/dv do associado.' ;
  COMMENT ON COLUMN TBCOBRAN_LOG_ITEM_ARQ_IEPTB.NRDOCMTO
IS
  'Numero do documento(Boleto).' ;
  COMMENT ON COLUMN TBCOBRAN_LOG_ITEM_ARQ_IEPTB.VLTITULO
IS
  'Valor do titulo em cobranca.' ;
  ALTER TABLE TBCOBRAN_LOG_ITEM_ARQ_IEPTB ADD CONSTRAINT TBCOBRAN_LOG_ITEM_ARQ_IEPTB_PK PRIMARY KEY ( IDLOG_ARQUIVO, IDSEQ_BOLETO ) ;
  ALTER TABLE TBCOBRAN_LOG_ITEM_ARQ_IEPTB ADD CONSTRAINT TBCOBRAN_LOG_ITEM_ARQ_IEPTBFK1 FOREIGN KEY ( IDLOG_ARQUIVO ) REFERENCES TBCOBRAN_LOG_ARQUIVO_IEPTB ( IDLOG_ARQUIVO ) ;
  
-- Create sequence 
CREATE SEQUENCE CECRED.TBCOBRAN_LOG_ARQUIVO_IEPTB_SEQ
MINVALUE 1
MAXVALUE 9999999999
START WITH 1
INCREMENT BY 1
CYCLE;