/*
Incluído históricos para serem apresentados na tela de créditos recebidos:
2454-ANTECIPACAO DE VENDAS COM CARTOES - REDE 
2446-CREDITO DE VENDAS COM CARTOES A DEBITO - REDE 
1590-DEPOSITO TRANSPORTE DE VALORES (ESTABELECIMENTOS)
2104-CREDITO DISTRIBUICAO DE LUCROS 
2105-CREDITO REEMBOLSO 
2442-CREDITO DE VENDAS COM CARTOES A CREDITO - REDE 
*/
UPDATE crapprm prm
   SET prm.dsvlrprm = prm.dsvlrprm || '2454;2446;1590;2104;2105;2442;'
 WHERE prm.nmsistem = 'CRED'
   AND prm.cdacesso = 'HIS_CRED_RECEBIDOS';
	 
-- Efetuar commit
COMMIT;
