
update tbchq_deposito_cheque_mob set insituacao = 4 where idseqdeposito = 226;
update tbchq_deposito_cheque_mob set insituacao = 4 where idseqdeposito = 227;
update tbchq_deposito_cheque_mob set insituacao = 4 where idseqdeposito = 228;
update tbchq_deposito_cheque_mob set insituacao = 4 where idseqdeposito = 229;
update tbchq_deposito_cheque_mob set insituacao = 4 where idseqdeposito = 230;
update tbchq_deposito_cheque_mob set insituacao = 4 where idseqdeposito = 231;
update tbchq_deposito_cheque_mob set insituacao = 4 where idseqdeposito = 232;
update tbchq_deposito_cheque_mob set dsmotivo_recusa = 'Formalistica' where idseqdeposito = 226;
update tbchq_deposito_cheque_mob set dsmotivo_recusa = 'Formalistica' where idseqdeposito = 227;
update tbchq_deposito_cheque_mob set dsmotivo_recusa = 'Formalistica' where idseqdeposito = 228;
update tbchq_deposito_cheque_mob set dsmotivo_recusa = 'Formalistica' where idseqdeposito = 229;
update tbchq_deposito_cheque_mob set dsmotivo_recusa = 'Formalistica' where idseqdeposito = 230;
update tbchq_deposito_cheque_mob set dsmotivo_recusa = 'Formalistica' where idseqdeposito = 231;
update tbchq_deposito_cheque_mob set dsmotivo_recusa = 'Formalistica' where idseqdeposito = 232;
update tbchq_deposito_cheque_mob set origem_recusa = 1 where idseqdeposito = 226;
update tbchq_deposito_cheque_mob set origem_recusa = 1 where idseqdeposito = 227;
update tbchq_deposito_cheque_mob set origem_recusa = 1 where idseqdeposito = 228;
update tbchq_deposito_cheque_mob set origem_recusa = 1 where idseqdeposito = 229;
update tbchq_deposito_cheque_mob set origem_recusa = 1 where idseqdeposito = 230;
update tbchq_deposito_cheque_mob set origem_recusa = 1 where idseqdeposito = 231;
update tbchq_deposito_cheque_mob set origem_recusa = 1 where idseqdeposito = 232;
update tbchq_deposito_cheque_mob set dscomplemento = 'RC TRANSPORT' where idseqdeposito = 280;
update tbchq_deposito_cheque_mob set dscomplemento = '13' where idseqdeposito = 281;
update tbchq_deposito_cheque_mob set dscomplemento = 'Bau camara' where idseqdeposito = 289;
update tbchq_deposito_cheque_mob set dscomplemento = 'Cheque Sze' where idseqdeposito = 306;
update tbchq_deposito_cheque_mob set dscomplemento = 'IIP1307' where idseqdeposito = 312;
update tbchq_deposito_cheque_mob set dscomplemento = 'Irmos Knies' where idseqdeposito = 329;
update tbchq_deposito_cheque_mob set dscomplemento = 'Posto Castelao' where idseqdeposito = 333;
update tbchq_deposito_cheque_mob set dscomplemento = 'Posto Castelao' where idseqdeposito = 332;
COMMIT;