BEGIN
      INSERT INTO CECRED.CRAPBAT B (CDBATTAR, NMIDENTI, CDPROGRA, TPCADAST, CDCADAST) VALUES ('SAQUETAAPJ', 'SAQUE TERMINAL DE AUTO ATENDIMENTO PESSOA JURIDICA', 'CRPS581', 1, 247);
	  INSERT INTO CECRED.CRAPBAT B (CDBATTAR, NMIDENTI, TPCADAST, CDCADAST) VALUES ('SAQBAN24PJ', 'SAQUE CARTAO CECRED BANCO 24 HORAS PJ', '', 1, 249);
	  INSERT INTO CECRED.CRAPBAT B (CDBATTAR, NMIDENTI, TPCADAST, CDCADAST) VALUES ('SAQBAN24PF', 'SAQUE CARTAO CECRED BANCO 24 HORAS PF', '', 1, 248);
      COMMIT;
END;