BEGIN

  declare

  vr_nrctrcrd crawcrd.nrctrcrd%TYPE;
  vr_nrseqcrd crawcrd.nrseqcrd%TYPE;

  begin

  vr_nrctrcrd := fn_sequence('CRAPMAT','NRCTRCRD', 2);
  vr_nrseqcrd := CCRD0003.fn_sequence_nrseqcrd(2);

  insert into cecred.crawcrd
    (nrdconta,
    nrcrcard,
    nrcctitg,
    nrcpftit,
    vllimcrd,
    flgctitg,
    dtmvtolt,
    nmextttl,
    flgprcrd,
    tpdpagto,
    flgdebcc,
    tpenvcrd,
    vlsalari,
    dddebito,
    cdlimcrd,
    tpcartao,
    dtnasccr,
    nrdoccrd,
    nmtitcrd,
    nrctrcrd,
    cdadmcrd,
    cdcooper,
    nrseqcrd,
    dtpropos,
    dtsolici,
    flgdebit,
    cdgraupr,
    insitcrd,
    dtlibera,
    insitdec)
  values  (13085514,       
    '5161620005378459',   
    7563239780753,    
    11351729942,     
    2600,      
    3,        
    trunc(sysdate),   
    'SABRINA NASCIMENTO',  
    1,      
    3,    
    0,   
    0,   
    2000,    
    22,    
    0,     
    2,    
    to_date('14/02/2000','dd/mm/yyyy'),
    '124360471',     
    'SABRINA NASCIMENTO',   
    vr_nrctrcrd,   
    18,      
    1,      
    vr_nrseqcrd,     
    to_date('20/09/2022','dd/mm/rrrr'), 
    to_date('20/09/2022','dd/mm/rrrr'), 
    1,         
    5,       
    4,       
    null,   
    2     
    );

  insert into cecred.crapcrd
    (cdcooper,
    nrdconta,
    nrcrcard,
    nrcpftit,
    nmtitcrd,
    dddebito,
    cdlimcrd,
    dtvalida,
    nrctrcrd,
    cdmotivo,
    nrprotoc,
    cdadmcrd,
    tpcartao,
    dtcancel,
    flgdebit,
    flgprovi)
  values  (1,     
    13085514,       
    '5161620005378459',  
    11351729942,    
    'SABRINA NASCIMENTO', 
    22,      
    0,     
    NULL,    
    vr_nrctrcrd,   
    0,  
    0,       
    18,     
    2,     
    NULL,  
    1,   
    0      
    );
    commit;  
    
  vr_nrctrcrd := fn_sequence('CRAPMAT','NRCTRCRD', 2);
  vr_nrseqcrd := CCRD0003.fn_sequence_nrseqcrd(2);

  insert into cecred.crawcrd
    (nrdconta,
    nrcrcard,
    nrcctitg,
    nrcpftit,
    vllimcrd,
    flgctitg,
    dtmvtolt,
    nmextttl,
    flgprcrd,
    tpdpagto,
    flgdebcc,
    tpenvcrd,
    vlsalari,
    dddebito,
    cdlimcrd,
    tpcartao,
    dtnasccr,
    nrdoccrd,
    nmtitcrd,
    nrctrcrd,
    cdadmcrd,
    cdcooper,
    nrseqcrd,
    dtpropos,
    dtsolici,
    flgdebit,
    cdgraupr,
    insitcrd,
    dtlibera,
    insitdec)
  values  (8397945,       
    '5474080256782200',   
    7563239063755,    
    98830864900,     
    50000,      
    3,        
    trunc(sysdate),   
    'JULIANO SOUZA MEDEIROS',  
    0,      
    3,    
    1,   
    0,   
    2636,    
    19,    
    0,     
    2,    
    to_date('19/01/1979','dd/mm/yyyy'),
    '0',     
    'JULIANO SOUZA MEDEIROS',   
    vr_nrctrcrd,   
    15,      
    1,      
    vr_nrseqcrd,     
    to_date('11/05/2022','dd/mm/rrrr'), 
    to_date('11/05/2022','dd/mm/rrrr'), 
    1,         
    0,       
    4,       
    null,   
    1     
    );

  insert into cecred.crapcrd
    (cdcooper,
    nrdconta,
    nrcrcard,
    nrcpftit,
    nmtitcrd,
    dddebito,
    cdlimcrd,
    dtvalida,
    nrctrcrd,
    cdmotivo,
    nrprotoc,
    cdadmcrd,
    tpcartao,
    dtcancel,
    flgdebit,
    flgprovi)
  values  (1,     
    8397945,       
    '5474080256782200',  
    98830864900,    
    'JULIANO SOUZA MEDEIROS', 
    19,      
    54,     
    NULL,    
    vr_nrctrcrd,   
    0,  
    0,       
    15,     
    2,     
    NULL,  
    1,   
    0      
    );
    commit;    
    
  vr_nrctrcrd := fn_sequence('CRAPMAT','NRCTRCRD', 2);
  vr_nrseqcrd := CCRD0003.fn_sequence_nrseqcrd(2);

  insert into cecred.crawcrd
    (nrdconta,
    nrcrcard,
    nrcctitg,
    nrcpftit,
    vllimcrd,
    flgctitg,
    dtmvtolt,
    nmextttl,
    flgprcrd,
    tpdpagto,
    flgdebcc,
    tpenvcrd,
    vlsalari,
    dddebito,
    cdlimcrd,
    tpcartao,
    dtnasccr,
    nrdoccrd,
    nmtitcrd,
    nrctrcrd,
    cdadmcrd,
    cdcooper,
    nrseqcrd,
    dtpropos,
    dtsolici,
    flgdebit,
    cdgraupr,
    insitcrd,
    dtlibera,
    insitdec)
  values  (11065834,       
    '5474080268033253',   
    7563239551903,    
    10154564990,     
    12200,      
    3,        
    trunc(sysdate),   
    'ALICE M A CARPEGGIANI',  
    1,      
    1,    
    1,   
    0,   
    0,    
    19,    
    0,     
    2,    
    to_date('11/04/1996','dd/mm/yyyy'),
    '5869188',     
    'ALICE M A CARPEGGIANI',   
    vr_nrctrcrd,   
    15,      
    1,      
    vr_nrseqcrd,     
    to_date('11/08/2022','dd/mm/rrrr'), 
    to_date('11/08/2022','dd/mm/rrrr'), 
    1,         
    5,       
    4,       
    null,   
    1     
    );

  insert into cecred.crapcrd
    (cdcooper,
    nrdconta,
    nrcrcard,
    nrcpftit,
    nmtitcrd,
    dddebito,
    cdlimcrd,
    dtvalida,
    nrctrcrd,
    cdmotivo,
    nrprotoc,
    cdadmcrd,
    tpcartao,
    dtcancel,
    flgdebit,
    flgprovi)
  values  (1,     
    11065834,       
    '5474080268033253',  
    10154564990,    
    'ALICE M A CARPEGGIANI', 
    19,      
    0,     
    NULL,    
    vr_nrctrcrd,   
    0,  
    0,       
    15,     
    2,     
    NULL,  
    1,   
    0      
    );
    commit;   

  vr_nrctrcrd := fn_sequence('CRAPMAT','NRCTRCRD', 2);
  vr_nrseqcrd := CCRD0003.fn_sequence_nrseqcrd(2);

  insert into cecred.crawcrd
    (nrdconta,
    nrcrcard,
    nrcctitg,
    nrcpftit,
    vllimcrd,
    flgctitg,
    dtmvtolt,
    nmextttl,
    flgprcrd,
    tpdpagto,
    flgdebcc,
    tpenvcrd,
    vlsalari,
    dddebito,
    cdlimcrd,
    tpcartao,
    dtnasccr,
    nrdoccrd,
    nmtitcrd,
    nrctrcrd,
    cdadmcrd,
    cdcooper,
    nrseqcrd,
    dtpropos,
    dtsolici,
    flgdebit,
    cdgraupr,
    insitcrd,
    dtlibera,
    insitdec)
  values  (11359528,       
    '5474080315512259',   
    7563239589080,    
    8427768931,     
    20000,      
    3,        
    trunc(sysdate),   
    'ANDRE L DUARTE ROEDEL',  
    1,      
    1,    
    1,   
    0,   
    0,    
    11,    
    54,     
    2,    
    to_date('19/03/2000','dd/mm/yyyy'),
    '124533236',     
    'ANDRE L D ROEDEL',   
    vr_nrctrcrd,   
    15,      
    1,      
    vr_nrseqcrd,     
    to_date('03/07/2023','dd/mm/rrrr'), 
    to_date('03/07/2023','dd/mm/rrrr'), 
    1,         
    5,       
    4,       
    null,   
    1     
    );

  insert into cecred.crapcrd
    (cdcooper,
    nrdconta,
    nrcrcard,
    nrcpftit,
    nmtitcrd,
    dddebito,
    cdlimcrd,
    dtvalida,
    nrctrcrd,
    cdmotivo,
    nrprotoc,
    cdadmcrd,
    tpcartao,
    dtcancel,
    flgdebit,
    flgprovi)
  values  (1,     
    11359528,       
    '5474080315512259',  
    8427768931,    
    'ANDRE L D ROEDEL', 
    11,      
    86,     
    NULL,    
    vr_nrctrcrd,   
    0,  
    0,       
    15,     
    2,     
    NULL,  
    1,   
    0      
    );
    commit;  

  end;

END;
