BEGIN
  UPDATE CECRED.CRAPRDA RDA
     SET RDA.INSAQTOT = 1
     WHERE RDA.NRDCONTA = 99602636
     AND RDA.CDCOOPER = 16
     AND RDA.NRAPLICA = 1;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
END;
