BEGIN
  INSERT INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) 
  VALUES ('CRED', 0, 'EMAIL_ARQ_SICREDI_RECEBE', 'Email para as criticas no programa PC_CNS_RECEBE_ARQ', 'consorcio@ailos.coop.br');
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20003,'Erro ao inserir parâmetro' || SQLERRM);
    ROLLBACK;
END;