update tbcc_lancamentos_pendentes l set l.idsituacao = 'A', l.DSCRITICA = '', l.qtexecucoes = 1 where l.idseq_lancamento = 1857339;
update tbcc_lancamentos_pendentes l set l.idsituacao = 'A', l.DSCRITICA = '', l.qtexecucoes = 1 where l.idseq_lancamento = 1857340;
update tbcc_lancamentos_pendentes l set l.idsituacao = 'A', l.DSCRITICA = '', l.qtexecucoes = 1 where l.idseq_lancamento = 1857341;
update tbcc_lancamentos_pendentes l set l.idsituacao = 'A', l.DSCRITICA = '', l.qtexecucoes = 1 where l.idseq_lancamento = 1857342;
update tbcc_lancamentos_pendentes l set l.idsituacao = 'A', l.DSCRITICA = '', l.qtexecucoes = 1 where l.idseq_lancamento = 1857343;
update tbcc_lancamentos_pendentes l set l.idsituacao = 'A', l.DSCRITICA = '', l.qtexecucoes = 1 where l.idseq_lancamento = 1857344;
update tbcc_lancamentos_pendentes l set l.idsituacao = 'A', l.DSCRITICA = '', l.qtexecucoes = 1 where l.idseq_lancamento = 1857345;
update tbcc_lancamentos_pendentes l set l.idsituacao = 'A', l.DSCRITICA = '', l.qtexecucoes = 1 where l.idseq_lancamento = 1857346;
update tbcc_lancamentos_pendentes l set l.idsituacao = 'A', l.DSCRITICA = '', l.qtexecucoes = 1 where l.idseq_lancamento = 1857347;
update tbcc_lancamentos_pendentes l set l.idsituacao = 'A', l.DSCRITICA = '', l.qtexecucoes = 1 where l.idseq_lancamento = 1857348;
commit;
