-- Carga classes de scores por cooperativas ativas
BEGIN
  FOR rw_crapcop IN (SELECT cdcooper FROM crapcop c WHERE c.flgativo = 1) LOOP  

    INSERT INTO credito.TBCRED_RISCO_SCORE (CDCOOPER, DSCLASSE_SCORE, CDFAIXA_RISCO, CDOPERAD, DTREFERENCIA, IDORDENACAO)
    VALUES (rw_crapcop.cdcooper, 'BAIXISSIMO RISCO', 'R18', '1', SYSDATE, 5);

    INSERT INTO credito.TBCRED_RISCO_SCORE (CDCOOPER, DSCLASSE_SCORE, CDFAIXA_RISCO, CDOPERAD, DTREFERENCIA, IDORDENACAO)
    VALUES (rw_crapcop.cdcooper, 'BAIXO RISCO', 'R21', '1', SYSDATE, 10);

    INSERT INTO credito.TBCRED_RISCO_SCORE (CDCOOPER, DSCLASSE_SCORE, CDFAIXA_RISCO, CDOPERAD, DTREFERENCIA, IDORDENACAO)
    VALUES (rw_crapcop.cdcooper, 'MEDIO RISCO 1', 'R24', '1', SYSDATE, 15);

    INSERT INTO credito.TBCRED_RISCO_SCORE (CDCOOPER, DSCLASSE_SCORE, CDFAIXA_RISCO, CDOPERAD, DTREFERENCIA, IDORDENACAO)
    VALUES (rw_crapcop.cdcooper, 'MEDIO RISCO 2', 'R27', '1', SYSDATE, 20);
    
    INSERT INTO credito.TBCRED_RISCO_SCORE (CDCOOPER, DSCLASSE_SCORE, CDFAIXA_RISCO, CDOPERAD, DTREFERENCIA, IDORDENACAO)
    VALUES (rw_crapcop.cdcooper, 'MEDIO RISCO 3', 'R30', '1', SYSDATE, 25);
    
    INSERT INTO credito.TBCRED_RISCO_SCORE (CDCOOPER, DSCLASSE_SCORE, CDFAIXA_RISCO, CDOPERAD, DTREFERENCIA, IDORDENACAO)
    VALUES (rw_crapcop.cdcooper, 'ALTO RISCO', 'R33', '1', SYSDATE, 30);

    INSERT INTO credito.TBCRED_RISCO_SCORE (CDCOOPER, DSCLASSE_SCORE, CDFAIXA_RISCO, CDOPERAD, DTREFERENCIA, IDORDENACAO)
    VALUES (rw_crapcop.cdcooper, 'ALTISSIMO RISCO', 'R36', '1', SYSDATE, 35);
    
    INSERT INTO credito.TBCRED_RISCO_SCORE (CDCOOPER, DSCLASSE_SCORE, CDFAIXA_RISCO, CDOPERAD, DTREFERENCIA, IDORDENACAO)
    VALUES (rw_crapcop.cdcooper, 'SEM CLASSIFICACAO BAIXO RISCO', 'R21', '1', SYSDATE, 100);
    
    INSERT INTO credito.TBCRED_RISCO_SCORE (CDCOOPER, DSCLASSE_SCORE, CDFAIXA_RISCO, CDOPERAD, DTREFERENCIA, IDORDENACAO)
    VALUES (rw_crapcop.cdcooper, 'SEM CLASSIFICACAO MEDIO RISCO', 'R24', '1', SYSDATE, 200);
    
    INSERT INTO credito.TBCRED_RISCO_SCORE (CDCOOPER, DSCLASSE_SCORE, CDFAIXA_RISCO, CDOPERAD, DTREFERENCIA, IDORDENACAO)
    VALUES (rw_crapcop.cdcooper, 'SEM CLASSIFICACAO ALTO RISCO', 'R27', '1', SYSDATE, 300);
    
    INSERT INTO credito.TBCRED_RISCO_SCORE (CDCOOPER, DSCLASSE_SCORE, CDFAIXA_RISCO, CDOPERAD, DTREFERENCIA, IDORDENACAO)
    VALUES (rw_crapcop.cdcooper, 'SEM CLASSIFICACAO RISCO', 'R24', '1', SYSDATE, 400);
   
  END LOOP;
  COMMIT;
  EXCEPTION 
    WHEN OTHERS THEN 
      ROLLBACK;
END;
/

--crapaca
INSERT INTO CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR)
VALUES ('BUSCAR_RISCO_SCORE','TELA_LCREDI','pc_busca_risco_score','',
                      (SELECT a.nrseqrdr FROM CRAPRDR a WHERE a.nmprogra = 'TELA_LCREDI' AND ROWNUM = 1));

INSERT INTO CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR)
VALUES ('ALTERAR_RISCO_SCORE','TELA_LCREDI','pc_altera_risco_score_web','pr_risco_score_cc,pr_risco_score_sc,pr_risco_score_ca',
                      (SELECT a.nrseqrdr FROM CRAPRDR a WHERE a.nmprogra = 'TELA_LCREDI' AND ROWNUM = 1));
					  
COMMIT;					  

