BEGIN
  UPDATE TBCADAST_DOMINIO_CAMPO
     SET DSCODIGO = 'Cancelada'
   WHERE NMDOMINIO = 'SITUACAO_RECEITA_FEDERAL'
     AND CDDOMINIO = '3';

  UPDATE TBCADAST_DOMINIO_CAMPO
     SET DSCODIGO = 'Nula'
   WHERE NMDOMINIO = 'SITUACAO_RECEITA_FEDERAL'
     AND CDDOMINIO = '4';

  UPDATE TBCADAST_DOMINIO_CAMPO
     SET DSCODIGO = 'Suspensa'
   WHERE NMDOMINIO = 'SITUACAO_RECEITA_FEDERAL'
     AND CDDOMINIO = '5';

  INSERT INTO TBCADAST_DOMINIO_CAMPO
    (NMDOMINIO, CDDOMINIO, DSCODIGO)
  VALUES
    ('SITUACAO_RECEITA_FEDERAL', '6', 'Titular falecido');

  INSERT INTO TBCADAST_DOMINIO_CAMPO
    (NMDOMINIO, CDDOMINIO, DSCODIGO)
  VALUES
    ('SITUACAO_RECEITA_FEDERAL', '7', 'Baixada');

  INSERT INTO TBCADAST_DOMINIO_CAMPO
    (NMDOMINIO, CDDOMINIO, DSCODIGO)
  VALUES
    ('SITUACAO_RECEITA_FEDERAL', '8', 'Inapta');

  INSERT INTO TBCADAST_DOMINIO_CAMPO
    (NMDOMINIO, CDDOMINIO, DSCODIGO)
  VALUES
    ('SITUACAO_RECEITA_FEDERAL', '9', 'Ativa');

  COMMIT;
END;
