BEGIN
  
  UPDATE CRAPPAT
     SET NMPARTAR = 'HABILITA ROTINA CRPS672 = 0 (REVITALIZAR.PC_CRPS672) - 1 (CARTAO.GERARARQUIVOCRPS672) - 2 (CARTAO.CRD_CRPS672)'
   WHERE CDPARTAR = 77;
  
  UPDATE CRAPPCO
     SET DSCONTEU = 0
   WHERE CDPARTAR = 77;  

  COMMIT;
  
END;
