DECLARE

BEGIN
    UPDATE GNSBMOD
       SET GNSBMOD.DSSUBMOD = 'Home Equity'
     WHERE GNSBMOD.CDSUBMOD = '11' 
       AND GNSBMOD.CDMODALI = '02';  
COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    RAISE_application_error(-20500,SQLERRM);
    ROLLBACK;
END;
