begin

 UPDATE CRAPASS SET NMPRIMTL = 'RAFAEL ANDRZEJEVSKI' WHERE CDCOOPER = 16 AND NRDCONTA = 232858;
 UPDATE CRAPASS SET NMPRIMTL = 'FRANCIELY LUCIANE ADRIANO CALIXTO' WHERE CDCOOPER = 6 AND NRDCONTA = 237795;
 UPDATE CRAPASS SET NMPRIMTL = 'MICHEL DE OLIVEIRA CORREIA' WHERE CDCOOPER = 1 AND NRDCONTA = 12708038;
 
 UPDATE CRAPTTL SET NMEXTTTL = 'NILTON ELIZIO' WHERE CDCOOPER = 2 AND NRDCONTA = 27448 AND IDSEQTTL = 2;
 UPDATE CRAPTTL SET NMEXTTTL = 'NILTON ELIZIO' WHERE CDCOOPER = 1 AND NRDCONTA = 80027440  AND IDSEQTTL = 2;
 UPDATE CRAPTTL SET NMEXTTTL = 'RAFAEL ANDRZEJEVSKI' WHERE CDCOOPER = 16 AND NRDCONTA = 232858  AND IDSEQTTL = 1;
 UPDATE CRAPTTL SET NMEXTTTL = 'FRANCIELY LUCIANE ADRIANO CALIXTO' WHERE CDCOOPER = 6 AND NRDCONTA = 237795   AND IDSEQTTL = 1;
 UPDATE CRAPTTL SET NMEXTTTL = 'MICHEL DE OLIVEIRA CORREIA' WHERE CDCOOPER = 1 AND NRDCONTA = 12708038   AND IDSEQTTL = 1;
 

  commit;


end;


