DECLARE
  vr_idcampo tbgen_layout.IDLAYOUT%TYPE;
BEGIN

  DELETE FROM tbgen_layout_programa c 
    WHERE EXISTS (SELECT 1 FROM tbgen_layout l WHERE l.idlayout = c.idlayout AND l.nmlayout = 'GFGF200R');
  DELETE FROM tbgen_layout_campo c 
    WHERE EXISTS (SELECT 1 FROM tbgen_layout l WHERE l.idlayout = c.idlayout AND l.nmlayout = 'GFGF200R');
  DELETE FROM tbgen_layout l WHERE l.nmlayout = 'GFGF200R';

  SELECT MAX(IDLAYOUT)+1 INTO vr_idcampo FROM tbgen_layout;

  -- Insere o novo layout
  INSERT INTO tbgen_layout (IDLAYOUT, NMLAYOUT, DSLAYOUT, DSDELIMITADOR, DSOBSERVACAO)
  VALUES (vr_idcampo, 'GFGF200R', 'Pronampe - Valida豫o dos Eventos do Agentea', null, '2� Retorno');

  -- Insere nome do programa para rastreabilidade
    INSERT INTO tbgen_layout_programa (IDLAYOUT, CDPROGRA)
    VALUES (vr_idcampo, 'incluirPronampeGFGF200R');

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values (vr_idcampo, 'H', 1, 'CDTIPOREG', 'T', null, 8, 2, null, 'TIPO DE REGISTRO', '01');

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, 'H', 2, 'NRSEQREMESSA', 'N', null, 32, 4, null, 'SEQUENCIAL DO ARQUIVO DE REMESSA', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, 'T', 1, 'CDTIPOREG', 'T', null, 8, 2, null, 'TIPO DE REGISTRO', '99');

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '03', 1, 'TPREGISTRO', 'T', null, 8, 2, null, 'TIPO DE REGISTRO', '03');

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '03', 2, 'IDCONTRATO', 'T', null, 10, 20, null, 'ID DO CONTRATO - PROGRESSRECID', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '03', 3, 'VLFINANCIADO', 'N', null, 192, 17, 2, 'VALOR FINANCIADO PARA O COOPERADO', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '03', 4, 'CDREJEICAO', 'N', null, 209, 3, null, 'CODIGO DE REJEI플O (DOMINIO PRONAMP_RETORNOREG)', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '04', 1, 'TPREGISTRO', 'T', null, 8, 2, null, 'TIPO DE REGISTRO', '04');

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '04', 2, 'IDCONTRATO', 'T', null, 10, 20, null, 'ID DO CONTRATO - PROGRESSRECID', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '04', 3, 'CDREJEICAO', 'N', null, 209, 3, null, 'CODIGO DE REJEI플O (DOMINIO PRONAMP_RETORNOREG)', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '05', 1, 'TPREGISTRO', 'T', null, 8, 2, null, 'TIPO DE REGISTRO', '05');

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '05', 2, 'IDCONTRATO', 'T', null, 10, 20, null, 'ID DO CONTRATO - PROGRESSRECID', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '05', 3, 'CDREJEICAO', 'N', null, 209, 3, null, 'CODIGO DE REJEI플O (DOMINIO PRONAMP_RETORNOREG)', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '06', 1, 'TPREGISTRO', 'T', null, 8, 2, null, 'TIPO DE REGISTRO', '06');

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '06', 2, 'IDCONTRATO', 'T', null, 10, 20, null, 'ID DO CONTRATO - PROGRESSRECID', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '06', 3, 'CDREJEICAO', 'N', null, 209, 3, null, 'CODIGO DE REJEI플O (DOMINIO PRONAMP_RETORNOREG)', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '07', 1, 'TPREGISTRO', 'T', null, 8, 2, null, 'TIPO DE REGISTRO', '07');

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '07', 2, 'IDCONTRATO', 'T', null, 10, 20, null, 'ID DO CONTRATO - PROGRESSRECID', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '07', 3, 'CDREJEICAO', 'N', null, 209, 3, null, 'CODIGO DE REJEI플O (DOMINIO PRONAMP_RETORNOREG)', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '08', 1, 'TPREGISTRO', 'T', null, 8, 2, null, 'TIPO DE REGISTRO', '08');

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '08', 2, 'IDCONTRATO', 'T', null, 10, 20, null, 'ID DO CONTRATO - PROGRESSRECID', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '08', 3, 'DTRECUPERACAO', 'D', 'RRRRMMDD', 30, 8, null, 'DATA DA RECUPERACAO DO VALOR', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '08', 4, 'VLRECUPERADO', 'N', null, 38, 17, 2, 'VALOR RECUPERADO A CANCELAR', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '08', 5, 'DTCANCELAMENTO', 'D', 'RRRRMMDD', 55, 8, null, 'DATA DO CANCELAMENTO DO VALOR RECUPERADO', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '09', 1, 'TPREGISTRO', 'T', null, 8, 2, null, 'TIPO DE REGISTRO', '09');

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '09', 2, 'IDCONTRATO', 'T', null, 10, 20, null, 'ID DO CONTRATO - PROGRESSRECID', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '09', 3, 'DTDEVOLUCAO', 'D', 'RRRRMMDD', 30, 8, null, 'DATA DA DEVOLUCAO DO VALOR HONRADO', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '10', 1, 'TPREGISTRO', 'T', null, 8, 2, null, 'TIPO DE REGISTRO', '10');

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '10', 2, 'IDCONTRATO', 'T', null, 10, 20, null, 'ID DO CONTRATO - PROGRESSRECID', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '10', 3, 'CDREJEICAO', 'N', null, 209, 3, null, 'CODIGO DE REJEI플O (DOMINIO PRONAMP_RETORNOREG)', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '11', 1, 'TPREGISTRO', 'T', null, 8, 2, null, 'TIPO DE REGISTRO', '11');

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '11', 2, 'IDCONTRATO', 'T', null, 10, 20, null, 'ID DO CONTRATO - PROGRESSRECID', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '11', 3, 'CDREJEICAO', 'N', null, 209, 3, null, 'CODIGO DE REJEI플O (DOMINIO PRONAMP_RETORNOREG)', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '12', 1, 'TPREGISTRO', 'T', null, 8, 2, null, 'TIPO DE REGISTRO', '12');

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '12', 2, 'IDCONTRATO', 'T', null, 10, 20, null, 'ID DO CONTRATO - PROGRESSRECID', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '12', 3, 'CDREJEICAO', 'N', null, 209, 3, null, 'CODIGO DE REJEI플O (DOMINIO PRONAMP_RETORNOREG)', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '13', 1, 'TPREGISTRO', 'T', null, 8, 2, null, 'TIPO DE REGISTRO', '13');

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '13', 2, 'IDCONTRATO', 'T', null, 10, 20, null, 'ID DO CONTRATO - PROGRESSRECID', null);

	insert into tbgen_layout_campo ( IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
	values ( vr_idcampo, '13', 3, 'CDREJEICAO', 'N', null, 209, 3, null, 'CODIGO DE REJEI플O (DOMINIO PRONAMP_RETORNOREG)', null);

  
  COMMIT;  
END;
