DECLARE
  vr_idcampo tbgen_layout.IDLAYOUT%TYPE;
BEGIN

  SELECT MAX(IDLAYOUT)+1 INTO vr_idcampo FROM tbgen_layout;

  -- Insere o novo layout
  insert into tbgen_layout (IDLAYOUT, NMLAYOUT, DSLAYOUT, DSDELIMITADOR, DSOBSERVACAO)
  values (vr_idcampo, 'GFGF290R', 'Pronampe - Eventos do Administrador', null, '3º Retorno');

  -- Insere nome do programa para rastreabilidade
  --  insert into tbgen_layout_programa (IDLAYOUT, CDPROGRA)
  --  values (vr_idcampo, '');

  -- Header
  insert into tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  values (vr_idcampo, 'H', 1, 'NRSEQUENCIAL', 'N', null, 1, 7, null, 'NUMERO SEQUENCIAL REMESSA', '0000001');

  insert into tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  values (vr_idcampo, 'H', 2, 'CDTIPOREG', 'N', null, 8, 2, null, 'TIPO DE REGISTRO', null);

  insert into tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  values (vr_idcampo, 'H', 3, 'NMARQUIVO', 'T', null, 10, 8, null, 'NOME DO ARQUIVO RETORNO', null);

  insert into tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  values (vr_idcampo, 'H', 4, 'NRSEQREMESSA', 'N', null, 32, 4, null, 'SEQUENCIAL DO ARQUIVO DE REMESSA', null);

  insert into tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  values (vr_idcampo, 'H', 5, 'DTPROCESSAMENTO', 'D', 'RRRRMMDD', 36, 8, null, 'DATA PROCESSAMENTO REMESSA', null);


  -- 92 - Detalhe da situacao da operacao
  
  insert into tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  values (vr_idcampo, '92', 1, 'TPREGISTRO', 'N', null, 8, 2, null, 'TIPO DE REGISTRO', '92');

  insert into tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  values (vr_idcampo, '92', 2, 'IDCONTRATO', 'T', null, 10, 20, null, 'CODIGO IDENTIFICADOR DA OPERACAO DE CREDITO', null);
  
  insert into tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  values (vr_idcampo, '92', 3, 'CDPENDENCIA', 'N', null, 30, 2, null, 'TIPO DE PENDENCIA', null);
 
  insert into tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  values (vr_idcampo, '92', 4, 'DTREGISTRO', 'D', 'RRRRMMDD', 32, 8, null, 'DATA DO REGISTRO', null);

  insert into tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  values (vr_idcampo, '92', 5, 'DTVENCIMENTO', 'D', 'RRRRMMDD', 40, 8, null, 'DATA DE VENCIMENTO DA OPERACAO', null);

  insert into tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  values (vr_idcampo, '92', 6, 'CDSITUACAO', 'N', null, 48, 2, null, 'SITUACAO DA OPERACAO', null);

  insert into tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  values (vr_idcampo, '92', 7, 'DTINIPENDENCIA', 'D', 'RRRRMMDD', 50, 8, null, 'DATA DE INICIO DA PENDENCIA', null);


  -- 93 - Motivo da operacao encerrada
  
  insert into tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  values (vr_idcampo, '93', 1, 'TPREGISTRO', 'N', null, 8, 2, null, 'TIPO DE REGISTRO', '93');

  insert into tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  values (vr_idcampo, '93', 2, 'IDCONTRATO', 'T', null, 10, 20, null, 'CODIGO IDENTIFICADOR DA OPERACAO DE CREDITO', null);
  
  insert into tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  values (vr_idcampo, '93', 3, 'CDENCERRAMENTO', 'N', null, 30, 2, null, 'MOTIVO DE ENCERRAMENTO', null);
 
  insert into tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  values (vr_idcampo, '93', 4, 'DTENCERRAMENTO', 'D', 'RRRRMMDD', 32, 8, null, 'DATA DE ENCERRAMENTO', null);


  -- 94 - Motivo da operacao impugnada

  insert into tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  values (vr_idcampo, '94', 1, 'TPREGISTRO', 'N', null, 8, 2, null, 'TIPO DE REGISTRO', '94');

  insert into tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  values (vr_idcampo, '94', 2, 'IDCONTRATO', 'T', null, 10, 20, null, 'CODIGO IDENTIFICADOR DA OPERACAO DE CREDITO', null);
  
  insert into tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  values (vr_idcampo, '94', 3, 'CDIMPUGNACAO', 'N', null, 30, 2, null, 'MOTIVO DE IMPUGNACAO', null);
 
  insert into tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  values (vr_idcampo, '94', 4, 'DTIMPUGNACAO', 'D', 'RRRRMMDD', 32, 8, null, 'DATA DE IMPUGNACAO', null);


  -- Trailer

  insert into tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  values (vr_idcampo, 'T', 1, 'CDTIPOREG', 'N', nuLL, 8, 2, null, 'TIPO DE REGISTRO', 99);
  
  commit;  
END;
