DECLARE
  vr_idcampo tbgen_layout.IDLAYOUT%TYPE;
BEGIN

  DELETE FROM tbgen_layout_programa c 
    WHERE EXISTS (SELECT 1 FROM tbgen_layout l WHERE l.idlayout = c.idlayout AND l.nmlayout = 'GFGF270R');
  DELETE FROM tbgen_layout_campo c 
    WHERE EXISTS (SELECT 1 FROM tbgen_layout l WHERE l.idlayout = c.idlayout AND l.nmlayout = 'GFGF270R');
  DELETE FROM tbgen_layout l WHERE l.nmlayout = 'GFGF270R';

  SELECT MAX(IDLAYOUT)+1 INTO vr_idcampo FROM tbgen_layout;

  -- Insere o novo layout
  INSERT INTO tbgen_layout (IDLAYOUT, NMLAYOUT, DSLAYOUT, DSDELIMITADOR, DSOBSERVACAO)
  VALUES (vr_idcampo, 'GFGF270R', 'Pronampe - Informativo Diario', null, 'Info. Diario');

  -- Insere nome do programa para rastreabilidade
    INSERT INTO tbgen_layout_programa (IDLAYOUT, CDPROGRA)
    VALUES (vr_idcampo, 'incluirPronampeGFGF270R');

  -- Header
  INSERT INTO tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, 'H', 1, 'NRSEQUENCIAL', 'N', null, 1, 7, null, 'NUMERO SEQUENCIAL REMESSA', '0000001');

  INSERT INTO tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, 'H', 2, 'CDTIPOREG', 'N', null, 8, 2, null, 'TIPO DE REGISTRO', null);

  INSERT INTO tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, 'H', 3, 'NMARQUIVO', 'T', null, 10, 8, null, 'NOME DO ARQUIVO RETORNO', null);

  -- 98 - DETALHE (SALDO HONRADO A RECUPERAR)
  
  INSERT INTO tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '98', 1, 'TPREGISTRO', 'N', null, 8, 2, null, 'TIPO DE REGISTRO', '98');

  INSERT INTO tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '98', 2, 'IDCONTRATO', 'T', null, 10, 20, null, 'CODIGO IDENTIFICADOR DA OPERACAO DE CREDITO', null);

  INSERT INTO tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '98', 3, 'DTVALIDSALDO', 'D', 'RRRRMMDD', 30, 8, null, 'DATA DE VALIDADE DO SALDO PARA COBRANCA', null);

  INSERT INTO tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '98', 4, 'VLSALDOHONRA', 'N', null, 38, 17, null, 'VALOR DO SALDO HONRADO A RECUPERAR', null);


  INSERT INTO tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '91', 1, 'TPREGISTRO', 'N', null, 8, 2, null, 'TIPO DE REGISTRO', '91');


  INSERT INTO tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, '96', 1, 'TPREGISTRO', 'N', null, 8, 2, null, 'TIPO DE REGISTRO', '96');
  
  -- Trailer

  INSERT INTO tbgen_layout_campo (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, QTDDECIMAIS, DSOBSERVACAO, DSIDENTIFICADOR_REGISTRO)
  VALUES (vr_idcampo, 'T', 1, 'CDTIPOREG', 'N', nuLL, 8, 2, null, 'TIPO DE REGISTRO', 99);
  
  COMMIT;  
END;
