insert into menumobile (MENUMOBILEID, MENUPAIID, NOME, SEQUENCIA, HABILITADO, AUTORIZACAO, VERSAOMINIMAAPP, VERSAOMAXIMAAPP)
values (1023, 1009, 'Chaves Favoritas', 1, 1, 1, '2.31.0', null);
COMMIT;
