DECLARE
								 
BEGIN
 UPDATE TBGEN_FIPE_MARCA 
	SET DSMARCAFIPE = 'Citroen' 
  WHERE INMARCAFIPE = 13
    AND TPVEICULOFIPE = 1;
COMMIT;				              
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE_application_error(-20500, SQLERRM);
END;	   