BEGIN

  BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE CREDITO.gerarArquivoHomeEquity';
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    RAISE_application_error(-20500, SQLERRM);
  
END;
