BEGIN
  UPDATE CONTACORRENTE.TBPIX_ALTERACAO_COOPERADO A SET
    A.FLJOB_EXECUTADO = 0,
    A.DHEXECUCAO_JOB = NULL
  WHERE A.DTREGISTRO >= TO_DATE('17/03/2022 15:00', 'DD/MM/YYYY HH24:MI');
  
  COMMIT;
END;