BEGIN

	UPDATE TBTAA_REQUISICAO_SEP A
	SET A.INSITUACAO_TRANSACAO = 'P'
	WHERE TRUNC(A.DTTRANSACAO) = '31/03/2022'
	AND A.INTRANSACAO_REQUISICAO = 'DEPOSITO'
	AND A.INSITUACAO_TRANSACAO = 'F'
	AND NOT EXISTS (SELECT 1
			FROM TBTAA_DEPOSITO_SEP X
			WHERE X.CDNSUSEP = A.DSNSU);
	
	commit;
END;