BEGIN
  insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
  values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', null, ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 1, 0.00032);

  insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
  values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 2, 0.00032);

  insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
  values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 3, 0.00032);

  insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
  values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 4, 0.00032);

  insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
  values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 5, 0.00032);

  insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
  values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 6, 0.00032);

  insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
  values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 7, 0.00032);

  insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
  values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 8, 0.00032);

  insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
  values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 9, 0.00032);

  insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
  values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 10, 0.00032);

  insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
  values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 11, 0.00032);

  insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
  values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 12, 0.00032);

  insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
  values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 13, 0.00032);

  insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
  values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 14, 0.00032);

  insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
  values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 15, 0.00032);

  insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
  values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 16, 0.00032);

  insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
  values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 17, 0.00032);

	COMMIT;
END;
