BEGIN
	insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, PROGRESS_RECID, QTMINMED)
	values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', null, ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 1, 23866, 0.00032);

	insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, PROGRESS_RECID, QTMINMED)
	values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 2, 23867, 0.00032);

	insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, PROGRESS_RECID, QTMINMED)
	values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 3, 23868, 0.00032);

	insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, PROGRESS_RECID, QTMINMED)
	values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 4, 23869, 0.00032);

	insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, PROGRESS_RECID, QTMINMED)
	values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 5, 23870, 0.00032);

	insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, PROGRESS_RECID, QTMINMED)
	values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 6, 23871, 0.00032);

	insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, PROGRESS_RECID, QTMINMED)
	values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 7, 23872, 0.00032);

	insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, PROGRESS_RECID, QTMINMED)
	values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 8, 23873, 0.00032);

	insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, PROGRESS_RECID, QTMINMED)
	values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 9, 23874, 0.00032);

	insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, PROGRESS_RECID, QTMINMED)
	values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 10, 23875, 0.00032);

	insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, PROGRESS_RECID, QTMINMED)
	values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 11, 23876, 0.00032);

	insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, PROGRESS_RECID, QTMINMED)
	values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 12, 23877, 0.00032);

	insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, PROGRESS_RECID, QTMINMED)
	values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 13, 23878, 0.00032);

	insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, PROGRESS_RECID, QTMINMED)
	values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 14, 23879, 0.00032);

	insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, PROGRESS_RECID, QTMINMED)
	values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 15, 23880, 0.00032);

	insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, PROGRESS_RECID, QTMINMED)
	values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 16, 23881, 0.00032);

	insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, PROGRESS_RECID, QTMINMED)
	values ('CRED', 'CRPS664_PL', 'ENVIO DO ARQUIVO RETORNO - Débito Automático', ' ', ' ', ' ', 0, 57, 2, 664, 0, 0, 0, 0, 1, 17, 23882, 0.00032);

	COMMIT;
END;