
insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS787', 'Geracao Arq. Atual.Cad.Debito Aut.Bancoob', 'Executado pela JOB', '.', '.', 998, 142, 1, 804, 0, 0, 0, 0, 1, 6);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS787', 'Geracao Arq. Atual.Cad.Debito Aut.Bancoob', 'Executado pela JOB', '.', '.', 998, 142, 1, 804, 0, 0, 0, 0, 1, 17);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS787', 'Geracao Arq. Atual.Cad.Debito Aut.Bancoob', 'Executado pela JOB', '.', '.', 998, 142, 1, 804, 0, 0, 0, 0, 1, 14);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS787', 'Geracao Arq. Atual.Cad.Debito Aut.Bancoob', 'Executado pela JOB', '.', '.', 998, 142, 1, 804, 0, 0, 0, 0, 1, 9);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS787', 'Geracao Arq. Atual.Cad.Debito Aut.Bancoob', 'Executado pela JOB', '.', '.', 998, 142, 1, 804, 0, 0, 0, 0, 1, 11);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS787', 'Geracao Arq. Atual.Cad.Debito Aut.Bancoob', 'Executado pela JOB', '.', '.', 998, 142, 1, 804, 0, 0, 0, 0, 1, 15);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS787', 'Geracao Arq. Atual.Cad.Debito Aut.Bancoob', 'Executado pela JOB', '.', '.', 998, 142, 1, 804, 0, 0, 0, 0, 1, 2);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS787', 'Geracao Arq. Atual.Cad.Debito Aut.Bancoob', 'Executado pela JOB', '.', '.', 998, 142, 1, 804, 0, 0, 0, 0, 1, 4);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS787', 'Geracao Arq. Atual.Cad.Debito Aut.Bancoob', 'Executado pela JOB', '.', '.', 998, 142, 1, 804, 0, 0, 0, 0, 1, 7);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS787', 'Geracao Arq. Atual.Cad.Debito Aut.Bancoob', 'Executado pela JOB', '.', '.', 998, 142, 1, 804, 0, 0, 0, 0, 1, 16);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS787', 'Geracao Arq. Atual.Cad.Debito Aut.Bancoob', 'Executado pela JOB', '.', '.', 998, 142, 1, 804, 0, 0, 0, 0, 1, 12);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS787', 'Geracao Arq. Atual.Cad.Debito Aut.Bancoob', 'Executado pela JOB', '.', '.', 998, 142, 1, 804, 0, 0, 0, 0, 1, 1);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS787', 'Geracao Arq. Atual.Cad.Debito Aut.Bancoob', 'Executado pela JOB', '.', '.', 998, 142, 1, 804, 0, 0, 0, 0, 1, 8);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS787', 'Geracao Arq. Atual.Cad.Debito Aut.Bancoob', 'Executado pela JOB', '.', '.', 998, 142, 1, 804, 0, 0, 0, 0, 1, 10);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS787', 'Geracao Arq. Atual.Cad.Debito Aut.Bancoob', 'Executado pela JOB', '.', '.', 998, 142, 1, 804, 0, 0, 0, 0, 1, 3);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS787', 'Geracao Arq. Atual.Cad.Debito Aut.Bancoob', 'Executado pela JOB', '.', '.', 998, 142, 1, 804, 0, 0, 0, 0, 1, 13);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS787', 'Geracao Arq. Atual.Cad.Debito Aut.Bancoob', 'Executado pela JOB', '.', '.', 998, 142, 1, 804, 0, 0, 0, 0, 1, 5);



insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS788', 'Integracao Arq. Debitos Aut. Bancoob', '.', '.', '.', 998, 143, 1, 803, 0, 0, 0, 0, 1, 6);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS788', 'Integracao Arq. Debitos Aut. Bancoob', '.', '.', '.', 998, 143, 1, 803, 0, 0, 0, 0, 1, 17);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS788', 'Integracao Arq. Debitos Aut. Bancoob', '.', '.', '.', 998, 143, 1, 803, 0, 0, 0, 0, 1, 14);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS788', 'Integracao Arq. Debitos Aut. Bancoob', '.', '.', '.', 998, 143, 1, 803, 0, 0, 0, 0, 1, 9);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS788', 'Integracao Arq. Debitos Aut. Bancoob', '.', '.', '.', 998, 143, 1, 803, 0, 0, 0, 0, 1, 11);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS788', 'Integracao Arq. Debitos Aut. Bancoob', '.', '.', '.', 998, 143, 1, 803, 0, 0, 0, 0, 1, 15);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS788', 'Integracao Arq. Debitos Aut. Bancoob', '.', '.', '.', 998, 143, 1, 803, 0, 0, 0, 0, 1, 2);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS788', 'Integracao Arq. Debitos Aut. Bancoob', '.', '.', '.', 998, 143, 1, 803, 0, 0, 0, 0, 1, 4);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS788', 'Integracao Arq. Debitos Aut. Bancoob', '.', '.', '.', 998, 143, 1, 803, 0, 0, 0, 0, 1, 7);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS788', 'Integracao Arq. Debitos Aut. Bancoob', '.', '.', '.', 998, 143, 1, 803, 0, 0, 0, 0, 1, 16);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS788', 'Integracao Arq. Debitos Aut. Bancoob', '.', '.', '.', 998, 143, 1, 803, 0, 0, 0, 0, 1, 12);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS788', 'Integracao Arq. Debitos Aut. Bancoob', '.', '.', '.', 998, 143, 1, 803, 0, 0, 0, 0, 1, 1);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS788', 'Integracao Arq. Debitos Aut. Bancoob', '.', '.', '.', 998, 143, 1, 803, 0, 0, 0, 0, 1, 8);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS788', 'Integracao Arq. Debitos Aut. Bancoob', '.', '.', '.', 998, 143, 1, 803, 0, 0, 0, 0, 1, 10);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS788', 'Integracao Arq. Debitos Aut. Bancoob', '.', '.', '.', 998, 143, 1, 803, 0, 0, 0, 0, 1, 3);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS788', 'Integracao Arq. Debitos Aut. Bancoob', '.', '.', '.', 998, 143, 1, 803, 0, 0, 0, 0, 1, 13);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS788', 'Integracao Arq. Debitos Aut. Bancoob', '.', '.', '.', 998, 143, 1, 803, 0, 0, 0, 0, 1, 5);




insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS789', 'Gerar Arquivo Debito Automatico Bancoob', 'Executado pela JOB', '.', '.', 998, 144, 1, 805, 0, 0, 0, 0, 1, 6);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS789', 'Gerar Arquivo Debito Automatico Bancoob', 'Executado pela JOB', '.', '.', 998, 144, 1, 805, 0, 0, 0, 0, 1, 17);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS789', 'Gerar Arquivo Debito Automatico Bancoob', 'Executado pela JOB', '.', '.', 998, 144, 1, 805, 0, 0, 0, 0, 1, 14);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS789', 'Gerar Arquivo Debito Automatico Bancoob', 'Executado pela JOB', '.', '.', 998, 144, 1, 805, 0, 0, 0, 0, 1, 9);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS789', 'Gerar Arquivo Debito Automatico Bancoob', 'Executado pela JOB', '.', '.', 998, 144, 1, 805, 0, 0, 0, 0, 1, 11);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS789', 'Gerar Arquivo Debito Automatico Bancoob', 'Executado pela JOB', '.', '.', 998, 144, 1, 805, 0, 0, 0, 0, 1, 15);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS789', 'Gerar Arquivo Debito Automatico Bancoob', 'Executado pela JOB', '.', '.', 998, 144, 1, 805, 0, 0, 0, 0, 1, 2);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS789', 'Gerar Arquivo Debito Automatico Bancoob', 'Executado pela JOB', '.', '.', 998, 144, 1, 805, 0, 0, 0, 0, 1, 4);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS789', 'Gerar Arquivo Debito Automatico Bancoob', 'Executado pela JOB', '.', '.', 998, 144, 1, 805, 0, 0, 0, 0, 1, 7);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS789', 'Gerar Arquivo Debito Automatico Bancoob', 'Executado pela JOB', '.', '.', 998, 144, 1, 805, 0, 0, 0, 0, 1, 16);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS789', 'Gerar Arquivo Debito Automatico Bancoob', 'Executado pela JOB', '.', '.', 998, 144, 1, 805, 0, 0, 0, 0, 1, 12);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS789', 'Gerar Arquivo Debito Automatico Bancoob', 'Executado pela JOB', '.', '.', 998, 144, 1, 805, 0, 0, 0, 0, 1, 1);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS789', 'Gerar Arquivo Debito Automatico Bancoob', 'Executado pela JOB', '.', '.', 998, 144, 1, 805, 0, 0, 0, 0, 1, 8);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS789', 'Gerar Arquivo Debito Automatico Bancoob', 'Executado pela JOB', '.', '.', 998, 144, 1, 805, 0, 0, 0, 0, 1, 10);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS789', 'Gerar Arquivo Debito Automatico Bancoob', 'Executado pela JOB', '.', '.', 998, 144, 1, 805, 0, 0, 0, 0, 1, 3);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS789', 'Gerar Arquivo Debito Automatico Bancoob', 'Executado pela JOB', '.', '.', 998, 144, 1, 805, 0, 0, 0, 0, 1, 13);

insert into crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
values ('CRED', 'CRPS789', 'Gerar Arquivo Debito Automatico Bancoob', 'Executado pela JOB', '.', '.', 998, 144, 1, 805, 0, 0, 0, 0, 1, 5);







insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (803, 1, 1, 'INTEGR.ARQ.DEBITOS AUTOMATICO', 5, 'Debito Automatico', '80COL', 0, 1, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (803, 1, 1, 'INTEGR.ARQ.DEBITOS AUTOMATICO', 5, 'FINANCEIRO', '80COL', 0, 2, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (803, 1, 1, 'INTEGR.ARQ.DEBITOS AUTOMATICO', 5, 'CONTABILIDADE', '80COL', 0, 3, 'D', 1, 1, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (803, 1, 1, 'INTEGR.ARQ.DEBITOS AUTOMATICO', 5, 'CONTABILIDADE', '80COL', 0, 4, 'D', 1, 1, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (803, 1, 1, 'INTEGR.ARQ.DEBITOS AUTOMATICO', 5, 'CONTABILIDADE', '80COL', 0, 5, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (803, 1, 1, 'INTEGR.ARQ.DEBITOS AUTOMATICO', 5, 'CONTABILIDADE', '80COL', 0, 6, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (803, 1, 1, 'INTEGR.ARQ.DEBITOS AUTOMATICO', 5, 'CONTABILIDADE', '80COL', 0, 7, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (803, 1, 1, 'INTEGR.ARQ.DEBITOS AUTOMATICO', 5, 'Finac./Gean', '80COL', 0, 8, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (803, 1, 1, 'INTEGR.ARQ.DEBITOS AUTOMATICO', 5, 'Maycon', '80COL', 0, 9, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (803, 1, 1, 'INTEGR.ARQ.DEBITOS AUTOMATICO', 5, 'CRISTINA', '80COL', 0, 10, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (803, 1, 1, 'INTEGR.ARQ.DEBITOS AUTOMATICO', 5, 'Finac./Marieli', '80COL', 0, 11, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (803, 1, 1, 'INTEGR.ARQ.DEBITOS AUTOMATICO', 5, 'Bianca', '80COL', 0, 12, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (803, 1, 1, 'INTEGR.ARQ.DEBITOS AUTOMATICO', 5, 'Finac./Marieli', '80COL', 0, 13, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (803, 1, 1, 'INTEGR.ARQ.DEBITOS AUTOMATICO', 5, 'debora', '80COL', 0, 14, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (803, 1, 1, 'INTEGR.ARQ.DEBITOS AUTOMATICO', 5, 'debora', '80COL', 0, 15, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (803, 1, 1, 'INTEGR.ARQ.DEBITOS AUTOMATICO', 5, 'debora', '80COL', 0, 16, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (803, 1, 1, 'INTEGR.ARQ.DEBITOS AUTOMATICO', 5, 'debora', '80COL', 0, 17, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (804, 1, 1, 'RESUMO ATUAL.ARQ.DEBITOS(GENERICO)', 5, 'Administrativo', 'padrao', 0, 1, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (804, 1, 1, 'RESUMO ATUAL.ARQ.DEBITOS(GENERICO)', 5, ' ', 'padrao', 0, 2, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (804, 1, 1, 'RESUMO ATUAL.ARQ.DEBITOS(GENERICO)', 5, 'CONTABILIDADE', 'padrao', 0, 3, 'D', 1, 1, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (804, 1, 1, 'RESUMO ATUAL.ARQ.DEBITOS(GENERICO)', 5, 'CONTABILIDADE', 'padrao', 0, 4, 'D', 1, 1, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (804, 1, 1, 'RESUMO ATUAL.ARQ.DEBITOS(GENERICO)', 5, 'CONTABILIDADE', 'padrao', 0, 5, 'D', 1, 1, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (804, 1, 1, 'RESUMO ATUAL.ARQ.DEBITOS(GENERICO)', 5, 'CONTABILIDADE', 'padrao', 0, 6, 'D', 1, 1, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (804, 1, 1, 'RESUMO ATUAL.ARQ.DEBITOS(GENERICO)', 5, 'CONTABILIDADE', 'padrao', 0, 7, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (804, 1, 1, 'RESUMO ATUAL.ARQ.DEBITOS(GENERICO)', 5, 'Administrativo', 'padrao', 0, 8, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (804, 1, 1, 'RESUMO ATUAL.ARQ.DEBITOS(GENERICO)', 5, 'Administrativo', 'padrao', 0, 9, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (804, 1, 1, 'RESUMO ATUAL.ARQ.DEBITOS(GENERICO)', 5, 'Administrativo', 'padrao', 0, 10, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (804, 1, 1, 'RESUMO ATUAL.ARQ.DEBITOS(GENERICO)', 5, 'Administrativo', 'padrao', 0, 11, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (804, 1, 1, 'RESUMO ATUAL.ARQ.DEBITOS(GENERICO)', 5, 'Administrativo', 'padrao', 0, 12, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (804, 1, 1, 'RESUMO ATUAL.ARQ.DEBITOS(GENERICO)', 5, 'Administrativo', 'padrao', 0, 13, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (804, 1, 1, 'RESUMO ATUAL.ARQ.DEBITOS(GENERICO)', 5, 'Administrativo', 'padrao', 0, 14, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (804, 1, 1, 'RESUMO ATUAL.ARQ.DEBITOS(GENERICO)', 5, 'Administrativo', 'padrao', 0, 15, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (804, 1, 1, 'RESUMO ATUAL.ARQ.DEBITOS(GENERICO)', 5, 'Administrativo', 'padrao', 0, 16, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (804, 1, 1, 'RESUMO ATUAL.ARQ.DEBITOS(GENERICO)', 5, 'Administrativo', 'padrao', 0, 17, 'D', 1, 2, 1, ' ', null, null);


insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (805, 1, 1, 'RESUMO DEBITO CONTA CONV.AUTOM.', 5, 'Debito Automatico', '80col', 0, 12, 'D', 1, 2, 1, ' ',  null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (805, 1, 1, 'RESUMO DEBITO CONTA CONV.AUTOM.', 5, 'CONTABILIDADE', '80col', 0, 3, 'D', 1, 1, 1, ' ',  null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (805, 1, 1, 'RESUMO DEBITO CONTA CONV.AUTOM.', 5, 'Debito Automatico', '80col', 0, 15, 'D', 1, 2, 1, ' ',  null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (805, 1, 1, 'RESUMO DEBITO CONTA CONV.AUTOM.', 5, 'CONTABILIDADE', '80col', 0, 7, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (805, 1, 1, 'RESUMO DEBITO CONTA CONV.AUTOM.', 5, 'Debito Automatico', '80col', 0, 13, 'D', 1, 2, 1, ' ',  null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (805, 1, 1, 'RESUMO DEBITO CONTA CONV.AUTOM.', 5, 'Finc./Evandro', '80col', 0, 8, 'D', 1, 2, 1, ' ',  null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (805, 1, 1, 'RESUMO DEBITO CONTA CONV.AUTOM.', 5, 'Debito Automatico', '80col', 0, 17, 'D', 1, 2, 1, ' ',  null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (805, 1, 1, 'RESUMO DEBITO CONTA CONV.AUTOM.', 5, 'Debito Automatico', '80col', 0, 16, 'D', 1, 2, 1, ' ',  null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (805, 1, 1, 'RESUMO DEBITO CONTA CONV.AUTOM.', 5, 'Debito Automatico', '80col', 0, 14, 'D', 1, 2, 1, ' ',  null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (805, 1, 1, 'RESUMO DEBITO CONTA CONV.AUTOM.', 5, 'CONTABILIDADE', '80col', 0, 2, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (805, 1, 1, 'RESUMO DEBITO CONTA CONV.AUTOM.', 5, 'CONTABILIDADE', '80col', 0, 5, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (805, 1, 1, 'RESUMO DEBITO CONTA CONV.AUTOM.', 5, 'Debito Automatico', '80col', 0, 1, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (805, 1, 1, 'RESUMO DEBITO CONTA CONV.AUTOM.', 5, 'CONTABILIDADE', '80col', 0, 4, 'D', 1, 1, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (805, 1, 1, 'RESUMO DEBITO CONTA CONV.AUTOM.', 5, 'Finc./Evandro', '80col', 0, 9, 'D', 1, 2, 1, ' ', null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (805, 1, 1, 'RESUMO DEBITO CONTA CONV.AUTOM.', 5, 'Debito Automatico', '80col', 0, 10, 'D', 1, 2, 1, ' ',  null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (805, 1, 1, 'RESUMO DEBITO CONTA CONV.AUTOM.', 5, 'Debito Automatico', '80col', 0, 11, 'D', 1, 2, 1, ' ',  null, null);

insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL,  CDFILREL, NRSEQPRI)
values (805, 1, 1, 'RESUMO DEBITO CONTA CONV.AUTOM.', 5, 'CONTABILIDADE', '80col', 0, 6, 'D', 1, 2, 1, ' ', null, null);




insert into crapprm (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM, PROGRESS_RECID)
values ('CRED', 0, 'CRPS788_EMAIL', 'Email para as criticas no programa CRPS788', 'convenios@ailos.coop.br', 21);



insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (1, '787', 'CAD.DEB.AUT. BANCOOB', 66000, 69300, 0, null, '1', 1, 34);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (2, '787', 'CAD.DEB.AUT. BANCOOB', 66000, 69300, 0, null, '1', 1, 34);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (4, '787', 'CAD.DEB.AUT. BANCOOB', 66000, 68400, 0, null, '1', 1, 34);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (5, '787', 'CAD.DEB.AUT. BANCOOB', 66000, 69300, 0, null, '1', 1, 34);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (6, '787', 'CAD.DEB.AUT. BANCOOB', 66000, 69300, 0, null, '1', 1, 34);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (7, '787', 'CAD.DEB.AUT. BANCOOB', 66000, 69300, 0, null, '1', 1, 34);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (8, '787', 'CAD.DEB.AUT. BANCOOB', 66000, 69300, 0, null, '1', 1, 34);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (9, '787', 'CAD.DEB.AUT. BANCOOB', 66000, 69300, 0, null, '1', 1, 34);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (10, '787', 'CAD.DEB.AUT. BANCOOB', 66000, 69300, 0, null, '1', 1, 34);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (11, '787', 'CAD.DEB.AUT. BANCOOB', 66000, 69300, 0, null, '1', 1, 34);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (12, '787', 'CAD.DEB.AUT. BANCOOB', 66000, 69300, 0, null, '1', 1, 34);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (13, '787', 'CAD.DEB.AUT. BANCOOB', 66000, 69300, 0, null, '1', 1, 34);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (14, '787', 'CAD.DEB.AUT. BANCOOB', 66000, 69300, 0, null, '1', 1, 34);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (15, '787', 'CAD.DEB.AUT. BANCOOB', 66000, 69300, 0, null, '1', 1, 34);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (16, '787', 'CAD.DEB.AUT. BANCOOB', 66000, 69300, 0, null, '1', 1, 34);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (17, '787', 'CAD.DEB.AUT. BANCOOB', 66000, 69300, 0, null, '1', 1, 34);



insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (1, '788', 'IMP.DEB.AUT. BANCOOB', 77400, 80100, 0, null, '1', 1, 35);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (2, '788', 'IMP.DEB.AUT. BANCOOB', 77400, 80100, 0, null, '1', 1, 35);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (4, '788', 'IMP.DEB.AUT. BANCOOB', 77400, 80100, 0, null, '1', 1, 35);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (5, '788', 'IMP.DEB.AUT. BANCOOB', 77400, 80100, 0, null, '1', 1, 35);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (6, '788', 'IMP.DEB.AUT. BANCOOB', 77400, 80100, 0, null, '1', 1, 35);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (7, '788', 'IMP.DEB.AUT. BANCOOB', 77400, 80100, 0, null, '1', 1, 35);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (8, '788', 'IMP.DEB.AUT. BANCOOB', 77400, 80100, 0, null, '1', 1, 35);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (9, '788', 'IMP.DEB.AUT. BANCOOB', 77400, 80100, 0, null, '1', 1, 35);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (10, '788', 'IMP.DEB.AUT. BANCOOB', 77400, 80100, 0, null, '1', 1, 35);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (11, '788', 'IMP.DEB.AUT. BANCOOB', 77400, 80100, 0, null, '1', 1, 35);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (12, '788', 'IMP.DEB.AUT. BANCOOB', 77400, 80100, 0, null, '1', 1, 35);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (13, '788', 'IMP.DEB.AUT. BANCOOB', 77400, 80100, 0, null, '1', 1, 35);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (14, '788', 'IMP.DEB.AUT. BANCOOB', 77400, 80100, 0, null, '1', 1, 35);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (15, '788', 'IMP.DEB.AUT. BANCOOB', 77400, 80100, 0, null, '1', 1, 35);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (16, '788', 'IMP.DEB.AUT. BANCOOB', 77400, 80100, 0, null, '1', 1, 35);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (17, '788', 'IMP.DEB.AUT. BANCOOB', 77400, 80100, 0, null, '1', 1, 35);




insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (1, '789', 'RET.DEB.AUT. BANCOOB', 68400, 70200, 0, null, '1', 1, 36);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (2, '789', 'RET.DEB.AUT. BANCOOB', 68400, 70200, 0, null, '1', 1, 36);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (4, '789', 'RET.DEB.AUT. BANCOOB', 68400, 70200, 0, null, '1', 1, 36);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (5, '789', 'RET.DEB.AUT. BANCOOB', 68400, 70200, 0, null, '1', 1, 36);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (6, '789', 'RET.DEB.AUT. BANCOOB', 68400, 70200, 0, null, '1', 1, 36);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (7, '789', 'RET.DEB.AUT. BANCOOB', 68400, 70200, 0, null, '1', 1, 36);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (8, '789', 'RET.DEB.AUT. BANCOOB', 68400, 70200, 0, null, '1', 1, 36);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (9, '789', 'RET.DEB.AUT. BANCOOB', 68400, 70200, 0, null, '1', 1, 36);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (10, '789', 'RET.DEB.AUT. BANCOOB', 68400, 70200, 0, null, '1', 1, 36);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (11, '789', 'RET.DEB.AUT. BANCOOB', 68400, 70200, 0, null, '1', 1, 36);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (12, '789', 'RET.DEB.AUT. BANCOOB', 68400, 70200, 0, null, '1', 1, 36);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (13, '789', 'RET.DEB.AUT. BANCOOB', 68400, 70200, 0, null, '1', 1, 36);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (14, '789', 'RET.DEB.AUT. BANCOOB', 68400, 70200, 0, null, '1', 1, 36);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (15, '789', 'RET.DEB.AUT. BANCOOB', 68400, 70200, 0, null, '1', 1, 36);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (16, '789', 'RET.DEB.AUT. BANCOOB', 68400, 70200, 0, null, '1', 1, 36);

insert into craPhec (CDCOOPER, CDPROGRA, DSPROGRA, HRINIEXE, HRFIMEXE, HRULTEXC, DTULTEXC, CDOPERAD, FLGATIVO, NRSEQEXE)
values (17, '789', 'RET.DEB.AUT. BANCOOB', 68400, 70200, 0, null, '1', 1, 36);



commit;
