begin  
  --#######################################################################################################################################
  begin
    declare 
    -- nome da rotina
    wk_rotina varchar2(200) := 'Script de BACA ';
    begin
		
		--criação dos registros de modalidade para o cartão AILOS NOW
		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW', 1, 'BRASILIA', 'SIG, Quadra 6, Lote 2.080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 201100001, 7, 0, 2011, 7, 'BANCOOB', 'AILOS NOW', 'cartoes@ailos.coop.br,,,,', 1, 0, 0, null, 1, 111111, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW', 1, 'BRASILIA', 'SIG, Quadra 6, Lote 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 326500001, 0, 0, 3265, 4, 'BANCOOB', 'AILOS NOW', 'cartoes@ailos.coop.br,,,,', 2, 0, 0, null, 1, 111111, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 331800001, 9, 0, 3318, 9, 'BANCOOB', 'AILOS NOW', 'cartoes@ailos.coop.br,,,,', 5, 0, 0, null, 1, 111111, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 323200001, 0, 0, 3232, 8, 'BANCOOB', 'AILOS NOW', 'cartoes@ailos.coop.br,,,,', 6, 3, 0, null, 1, 111111, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 441600001, 4, 0, 4416, 4, 'BANCOOB', 'AILOS NOW', 'cartoes@ailos.coop.br,,,,', 7, 0, 0, null, 1, 111111, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 443500001, 6, 0, 4435, 0, 'BANCOOB', 'AILOS NOW', 'cartoes@ailos.coop.br,,,,', 8, 0, 0, null, 1, 111111, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 444400001, 5, 0, 4444, 0, 'BANCOOB', 'AILOS NOW', 'cartoes@ailos.coop.br,,,,', 9, 0, 0, null, 1, 111111, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 444300001, 1, 0, 4443, 1, 'BANCOOB', 'AILOS NOW', 'cartoes@ailos.coop.br,,,,', 10, 0, 0, null, 1, 111111, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 443800001, 7, 0, 4438, 5, 'BANCOOB', 'AILOS NOW', 'cartoes@ailos.coop.br,,,,', 11, 0, 0, null, 1, 111111, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 444900001, 3, 0, 4449, 0, 'BANCOOB', 'AILOS NOW', 'cartoes@ailos.coop.br,,,,', 12, 0, 0, null, 1, 111111, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 445700001, 9, 0, 4457, 1, 'BANCOOB', 'AILOS NOW', 'cartoes@ailos.coop.br,,,,', 13, 0, 0, null, 1, 111111, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 446800001, 5, 0, 4468, 7, 'BANCOOB', 'AILOS NOW', 'cartoes@ailos.coop.br,,,,', 14, 0, 0, null, 1, 111111, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 442000001, 5, 0, 4420, 2, 'BANCOOB', 'AILOS NOW', 'cartoes@ailos.coop.br,,,,', 16, 0, 0, null, 1, 111111, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 457100001, 4, 0, 4571, 3, 'BANCOOB', 'AILOS NOW', 'cartoes@ailos.coop.br,,,,', 17, 0, 0, null, 1, 111111, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);
		
				   
      commit;
	  
      dbms_output.put_line('Sucesso ao executar: ' || wk_rotina);
    exception
      when others then
      dbms_output.put_line('Erro ao executar: ' || wk_rotina ||' --- detalhes do erro: '|| SQLCODE || ': ' || SQLERRM);
      ROLLBACK;
    end;
  end;
end;