begin  
  --#######################################################################################################################################
  begin
    declare 
    -- nome da rotina
    wk_rotina varchar2(200) := 'Script de BACA ';
    begin
		
		--criação dos registros de modalidade para o cartão AILOS MASTERCARD NOW EXPRESSO
		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW EXPRESSO', 1, 'BRASILIA', 'SIG, Quadra 6, Lote 2.080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 201100001, 7, 0, 2011, 7, 'BANCOOB', 'AILOS NOW EXPRESSO', 'cartoes@ailos.coop.br', 1, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW EXPRESSO', 1, 'BRASILIA', 'SIG, Quadra 6, Lote 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 326500001, 0, 0, 3265, 4, 'BANCOOB', 'AILOS NOW EXPRESSO', 'cartoes@ailos.coop.br', 2, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW EXPRESSO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 331800001, 9, 0, 3318, 9, 'BANCOOB', 'AILOS NOW EXPRESSO', 'cartoes@ailos.coop.br', 5, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW EXPRESSO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 323200001, 0, 0, 3232, 8, 'BANCOOB', 'AILOS NOW EXPRESSO', 'cartoes@ailos.coop.br', 6, 3, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW EXPRESSO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 441600001, 4, 0, 4416, 4, 'BANCOOB', 'AILOS NOW EXPRESSO', 'cartoes@ailos.coop.br', 7, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW EXPRESSO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 443500001, 6, 0, 4435, 0, 'BANCOOB', 'AILOS NOW EXPRESSO', 'cartoes@ailos.coop.br', 8, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW EXPRESSO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 444400001, 5, 0, 4444, 0, 'BANCOOB', 'AILOS NOW EXPRESSO', 'cartoes@ailos.coop.br', 9, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW EXPRESSO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 444300001, 1, 0, 4443, 1, 'BANCOOB', 'AILOS NOW EXPRESSO', 'cartoes@ailos.coop.br', 10, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW EXPRESSO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 443800001, 7, 0, 4438, 5, 'BANCOOB', 'AILOS NOW EXPRESSO', 'cartoes@ailos.coop.br', 11, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW EXPRESSO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 444900001, 3, 0, 4449, 0, 'BANCOOB', 'AILOS NOW EXPRESSO', 'cartoes@ailos.coop.br', 12, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW EXPRESSO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 445700001, 9, 0, 4457, 1, 'BANCOOB', 'AILOS NOW EXPRESSO', 'cartoes@ailos.coop.br', 13, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW EXPRESSO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 446800001, 5, 0, 4468, 7, 'BANCOOB', 'AILOS NOW EXPRESSO', 'cartoes@ailos.coop.br', 14, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW EXPRESSO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 442000001, 5, 0, 4420, 2, 'BANCOOB', 'AILOS NOW EXPRESSO', 'cartoes@ailos.coop.br', 16, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (18, 'AILOS MASTERCARD NOW EXPRESSO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 457100001, 4, 0, 4571, 3, 'BANCOOB', 'AILOS NOW EXPRESSO', 'cartoes@ailos.coop.br', 17, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);
		
		--grupo de afinidade AILOS MASTERCARD NOW EXPRESSO
		
		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9803239, 1, 0, 18, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9803265, 2, 0, 18, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9803318, 5, 0, 18, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9803232, 6, 0, 18, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9804416, 7, 0, 18, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9804435, 8, 0, 18, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9804444, 9, 0, 18, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9804443, 10, 0, 18, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9804438, 11, 0, 18, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9804449, 18, 0, 18, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9804457, 13, 0, 18, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9804468, 14, 0, 18, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9804420, 16, 0, 18, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9804571, 17, 0, 18, null);
		
		--criação dos registros de modalidade para o cartão AILOS NOW PERSONALIZADO
		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (19, 'AILOS MASTERCARD NOW PERSONALIZADO', 1, 'BRASILIA', 'SIG, Quadra 6, Lote 2.080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 201100001, 7, 0, 2011, 7, 'BANCOOB', 'AILOS NOW PERSONALIZADO', 'cartoes@ailos.coop.br', 1, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (19, 'AILOS MASTERCARD NOW PERSONALIZADO', 1, 'BRASILIA', 'SIG, Quadra 6, Lote 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 326500001, 0, 0, 3265, 4, 'BANCOOB', 'AILOS NOW PERSONALIZADO', 'cartoes@ailos.coop.br', 2, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (19, 'AILOS MASTERCARD NOW PERSONALIZADO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 331800001, 9, 0, 3318, 9, 'BANCOOB', 'AILOS NOW PERSONALIZADO', 'cartoes@ailos.coop.br', 5, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (19, 'AILOS MASTERCARD NOW PERSONALIZADO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 323200001, 0, 0, 3232, 8, 'BANCOOB', 'AILOS NOW PERSONALIZADO', 'cartoes@ailos.coop.br', 6, 3, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (19, 'AILOS MASTERCARD NOW PERSONALIZADO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 441600001, 4, 0, 4416, 4, 'BANCOOB', 'AILOS NOW PERSONALIZADO', 'cartoes@ailos.coop.br', 7, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (19, 'AILOS MASTERCARD NOW PERSONALIZADO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 443500001, 6, 0, 4435, 0, 'BANCOOB', 'AILOS NOW PERSONALIZADO', 'cartoes@ailos.coop.br', 8, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (19, 'AILOS MASTERCARD NOW PERSONALIZADO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 444400001, 5, 0, 4444, 0, 'BANCOOB', 'AILOS NOW PERSONALIZADO', 'cartoes@ailos.coop.br', 9, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (19, 'AILOS MASTERCARD NOW PERSONALIZADO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 444300001, 1, 0, 4443, 1, 'BANCOOB', 'AILOS NOW PERSONALIZADO', 'cartoes@ailos.coop.br', 10, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (19, 'AILOS MASTERCARD NOW PERSONALIZADO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 443800001, 7, 0, 4438, 5, 'BANCOOB', 'AILOS NOW PERSONALIZADO', 'cartoes@ailos.coop.br', 11, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (19, 'AILOS MASTERCARD NOW PERSONALIZADO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 444900001, 3, 0, 4449, 0, 'BANCOOB', 'AILOS NOW PERSONALIZADO', 'cartoes@ailos.coop.br', 12, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (19, 'AILOS MASTERCARD NOW PERSONALIZADO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 445700001, 9, 0, 4457, 1, 'BANCOOB', 'AILOS NOW PERSONALIZADO', 'cartoes@ailos.coop.br', 13, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (19, 'AILOS MASTERCARD NOW PERSONALIZADO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 446800001, 5, 0, 4468, 7, 'BANCOOB', 'AILOS NOW PERSONALIZADO', 'cartoes@ailos.coop.br', 14, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (19, 'AILOS MASTERCARD NOW PERSONALIZADO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 442000001, 5, 0, 4420, 2, 'BANCOOB', 'AILOS NOW PERSONALIZADO', 'cartoes@ailos.coop.br', 16, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);

		insert into crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, PROGRESS_RECID, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, flgbnand)
		values (19, 'AILOS MASTERCARD NOW PERSONALIZADO', 1, 'BRASILIA', 'SIG, QUADRA 6, LOTE 2080', 'SIG', 'DF', 70610460, 'ZOILA', 'MASTERCARD', 23, 457100001, 4, 0, 4571, 3, 'BANCOOB', 'AILOS NOW PERSONALIZADO', 'cartoes@ailos.coop.br', 17, 0, 0, null, 1, 516162, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 114.00, 1);
		
		--grupo de afinidade AILOS MASTERCARD NOW PERSONALIZADO
		
		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9813239, 1, 0, 19, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9813265, 2, 0, 19, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9813318, 5, 0, 19, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9813232, 6, 0, 19, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9814416, 7, 0, 19, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9814435, 8, 0, 19, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9814444, 9, 0, 19, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9814443, 10, 0, 19, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9814438, 11, 0, 19, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9814449, 18, 0, 19, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9814457, 13, 0, 19, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9814468, 14, 0, 19, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9814420, 16, 0, 19, null);

		insert into CRAPACB (CDGRAFIN, CDCOOPER, CDAGENCI, CDADMCRD, PROGRESS_RECID)
		values (9814571, 17, 0, 19, null);
				   
		--criação dos registros de limite para a modalidade 18
		--TPLIMCRD : 0 = concessão
		--TPLIMCRD : 1 = alteração de limite 
		--TPLIMCRD : 2 = pré-aprovado
		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (1, 18, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (1, 18, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (1, 18, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (2, 18, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (2, 18, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (2, 18, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (3, 18, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (3, 18, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (3, 18, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (5, 18, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (5, 18, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (5, 18, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (6, 18, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (6, 18, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (6, 18, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (7, 18, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (7, 18, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (7, 18, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (8, 18, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (8, 18, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (8, 18, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (9, 18, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (9, 18, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (9, 18, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (10, 18, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (10, 18, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (10, 18, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (11, 18, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (11, 18, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (11, 18, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (12, 18, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (12, 18, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (12, 18, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (13, 18, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (13, 18, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (13, 18, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (14, 18, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (14, 18, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (14, 18, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (16, 18, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (16, 18, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (16, 18, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (17, 18, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (17, 18, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (17, 18, 500, 100000, '3,7,11,19,22', 2);

		--criação dos registros de limite para a modalidade 19
		--TPLIMCRD : 0 = concessão
		--TPLIMCRD : 1 = alteração de limite 
		--TPLIMCRD : 2 = pré-aprovado
		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (1, 19, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (1, 19, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (1, 19, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (2, 19, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (2, 19, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (2, 19, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (3, 19, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (3, 19, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (3, 19, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (5, 19, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (5, 19, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (5, 19, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (6, 19, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (6, 19, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (6, 19, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (7, 19, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (7, 19, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (7, 19, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (8, 19, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (8, 19, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (8, 19, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (9, 19, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (9, 19, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (9, 19, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (10, 19, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (10, 19, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (10, 19, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (11, 19, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (11, 19, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (11, 19, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (12, 19, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (12, 19, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (12, 19, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (13, 19, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (13, 19, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (13, 19, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (14, 19, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (14, 19, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (14, 19, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (16, 19, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (16, 19, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (16, 19, 500, 100000, '3,7,11,19,22', 2);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (17, 19, 500, 100000, '3,7,11,19,22', 0);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (17, 19, 0, 100000, '3,7,11,19,22', 1);

		insert into tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
		values (17, 19, 500, 100000, '3,7,11,19,22', 2);

		
      commit;
	  
      dbms_output.put_line('Sucesso ao executar: ' || wk_rotina);
    exception
      when others then
      dbms_output.put_line('Erro ao executar: ' || wk_rotina ||' --- detalhes do erro: '|| SQLCODE || ': ' || SQLERRM);
      ROLLBACK;
    end;
  end;
end;