begin

	DELETE tbcrd_limoper;

	insert into tbcrd_limoper (IDLIMOP, CDCOOPER, VLLIMOUTORG, VLLIMCONSUMD, VLLIMDISP, NRPERCSEG, NRPERCDISPMAJOR, NRPERCDISPPA, NRPERCDISPOPNORM, DSEMAILS, CDOPERAD, DTALTERA, DTCADASTRO)
	values (1284352, 1, 1600000000.00, 1341937479.34, 258062520.66, 4, 0, 0, 96, 'xxxx@ailos.coop.br;caio.kraetzer@ailos.coop.br;gionei.correia@ailos.coop.br;andreia.johse@ailos.coop.br;camila.schluter@ailos.coop.br', 'f0011679', to_date('26-03-2021 19:58:58', 'dd-mm-yyyy hh24:mi:ss'), to_date('17-03-2021 15:17:16', 'dd-mm-yyyy hh24:mi:ss'));

	insert into tbcrd_limoper (IDLIMOP, CDCOOPER, VLLIMOUTORG, VLLIMCONSUMD, VLLIMDISP, NRPERCSEG, NRPERCDISPMAJOR, NRPERCDISPPA, NRPERCDISPOPNORM, DSEMAILS, CDOPERAD, DTALTERA, DTCADASTRO)
	values (1284316, 2, 89500000.00, 51967028.94, 37532971.06, 2, 10, 5, 83, 'xxxx@ailos.coop.br;caio.kraetzer@ailos.coop.br;gionei.correia@ailos.coop.br;andreia.johse@ailos.coop.br;camila.schluter@ailos.coop.br', 'f0020278', to_date('26-03-2021 18:23:58', 'dd-mm-yyyy hh24:mi:ss'), to_date('26-03-2021 13:13:16', 'dd-mm-yyyy hh24:mi:ss'));

	insert into tbcrd_limoper (IDLIMOP, CDCOOPER, VLLIMOUTORG, VLLIMCONSUMD, VLLIMDISP, NRPERCSEG, NRPERCDISPMAJOR, NRPERCDISPPA, NRPERCDISPOPNORM, DSEMAILS, CDOPERAD, DTALTERA, DTCADASTRO)
	values (1284230, 5, 47000000.00, 35657295.64, 11342704.36, 2, 10, 5, 83, 'xxxx@ailos.coop.br;caio.kraetzer@ailos.coop.br;andreia.johse@ailos.coop.br;anderson.felipe@ailos.coop.br;gionei.correia@ailos.coop.br;camila.schluter@ailos.coop.br', 'f0050214', to_date('26-03-2021 16:55:08', 'dd-mm-yyyy hh24:mi:ss'), to_date('17-03-2021 14:57:36', 'dd-mm-yyyy hh24:mi:ss'));

	insert into tbcrd_limoper (IDLIMOP, CDCOOPER, VLLIMOUTORG, VLLIMCONSUMD, VLLIMDISP, NRPERCSEG, NRPERCDISPMAJOR, NRPERCDISPPA, NRPERCDISPOPNORM, DSEMAILS, CDOPERAD, DTALTERA, DTCADASTRO)
	values (1284259, 6, 66000000.00, 41508517.35, 24491482.65, 2, 10, 5, 83, 'xxxx@ailos.coop.br;caio.kraetzer@ailos.coop.br;andreia.johse@ailos.coop.br;camila.schluter@ailos.coop.br', 'f0060128', to_date('26-03-2021 17:09:55', 'dd-mm-yyyy hh24:mi:ss'), to_date('17-03-2021 15:14:57', 'dd-mm-yyyy hh24:mi:ss'));

	insert into tbcrd_limoper (IDLIMOP, CDCOOPER, VLLIMOUTORG, VLLIMCONSUMD, VLLIMDISP, NRPERCSEG, NRPERCDISPMAJOR, NRPERCDISPPA, NRPERCDISPOPNORM, DSEMAILS, CDOPERAD, DTALTERA, DTCADASTRO)
	values (1284290, 7, 140000000.00, 81391646.26, 58608353.74, 2, 10, 5, 83, 'xxxx@ailos.coop.br;caio.kraetzer@ailos.coop.br;andreia.johse@ailos.coop.br;camila.schluter@ailos.coop.br', 'f0070281', to_date('26-03-2021 17:37:18', 'dd-mm-yyyy hh24:mi:ss'), to_date('17-03-2021 15:00:21', 'dd-mm-yyyy hh24:mi:ss'));

	insert into tbcrd_limoper (IDLIMOP, CDCOOPER, VLLIMOUTORG, VLLIMCONSUMD, VLLIMDISP, NRPERCSEG, NRPERCDISPMAJOR, NRPERCDISPPA, NRPERCDISPOPNORM, DSEMAILS, CDOPERAD, DTALTERA, DTCADASTRO)
	values (1284136, 8, 15400000.00, 5604127.78, 9795872.22, 2, 10, 5, 83, 'xxxx@ailos.coop.br;caio.kraetzer@ailos.coop.br;andreia.johse@ailos.coop.br;camila.schluter@ailos.coop.br', 'f0080080', to_date('26-03-2021 16:24:30', 'dd-mm-yyyy hh24:mi:ss'), to_date('17-03-2021 15:02:23', 'dd-mm-yyyy hh24:mi:ss'));

	insert into tbcrd_limoper (IDLIMOP, CDCOOPER, VLLIMOUTORG, VLLIMCONSUMD, VLLIMDISP, NRPERCSEG, NRPERCDISPMAJOR, NRPERCDISPPA, NRPERCDISPOPNORM, DSEMAILS, CDOPERAD, DTALTERA, DTCADASTRO)
	values (1284305, 9, 106700000.00, 65805264.01, 40894735.99, 2, 10, 5, 83, 'xxxx@ailos.coop.br;caio.kraetzer@ailos.coop.br;gionei.correia@ailos.coop.br;andreia.johse@ailos.coop.br;camila.schluter@ailos.coop.br', 'f0090384', to_date('26-03-2021 17:59:59', 'dd-mm-yyyy hh24:mi:ss'), to_date('17-03-2021 15:12:39', 'dd-mm-yyyy hh24:mi:ss'));

	insert into tbcrd_limoper (IDLIMOP, CDCOOPER, VLLIMOUTORG, VLLIMCONSUMD, VLLIMDISP, NRPERCSEG, NRPERCDISPMAJOR, NRPERCDISPPA, NRPERCDISPOPNORM, DSEMAILS, CDOPERAD, DTALTERA, DTCADASTRO)
	values (1284284, 10, 39100000.00, 20838043.19, 18261956.81, 2, 10, 5, 83, 'xxxx@ailos.coop.br;caio.kraetzer@ailos.coop.br;andreia.johse@ailos.coop.br;camila.schluter@ailos.coop.br', 'f0100201', to_date('26-03-2021 17:32:29', 'dd-mm-yyyy hh24:mi:ss'), to_date('17-03-2021 15:03:04', 'dd-mm-yyyy hh24:mi:ss'));

	insert into tbcrd_limoper (IDLIMOP, CDCOOPER, VLLIMOUTORG, VLLIMCONSUMD, VLLIMDISP, NRPERCSEG, NRPERCDISPMAJOR, NRPERCDISPPA, NRPERCDISPOPNORM, DSEMAILS, CDOPERAD, DTALTERA, DTCADASTRO)
	values (1284297, 11, 171200000.00, 88614298.92, 82585701.08, 2, 10, 5, 83, 'xxxx@ailos.coop.br;caio.kraetzer@ailos.coop.br;andreia.johse@ailos.coop.br;camila.schluter@ailos.coop.br', 'f0110331', to_date('26-03-2021 17:46:46', 'dd-mm-yyyy hh24:mi:ss'), to_date('17-03-2021 15:06:10', 'dd-mm-yyyy hh24:mi:ss'));

	insert into tbcrd_limoper (IDLIMOP, CDCOOPER, VLLIMOUTORG, VLLIMCONSUMD, VLLIMDISP, NRPERCSEG, NRPERCDISPMAJOR, NRPERCDISPPA, NRPERCDISPOPNORM, DSEMAILS, CDOPERAD, DTALTERA, DTCADASTRO)
	values (1284256, 12, 30600000.00, 18435486.43, 12164513.57, 2, 10, 5, 83, 'xxxx@ailos.coop.br;caio.kraetzer@ailos.coop.br;andreia.johse@ailos.coop.br;camila.schluter@ailos.coop.br', 'ESTEIRA', to_date('26-03-2021 17:06:38', 'dd-mm-yyyy hh24:mi:ss'), to_date('17-03-2021 15:07:05', 'dd-mm-yyyy hh24:mi:ss'));

	insert into tbcrd_limoper (IDLIMOP, CDCOOPER, VLLIMOUTORG, VLLIMCONSUMD, VLLIMDISP, NRPERCSEG, NRPERCDISPMAJOR, NRPERCDISPPA, NRPERCDISPOPNORM, DSEMAILS, CDOPERAD, DTALTERA, DTCADASTRO)
	values (1284345, 13, 100000000.00, 55436109.05, 44563890.95, 2, 10, 5, 83, 'xxxx@ailos.coop.br;caio.kraetzer@ailos.coop.br;gionei.correia@ailos.coop.br;andreia.johse@ailos.coop.br;camila.schluter@ailos.coop.br', 'f0130380', to_date('26-03-2021 19:32:16', 'dd-mm-yyyy hh24:mi:ss'), to_date('17-03-2021 14:59:26', 'dd-mm-yyyy hh24:mi:ss'));

	insert into tbcrd_limoper (IDLIMOP, CDCOOPER, VLLIMOUTORG, VLLIMCONSUMD, VLLIMDISP, NRPERCSEG, NRPERCDISPMAJOR, NRPERCDISPPA, NRPERCDISPOPNORM, DSEMAILS, CDOPERAD, DTALTERA, DTCADASTRO)
	values (1284254, 14, 72400000.00, 55307166.60, 17092833.40, 2, 10, 5, 83, 'xxxx@ailos.coop.br;caio.kraetzer@ailos.coop.br;andreia.johse@ailos.coop.br;camila.schluter@ailos.coop.br', 'f0140298', to_date('26-03-2021 17:06:14', 'dd-mm-yyyy hh24:mi:ss'), to_date('17-03-2021 15:11:06', 'dd-mm-yyyy hh24:mi:ss'));

	insert into tbcrd_limoper (IDLIMOP, CDCOOPER, VLLIMOUTORG, VLLIMCONSUMD, VLLIMDISP, NRPERCSEG, NRPERCDISPMAJOR, NRPERCDISPPA, NRPERCDISPOPNORM, DSEMAILS, CDOPERAD, DTALTERA, DTCADASTRO)
	values (1284247, 16, 230000000.00, 138257341.67, 91742658.33, 2, 10, 5, 83, 'xxxx@ailos.coop.br;caio.kraetzer@ailos.coop.br;andreia.johse@ailos.coop.br;camila.schluter@ailos.coop.br', 'f0160359', to_date('26-03-2021 17:01:05', 'dd-mm-yyyy hh24:mi:ss'), to_date('17-03-2021 15:19:26', 'dd-mm-yyyy hh24:mi:ss'));


	DELETE FROM crapaca a WHERE a.nmdeacao = 'VERIFICA_LIMITE_OPERACIONAL';
	UPDATE tbcartao_limite_operacional 
	   SET dsvlrprm = to_char(0)
	 WHERE cdacesso IN ('VLPROPCORRENTEMAJORADO', 'VLPROPCORRENTECRD', 'VLPROPCORRENTEPREAPROV');
	commit;
end;