/* ritm0128308 incremento de paralelismo */
UPDATE crapprm p SET p.dsvlrprm = 40 WHERE cdacesso = 'QTD_PARALE_CRPS750' AND cdcooper = 1;
UPDATE crapprm p SET p.dsvlrprm = 30 WHERE cdacesso = 'QTD_PARALE_CRPS414';
UPDATE TBGEN_BATCH_PARAM B
   SET B.QTPARALELO = 30
 WHERE B.CDPROGRAMA IN ('CRPS723','CRPS147','CRPS148',
                        'CRPS349','CRPS110','CRPS008',
                        'CRPS140','CRPS024','CRPS133',
                        'CRPS168','CRPS280') AND B.CDCOOPER = 1; 
UPDATE TBGEN_BATCH_PARAM B SET B.QTPARALELO = 20 WHERE B.CDPROGRAMA IN ('CRPS516','CRPS734') AND B.CDCOOPER = 1;
UPDATE TBGEN_BATCH_PARAM B SET B.QTPARALELO = 35 WHERE B.CDPROGRAMA = 'CRPS010' AND B.CDCOOPER = 1;
COMMIT;
