--RITM0121589 paralelismo do programa crps145
INSERT INTO TBGEN_BATCH_PARAM
  (IDPARAMETRO, QTPARALELO, QTREG_TRANSACAO, CDCOOPER, CDPROGRAMA)
VALUES
  ((SELECT MAX(IDPARAMETRO) + 1 FROM TBGEN_BATCH_PARAM),
   20,
   0,
   1,
   'CRPS145');
COMMIT;
