/*ritm0127166 
desativar crapprg crps114;
remover registros craptab 'EXESOLADMI'.
*/
UPDATE CRAPPRG
   SET CRAPPRG.INLIBPRG = 2, CRAPPRG.NRSOLICI = 9114
 WHERE CRAPPRG.CDPROGRA = 'CRPS114';
--SELECT * FROM crapprg WHERE cdprogra = 'CRPS114';
/*rollback:
UPDATE CRAPPRG
   SET CRAPPRG.INLIBPRG = 1, CRAPPRG.NRSOLICI = 59
 WHERE CRAPPRG.CDPROGRA = 'CRPS114'; */

DELETE FROM CRAPTAB T
 WHERE UPPER(T.NMSISTEM) = 'CRED'
   AND UPPER(T.TPTABELA) = 'GENERI'
   AND T.CDEMPRES = 0
   AND UPPER(T.CDACESSO) = 'EXESOLADMI'
   AND T.TPREGIST = 1;
--SELECT * FROM CRAPTAB T WHERE UPPER(T.NMSISTEM) = 'CRED' AND UPPER(T.TPTABELA) = 'GENERI' AND t.cdempres = 0 AND UPPER(T.CDACESSO) = 'EXESOLADMI' AND t.tpregist = 1;
/*rollback:
INSERT ALL
INTO craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER) VALUES ('CRED', 'GENERI', 0, 'EXESOLADMI', 1, '1', 1)
INTO craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER) VALUES ('CRED', 'GENERI', 0, 'EXESOLADMI', 1, '1', 2)
INTO craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER) VALUES ('CRED', 'GENERI', 0, 'EXESOLADMI', 1, '1', 3)
INTO craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER) VALUES ('CRED', 'GENERI', 0, 'EXESOLADMI', 1, '0', 4)
INTO craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER) VALUES ('CRED', 'GENERI', 0, 'EXESOLADMI', 1, '1', 5)
INTO craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER) VALUES ('CRED', 'GENERI', 0, 'EXESOLADMI', 1, '1', 6)
INTO craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER) VALUES ('CRED', 'GENERI', 0, 'EXESOLADMI', 1, '1', 7)
INTO craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER) VALUES ('CRED', 'GENERI', 0, 'EXESOLADMI', 1, '1', 8)
INTO craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER) VALUES ('CRED', 'GENERI', 0, 'EXESOLADMI', 1, '1', 9)
INTO craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER) VALUES ('CRED', 'GENERI', 0, 'EXESOLADMI', 1, '1', 10)
INTO craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER) VALUES ('CRED', 'GENERI', 0, 'EXESOLADMI', 1, '1', 11)
INTO craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER) VALUES ('CRED', 'GENERI', 0, 'EXESOLADMI', 1, '1', 12)
INTO craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER) VALUES ('CRED', 'GENERI', 0, 'EXESOLADMI', 1, '1', 13)
INTO craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER) VALUES ('CRED', 'GENERI', 0, 'EXESOLADMI', 1, '1', 14)
INTO craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER) VALUES ('CRED', 'GENERI', 0, 'EXESOLADMI', 1, '0', 15)
INTO craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER) VALUES ('CRED', 'GENERI', 0, 'EXESOLADMI', 1, '1', 16)
INTO craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER) VALUES ('CRED', 'GENERI', 0, 'EXESOLADMI', 1, '0', 17)
SELECT 1 FROM dual;
*/
COMMIT;
