-- Linhas enviadas da Credelesc
UPDATE crappco SET dsconteu = '158;159;160;162;163;164;168;174;194;206;7081;74'
 WHERE cdpartar IN (SELECT cdcadast FROM crapbat WHERE cdbattar = 'DEC4803LIN')
   AND cdcooper = 8;


INSERT ALL 
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 1, 'CORONA_SEM_COMPOSICAO', 'CREDITO - Finalidades que nao podem ser usadas para 4-Composicao', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 2, 'CORONA_SEM_COMPOSICAO', 'CREDITO - Finalidades que nao podem ser usadas para 4-Composicao', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 3, 'CORONA_SEM_COMPOSICAO', 'CREDITO - Finalidades que nao podem ser usadas para 4-Composicao', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 5, 'CORONA_SEM_COMPOSICAO', 'CREDITO - Finalidades que nao podem ser usadas para 4-Composicao', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 6, 'CORONA_SEM_COMPOSICAO', 'CREDITO - Finalidades que nao podem ser usadas para 4-Composicao', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 7, 'CORONA_SEM_COMPOSICAO', 'CREDITO - Finalidades que nao podem ser usadas para 4-Composicao', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 8, 'CORONA_SEM_COMPOSICAO', 'CREDITO - Finalidades que nao podem ser usadas para 4-Composicao', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 9, 'CORONA_SEM_COMPOSICAO', 'CREDITO - Finalidades que nao podem ser usadas para 4-Composicao', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 10, 'CORONA_SEM_COMPOSICAO', 'CREDITO - Finalidades que nao podem ser usadas para 4-Composicao', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 11, 'CORONA_SEM_COMPOSICAO', 'CREDITO - Finalidades que nao podem ser usadas para 4-Composicao', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 12, 'CORONA_SEM_COMPOSICAO', 'CREDITO - Finalidades que nao podem ser usadas para 4-Composicao', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 13, 'CORONA_SEM_COMPOSICAO', 'CREDITO - Finalidades que nao podem ser usadas para 4-Composicao', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 14, 'CORONA_SEM_COMPOSICAO', 'CREDITO - Finalidades que nao podem ser usadas para 4-Composicao', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 16, 'CORONA_SEM_COMPOSICAO', 'CREDITO - Finalidades que nao podem ser usadas para 4-Composicao', '82')
SELECT * FROM dual;

COMMIT;