BEGIN

  INSERT INTO craptab (NMSISTEM,TPTABELA,CDEMPRES,CDACESSO   ,TPREGIST,DSTEXTAB,CDCOOPER)  
               VALUES ('CRED'  ,'GENERI',0      ,'SAQMAXCASH',104     ,'500,00',16);

  INSERT INTO craptab (NMSISTEM,TPTABELA,CDEMPRES,CDACESSO   ,TPREGIST,DSTEXTAB,CDCOOPER)  
               VALUES ('CRED'  ,'GENERI',0      ,'SAQMAXCASH',105     ,'500,00',16);

  COMMIT;

END;
