BEGIN
  SYS.DBMS_SCHEDULER.DISABLE('CECRED.JBPIX_SINCRONIZA_VERLOG');
EXCEPTION
  WHEN OTHERS THEN
    CECRED.PC_INTERNAL_EXCEPTION(pr_compleme => 'PRB0048499');
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;