BEGIN

    INSERT INTO crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
    VALUES ('CRED', 'RELSLDASS', 'SALDOS DOS ASSOCIADOS', '.', '.', '.', 12, 1, 2, 6, 7, 30, 225, 55, 1, 1, 0);
    
    INSERT INTO crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
    VALUES ('CRED', 'RELSLDASS', 'SALDOS DOS ASSOCIADOS', '.', '.', '.', 12, 1, 2, 6, 7, 30, 225, 55, 1, 2, 0);
    
    INSERT INTO crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
    VALUES ('CRED', 'RELSLDASS', 'SALDOS DOS ASSOCIADOS', '.', '.', '.', 12, 1, 2, 6, 7, 30, 225, 55, 1, 3, 0);
    
    INSERT INTO crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
    VALUES ('CRED', 'RELSLDASS', 'SALDOS DOS ASSOCIADOS', '.', '.', '.', 12, 1, 2, 6, 7, 30, 225, 55, 1, 4, 0);
    
    INSERT INTO crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
    VALUES ('CRED', 'RELSLDASS', 'SALDOS DOS ASSOCIADOS', '.', '.', '.', 12, 1, 2, 6, 7, 30, 225, 55, 1, 5, 0);
    
    INSERT INTO crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
    VALUES ('CRED', 'RELSLDASS', 'SALDOS DOS ASSOCIADOS', '.', '.', '.', 12, 1, 2, 6, 7, 30, 225, 55, 1, 6, 0);
    
    INSERT INTO crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
    VALUES ('CRED', 'RELSLDASS', 'SALDOS DOS ASSOCIADOS', '.', '.', '.', 12, 1, 2, 6, 7, 30, 225, 55, 1, 7, 0);
    
    INSERT INTO crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
    VALUES ('CRED', 'RELSLDASS', 'SALDOS DOS ASSOCIADOS', '.', '.', '.', 12, 1, 2, 6, 7, 30, 225, 55, 1, 8, 0);
    
    INSERT INTO crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
    VALUES ('CRED', 'RELSLDASS', 'SALDOS DOS ASSOCIADOS', '.', '.', '.', 12, 1, 2, 6, 7, 30, 225, 55, 1, 9, 0);
    
    INSERT INTO crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
    VALUES ('CRED', 'RELSLDASS', 'SALDOS DOS ASSOCIADOS', '.', '.', '.', 12, 1, 2, 6, 7, 30, 225, 55, 1, 10, 0);
    
    INSERT INTO crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
    VALUES ('CRED', 'RELSLDASS', 'SALDOS DOS ASSOCIADOS', '.', '.', '.', 12, 1, 2, 6, 7, 30, 225, 55, 1, 11, 0);
    
    INSERT INTO crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
    VALUES ('CRED', 'RELSLDASS', 'SALDOS DOS ASSOCIADOS', '.', '.', '.', 12, 1, 2, 6, 7, 30, 225, 55, 1, 12, 0);
    
    INSERT INTO crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
    VALUES ('CRED', 'RELSLDASS', 'SALDOS DOS ASSOCIADOS', '.', '.', '.', 12, 1, 2, 6, 7, 30, 225, 55, 1, 13, 0);
    
    INSERT INTO crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
    VALUES ('CRED', 'RELSLDASS', 'SALDOS DOS ASSOCIADOS', '.', '.', '.', 12, 1, 2, 6, 7, 30, 225, 55, 1, 14, 0);
    
    INSERT INTO crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
    VALUES ('CRED', 'RELSLDASS', 'SALDOS DOS ASSOCIADOS', '.', '.', '.', 12, 1, 2, 6, 7, 30, 225, 55, 1, 15, 0);
    
    INSERT INTO crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
    VALUES ('CRED', 'RELSLDASS', 'SALDOS DOS ASSOCIADOS', '.', '.', '.', 12, 1, 2, 6, 7, 30, 225, 55, 1, 16, 0);
    
    INSERT INTO crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
    VALUES ('CRED', 'RELSLDASS', 'SALDOS DOS ASSOCIADOS', '.', '.', '.', 12, 1, 2, 6, 7, 30, 225, 55, 1, 17, 0);

	COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
END;
