BEGIN
	merge into CECRED.TBCADAST_PESSOA R
    using CECRED.crapass FN
    on(R.NRDCONTA <> FN.NRDCONTA and R.NRCPFCGC = FN.NRCPFCGC and R.CDCOOPER = FN.CDCOOPER)
    when matched then
        update
        set R.NRDCONTA = FN.NRDCONTA

	COMMIT;
EXCEPTION WHEN OTHERS THEN
	ROLLBACK;
END;