BEGIN

  UPDATE CECRED.CRAPPEP P
       SET P.DTULTPAG = P.DTVENCTO
   WHERE EXISTS (SELECT 1
            FROM CECRED.CRAPEPR E
           WHERE E.CDCOOPER = P.CDCOOPER
             AND E.NRDCONTA = P.NRDCONTA
             AND E.NRCTREMP = P.NRCTREMP
             AND E.INLIQUID = 1
             AND E.INPREJUZ = 1
             AND E.TPDESCTO = 2
             AND E.TPEMPRST = 1
             AND P.INLIQUID = 1
             AND P.INPREJUZ = 0
             AND E.VLSDPREJ > 0
             AND P.DTULTPAG IS NULL);

  COMMIT;

EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20500, SQLERRM);
END;
