USE [DBWEBJUD]
GO
   UPDATE VM_MESSAGES
      SET GRAVOU_OFICIO = 'S'
    WHERE NUM_SISBACEN = '123163455';

   UPDATE VM_MESSAGES_UNITS
      SET FG_GRAVOU_OFICIO = '1'
    WHERE COD_MSG IN(SELECT COD_MSG FROM VM_MESSAGES WHERE NUM_SISBACEN = '123163455');

  COMMIT;
  
GO