
begin
  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '30000 79200', 1);  

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '30000 79200', 2);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '30000 79200', 3);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '30000 79200', 4);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '30000 79200', 5);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '30000 79200', 6);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '30000 79200', 7);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '30000 79200', 8);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '30000 79200', 9);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '30000 79200', 10);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '30000 79200', 11);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '30000 79200', 12);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '30000 79200', 13);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '30000 79200', 14);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '30000 79200', 15);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '30000 79200', 16);

  insert into craptab (NMSISTEM, TPTABELA, CDEMPRES, CDACESSO, TPREGIST, DSTEXTAB, CDCOOPER)
  values ('CRED', 'GENERI', 0, 'HRLMNOTURNO', 1, '30000 79200', 17);
  
  COMMIT;
  
EXCEPTION WHEN OTHERS THEN
  ROLLBACK;
END;  
/
BEGIN
  update CRAPSNH SNH 
     set SNH.vllimnottrans = 1000 
   where SNH.tpdsenha = 1;   
  commit;  
EXCEPTION WHEN OTHERS THEN
	ROLLBACK;
END;  
/
BEGIN
  update CRAPSNH SNH 
     set SNH.vllimnotpgbo = 1000 
   where SNH.tpdsenha = 1;    
  commit;
EXCEPTION WHEN OTHERS THEN
	ROLLBACK;
END;  
/