declare

    conta_13352881_4602620 clob := '<?xml version="1.0"?>
<Root>
  <convenioCredito>
    <cooperativa>
      <codigo>1</codigo>
    </cooperativa>
    <numeroContrato>6502</numeroContrato>
  </convenioCredito>
  <configuracaoCredito>
    <financiaIOF>false</financiaIOF>
    <financiaTarifa>false</financiaTarifa>
    <diasCarencia>26</diasCarencia>
  </configuracaoCredito>
  <propostaContratoCredito>
    <CETPercentAoAno>11.09</CETPercentAoAno>
    <dataPrimeiraParcela>2021-11-01</dataPrimeiraParcela>
    <produto>
      <codigo>162</codigo>
    </produto>
    <quantidadeParcelas>120</quantidadeParcelas>
    <taxaJurosRemuneratorios>0.88</taxaJurosRemuneratorios>
    <taxaJurosRemuneratoriosAnual>11.09</taxaJurosRemuneratoriosAnual>
    <tipoLiberacao>
      <codigo>6</codigo>
    </tipoLiberacao>
    <tipoLiquidacao>
      <codigo>4</codigo>
    </tipoLiquidacao>
    <tributoIOFValor>1012.8</tributoIOFValor>
    <valor>59200.00</valor>
    <valorBase>59200.00</valorBase>
    <dataProposta>2021-10-19T16:16:16</dataProposta>
    <emitente>
      <dataNascOuConstituicao>1984-02-27T00:00:00</dataNascOuConstituicao>
      <identificadorReceitaFederal>4361160902</identificadorReceitaFederal>
      <razaoSocialOuNome>TALITA PRISCILA BOENG DOS REIS</razaoSocialOuNome>
      <nacionalidade>
        <codigo>42</codigo>
      </nacionalidade>
      <tipo>
        <codigo>1</codigo>
      </tipo>
      <contaCorrente>
        <agencia>
          <codigo>101</codigo>
        </agencia>
        <banco>
          <codigo>85</codigo>
        </banco>
        <codigoConta>13352881</codigoConta>
        <cooperativa>
          <codigo>1</codigo>
        </cooperativa>
      </contaCorrente>
      <numeroTitularidade>1</numeroTitularidade>
      <pessoaContatoEndereco>
        <CEP>83326140</CEP>
        <cidade>
          <descricao>PINHAIS</descricao>
        </cidade>
        <nomeBairro>ATUBA</nomeBairro>
        <numeroLogradouro>650</numeroLogradouro>
        <tipoEndereco>
          <codigo>13</codigo>
        </tipoEndereco>
        <tipoENomeLogradouro>RUA ALZIRA DE ARAUJO</tipoENomeLogradouro>
        <UF>PR</UF>
      </pessoaContatoEndereco>
    </emitente>
    <identificadorProposta>4602620</identificadorProposta>
    <statusProposta>
      <codigo>26</codigo>
    </statusProposta>
  </propostaContratoCredito>
  <pessoaDocumento>
    <identificador>06987597465</identificador>
    <tipo>
      <sigla>CI</sigla>
    </tipo>
  </pessoaDocumento>
  <pessoaFisicaOcupacao>
    <naturezaOcupacao>
      <codigo>6</codigo>
    </naturezaOcupacao>
  </pessoaFisicaOcupacao>
  <pessoaFisicaDetalhamento>
    <estadoCivil>
      <codigo>4</codigo>
    </estadoCivil>
    <sexo>
      <codigo>2</codigo>
    </sexo>
  </pessoaFisicaDetalhamento>
  <pessoaFisicaRendimento>
    <identificadorRegistroFuncionario>43747601</identificadorRegistroFuncionario>
  </pessoaFisicaRendimento>
  <remuneracaoColaborador>
    <empregador>
      <identificadorReceitaFederal>95423000000100</identificadorReceitaFederal>
      <razaoSocialOuNome>MUNICIPIO DE PINHAIS</razaoSocialOuNome>
    </empregador>
  </remuneracaoColaborador>
  <beneficio/>
  <listaPessoasEndereco>
    <pessoaEndereco>
      <parametroConsignado>
        <tipoPessoaEndereco>EMPREGADOR</tipoPessoaEndereco>
      </parametroConsignado>
      <pessoaContatoEndereco>
        <CEP>83323400</CEP>
        <cidade>
          <descricao>PINHAIS</descricao>
        </cidade>
        <nomeBairro>CENTRO</nomeBairro>
        <numeroLogradouro>536</numeroLogradouro>
        <tipoENomeLogradouro>RUA WANDA DOS SANTOS MALLMANN</tipoENomeLogradouro>
        <UF>PR</UF>
      </pessoaContatoEndereco>
    </pessoaEndereco>
  </listaPessoasEndereco>
  <parcela>
    <valor>799.87</valor>
  </parcela>
  <tarifa>
    <valor>0.0</valor>
  </tarifa>
  <inadimplencia>
    <despesasCartorarias>0.0</despesasCartorarias>
  </inadimplencia>
  <usuarioDominioCecred>
    <codigo/>
  </usuarioDominioCecred>
  <parametroConsignado>
    <codigoFisTabelaJuros>1</codigoFisTabelaJuros>
    <indicadorContaPrincipal>true</indicadorContaPrincipal>
    <naturalidade>CURITIBA</naturalidade>
    <dataCalculoLegado>2021-10-06T00:00:00</dataCalculoLegado>
  </parametroConsignado>
</Root>
';
    conta_9501096_4531209 clob := '<?xml version="1.0"?>
<Root>
  <convenioCredito>
    <cooperativa>
      <codigo>1</codigo>
    </cooperativa>
    <numeroContrato>2461</numeroContrato>
  </convenioCredito>
  <configuracaoCredito>
    <financiaIOF>true</financiaIOF>
    <financiaTarifa>true</financiaTarifa>
    <diasCarencia>30</diasCarencia>
  </configuracaoCredito>
  <propostaContratoCredito>
    <CETPercentAoAno>17.76</CETPercentAoAno>
    <dataPrimeiraParcela>2021-11-10</dataPrimeiraParcela>
    <produto>
      <codigo>161</codigo>
    </produto>
    <quantidadeParcelas>48</quantidadeParcelas>
    <taxaJurosRemuneratorios>1.35</taxaJurosRemuneratorios>
    <taxaJurosRemuneratoriosAnual>17.46</taxaJurosRemuneratoriosAnual>
    <tipoLiberacao>
      <codigo>6</codigo>
    </tipoLiberacao>
    <tipoLiquidacao>
      <codigo>4</codigo>
    </tipoLiquidacao>
    <tributoIOFValor>211.85</tributoIOFValor>
    <valor>49411.85</valor>
    <valorBase>49200.00</valorBase>
    <dataProposta>2021-10-19T16:16:16</dataProposta>
    <emitente>
      <dataNascOuConstituicao>1976-01-02T00:00:00</dataNascOuConstituicao>
      <identificadorReceitaFederal>93684177920</identificadorReceitaFederal>
      <razaoSocialOuNome>CRISTIANE DO ROCIO GONCALVES</razaoSocialOuNome>
      <nacionalidade>
        <codigo>42</codigo>
      </nacionalidade>
      <tipo>
        <codigo>1</codigo>
      </tipo>
      <contaCorrente>
        <agencia>
          <codigo>101</codigo>
        </agencia>
        <banco>
          <codigo>85</codigo>
        </banco>
        <codigoConta>9501096</codigoConta>
        <cooperativa>
          <codigo>1</codigo>
        </cooperativa>
      </contaCorrente>
      <numeroTitularidade>1</numeroTitularidade>
      <pessoaContatoEndereco>
        <CEP>89107000</CEP>
        <cidade>
          <descricao>POMERODE</descricao>
        </cidade>
        <nomeBairro>CENTRO</nomeBairro>
        <numeroLogradouro>211</numeroLogradouro>
        <tipoEndereco>
          <codigo>13</codigo>
        </tipoEndereco>
        <tipoENomeLogradouro>RUA RUDOLFO SCHIPPMA</tipoENomeLogradouro>
        <UF>SC</UF>
      </pessoaContatoEndereco>
    </emitente>
    <identificadorProposta>4531209</identificadorProposta>
    <statusProposta>
      <codigo>26</codigo>
    </statusProposta>
  </propostaContratoCredito>
  <pessoaDocumento>
    <identificador>34334483</identificador>
    <tipo>
      <sigla>CI</sigla>
    </tipo>
  </pessoaDocumento>
  <pessoaFisicaOcupacao>
    <naturezaOcupacao>
      <codigo>1</codigo>
    </naturezaOcupacao>
  </pessoaFisicaOcupacao>
  <pessoaFisicaDetalhamento>
    <estadoCivil>
      <codigo>4</codigo>
    </estadoCivil>
    <sexo>
      <codigo>2</codigo>
    </sexo>
  </pessoaFisicaDetalhamento>
  <pessoaFisicaRendimento>
    <identificadorRegistroFuncionario>9077</identificadorRegistroFuncionario>
  </pessoaFisicaRendimento>
  <remuneracaoColaborador>
    <empregador>
      <identificadorReceitaFederal>78855830000198</identificadorReceitaFederal>
      <razaoSocialOuNome>KYLY INDUSTRIA TEXTIL LTDA</razaoSocialOuNome>
    </empregador>
  </remuneracaoColaborador>
  <beneficio/>
  <listaPessoasEndereco>
    <pessoaEndereco>
      <parametroConsignado>
        <tipoPessoaEndereco>EMPREGADOR</tipoPessoaEndereco>
      </parametroConsignado>
      <pessoaContatoEndereco>
        <CEP>89107000</CEP>
        <cidade>
          <descricao>POMERODE</descricao>
        </cidade>
        <nomeBairro>CENTRO</nomeBairro>
        <numeroLogradouro>3155</numeroLogradouro>
        <tipoENomeLogradouro>RODOVIA SC 418</tipoENomeLogradouro>
        <UF>SC</UF>
      </pessoaContatoEndereco>
    </pessoaEndereco>
  </listaPessoasEndereco>
  <parcela>
    <valor>1405.41</valor>
  </parcela>
  <tarifa>
    <valor>0.0</valor>
  </tarifa>
  <inadimplencia>
    <despesasCartorarias>0.0</despesasCartorarias>
  </inadimplencia>
  <usuarioDominioCecred>
    <codigo/>
  </usuarioDominioCecred>
  <parametroConsignado>
    <codigoFisTabelaJuros>1</codigoFisTabelaJuros>
    <indicadorContaPrincipal>true</indicadorContaPrincipal>
    <naturalidade>PARANAGUA</naturalidade>
    <dataCalculoLegado>2021-10-11T00:00:00</dataCalculoLegado>
  </parametroConsignado>
</Root>
';
    conta_11934425_4573086 clob := '<?xml version="1.0"?>
<Root>
  <convenioCredito>
    <cooperativa>
      <codigo>1</codigo>
    </cooperativa>
    <numeroContrato>7922</numeroContrato>
  </convenioCredito>
  <configuracaoCredito>
    <financiaIOF>false</financiaIOF>
    <financiaTarifa>false</financiaTarifa>
    <diasCarencia>22</diasCarencia>
  </configuracaoCredito>
  <propostaContratoCredito>
    <CETPercentAoAno>11.09</CETPercentAoAno>
    <dataPrimeiraParcela>2021-11-05</dataPrimeiraParcela>
    <produto>
      <codigo>162</codigo>
    </produto>
    <quantidadeParcelas>91</quantidadeParcelas>
    <taxaJurosRemuneratorios>0.88</taxaJurosRemuneratorios>
    <taxaJurosRemuneratoriosAnual>11.09</taxaJurosRemuneratoriosAnual>
    <tipoLiberacao>
      <codigo>6</codigo>
    </tipoLiberacao>
    <tipoLiquidacao>
      <codigo>4</codigo>
    </tipoLiquidacao>
    <tributoIOFValor>658.59</tributoIOFValor>
    <valor>17049.02</valor>
    <valorBase>17049.02</valorBase>
    <dataProposta>2021-10-19T16:16:16</dataProposta>
    <emitente>
      <dataNascOuConstituicao>1956-10-02T00:00:00</dataNascOuConstituicao>
      <identificadorReceitaFederal>30454700920</identificadorReceitaFederal>
      <razaoSocialOuNome>WALDIR PASSOS LEMOS</razaoSocialOuNome>
      <nacionalidade>
        <codigo>42</codigo>
      </nacionalidade>
      <tipo>
        <codigo>1</codigo>
      </tipo>
      <contaCorrente>
        <agencia>
          <codigo>101</codigo>
        </agencia>
        <banco>
          <codigo>85</codigo>
        </banco>
        <codigoConta>11934425</codigoConta>
        <cooperativa>
          <codigo>1</codigo>
        </cooperativa>
      </contaCorrente>
      <numeroTitularidade>1</numeroTitularidade>
      <pessoaContatoEndereco>
        <CEP>89116700</CEP>
        <cidade>
          <descricao>GASPAR</descricao>
        </cidade>
        <nomeBairro>MARGEM ESQUERDA</nomeBairro>
        <numeroLogradouro>11</numeroLogradouro>
        <tipoEndereco>
          <codigo>13</codigo>
        </tipoEndereco>
        <tipoENomeLogradouro>RUA FRANCISCO LENFER</tipoENomeLogradouro>
        <UF>SC</UF>
      </pessoaContatoEndereco>
    </emitente>
    <identificadorProposta>4573086</identificadorProposta>
    <statusProposta>
      <codigo>26</codigo>
    </statusProposta>
  </propostaContratoCredito>
  <pessoaDocumento>
    <identificador>719963</identificador>
    <tipo>
      <sigla>CI</sigla>
    </tipo>
  </pessoaDocumento>
  <pessoaFisicaOcupacao>
    <naturezaOcupacao>
      <codigo>6</codigo>
    </naturezaOcupacao>
  </pessoaFisicaOcupacao>
  <pessoaFisicaDetalhamento>
    <estadoCivil>
      <codigo>4</codigo>
    </estadoCivil>
    <sexo>
      <codigo>1</codigo>
    </sexo>
  </pessoaFisicaDetalhamento>
  <pessoaFisicaRendimento>
    <identificadorRegistroFuncionario>0</identificadorRegistroFuncionario>
  </pessoaFisicaRendimento>
  <remuneracaoColaborador>
    <empregador>
      <identificadorReceitaFederal>82636028000184</identificadorReceitaFederal>
      <razaoSocialOuNome>SERVICO AUTONOMO MUNICIPAL DE AGUA </razaoSocialOuNome>
    </empregador>
  </remuneracaoColaborador>
  <beneficio/>
  <listaPessoasEndereco>
    <pessoaEndereco>
      <parametroConsignado>
        <tipoPessoaEndereco>EMPREGADOR</tipoPessoaEndereco>
      </parametroConsignado>
      <pessoaContatoEndereco>
        <CEP>89114320</CEP>
        <cidade>
          <descricao>GASPAR</descricao>
        </cidade>
        <nomeBairro>SANTA TEREZINHA</nomeBairro>
        <numeroLogradouro>189</numeroLogradouro>
        <tipoENomeLogradouro>RUA JOAO VIEIRA</tipoENomeLogradouro>
        <UF>SC</UF>
      </pessoaContatoEndereco>
    </pessoaEndereco>
  </listaPessoasEndereco>
  <parcela>
    <valor>272.42</valor>
  </parcela>
  <tarifa>
    <valor>0.0</valor>
  </tarifa>
  <inadimplencia>
    <despesasCartorarias>0.0</despesasCartorarias>
  </inadimplencia>
  <posicao>
    <produtoCategoria>
      <codigo>32</codigo>
    </produtoCategoria>
    <saldo>17049.02</saldo>
  </posicao>
  <usuarioDominioCecred>
    <codigo/>
  </usuarioDominioCecred>
  <parametroConsignado>
    <codigoFisTabelaJuros>1</codigoFisTabelaJuros>
    <indicadorContaPrincipal>true</indicadorContaPrincipal>
    <naturalidade>PONTA GROSSA</naturalidade>
    <dataCalculoLegado>2021-10-14T00:00:00</dataCalculoLegado>
  </parametroConsignado>
</Root>
';
    conta_9942831_4445492 clob := '<?xml version="1.0"?>
<Root>
  <convenioCredito>
    <cooperativa>
      <codigo>1</codigo>
    </cooperativa>
    <numeroContrato>2461</numeroContrato>
  </convenioCredito>
  <configuracaoCredito>
    <financiaIOF>true</financiaIOF>
    <financiaTarifa>true</financiaTarifa>
    <diasCarencia>47</diasCarencia>
  </configuracaoCredito>
  <propostaContratoCredito>
    <CETPercentAoAno>19.47</CETPercentAoAno>
    <dataPrimeiraParcela>2021-11-10</dataPrimeiraParcela>
    <produto>
      <codigo>161</codigo>
    </produto>
    <quantidadeParcelas>48</quantidadeParcelas>
    <taxaJurosRemuneratorios>1.35</taxaJurosRemuneratorios>
    <taxaJurosRemuneratoriosAnual>17.46</taxaJurosRemuneratoriosAnual>
    <tipoLiberacao>
      <codigo>6</codigo>
    </tipoLiberacao>
    <tipoLiquidacao>
      <codigo>4</codigo>
    </tipoLiquidacao>
    <tributoIOFValor>734.9</tributoIOFValor>
    <valor>23862.91</valor>
    <valorBase>23138.00</valorBase>
    <dataProposta>2021-10-19T16:16:16</dataProposta>
    <emitente>
      <dataNascOuConstituicao>1992-07-21T00:00:00</dataNascOuConstituicao>
      <identificadorReceitaFederal>1026085985</identificadorReceitaFederal>
      <razaoSocialOuNome>HELINTON AMARILDO SIQUEIRA</razaoSocialOuNome>
      <nacionalidade>
        <codigo>42</codigo>
      </nacionalidade>
      <tipo>
        <codigo>1</codigo>
      </tipo>
      <contaCorrente>
        <agencia>
          <codigo>101</codigo>
        </agencia>
        <banco>
          <codigo>85</codigo>
        </banco>
        <codigoConta>9942831</codigoConta>
        <cooperativa>
          <codigo>1</codigo>
        </cooperativa>
      </contaCorrente>
      <numeroTitularidade>1</numeroTitularidade>
      <pessoaContatoEndereco>
        <CEP>89066300</CEP>
        <cidade>
          <descricao>BLUMENAU</descricao>
        </cidade>
        <nomeBairro>ITOUPAVAZINHA</nomeBairro>
        <numeroLogradouro>3001</numeroLogradouro>
        <tipoEndereco>
          <codigo>13</codigo>
        </tipoEndereco>
        <tipoENomeLogradouro>RUA FREDERICO JENSEN</tipoENomeLogradouro>
        <UF>SC</UF>
      </pessoaContatoEndereco>
    </emitente>
    <identificadorProposta>4445492</identificadorProposta>
    <statusProposta>
      <codigo>26</codigo>
    </statusProposta>
  </propostaContratoCredito>
  <pessoaDocumento>
    <identificador>11079169</identificador>
    <tipo>
      <sigla>CI</sigla>
    </tipo>
  </pessoaDocumento>
  <pessoaFisicaOcupacao>
    <naturezaOcupacao>
      <codigo>1</codigo>
    </naturezaOcupacao>
  </pessoaFisicaOcupacao>
  <pessoaFisicaDetalhamento>
    <estadoCivil>
      <codigo>4</codigo>
    </estadoCivil>
    <sexo>
      <codigo>1</codigo>
    </sexo>
  </pessoaFisicaDetalhamento>
  <pessoaFisicaRendimento>
    <identificadorRegistroFuncionario>0</identificadorRegistroFuncionario>
  </pessoaFisicaRendimento>
  <remuneracaoColaborador>
    <empregador>
      <identificadorReceitaFederal>78855830000198</identificadorReceitaFederal>
      <razaoSocialOuNome>KYLY INDUSTRIA TEXTIL LTDA</razaoSocialOuNome>
    </empregador>
  </remuneracaoColaborador>
  <beneficio/>
  <listaPessoasEndereco>
    <pessoaEndereco>
      <parametroConsignado>
        <tipoPessoaEndereco>EMPREGADOR</tipoPessoaEndereco>
      </parametroConsignado>
      <pessoaContatoEndereco>
        <CEP>89107000</CEP>
        <cidade>
          <descricao>POMERODE</descricao>
        </cidade>
        <nomeBairro>CENTRO</nomeBairro>
        <numeroLogradouro>3155</numeroLogradouro>
        <tipoENomeLogradouro>RODOVIA SC 418</tipoENomeLogradouro>
        <UF>SC</UF>
      </pessoaContatoEndereco>
    </pessoaEndereco>
  </listaPessoasEndereco>
  <parcela>
    <valor>684.19</valor>
  </parcela>
  <tarifa>
    <valor>0.0</valor>
  </tarifa>
  <inadimplencia>
    <despesasCartorarias>0.0</despesasCartorarias>
  </inadimplencia>
  <usuarioDominioCecred>
    <codigo/>
  </usuarioDominioCecred>
  <parametroConsignado>
    <codigoFisTabelaJuros>1</codigoFisTabelaJuros>
    <indicadorContaPrincipal>true</indicadorContaPrincipal>
    <naturalidade>GUARANIACU</naturalidade>
    <dataCalculoLegado>2021-09-24T00:00:00</dataCalculoLegado>
  </parametroConsignado>
</Root>
';
    conta_13440241_4539828 clob := '<?xml version="1.0"?>
<Root>
  <convenioCredito>
    <cooperativa>
      <codigo>1</codigo>
    </cooperativa>
    <numeroContrato>6502</numeroContrato>
  </convenioCredito>
  <configuracaoCredito>
    <financiaIOF>false</financiaIOF>
    <financiaTarifa>false</financiaTarifa>
    <diasCarencia>27</diasCarencia>
  </configuracaoCredito>
  <propostaContratoCredito>
    <CETPercentAoAno>11.09</CETPercentAoAno>
    <dataPrimeiraParcela>2021-11-01</dataPrimeiraParcela>
    <produto>
      <codigo>162</codigo>
    </produto>
    <quantidadeParcelas>108</quantidadeParcelas>
    <taxaJurosRemuneratorios>0.88</taxaJurosRemuneratorios>
    <taxaJurosRemuneratoriosAnual>11.09</taxaJurosRemuneratoriosAnual>
    <tipoLiberacao>
      <codigo>6</codigo>
    </tipoLiberacao>
    <tipoLiquidacao>
      <codigo>4</codigo>
    </tipoLiquidacao>
    <tributoIOFValor>136.83</tributoIOFValor>
    <valor>3496.68</valor>
    <valorBase>3496.68</valorBase>
    <dataProposta>2021-10-19T16:16:16</dataProposta>
    <emitente>
      <dataNascOuConstituicao>1988-01-04T00:00:00</dataNascOuConstituicao>
      <identificadorReceitaFederal>5931035990</identificadorReceitaFederal>
      <razaoSocialOuNome>MONICA THAIS DE SOUZA</razaoSocialOuNome>
      <nacionalidade>
        <codigo>42</codigo>
      </nacionalidade>
      <tipo>
        <codigo>1</codigo>
      </tipo>
      <contaCorrente>
        <agencia>
          <codigo>101</codigo>
        </agencia>
        <banco>
          <codigo>85</codigo>
        </banco>
        <codigoConta>13440241</codigoConta>
        <cooperativa>
          <codigo>1</codigo>
        </cooperativa>
      </contaCorrente>
      <numeroTitularidade>1</numeroTitularidade>
      <pessoaContatoEndereco>
        <CEP>83321300</CEP>
        <cidade>
          <descricao>PINHAIS</descricao>
        </cidade>
        <nomeBairro>VARGEM GRANDE</nomeBairro>
        <numeroLogradouro>916</numeroLogradouro>
        <tipoEndereco>
          <codigo>13</codigo>
        </tipoEndereco>
        <tipoENomeLogradouro>RUA CARLOS DRUMMOND </tipoENomeLogradouro>
        <UF>PR</UF>
      </pessoaContatoEndereco>
    </emitente>
    <identificadorProposta>4539828</identificadorProposta>
    <statusProposta>
      <codigo>26</codigo>
    </statusProposta>
  </propostaContratoCredito>
  <pessoaDocumento>
    <identificador>100417286</identificador>
    <tipo>
      <sigla>CI</sigla>
    </tipo>
  </pessoaDocumento>
  <pessoaFisicaOcupacao>
    <naturezaOcupacao>
      <codigo>6</codigo>
    </naturezaOcupacao>
  </pessoaFisicaOcupacao>
  <pessoaFisicaDetalhamento>
    <estadoCivil>
      <codigo>4</codigo>
    </estadoCivil>
    <sexo>
      <codigo>2</codigo>
    </sexo>
  </pessoaFisicaDetalhamento>
  <pessoaFisicaRendimento>
    <identificadorRegistroFuncionario>0</identificadorRegistroFuncionario>
  </pessoaFisicaRendimento>
  <remuneracaoColaborador>
    <empregador>
      <identificadorReceitaFederal>95423000000100</identificadorReceitaFederal>
      <razaoSocialOuNome>MUNICIPIO DE PINHAIS</razaoSocialOuNome>
    </empregador>
  </remuneracaoColaborador>
  <beneficio/>
  <listaPessoasEndereco>
    <pessoaEndereco>
      <parametroConsignado>
        <tipoPessoaEndereco>EMPREGADOR</tipoPessoaEndereco>
      </parametroConsignado>
      <pessoaContatoEndereco>
        <CEP>83323400</CEP>
        <cidade>
          <descricao>PINHAIS</descricao>
        </cidade>
        <nomeBairro>CENTRO</nomeBairro>
        <numeroLogradouro>536</numeroLogradouro>
        <tipoENomeLogradouro>RUA WANDA DOS SANTOS MALLMANN</tipoENomeLogradouro>
        <UF>PR</UF>
      </pessoaContatoEndereco>
    </pessoaEndereco>
  </listaPessoasEndereco>
  <parcela>
    <valor>50.25</valor>
  </parcela>
  <tarifa>
    <valor>0.0</valor>
  </tarifa>
  <inadimplencia>
    <despesasCartorarias>0.0</despesasCartorarias>
  </inadimplencia>
  <usuarioDominioCecred>
    <codigo/>
  </usuarioDominioCecred>
  <parametroConsignado>
    <codigoFisTabelaJuros>1</codigoFisTabelaJuros>
    <indicadorContaPrincipal>true</indicadorContaPrincipal>
    <naturalidade>PIRAQUARA</naturalidade>
    <dataCalculoLegado>2021-10-05T00:00:00</dataCalculoLegado>
  </parametroConsignado>
</Root>
';
    conta_278963_39197 clob := '<?xml version="1.0"?>
<Root>
  <convenioCredito>
    <cooperativa>
      <codigo>14</codigo>
    </cooperativa>
    <numeroContrato>11</numeroContrato>
  </convenioCredito>
  <configuracaoCredito>
    <diasCarencia>34</diasCarencia>
    <financiaIOF>true</financiaIOF>
    <financiaTarifa>true</financiaTarifa>
  </configuracaoCredito>
  <propostaContratoCredito>
    <CETPercentAoAno>16.29</CETPercentAoAno>
    <dataPrimeiraParcela>2021-11-01</dataPrimeiraParcela>
    <produto>
      <codigo>161</codigo>
    </produto>
    <quantidadeParcelas>47</quantidadeParcelas>
    <taxaJurosRemuneratorios>1.10</taxaJurosRemuneratorios>
    <taxaJurosRemuneratoriosAnual>14.03</taxaJurosRemuneratoriosAnual>
    <tipoLiberacao>
      <codigo>6</codigo>
    </tipoLiberacao>
    <tipoLiquidacao>
      <codigo>4</codigo>
    </tipoLiquidacao>
    <tributoIOFValor>727.94</tributoIOFValor>
    <valor>20757.94</valor>
    <valorBase>20030.00</valorBase>
    <dataProposta>2021-10-19T16:16:16</dataProposta>
    <emitente>
      <dataNascOuConstituicao>1995-05-14T00:00:00</dataNascOuConstituicao>
      <identificadorReceitaFederal>9596412973</identificadorReceitaFederal>
      <razaoSocialOuNome>TATIANE CARDOSO</razaoSocialOuNome>
      <nacionalidade>
        <codigo>42</codigo>
      </nacionalidade>
      <tipo>
        <codigo>1</codigo>
      </tipo>
      <contaCorrente>
        <agencia>
          <codigo>113</codigo>
        </agencia>
        <banco>
          <codigo>85</codigo>
        </banco>
        <codigoConta>278963</codigoConta>
        <cooperativa>
          <codigo>14</codigo>
        </cooperativa>
      </contaCorrente>
      <numeroTitularidade>1</numeroTitularidade>
      <pessoaContatoEndereco>
        <CEP>85605410</CEP>
        <cidade>
          <descricao>FRANCISCO BELTRAO</descricao>
        </cidade>
        <nomeBairro>LUTHER KING</nomeBairro>
        <numeroLogradouro>1032</numeroLogradouro>
        <tipoEndereco>
          <codigo>13</codigo>
        </tipoEndereco>
        <tipoENomeLogradouro>RUA BOLIVIA</tipoENomeLogradouro>
        <UF>PR</UF>
      </pessoaContatoEndereco>
    </emitente>
    <identificadorProposta>39197</identificadorProposta>
    <statusProposta>
      <codigo>26</codigo>
    </statusProposta>
  </propostaContratoCredito>
  <pessoaDocumento>
    <identificador>05918886740</identificador>
    <tipo>
      <sigla>CI</sigla>
    </tipo>
  </pessoaDocumento>
  <pessoaFisicaOcupacao>
    <naturezaOcupacao>
      <codigo>0</codigo>
    </naturezaOcupacao>
  </pessoaFisicaOcupacao>
  <pessoaFisicaDetalhamento>
    <estadoCivil>
      <codigo>4</codigo>
    </estadoCivil>
    <sexo>
      <codigo>2</codigo>
    </sexo>
  </pessoaFisicaDetalhamento>
  <pessoaFisicaRendimento>
    <identificadorRegistroFuncionario>0</identificadorRegistroFuncionario>
  </pessoaFisicaRendimento>
  <remuneracaoColaborador>
    <empregador>
      <identificadorReceitaFederal>10311218000110</identificadorReceitaFederal>
      <razaoSocialOuNome>COOPERATIVA DE CREDITO EVOLUA</razaoSocialOuNome>
    </empregador>
  </remuneracaoColaborador>
  <beneficio/>
  <listaPessoasEndereco>
    <pessoaEndereco>
      <parametroConsignado>
        <tipoPessoaEndereco>EMPREGADOR</tipoPessoaEndereco>
      </parametroConsignado>
      <pessoaContatoEndereco>
        <CEP>85601630</CEP>
        <cidade>
          <descricao>FRANCISCO BELTRAO</descricao>
        </cidade>
        <nomeBairro>CENTRO</nomeBairro>
        <numeroLogradouro>1819</numeroLogradouro>
        <tipoENomeLogradouro>RUA CURITIBA</tipoENomeLogradouro>
        <UF>PR</UF>
      </pessoaContatoEndereco>
    </pessoaEndereco>
  </listaPessoasEndereco>
  <parcela>
    <valor>568.82</valor>
  </parcela>
  <tarifa>
    <valor>0.0</valor>
  </tarifa>
  <inadimplencia>
    <despesasCartorarias>0.0</despesasCartorarias>
  </inadimplencia>
  <usuarioDominioCecred>
    <codigo/>
  </usuarioDominioCecred>
  <parametroConsignado>
    <codigoFisTabelaJuros>1</codigoFisTabelaJuros>
    <indicadorContaPrincipal>true</indicadorContaPrincipal>
    <naturalidade>FRANCISCO BELTRAO</naturalidade>
    <dataCalculoLegado>2021-09-28T00:00:00</dataCalculoLegado>
  </parametroConsignado>
</Root>
';

begin
  
    insert into tbgen_evento_soa(cdcooper, nrdconta, nrctrprp, tpevento, tproduto_evento, tpoperacao, dhoperacao, dsprocessamento, dsstatus, dhevento, dserro, nrtentativas, dsconteudo_requisicao) 
    values (1, 13352881, 4602620, 'EFETIVA_PROPOSTA', 'CONSIGNADO', 'INSERT', sysdate, null, null, null, null, null, conta_13352881_4602620);

    insert into tbgen_evento_soa(cdcooper, nrdconta, nrctrprp, tpevento, tproduto_evento, tpoperacao, dhoperacao, dsprocessamento, dsstatus, dhevento, dserro, nrtentativas, dsconteudo_requisicao) 
    values (1, 9501096, 4531209, 'EFETIVA_PROPOSTA', 'CONSIGNADO', 'INSERT', sysdate, null, null, null, null, null, conta_9501096_4531209);

    insert into tbgen_evento_soa(cdcooper, nrdconta, nrctrprp, tpevento, tproduto_evento, tpoperacao, dhoperacao, dsprocessamento, dsstatus, dhevento, dserro, nrtentativas, dsconteudo_requisicao) 
    values (1, 11934425, 4573086, 'EFETIVA_PROPOSTA', 'CONSIGNADO', 'INSERT', sysdate, null, null, null, null, null, conta_11934425_4573086);

    insert into tbgen_evento_soa(cdcooper, nrdconta, nrctrprp, tpevento, tproduto_evento, tpoperacao, dhoperacao, dsprocessamento, dsstatus, dhevento, dserro, nrtentativas, dsconteudo_requisicao) 
    values (1, 9942831, 4445492, 'EFETIVA_PROPOSTA', 'CONSIGNADO', 'INSERT', sysdate, null, null, null, null, null, conta_9942831_4445492);

    insert into tbgen_evento_soa(cdcooper, nrdconta, nrctrprp, tpevento, tproduto_evento, tpoperacao, dhoperacao, dsprocessamento, dsstatus, dhevento, dserro, nrtentativas, dsconteudo_requisicao) 
    values (1, 13440241, 4539828, 'EFETIVA_PROPOSTA', 'CONSIGNADO', 'INSERT', sysdate, null, null, null, null, null, conta_13440241_4539828); 

    insert into tbgen_evento_soa(cdcooper, nrdconta, nrctrprp, tpevento, tproduto_evento, tpoperacao, dhoperacao, dsprocessamento, dsstatus, dhevento, dserro, nrtentativas, dsconteudo_requisicao) 
    values (14, 278963, 39197, 'EFETIVA_PROPOSTA', 'CONSIGNADO', 'INSERT', sysdate, null, null, null, null, null, conta_278963_39197);

    commit;

EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;

end;