BEGIN
  UPDATE TBCRED_PEAC_CONTRATO
     SET TBCRED_PEAC_CONTRATO.CDSITUACAOHONRA    = 0
        ,TBCRED_PEAC_CONTRATO.DTSOLICITACAOHONRA = NULL
        ,TBCRED_PEAC_CONTRATO.VLSOLICITACAOHONRA = NULL
        ,TBCRED_PEAC_CONTRATO.VLSALDORECUPERAR   = NULL
   WHERE NRCONTRATO IN (2977711, 2987483)
     AND CDCOOPER = 1;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20500,SQLERRM);
    ROLLBACK;
END;
