BEGIN
    
  UPDATE CECRED.TBCONV_REGISTRO_REMESSA_PAGFOR PAG 
     SET PAG.CDSTATUS_PROCESSAMENTO = 3,
         PAG.DSPROCESSAMENTO = 'Aceito para processamento'
   WHERE PAG.IDSICREDI = 6130950;
   
  UPDATE CECRED.CRAPPRO
     SET DSPROTOC = SUBSTR(DSPROTOC, 1, LENGTH(DSPROTOC)-38)
   WHERE PROGRESS_RECID IN (
    SELECT PRO.PROGRESS_RECID
      FROM CECRED.CRAPLFT LFT
      INNER JOIN CECRED.CRAPPRO PRO on PRO.cdcooper = LFT.cdcooper AND PRO.nrdconta = LFT.nrdconta 
            AND PRO.dtmvtolt = LFT.dtmvtolt AND PRO.nrseqaut = LFT.nrautdoc
     WHERE LFT.IDSICRED = 6130950
       AND PRO.DSPROTOC LIKE '%ESTORN%'
   );

  UPDATE CECRED.CRAPPRO PRO
      SET PRO.DSCOMPROVANTE_PARCEIRO = 'LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KICAgICBTSVNCUi1TSVNURU1BIERFIElORk9STUFUSUNBIERPIFNJQ09PQiAgICAgCiAgIDA3LzExLzIwMjIgLSAyIFZJQSBDT01QUk9WQU5URSAtIDE1OjU0OjUzICAgCiAgICAgICAgREUgUEFHQU1FTlRPIERFIFNJTVBMRVMgTkFDSU9OQUwgICAgICAgIAoKICAgICAgICAgICAgICAgT1JJR0VNIERBIE9QRVJBQ0FPICAgICAgICAgICAgICAgCkJBTkNPOiA3NTYgLSBBRzogMDAwMSAtIEJBTkNPT0IgUEFCIC0gQUdFTkNJQSBCUgogICAgICBDQU5BTCBERSBQQUdBTUVOVE8gSU5URVJORVQgQkFOS0lORyAgICAgIAoKQUcuIEFSUkVDQURBRE9SOkNOQyA3NTYgQkFOQ08gQ09PUEVSQVRJVk8gQlJBU0lMCk9QRVJBQ0FPOi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4wNS8wMSAtIENPTlZFTklPUwpOQVRVUkVaQSBEQSBPUEVSQUNBTzouLi4uLi4uLi4uLi4uLi4uLi4uLkNSRURJVE8KTi4gREEgQVVURU5USUNBQ0FPOi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLjAwMDAxCg1DT0RJR08gREUgQkFSUkFTOiAgICAgICAgODU4MjAwMDAwMDAgODIxOTAzMjgyMjMKICAgICAgICAgICAgICAgICAgICAgICAgIDM0MDcwODIyMzA4IDA2MjM4NTUxMzEyCgoNREFUQSBQQUdBTUVOVE86Li4uLi4uLi4uLi4uLi4uLi4uLi4uLi4wNy8xMS8yMDIyClZBTE9SIFRPVEFMOi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi4uLi44MiwxOQotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQoKQVVURU5USUNBQ0FPOgpCQU5DT09CMDAwMTAwOCAwNzExMjIgMDU4IDAwMDAuLi4uLi4uODIsMTkgMDUwMQoNQ0k6NDQyMCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCg0xOThCMzE5NS1DMEEzLTQxOEUtQjVDMC0zRTBGRUQ0NEE2ODQKDQogICAgICBPVVZJRE9SSUEgQkFOQ08gU0lDT09COiAwODAwNjQ2NDAwMSAgICAgIAotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ=='
      WHERE PRO.CDCOOPER = 16
        AND PRO.NRDCONTA = 1073680
        AND PRO.DTMVTOLT = TO_DATE('04/11/2022', 'DD/MM/YYYY')
        AND PRO.VLDOCMTO = 82.19;
  
  COMMIT;
END;
