BEGIN
    
  UPDATE CECRED.TBCONV_REGISTRO_REMESSA_PAGFOR PAG 
     SET PAG.CDSTATUS_PROCESSAMENTO = 3,
         PAG.DSPROCESSAMENTO = 'Aceito para processamento'
   WHERE PAG.IDSICREDI = 6130950;
   
  UPDATE CECRED.CRAPPRO
     SET DSPROTOC = SUBSTR(DSPROTOC, 1, LENGTH(DSPROTOC)-38)
   WHERE PROGRESS_RECID IN (
    SELECT PRO.PROGRESS_RECID
      FROM CECRED.CRAPLFT LFT
      INNER JOIN CECRED.CRAPPRO PRO on PRO.cdcooper = LFT.cdcooper AND PRO.nrdconta = LFT.nrdconta 
            AND PRO.dtmvtolt = LFT.dtmvtolt AND PRO.nrseqaut = LFT.nrautdoc
     WHERE LFT.IDSICRED = 6130950
       AND PRO.DSPROTOC LIKE '%ESTORN%'
   );
  
  COMMIT;
END;
