UPDATE CRAPTTL 
   SET NMMAETTL = 'JOANA DARC DA SILVA'
     , NMPAITTL = 'MARCELO RIBEIRO DA SILVA'
 WHERE CDCOOPER = 1
   AND NRDCONTA = 11599049;
   
UPDATE CRAPASS 
   SET NMMAEPTL = 'JOANA DARC DA SILVA'
     , NMPAITL  = 'MARCELO RIBEIRO DA SILVA'
     , DSFILIAC = 'MARCELO RIBEIRO DA SILVA E JOANA DARC DA SILVA'
 WHERE CDCOOPER = 1
   AND NRDCONTA = 11599049;  

UPDATE CRAPTTL 
   SET NMMAETTL = 'RITA ESPINDOLA'
     , NMPAITTL = 'LEOPOLDO ESPINDOLA'
 WHERE CDCOOPER = 1
   AND NRDCONTA = 1838091;
   
UPDATE CRAPASS 
   SET NMMAEPTL = 'RITA ESPINDOLA'
     , NMPAITL  = 'LEOPOLDO ESPINDOLA'
     , DSFILIAC = 'LEOPOLDO ESPINDOLA E RITA ESPINDOLA'
 WHERE CDCOOPER = 1
   AND NRDCONTA = 1838091;   

UPDATE CRAPTTL 
   SET NMMAETTL = 'MARIA DAS GRACAS RODRIGUES'
     , NMPAITTL = 'GASPAR ANTONIO DRESCHA'
 WHERE CDCOOPER = 14
   AND NRDCONTA = 199150;
   
UPDATE CRAPASS 
   SET NMMAEPTL = 'MARIA DAS GRACAS RODRIGUES'
     , NMPAITL  = 'GASPAR ANTONIO DRESCHA'
     , DSFILIAC = 'GASPAR ANTONIO DRESCH E MARIA DAS GRACAS RODRIGUES'
 WHERE CDCOOPER = 14
   AND NRDCONTA = 199150;    

UPDATE CRAPTTL 
   SET NMMAETTL = 'GILDA ARTONI DE CARVALHO'
     , NMPAITTL = 'LOURENAO AUGUSTO THOMAZONI DE CARVALHO'
 WHERE CDCOOPER = 7
   AND NRDCONTA = 354112;
   
UPDATE CRAPASS 
   SET NMMAEPTL = 'GILDA ARTONI DE CARVALHO'
     , NMPAITL  = 'LOURENAO AUGUSTO THOMAZONI DE CARVALHO'
     , DSFILIAC = 'LOURENAO AUGUSTO THOMAZONI DE CARVALHO E GILDA ARTONI DE CARVALHO'
 WHERE CDCOOPER = 7
   AND NRDCONTA = 354112;  