CREATE TABLE PIX.TBPIX_PARTICIPANTE_SPI(
ID NUMBER NOT NULL,
ISPB NUMBER(15) NOT NULL,
NOME_PARTICIPANTE VARCHAR2(500) NOT NULL,
TIPO_PARTICIPANTE VARCHAR2(10) NOT NULL,
DATA_HORA_INICIO_OPERACAO DATE NOT NULL,
FLGATIVO NUMBER(1) NOT NULL,
PRIORIDADE NUMBER(10) default 0 NOT NULL);

-- Add comments to the table 
COMMENT ON TABLE PIX.TBPIX_PARTICIPANTE_SPI
  IS 'Tabela que conterá todas os participantes disponibilizados pelo banco central';
-- Add comments to the columns 
COMMENT ON COLUMN PIX.TBPIX_PARTICIPANTE_SPI.ISPB
  IS 'Identificador ISPB';
COMMENT ON COLUMN PIX.TBPIX_PARTICIPANTE_SPI.NOME_PARTICIPANTE
  IS 'Nome do participante';
COMMENT ON COLUMN PIX.TBPIX_PARTICIPANTE_SPI.TIPO_PARTICIPANTE
  IS 'Tipo do participantes';
COMMENT ON COLUMN PIX.TBPIX_PARTICIPANTE_SPI.DATA_HORA_INICIO_OPERACAO
  IS 'Data que inicio as operacao';
COMMENT ON COLUMN PIX.TBPIX_PARTICIPANTE_SPI.FLGATIVO
  IS 'Flag 0/1 de Participante Indireto 1 - Ativo ou 0 - Desativado';
COMMENT ON COLUMN PIX.TBPIX_PARTICIPANTE_SPI.PRIORIDADE
  IS 'Prioridade ';

CREATE UNIQUE INDEX PIX.TBPIX_PARTICIPANTE_SPI_IDX_01 on PIX.TBPIX_PARTICIPANTE_SPI (ISPB);
CREATE INDEX PIX.TBPIX_PARTICIPANTE_SPI_IDX_02 on PIX.TBPIX_PARTICIPANTE_SPI (ISPB, NOME_PARTICIPANTE);
CREATE INDEX PIX.TBPIX_PARTICIPANTE_SPI_IDX_03 on PIX.TBPIX_PARTICIPANTE_SPI (ISPB, NOME_PARTICIPANTE, PRIORIDADE);
CREATE INDEX PIX.TBPIX_PARTICIPANTE_SPI_IDX_04 on PIX.TBPIX_PARTICIPANTE_SPI (ISPB, NOME_PARTICIPANTE, TIPO_PARTICIPANTE);
CREATE INDEX PIX.TBPIX_PARTICIPANTE_SPI_IDX_05 on PIX.TBPIX_PARTICIPANTE_SPI (ISPB, NOME_PARTICIPANTE, TIPO_PARTICIPANTE, PRIORIDADE);

ALTER TABLE PIX.TBPIX_PARTICIPANTE_SPI ADD CONSTRAINT TBPIX_PARTICIPANTE_SPI_PK PRIMARY KEY (ID);

-- Create sequence 
create sequence PIX.TBPIX_PARTICIPANTE_SPI_SEQ
minvalue 1
maxvalue 9999999999999999999999999999
start with 10
increment by 1
nocache
order;

CREATE OR REPLACE TRIGGER PIX.TBPIX_PARTICIPANTE_SPI_trg_01 BEFORE
    INSERT ON pix.TBPIX_PARTICIPANTE_SPI
    FOR EACH ROW
    WHEN ( new.ID IS NULL )
BEGIN
    :new.ID := pix.TBPIX_PARTICIPANTE_SPI_SEQ.nextval;
END;

commit;
