BEGIN
	
	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (815, 1, 999, 'ENVIO DO ARQUIVO PRESTAMISTA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 1);
	
	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (815, 1, 999, 'ENVIO DO ARQUIVO PRESTAMISTA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 2);
	
	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (815, 1, 999, 'ENVIO DO ARQUIVO PRESTAMISTA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 3);
	
	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (815, 1, 999, 'ENVIO DO ARQUIVO PRESTAMISTA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 4);
	
	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (815, 1, 999, 'ENVIO DO ARQUIVO PRESTAMISTA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 5);
	
	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (815, 1, 999, 'ENVIO DO ARQUIVO PRESTAMISTA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 6);
	
	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (815, 1, 999, 'ENVIO DO ARQUIVO PRESTAMISTA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 7);
	
	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (815, 1, 999, 'ENVIO DO ARQUIVO PRESTAMISTA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 8);
	
	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (815, 1, 999, 'ENVIO DO ARQUIVO PRESTAMISTA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 9);
	
	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (815, 1, 999, 'ENVIO DO ARQUIVO PRESTAMISTA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 10);
	
	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (815, 1, 999, 'ENVIO DO ARQUIVO PRESTAMISTA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 11);
	
	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (815, 1, 999, 'ENVIO DO ARQUIVO PRESTAMISTA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 12);
	
	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (815, 1, 999, 'ENVIO DO ARQUIVO PRESTAMISTA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 13);
	
	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (815, 1, 999, 'ENVIO DO ARQUIVO PRESTAMISTA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 14);
	
	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (815, 1, 999, 'ENVIO DO ARQUIVO PRESTAMISTA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 15);
	
	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (815, 1, 999, 'ENVIO DO ARQUIVO PRESTAMISTA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 16);
	
	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (815, 1, 999, 'ENVIO DO ARQUIVO PRESTAMISTA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 17);
	
	-- NAO PRESTAMISTA
	
	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (816, 1, 999, 'PRESTAMISTA CRIADO POSTERIOR AO EMP. PELO SISTEMA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 1);

	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (816, 1, 999, 'PRESTAMISTA CRIADO POSTERIOR AO EMP. PELO SISTEMA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 2);

	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (816, 1, 999, 'PRESTAMISTA CRIADO POSTERIOR AO EMP. PELO SISTEMA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 3);

	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (816, 1, 999, 'PRESTAMISTA CRIADO POSTERIOR AO EMP. PELO SISTEMA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 4);

	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (816, 1, 999, 'PRESTAMISTA CRIADO POSTERIOR AO EMP. PELO SISTEMA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 5);

	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (816, 1, 999, 'PRESTAMISTA CRIADO POSTERIOR AO EMP. PELO SISTEMA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 6);

	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (816, 1, 999, 'PRESTAMISTA CRIADO POSTERIOR AO EMP. PELO SISTEMA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 7);

	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (816, 1, 999, 'PRESTAMISTA CRIADO POSTERIOR AO EMP. PELO SISTEMA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 8);

	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (816, 1, 999, 'PRESTAMISTA CRIADO POSTERIOR AO EMP. PELO SISTEMA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 9);

	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (816, 1, 999, 'PRESTAMISTA CRIADO POSTERIOR AO EMP. PELO SISTEMA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 10);

	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (816, 1, 999, 'PRESTAMISTA CRIADO POSTERIOR AO EMP. PELO SISTEMA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 11);

	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (816, 1, 999, 'PRESTAMISTA CRIADO POSTERIOR AO EMP. PELO SISTEMA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 12);

	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (816, 1, 999, 'PRESTAMISTA CRIADO POSTERIOR AO EMP. PELO SISTEMA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 13);

	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (816, 1, 999, 'PRESTAMISTA CRIADO POSTERIOR AO EMP. PELO SISTEMA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 14);

	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (816, 1, 999, 'PRESTAMISTA CRIADO POSTERIOR AO EMP. PELO SISTEMA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 15);

	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (816, 1, 999, 'PRESTAMISTA CRIADO POSTERIOR AO EMP. PELO SISTEMA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 16);

	insert into craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL, CDFILREL, NRSEQPRI, CDCOOPER)
	values (816, 1, 999, 'PRESTAMISTA CRIADO POSTERIOR AO EMP. PELO SISTEMA', 1, 'PRESTAMISTA', '234col', 0, 'Diario', 1, 1, 1, ' ', null, null, 17);

	COMMIT;
END;