BEGIN
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO)  VALUES ('OPERACAO_ADM_CDMOTIVO', '1','Defeito',1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO)  VALUES ('OPERACAO_ADM_CDMOTIVO', '2','Perda/Roubo',1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO)  VALUES ('OPERACAO_ADM_CDMOTIVO', '3','Pelo socio',1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO)  VALUES ('OPERACAO_ADM_CDMOTIVO', '4','Pela COOP',1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO)  VALUES ('OPERACAO_ADM_CDMOTIVO', '5','Cancelado',1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO)  VALUES ('OPERACAO_ADM_CDMOTIVO', '6','Por fraude',1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO)  VALUES ('OPERACAO_ADM_CDMOTIVO', '7','Alt.Dt.Venc',1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO)  VALUES ('OPERACAO_ADM_CDMOTIVO', '8','Comprometido',1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO)  VALUES ('OPERACAO_ADM_CDMOTIVO', '9','Devolvido/Destruido',1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO)  VALUES ('OPERACAO_ADM_CDMOTIVO', '10','Reposto/Reimpresso',1);
  INSERT INTO TBCRD_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO, INATIVO)  VALUES ('OPERACAO_ADM_CDMOTIVO', '11','Extraviado',1);
  COMMIT;
END;  