BEGIN
  UPDATE CECRED.crapprg p
     SET p.NRSOLICI = 86
        ,p.INLIBPRG = 1
   WHERE p.CDPROGRA = 'CRPS413'
     AND p.INLIBPRG = 2
     AND p.CDCOOPER <> 3;

  UPDATE CECRED.crapprg p
     SET p.NRSOLICI = 999
        ,p.INLIBPRG = 1
   WHERE p.CDPROGRA = 'CRPS413'
     AND p.INLIBPRG = 2
     AND p.CDCOOPER = 3;

  UPDATE CECRED.crapprg 
     SET NRSOLICI = 86
        ,INLIBPRG = 1
    WHERE CDPROGRA = 'CRPS457'
      AND CDCOOPER <> 3;

  UPDATE CECRED.crapprg 
     SET NRSOLICI = 999
        ,INLIBPRG = 1
    WHERE CDPROGRA = 'CRPS457'
      AND CDCOOPER = 3;
  
  UPDATE CECRED.CRAPPRG
     SET NRSOLICI = 82, INLIBPRG = 1
   WHERE CDPROGRA = 'CRPS253'
     AND CDCOOPER = 1;
  UPDATE CECRED.CRAPPRG
     SET NRSOLICI = 82, INLIBPRG = 1
   WHERE CDPROGRA = 'CRPS253'
     AND CDCOOPER = 2;
  UPDATE CECRED.CRAPPRG
     SET NRSOLICI = 999, INLIBPRG = 1
   WHERE CDPROGRA = 'CRPS253'
     AND CDCOOPER = 3;
  UPDATE CECRED.CRAPPRG
     SET NRSOLICI = 82, INLIBPRG = 1
   WHERE CDPROGRA = 'CRPS253'
     AND CDCOOPER = 5;
  UPDATE CECRED.CRAPPRG
     SET NRSOLICI = 82, INLIBPRG = 1
   WHERE CDPROGRA = 'CRPS253'
     AND CDCOOPER = 6;
  UPDATE CECRED.CRAPPRG
     SET NRSOLICI = 82, INLIBPRG = 1
   WHERE CDPROGRA = 'CRPS253'
     AND CDCOOPER = 7;
  UPDATE CECRED.CRAPPRG
     SET NRSOLICI = 82, INLIBPRG = 1
   WHERE CDPROGRA = 'CRPS253'
     AND CDCOOPER = 8;
  UPDATE CECRED.CRAPPRG
     SET NRSOLICI = 82, INLIBPRG = 1
   WHERE CDPROGRA = 'CRPS253'
     AND CDCOOPER = 9;
  UPDATE CECRED.CRAPPRG
     SET NRSOLICI = 82, INLIBPRG = 1
   WHERE CDPROGRA = 'CRPS253'
     AND CDCOOPER = 10;
  UPDATE CECRED.CRAPPRG
     SET NRSOLICI = 82, INLIBPRG = 1
   WHERE CDPROGRA = 'CRPS253'
     AND CDCOOPER = 11;
  UPDATE CECRED.CRAPPRG
     SET NRSOLICI = 82, INLIBPRG = 1
   WHERE CDPROGRA = 'CRPS253'
     AND CDCOOPER = 12;
  UPDATE CECRED.CRAPPRG
     SET NRSOLICI = 82, INLIBPRG = 1
   WHERE CDPROGRA = 'CRPS253'
     AND CDCOOPER = 13;
  UPDATE CECRED.CRAPPRG
     SET NRSOLICI = 82, INLIBPRG = 1
   WHERE CDPROGRA = 'CRPS253'
     AND CDCOOPER = 14;
  UPDATE CECRED.CRAPPRG
     SET NRSOLICI = 82, INLIBPRG = 1
   WHERE CDPROGRA = 'CRPS253'
     AND CDCOOPER = 16;

  COMMIT;
END;
