-- VIACREDI
INSERT INTO crapprm (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM)
 VALUES('CRED', 1, 'PROCESSO_COMPFORA', 'Indicado de execucao do processo COMPFORA', TO_CHAR(SYSDATE - 1,'dd/mm/RRRR') || '#1');
 
-- ACREDICOOP
INSERT INTO crapprm (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM)
 VALUES('CRED', 2, 'PROCESSO_COMPFORA', 'Indicado de execucao do processo COMPFORA', TO_CHAR(SYSDATE - 1,'dd/mm/RRRR') || '#1');
 
-- CONCREDI
INSERT INTO crapprm (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM)
 VALUES('CRED', 4, 'PROCESSO_COMPFORA', 'Indicado de execucao do processo COMPFORA', TO_CHAR(SYSDATE - 1,'dd/mm/RRRR') || '#1');
 
-- ACENTRA
INSERT INTO crapprm (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM)
 VALUES('CRED', 5, 'PROCESSO_COMPFORA', 'Indicado de execucao do processo COMPFORA', TO_CHAR(SYSDATE - 1,'dd/mm/RRRR') || '#1');
 
-- UNILOS
INSERT INTO crapprm (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM)
 VALUES('CRED', 6, 'PROCESSO_COMPFORA', 'Indicado de execucao do processo COMPFORA', TO_CHAR(SYSDATE - 1,'dd/mm/RRRR') || '#1');
 
-- CREDCREA
INSERT INTO crapprm (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM)
 VALUES('CRED', 7, 'PROCESSO_COMPFORA', 'Indicado de execucao do processo COMPFORA', TO_CHAR(SYSDATE - 1,'dd/mm/RRRR') || '#1');
 
-- CREDELESC
INSERT INTO crapprm (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM)
 VALUES('CRED', 8, 'PROCESSO_COMPFORA', 'Indicado de execucao do processo COMPFORA', TO_CHAR(SYSDATE - 1,'dd/mm/RRRR') || '#1');
 
-- TRANSPOCRED
INSERT INTO crapprm (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM)
 VALUES('CRED', 9, 'PROCESSO_COMPFORA', 'Indicado de execucao do processo COMPFORA', TO_CHAR(SYSDATE - 1,'dd/mm/RRRR') || '#1');
 
-- CREDICOMIN
INSERT INTO crapprm (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM)
 VALUES('CRED', 10, 'PROCESSO_COMPFORA', 'Indicado de execucao do processo COMPFORA', TO_CHAR(SYSDATE - 1,'dd/mm/RRRR') || '#1');
 
-- CREDIFOZ
INSERT INTO crapprm (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM)
 VALUES('CRED', 11, 'PROCESSO_COMPFORA', 'Indicado de execucao do processo COMPFORA', TO_CHAR(SYSDATE - 1,'dd/mm/RRRR') || '#1');
 
-- CREVISC
INSERT INTO crapprm (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM)
 VALUES('CRED', 12, 'PROCESSO_COMPFORA', 'Indicado de execucao do processo COMPFORA', TO_CHAR(SYSDATE - 1,'dd/mm/RRRR') || '#1');
 
-- CIVIA
INSERT INTO crapprm (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM)
 VALUES('CRED', 13, 'PROCESSO_COMPFORA', 'Indicado de execucao do processo COMPFORA', TO_CHAR(SYSDATE - 1,'dd/mm/RRRR') || '#1');
 
-- EVOLUA
INSERT INTO crapprm (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM)
 VALUES('CRED', 14, 'PROCESSO_COMPFORA', 'Indicado de execucao do processo COMPFORA', TO_CHAR(SYSDATE - 1,'dd/mm/RRRR') || '#1');
 
-- CREDIMILSUL
INSERT INTO crapprm (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM)
 VALUES('CRED', 15, 'PROCESSO_COMPFORA', 'Indicado de execucao do processo COMPFORA', TO_CHAR(SYSDATE - 1,'dd/mm/RRRR') || '#1');
 
-- VIACREDI AV
INSERT INTO crapprm (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM)
 VALUES('CRED', 16, 'PROCESSO_COMPFORA', 'Indicado de execucao do processo COMPFORA', TO_CHAR(SYSDATE - 1,'dd/mm/RRRR') || '#1');
 
-- TRANSULCRED
INSERT INTO crapprm (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM)
 VALUES('CRED', 17, 'PROCESSO_COMPFORA', 'Indicado de execucao do processo COMPFORA', TO_CHAR(SYSDATE - 1,'dd/mm/RRRR') || '#1');

COMMIT;