insert into menumobile (MENUMOBILEID, MENUPAIID, NOME, SEQUENCIA, HABILITADO, AUTORIZACAO, VERSAOMINIMAAPP, VERSAOMAXIMAAPP)
values (1022, 1009, 'Serviços de Atendimento Pix', 1, 1, 1, '2.19.0', null);
COMMIT;
