BEGIN
  DELETE FROM recuperacao.tbrecup_hist_lancamento_futuro;
  INSERT INTO recuperacao.tbrecup_hist_lancamento_futuro(cdhistor, nmestrut) VALUES (1441, 'CRAPLAT');
  INSERT INTO recuperacao.tbrecup_hist_lancamento_futuro(cdhistor, nmestrut) VALUES (1465, 'CRAPLAT');
  INSERT INTO recuperacao.tbrecup_hist_lancamento_futuro(cdhistor, nmestrut) VALUES (1215, 'CRAPLAT');
  INSERT INTO recuperacao.tbrecup_hist_lancamento_futuro(cdhistor, nmestrut) VALUES (1188, 'CRAPLAT');
  INSERT INTO recuperacao.tbrecup_hist_lancamento_futuro(cdhistor, nmestrut) VALUES (1219, 'CRAPLAT');
  INSERT INTO recuperacao.tbrecup_hist_lancamento_futuro(cdhistor, nmestrut) VALUES (1208, 'CRAPLAT');
  INSERT INTO recuperacao.tbrecup_hist_lancamento_futuro(cdhistor, nmestrut) VALUES (1493, 'CRAPLAT');
  INSERT INTO recuperacao.tbrecup_hist_lancamento_futuro(cdhistor, nmestrut) VALUES (2084, 'CRAPLAU');
  INSERT INTO recuperacao.tbrecup_hist_lancamento_futuro(cdhistor, nmestrut) VALUES (2087, 'CRAPLAU');
  INSERT INTO recuperacao.tbrecup_hist_lancamento_futuro(cdhistor, nmestrut) VALUES (2093, 'CRAPLAU');
  INSERT INTO recuperacao.tbrecup_hist_lancamento_futuro(cdhistor, nmestrut) VALUES (2090, 'CRAPLAU');
  COMMIT;
END;