BEGIN
  INSERT INTO recuperacao.tbrecup_hist_lancamento_futuro(cdhistor, nmestrut) VALUES (1441, 'CRAPLAT');
  INSERT INTO recuperacao.tbrecup_hist_lancamento_futuro(cdhistor, nmestrut) VALUES (1465, 'CRAPLAT');
  INSERT INTO recuperacao.tbrecup_hist_lancamento_futuro(cdhistor, nmestrut) VALUES (1215, 'CRAPLAT');
  INSERT INTO recuperacao.tbrecup_hist_lancamento_futuro(cdhistor, nmestrut) VALUES (1188, 'CRAPLAT');
  INSERT INTO recuperacao.tbrecup_hist_lancamento_futuro(cdhistor, nmestrut) VALUES (1219, 'CRAPLAT');
  INSERT INTO recuperacao.tbrecup_hist_lancamento_futuro(cdhistor, nmestrut) VALUES (1208, 'CRAPLAT');
  INSERT INTO recuperacao.tbrecup_hist_lancamento_futuro(cdhistor, nmestrut) VALUES (1493, 'CRAPLAT');
  COMMIT;
END;