declare
begin  
  MERGE INTO PIX.TBPIX_LIMITE_COOPERADO t1
  USING (SELECT crapsnh.CDCOOPER, crapsnh.NRDCONTA, crapsnh.IDSEQTTL, crapsnh.VLLIMTED FROM cecred.crapsnh crapsnh 
  INNER JOIN CECRED.CRAPASS CRAPASS ON CRAPASS.CDCOOPER = crapsnh.CDCOOPER AND CRAPASS.NRDCONTA = crapsnh.NRDCONTA AND CRAPASS.INPESSOA = 1
  WHERE crapsnh.TPDSENHA = 1) t2
  ON (t1.CDCOOPER = t2.CDCOOPER AND t1.NRDCONTA = t2.NRDCONTA AND t1.IDSEQTTL = t2.IDSEQTTL AND t1.IDTIPO_LIMITE = 4 AND t1.IDPERIODO = 1 AND t1.FLPOR_TRANSACAO = 0 AND t1.CDSITUACAO = 1)
  WHEN NOT MATCHED THEN
    INSERT (t1.CDCOOPER, t1.NRDCONTA, t1.IDSEQTTL, t1.IDTIPO_LIMITE, t1.IDPERIODO, t1.FLPOR_TRANSACAO, t1.DHREGISTRO, t1.DHEFETIVACAO, t1.CDSITUACAO, t1.VLLIMITE)
    VALUES(t2.CDCOOPER, t2.NRDCONTA, t2.IDSEQTTL, 4, 1, 0, sysdate, sysdate, 1, COALESCE(t2.VLLIMTED, 0));  
  
  MERGE INTO PIX.TBPIX_LIMITE_COOPERADO t1
  USING (
    SELECT CDCOOPER, NRDCONTA, IDSEQTTL, IDTIPO_LIMITE, IDPERIODO, FLPOR_TRANSACAO, VLLIMITE
    FROM PIX.TBPIX_LIMITE_COOPERADO
    WHERE IDTIPO_LIMITE = 4 AND IDPERIODO = 1 AND FLPOR_TRANSACAO = 0 AND CDSITUACAO = 1
  ) t2
  ON (t1.CDCOOPER = t2.CDCOOPER AND t1.NRDCONTA = t2.NRDCONTA AND t1.IDSEQTTL = t2.IDSEQTTL AND t1.IDTIPO_LIMITE = t2.IDTIPO_LIMITE AND t1.IDPERIODO = 2 AND t1.FLPOR_TRANSACAO = 0 AND t1.CDSITUACAO = 1)
  WHEN NOT MATCHED THEN
    INSERT (t1.CDCOOPER, t1.NRDCONTA, t1.IDSEQTTL, t1.IDTIPO_LIMITE, t1.IDPERIODO, t1.FLPOR_TRANSACAO, t1.DHREGISTRO, t1.DHEFETIVACAO, t1.CDSITUACAO, t1.VLLIMITE)
    VALUES(t2.CDCOOPER, t2.NRDCONTA, t2.IDSEQTTL, t2.IDTIPO_LIMITE, 2, 0, sysdate, sysdate, 1, (SELECT CASE WHEN COALESCE(t2.VLLIMITE,0) > 1000 THEN 1000 ELSE COALESCE(t2.VLLIMITE,0) END FROM dual));

  commit;
end;