BEGIN

  INSERT   INTO CECRED.TBCONV_LIBERACAO(TPARRECADACAO, CDCOOPER, CDEMPRES, CDCONVEN, FLGAUTDB)
  SELECT 3, coop.cdcooper, 0, 248, 1 FROM CECRED.crapcop coop;

  INSERT   INTO CECRED.TBCONV_LIBERACAO(TPARRECADACAO, CDCOOPER, CDEMPRES, CDCONVEN, FLGAUTDB)
  SELECT 3, coop.cdcooper, 0, 246, 1 FROM CECRED.crapcop coop;

  COMMIT;
END;	