DECLARE
  CURSOR cr_crapass(pr_cdcooper IN cecred.crapass.cdcooper%TYPE
                   ,pr_progress IN cecred.crapass.progress_recid%TYPE) IS
    SELECT a.nrdconta 
      FROM cecred.crapass a
     WHERE a.cdcooper = pr_cdcooper
       AND a.progress_recid = pr_progress;
  rw_crapass cr_crapass%ROWTYPE;
  
BEGIN
OPEN cr_crapass(pr_cdcooper => 	1	 ,pr_progress => 	1361681	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	1	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	343.82	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	343.82	WHERE cdcooper = 	1	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;
OPEN cr_crapass(pr_cdcooper => 	1	 ,pr_progress => 	1399276	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	1	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	57.65	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	57.65	WHERE cdcooper = 	1	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;
OPEN cr_crapass(pr_cdcooper => 	1	 ,pr_progress => 	1045843	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	1	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	389.62	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	389.62	WHERE cdcooper = 	1	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;
OPEN cr_crapass(pr_cdcooper => 	1	 ,pr_progress => 	1295283	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	1	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	678.1	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	678.1	WHERE cdcooper = 	1	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;
OPEN cr_crapass(pr_cdcooper => 	1	 ,pr_progress => 	1466819	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	1	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	121.45	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	121.45	WHERE cdcooper = 	1	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;
OPEN cr_crapass(pr_cdcooper => 	1	 ,pr_progress => 	1279721	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	1	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	241.75	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	241.75	WHERE cdcooper = 	1	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;
OPEN cr_crapass(pr_cdcooper => 	1	 ,pr_progress => 	1151052	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	1	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	239.91	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	239.91	WHERE cdcooper = 	1	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;
OPEN cr_crapass(pr_cdcooper => 	1	 ,pr_progress => 	1354039	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	1	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	1804.28	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	1804.28	WHERE cdcooper = 	1	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;
OPEN cr_crapass(pr_cdcooper => 	1	 ,pr_progress => 	757950	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	1	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	69.25	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	69.25	WHERE cdcooper = 	1	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;
OPEN cr_crapass(pr_cdcooper => 	1	 ,pr_progress => 	1153371	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	1	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	26.47	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	26.47	WHERE cdcooper = 	1	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;
OPEN cr_crapass(pr_cdcooper => 	1	 ,pr_progress => 	852360	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	1	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	0.63	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	0.63	WHERE cdcooper = 	1	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;
OPEN cr_crapass(pr_cdcooper => 	1	 ,pr_progress =>    844652	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	1	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	53.9	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	53.9	WHERE cdcooper = 	1	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;
OPEN cr_crapass(pr_cdcooper => 	1	 ,pr_progress => 	1300714	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	1	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	0.01	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	0.01	WHERE cdcooper = 	1	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;
OPEN cr_crapass(pr_cdcooper => 	16	 ,pr_progress => 	880539	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	16	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	242.17	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	242.17	WHERE cdcooper = 	16	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;
OPEN cr_crapass(pr_cdcooper => 	16	 ,pr_progress => 	523875	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	16	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	799.91	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	799.91	WHERE cdcooper = 	16	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;

COMMIT;

END;
