begin
create index CECRED.CRAPHIS##CRAPHIS4 on CECRED.CRAPHIS("CDHISTOR","DSHISTOR") ONLINE PARALLEL 16;
ALTER INDEX CECRED.CRAPHIS##CRAPHIS4 NOPARALLEL;

create index CECRED.CRAPFVL##CRAPFVL5 on CECRED.CRAPFVL("CDHISTOR","CDFAIXAV","CDTARIFA") ONLINE PARALLEL 16;
ALTER INDEX CECRED.CRAPFVL##CRAPFVL5 NOPARALLEL;

create index CECRED.CRAPSGR##CRAPSGR3 on CECRED.CRAPSGR("CDDGRUPO","CDSUBGRU") ONLINE PARALLEL 16;
ALTER INDEX CECRED.CRAPSGR##CRAPSGR3 NOPARALLEL;

create index CECRED.CRAPFCO##CRAPFCO4 on CECRED.CRAPFCO("FLGVIGEN","CDFAIXAV") ONLINE PARALLEL 16;
ALTER INDEX CECRED.CRAPFCO##CRAPFCO4 NOPARALLEL;
commit;
end;