DECLARE
  CURSOR cr_crapass(pr_cdcooper IN cecred.crapass.cdcooper%TYPE
                   ,pr_progress IN cecred.crapass.progress_recid%TYPE) IS
    SELECT a.nrdconta 
      FROM cecred.crapass a
     WHERE a.cdcooper = pr_cdcooper
       AND a.progress_recid = pr_progress;
  rw_crapass cr_crapass%ROWTYPE;
  
BEGIN
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	1031905	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  0.04  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  0.04  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	822602	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  0.95  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  0.95  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	12	 ,pr_progress =>  	547912	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	12	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	  3.90  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	  3.90  	WHERE cdcooper = 	12	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	1133178	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  5.70  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  5.70  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	12	 ,pr_progress =>  	1129619	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	12	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	  9.07  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	  9.07  	WHERE cdcooper = 	12	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	12	 ,pr_progress =>  	1332535	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	12	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	  9.32  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	  9.32  	WHERE cdcooper = 	12	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	12	 ,pr_progress =>  	1094186	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	12	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	  9.40  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	  9.40  	WHERE cdcooper = 	12	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	710015	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  10.56  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  10.56  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	12	 ,pr_progress =>  	931981	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	12	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	  10.57  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	  10.57  	WHERE cdcooper = 	12	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	950435	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  10.65  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  10.65  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	814827	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  11.04  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  11.04  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	12	 ,pr_progress =>  	930797	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	12	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	  11.81  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	  11.81  	WHERE cdcooper = 	12	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	1336545	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  12.20  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  12.20  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	12	 ,pr_progress =>  	890543	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	12	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	  12.25  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	  12.25  	WHERE cdcooper = 	12	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	12	 ,pr_progress =>  	1271311	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	12	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	  12.26  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	  12.26  	WHERE cdcooper = 	12	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	12	 ,pr_progress =>  	1160285	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	12	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	  12.29  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	  12.29  	WHERE cdcooper = 	12	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	917053	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  12.50  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  12.50  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	968814	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  12.84  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  12.84  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	12	 ,pr_progress =>  	1197094	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	12	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	  12.95  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	  12.95  	WHERE cdcooper = 	12	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	939606	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  13.02  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  13.02  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	894133	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  13.19  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  13.19  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	793510	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  13.21  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  13.21  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	14	 ,pr_progress =>  	1126740	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	14	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  13.49  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  13.49  	WHERE cdcooper = 	14	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	565146	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  13.81  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  13.81  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	958277	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  14.06  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  14.06  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	881238	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  14.22  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  14.22  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	1148456	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  14.25  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  14.25  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	12	 ,pr_progress =>  	938915	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	12	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	  14.58  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	  14.58  	WHERE cdcooper = 	12	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	1138681	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  14.85  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  14.85  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	593577	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  14.98  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  14.98  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	731361	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  15.16  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  15.16  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	16	 ,pr_progress =>  	619369	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	16	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  15.49  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  15.49  	WHERE cdcooper = 	16	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	796790	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  15.64  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  15.64  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	845820	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  15.72  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  15.72  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	466236	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  15.76  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  15.76  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	917078	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  16.15  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  16.15  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	888607	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  16.79  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  16.79  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	888607	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	  16.79  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	  16.79  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	1094091	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  16.86  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  16.86  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	932223	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  16.91  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  16.91  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	995339	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  20.93  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  20.93  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	1566342	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  26.26  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  26.26  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	1094344	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  29.84  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  29.84  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	951114	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  31.06  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  31.06  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	917710	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  31.54  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  31.54  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	1469926	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  38.87  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  38.87  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	611321	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  40.47  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  40.47  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	863161	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  46.01  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  46.01  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	1020425	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  48.16  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  48.16  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	1080314	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  57.24  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  57.24  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	977131	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  63.84  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  63.84  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	14	 ,pr_progress =>  	1150493	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	14	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  69.41  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  69.41  	WHERE cdcooper = 	14	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	743191	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  70.61  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  70.61  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	726286	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2408	and vllanmto = 	  220.92  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  220.92  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	8	 ,pr_progress =>  	927339	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	8	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2721	and vllanmto = 	  1200.00  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	  1200.00  	WHERE cdcooper = 	8	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	1	 ,pr_progress =>  	876934	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	1	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2722	and vllanmto = 	  1585.40  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	                                                                                                                                    END IF; CLOSE cr_crapass;									
OPEN cr_crapass(pr_cdcooper => 	1	 ,pr_progress =>  	1565927	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	1	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2722	and vllanmto = 	  2176.04  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  2176.04  	WHERE cdcooper = 	1	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	1	 ,pr_progress =>  	1565927	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	1	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2719	and vllanmto = 	  2176.04  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	+	  2176.04  	WHERE cdcooper = 	1	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			
OPEN cr_crapass(pr_cdcooper => 	1	 ,pr_progress =>  	1565927	);	FETCH cr_crapass INTO rw_crapass;	IF cr_crapass%FOUND THEN	delete from tbcc_prejuizo_detalhe where cdcooper =	1	and nrdconta = rw_crapass.nrdconta and cdhistor = 	2738	and vllanmto = 	  2176.04  	and dtmvtolt = to_date('', 'dd/mm/rrrr');	UPDATE tbcc_prejuizo SET vlsdprej = Nvl(vlsdprej, 0) 	-	  2176.04  	WHERE cdcooper = 	1	AND nrdconta = rw_crapass.nrdconta;	END IF; CLOSE cr_crapass;			

COMMIT;

END;
