BEGIN

UPDATE	CECRED.TBGRV_REGISTRO_CONTRATO
SET	CDSITUACAO_CONTRATO = 0
WHERE	IDREGISTRO_CONTRATO = 632567;

COMMIT;

EXCEPTION WHEN OTHERS THEN
	ROLLBACK;
    RAISE_APPLICATION_ERROR(-20000, 'ERRO ' || SQLERRM);
END;