BEGIN

UPDATE CREDITO.Tbcred_Proposta_Perda_Esperada
SET    CDESTAGIO_CONCESSAO = DECODE(CDESTAGIO_CONCESSAO,'B','2','C','3','1')
WHERE  CDESTAGIO_CONCESSAO NOT IN ('1','2','3');

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20000, 'ERRO ' || SQLERRM);
    ROLLBACK;
END;
