BEGIN

UPDATE CECRED.TBCADAST_EMPRESA_CONSIG EC SET EC.CDCANALGESTAOPAG = 1
WHERE EC.CDCANALGESTAOPAG = 2;

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20000, 'ERRO ' || SQLERRM);
    ROLLBACK;
END;