BEGIN
INSERT INTO CECRED.MENUMOBILE (MENUMOBILEID, MENUPAIID, NOME, SEQUENCIA, HABILITADO, AUTORIZACAO, VERSAOMINIMAAPP, VERSAOMAXIMAAPP, FLAVALIACAO)
VALUES (1054, 1053, 'Ler um QRCode', 1, 1, 1, '2.63.0', null, 0);

INSERT INTO CECRED.MENUMOBILE (MENUMOBILEID, MENUPAIID, NOME, SEQUENCIA, HABILITADO, AUTORIZACAO, VERSAOMINIMAAPP, VERSAOMAXIMAAPP, FLAVALIACAO)
VALUES (1055, 1053, 'Pix copia e cola', 1, 1, 1, '2.63.0', null, 0);

INSERT INTO CECRED.MENUMOBILE (MENUMOBILEID, MENUPAIID, NOME, SEQUENCIA, HABILITADO, AUTORIZACAO, VERSAOMINIMAAPP, VERSAOMAXIMAAPP, FLAVALIACAO)
VALUES (1056, 1053, 'Autorizações de pagamentos', 1, 1, 1, '2.63.0', null, 0);

INSERT INTO CECRED.MENUMOBILE (MENUMOBILEID, MENUPAIID, NOME, SEQUENCIA, HABILITADO, AUTORIZACAO, VERSAOMINIMAAPP, VERSAOMAXIMAAPP, FLAVALIACAO)
VALUES (1057, 1053, 'Pagamentos agendados', 1, 1, 1, '2.63.0', null, 0);

INSERT INTO CECRED.MENUMOBILE (MENUMOBILEID, MENUPAIID, NOME, SEQUENCIA, HABILITADO, AUTORIZACAO, VERSAOMINIMAAPP, VERSAOMAXIMAAPP, FLAVALIACAO)
VALUES (1058, 1053, 'Configurações', 1, 1, 1, '2.63.0', null, 0);

INSERT INTO CECRED.MENUMOBILE (MENUMOBILEID, MENUPAIID, NOME, SEQUENCIA, HABILITADO, AUTORIZACAO, VERSAOMINIMAAPP, VERSAOMAXIMAAPP, FLAVALIACAO)
VALUES (1059, 1053, 'Sobre o PIx Automático', 1, 1, 1, '2.63.0', null, 0);
COMMIT;
END;