begin

insert into credito.tbcred_preaprovado_cooperado (IDPREAPROVADO, CDCARGA, CDCOOPER, TPCARGA, CDPRODUTO, TPPESSOA, NRCPFCNPJ_BASE, CDLCREMP, VLPOT_PARC_MAXIMO, VLPOT_LIM_MAX, DSFAIXARISCO, PEPROBABILIDADE_DEFAULT_12, PEPROBABILIDADE_DEFAULT_LIFETIME, PEPERDA_ESPERADA_CONCESSAO, TPSCORE, NRSCORE_CREDITO, TPPOLITICA_CONCESSAO)
values (74, 3851, 2, 1, 11, 1, 13431583970, 30, 1, 700, 'R21', 1, 1, 1, 1, 1, null);

insert into credito.tbcred_preaprovado_cooperado (IDPREAPROVADO, CDCARGA, CDCOOPER, TPCARGA, CDPRODUTO, TPPESSOA, NRCPFCNPJ_BASE, CDLCREMP, VLPOT_PARC_MAXIMO, VLPOT_LIM_MAX, DSFAIXARISCO, PEPROBABILIDADE_DEFAULT_12, PEPROBABILIDADE_DEFAULT_LIFETIME, PEPERDA_ESPERADA_CONCESSAO, TPSCORE, NRSCORE_CREDITO, TPPOLITICA_CONCESSAO)
values (74, 3851, 2, 1, 11, 1, 10566553481, 30, 1, 1000, 'R21', 1, 1, 1, 1, 1, null);

insert into credito.tbcred_preaprovado_cooperado (IDPREAPROVADO, CDCARGA, CDCOOPER, TPCARGA, CDPRODUTO, TPPESSOA, NRCPFCNPJ_BASE, CDLCREMP, VLPOT_PARC_MAXIMO, VLPOT_LIM_MAX, DSFAIXARISCO, PEPROBABILIDADE_DEFAULT_12, PEPROBABILIDADE_DEFAULT_LIFETIME, PEPERDA_ESPERADA_CONCESSAO, TPSCORE, NRSCORE_CREDITO, TPPOLITICA_CONCESSAO)
values (74, 3851, 2, 1, 11, 1, 83570233987, 30, 1, 2000, 'R21', 1, 1, 1, 1, 1, null);

insert into credito.tbcred_preaprovado_cooperado (IDPREAPROVADO, CDCARGA, CDCOOPER, TPCARGA, CDPRODUTO, TPPESSOA, NRCPFCNPJ_BASE, CDLCREMP, VLPOT_PARC_MAXIMO, VLPOT_LIM_MAX, DSFAIXARISCO, PEPROBABILIDADE_DEFAULT_12, PEPROBABILIDADE_DEFAULT_LIFETIME, PEPERDA_ESPERADA_CONCESSAO, TPSCORE, NRSCORE_CREDITO, TPPOLITICA_CONCESSAO)
values (74, 3851, 2, 1, 11, 1, 12676450913, 30, 1, 1700, 'R21', 1, 1, 1, 1, 1, null);

insert into credito.tbcred_preaprovado_cooperado (IDPREAPROVADO, CDCARGA, CDCOOPER, TPCARGA, CDPRODUTO, TPPESSOA, NRCPFCNPJ_BASE, CDLCREMP, VLPOT_PARC_MAXIMO, VLPOT_LIM_MAX, DSFAIXARISCO, PEPROBABILIDADE_DEFAULT_12, PEPROBABILIDADE_DEFAULT_LIFETIME, PEPERDA_ESPERADA_CONCESSAO, TPSCORE, NRSCORE_CREDITO, TPPOLITICA_CONCESSAO)
values (74, 3851, 2, 1, 11, 1, 12447433999, 30, 1, 1300, 'R21', 1, 1, 1, 1, 1, null);

insert into credito.tbcred_preaprovado_cooperado (IDPREAPROVADO, CDCARGA, CDCOOPER, TPCARGA, CDPRODUTO, TPPESSOA, NRCPFCNPJ_BASE, CDLCREMP, VLPOT_PARC_MAXIMO, VLPOT_LIM_MAX, DSFAIXARISCO, PEPROBABILIDADE_DEFAULT_12, PEPROBABILIDADE_DEFAULT_LIFETIME, PEPERDA_ESPERADA_CONCESSAO, TPSCORE, NRSCORE_CREDITO, TPPOLITICA_CONCESSAO)
values (74, 3851, 2, 1, 11, 1, 9822967977, 30, 1, 2500, 'R21', 1, 1, 1, 1, 1, null);


commit;

end;