begin

insert into credito.tbcred_preaprovado_cooperado (IDPREAPROVADO, CDCARGA, CDCOOPER, TPCARGA, CDPRODUTO, TPPESSOA, NRCPFCNPJ_BASE, CDLCREMP, VLPOT_PARC_MAXIMO, VLPOT_LIM_MAX, DSFAIXARISCO, PEPROBABILIDADE_DEFAULT_12, PEPROBABILIDADE_DEFAULT_LIFETIME, PEPERDA_ESPERADA_CONCESSAO, TPSCORE, NRSCORE_CREDITO, TPPOLITICA_CONCESSAO)
values (75, 3852, 2, 1, 11, 1, 13010763760, 31, 1, 800, 'R21', 1, 1, 1, 1, 1, null);

insert into credito.tbcred_preaprovado_cooperado (IDPREAPROVADO, CDCARGA, CDCOOPER, TPCARGA, CDPRODUTO, TPPESSOA, NRCPFCNPJ_BASE, CDLCREMP, VLPOT_PARC_MAXIMO, VLPOT_LIM_MAX, DSFAIXARISCO, PEPROBABILIDADE_DEFAULT_12, PEPROBABILIDADE_DEFAULT_LIFETIME, PEPERDA_ESPERADA_CONCESSAO, TPSCORE, NRSCORE_CREDITO, TPPOLITICA_CONCESSAO)
values (75, 3852, 2, 1, 11, 1, 80038583992, 31, 1, 700, 'R21', 1, 1, 1, 1, 1, null);

insert into credito.tbcred_preaprovado_cooperado (IDPREAPROVADO, CDCARGA, CDCOOPER, TPCARGA, CDPRODUTO, TPPESSOA, NRCPFCNPJ_BASE, CDLCREMP, VLPOT_PARC_MAXIMO, VLPOT_LIM_MAX, DSFAIXARISCO, PEPROBABILIDADE_DEFAULT_12, PEPROBABILIDADE_DEFAULT_LIFETIME, PEPERDA_ESPERADA_CONCESSAO, TPSCORE, NRSCORE_CREDITO, TPPOLITICA_CONCESSAO)
values (75, 3852, 2, 1, 11, 1, 11731964986, 31, 1, 1200, 'R21', 1, 1, 1, 1, 1, null);

insert into credito.tbcred_preaprovado_cooperado (IDPREAPROVADO, CDCARGA, CDCOOPER, TPCARGA, CDPRODUTO, TPPESSOA, NRCPFCNPJ_BASE, CDLCREMP, VLPOT_PARC_MAXIMO, VLPOT_LIM_MAX, DSFAIXARISCO, PEPROBABILIDADE_DEFAULT_12, PEPROBABILIDADE_DEFAULT_LIFETIME, PEPERDA_ESPERADA_CONCESSAO, TPSCORE, NRSCORE_CREDITO, TPPOLITICA_CONCESSAO)
values (75, 3852, 2, 1, 11, 1, 10298210380, 31, 1, 1300, 'R21', 1, 1, 1, 1, 1, null);

insert into credito.tbcred_preaprovado_cooperado (IDPREAPROVADO, CDCARGA, CDCOOPER, TPCARGA, CDPRODUTO, TPPESSOA, NRCPFCNPJ_BASE, CDLCREMP, VLPOT_PARC_MAXIMO, VLPOT_LIM_MAX, DSFAIXARISCO, PEPROBABILIDADE_DEFAULT_12, PEPROBABILIDADE_DEFAULT_LIFETIME, PEPERDA_ESPERADA_CONCESSAO, TPSCORE, NRSCORE_CREDITO, TPPOLITICA_CONCESSAO)
values (75, 3852, 2, 1, 11, 1, 64602788904, 31, 1, 2000, 'R21', 1, 1, 1, 1, 1, null);

insert into credito.tbcred_preaprovado_cooperado (IDPREAPROVADO, CDCARGA, CDCOOPER, TPCARGA, CDPRODUTO, TPPESSOA, NRCPFCNPJ_BASE, CDLCREMP, VLPOT_PARC_MAXIMO, VLPOT_LIM_MAX, DSFAIXARISCO, PEPROBABILIDADE_DEFAULT_12, PEPROBABILIDADE_DEFAULT_LIFETIME, PEPERDA_ESPERADA_CONCESSAO, TPSCORE, NRSCORE_CREDITO, TPPOLITICA_CONCESSAO)
values (75, 3852, 2, 1, 11, 1, 6301687922, 31, 1, 600, 'R21', 1, 1, 1, 1, 1, null);

insert into credito.tbcred_preaprovado_cooperado (IDPREAPROVADO, CDCARGA, CDCOOPER, TPCARGA, CDPRODUTO, TPPESSOA, NRCPFCNPJ_BASE, CDLCREMP, VLPOT_PARC_MAXIMO, VLPOT_LIM_MAX, DSFAIXARISCO, PEPROBABILIDADE_DEFAULT_12, PEPROBABILIDADE_DEFAULT_LIFETIME, PEPERDA_ESPERADA_CONCESSAO, TPSCORE, NRSCORE_CREDITO, TPPOLITICA_CONCESSAO)
values (75, 3852, 2, 1, 11, 1, 7983531982, 31, 1, 600, 'R21', 1, 1, 1, 1, 1, null);

insert into credito.tbcred_preaprovado_cooperado (IDPREAPROVADO, CDCARGA, CDCOOPER, TPCARGA, CDPRODUTO, TPPESSOA, NRCPFCNPJ_BASE, CDLCREMP, VLPOT_PARC_MAXIMO, VLPOT_LIM_MAX, DSFAIXARISCO, PEPROBABILIDADE_DEFAULT_12, PEPROBABILIDADE_DEFAULT_LIFETIME, PEPERDA_ESPERADA_CONCESSAO, TPSCORE, NRSCORE_CREDITO, TPPOLITICA_CONCESSAO)
values (75, 3852, 2, 1, 11, 1, 15212105862, 31, 1, 550, 'R21', 1, 1, 1, 1, 1, null);

insert into credito.tbcred_preaprovado_cooperado (IDPREAPROVADO, CDCARGA, CDCOOPER, TPCARGA, CDPRODUTO, TPPESSOA, NRCPFCNPJ_BASE, CDLCREMP, VLPOT_PARC_MAXIMO, VLPOT_LIM_MAX, DSFAIXARISCO, PEPROBABILIDADE_DEFAULT_12, PEPROBABILIDADE_DEFAULT_LIFETIME, PEPERDA_ESPERADA_CONCESSAO, TPSCORE, NRSCORE_CREDITO, TPPOLITICA_CONCESSAO)
values (75, 3852, 2, 1, 11, 1, 7207464266, 31, 1, 730, 'R21', 1, 1, 1, 1, 1, null);

insert into credito.tbcred_preaprovado_cooperado (IDPREAPROVADO, CDCARGA, CDCOOPER, TPCARGA, CDPRODUTO, TPPESSOA, NRCPFCNPJ_BASE, CDLCREMP, VLPOT_PARC_MAXIMO, VLPOT_LIM_MAX, DSFAIXARISCO, PEPROBABILIDADE_DEFAULT_12, PEPROBABILIDADE_DEFAULT_LIFETIME, PEPERDA_ESPERADA_CONCESSAO, TPSCORE, NRSCORE_CREDITO, TPPOLITICA_CONCESSAO)
values (75, 3852, 2, 1, 11, 1, 96949015968, 31, 1, 1000, 'R21', 1, 1, 1, 1, 1, null);

commit;

end;