begin

insert into credito.tbcred_preaprovado_cooperado (IDPREAPROVADO, CDCARGA, CDCOOPER, TPCARGA, CDPRODUTO, TPPESSOA, NRCPFCNPJ_BASE, CDLCREMP, VLPOT_PARC_MAXIMO, VLPOT_LIM_MAX, DSFAIXARISCO, PEPROBABILIDADE_DEFAULT_12, PEPROBABILIDADE_DEFAULT_LIFETIME, PEPERDA_ESPERADA_CONCESSAO, TPSCORE, NRSCORE_CREDITO, TPPOLITICA_CONCESSAO)
values (72, 3802, 2, 1, 11, 1, 67790666991, 30, 1, 200, 'R21', 1, 1, 1, 1, 1, null);

insert into credito.tbcred_preaprovado_cooperado (IDPREAPROVADO, CDCARGA, CDCOOPER, TPCARGA, CDPRODUTO, TPPESSOA, NRCPFCNPJ_BASE, CDLCREMP, VLPOT_PARC_MAXIMO, VLPOT_LIM_MAX, DSFAIXARISCO, PEPROBABILIDADE_DEFAULT_12, PEPROBABILIDADE_DEFAULT_LIFETIME, PEPERDA_ESPERADA_CONCESSAO, TPSCORE, NRSCORE_CREDITO, TPPOLITICA_CONCESSAO)
values (72, 3802, 2, 1, 11, 1, 10566553481, 30, 1, 300, 'R21', 1, 1, 1, 1, 1, null);

insert into credito.tbcred_preaprovado_cooperado (IDPREAPROVADO, CDCARGA, CDCOOPER, TPCARGA, CDPRODUTO, TPPESSOA, NRCPFCNPJ_BASE, CDLCREMP, VLPOT_PARC_MAXIMO, VLPOT_LIM_MAX, DSFAIXARISCO, PEPROBABILIDADE_DEFAULT_12, PEPROBABILIDADE_DEFAULT_LIFETIME, PEPERDA_ESPERADA_CONCESSAO, TPSCORE, NRSCORE_CREDITO, TPPOLITICA_CONCESSAO)
values (72, 3802, 2, 1, 11, 1, 12447433999, 30, 1, 400, 'R21', 1, 1, 1, 1, 1, null);

commit;

end;