BEGIN

INSERT INTO MENUMOBILE (MENUMOBILEID, MENUPAIID, NOME, SEQUENCIA, HABILITADO, AUTORIZACAO, VERSAOMINIMAAPP, VERSAOMAXIMAAPP, FLAVALIACAO)
VALUES (1053, 1009, 'Pix automático', 1, 1, 1, '2.63.0', null, 0);
COMMIT;

END;