BEGIN
  UPDATE CECRED.TBTARIF_CONTAS_PACOTE T SET T.DTCANCELAMENTO = TO_DATE('13/09/2024', 'DD/MM/YYYY') WHERE T.CDCOOPER = 9 AND T.CDPACOTE = 240 AND T.CDOPERADOR_ADESAO = 'F0033201' AND T.DTCANCELAMENTO IS NULL;
  UPDATE CECRED.TBTARIF_CONTAS_PACOTE T SET T.DTCANCELAMENTO = TO_DATE('13/09/2024', 'DD/MM/YYYY') WHERE T.CDCOOPER = 9 AND T.CDPACOTE = 241 AND T.CDOPERADOR_ADESAO = 'F0033201' AND T.DTCANCELAMENTO IS NULL;
COMMIT;
END;