CREATE OR REPLACE VIEW CECRED.VWCADAST_PESSOA_JURIDICA AS
SELECT tbcadast_pessoa.idpessoa,
         tbcadast_pessoa.nrcpfcgc nrcnpj,
         tbcadast_pessoa.nmpessoa,
         tbcadast_pessoa.nmpessoa_receita,
         tbcadast_pessoa.tppessoa,
         tbcadast_pessoa.dtconsulta_spc,
         tbcadast_pessoa.dtconsulta_rfb,
         tbcadast_pessoa.cdsituacao_rfb,
         tbcadast_pessoa.tpconsulta_rfb,
         tbcadast_pessoa.dtatualiza_telefone,
         tbcadast_pessoa.dtconsulta_scr,
         tbcadast_pessoa.tpcadastro,
         tbcadast_pessoa.cdoperad_altera,
         tbcadast_pessoa.idcorrigido,
         tbcadast_pessoa.dtalteracao,
         tbcadast_pessoa.dtrevisao_cadastral,
         tbcadast_pessoa_juridica.cdcnae,
         tbcadast_pessoa_juridica.nmfantasia,
         tbcadast_pessoa_juridica.nrinscricao_estadual,
         tbcadast_pessoa_juridica.cdnatureza_juridica,
         tbcadast_pessoa_juridica.dtconstituicao,
         tbcadast_pessoa_juridica.dtinicio_atividade,
         tbcadast_pessoa_juridica.qtfilial,
         tbcadast_pessoa_juridica.qtfuncionario,
         tbcadast_pessoa_juridica.vlcapital,
         tbcadast_pessoa_juridica.dtregistro,
         tbcadast_pessoa_juridica.nrregistro,
         tbcadast_pessoa_juridica.dsorgao_registro,
         tbcadast_pessoa_juridica.dtinscricao_municipal,
         tbcadast_pessoa_juridica.nrnire,
         tbcadast_pessoa_juridica.inrefis,
         tbcadast_pessoa_juridica.dssite,
         tbcadast_pessoa_juridica.nrinscricao_municipal,
         tbcadast_pessoa_juridica.cdsetor_economico,
         tbcadast_pessoa_juridica.vlfaturamento_anual,
         tbcadast_pessoa_juridica.cdramo_atividade,
         tbcadast_pessoa_juridica.nrlicenca_ambiental,
         tbcadast_pessoa_juridica.dtvalidade_licenca_amb,
         tbcadast_pessoa_juridica.peunico_cliente,
         tbcadast_pessoa_juridica.tpregime_tributacao,
         tbcadast_pessoa_juridica.tppreferenciacontato,
         tbcadast_pessoa_estrangeira.incrs,
         tbcadast_pessoa_estrangeira.infatca,
         tbcadast_pessoa_estrangeira.cdpais,
         tbcadast_pessoa_estrangeira.nridentificacao,
         tbcadast_pessoa_estrangeira.dsnatureza_relacao,
         tbcadast_pessoa_estrangeira.dsestado,
         tbcadast_pessoa_estrangeira.nrpassaporte,
         tbcadast_pessoa_estrangeira.tpdeclarado,
         tbcadast_pessoa_estrangeira.dsnaturalidade,
         tbcadast_pessoa_juridica_fnc.vlreceita_bruta,
         tbcadast_pessoa_juridica_fnc.vlcusto_despesa_adm,
         tbcadast_pessoa_juridica_fnc.vldespesa_administrativa,
         tbcadast_pessoa_juridica_fnc.qtdias_recebimento,
         tbcadast_pessoa_juridica_fnc.qtdias_pagamento,
         tbcadast_pessoa_juridica_fnc.vlativo_caixa_banco_apl,
         tbcadast_pessoa_juridica_fnc.vlativo_contas_receber,
         tbcadast_pessoa_juridica_fnc.vlativo_estoque,
         tbcadast_pessoa_juridica_fnc.vlativo_imobilizado,
         tbcadast_pessoa_juridica_fnc.vlativo_outros,
         tbcadast_pessoa_juridica_fnc.vlpassivo_fornecedor,
         tbcadast_pessoa_juridica_fnc.vlpassivo_divida_bancaria,
         tbcadast_pessoa_juridica_fnc.vlpassivo_outros,
         tbcadast_pessoa_juridica_fnc.dtmes_base
    FROM tbcadast_pessoa_juridica_fnc,
         tbcadast_pessoa_estrangeira,
         tbcadast_pessoa_juridica,
         tbcadast_pessoa
   WHERE tbcadast_pessoa_juridica.idpessoa (+) = tbcadast_pessoa.idpessoa
     AND tbcadast_pessoa_estrangeira.idpessoa (+) = tbcadast_pessoa.idpessoa
     AND tbcadast_pessoa_juridica_fnc.idpessoa (+) = tbcadast_pessoa.idpessoa
     AND tbcadast_pessoa.tppessoa = 2;
