BEGIN
  SYS.DBMS_SCHEDULER.DISABLE('CECRED.jbdda_processa_crapdda');
  SYS.DBMS_SCHEDULER.DROP_JOB('CECRED.jbdda_processa_crapdda');
EXCEPTION
  WHEN OTHERS THEN
    CECRED.PC_INTERNAL_EXCEPTION(pr_compleme => 'PRB0042568');
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
