insert ALL 
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 1, 'FINALI_CORONA', 'CREDITO - Finalidade Exclusiva CoronaVirus', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 2, 'FINALI_CORONA', 'CREDITO - Finalidade Exclusiva CoronaVirus', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 3, 'FINALI_CORONA', 'CREDITO - Finalidade Exclusiva CoronaVirus', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 5, 'FINALI_CORONA', 'CREDITO - Finalidade Exclusiva CoronaVirus', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 6, 'FINALI_CORONA', 'CREDITO - Finalidade Exclusiva CoronaVirus', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 7, 'FINALI_CORONA', 'CREDITO - Finalidade Exclusiva CoronaVirus', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 8, 'FINALI_CORONA', 'CREDITO - Finalidade Exclusiva CoronaVirus', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 9, 'FINALI_CORONA', 'CREDITO - Finalidade Exclusiva CoronaVirus', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 10, 'FINALI_CORONA', 'CREDITO - Finalidade Exclusiva CoronaVirus', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 11, 'FINALI_CORONA', 'CREDITO - Finalidade Exclusiva CoronaVirus', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 12, 'FINALI_CORONA', 'CREDITO - Finalidade Exclusiva CoronaVirus', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 13, 'FINALI_CORONA', 'CREDITO - Finalidade Exclusiva CoronaVirus', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 14, 'FINALI_CORONA', 'CREDITO - Finalidade Exclusiva CoronaVirus', '82')
INTO CECRED.CRAPPRM (NMSISTEM, CDCOOPER, CDACESSO, DSTEXPRM, DSVLRPRM) VALUES ('CRED', 16, 'FINALI_CORONA', 'CREDITO - Finalidade Exclusiva CoronaVirus', '82')
SELECT * FROM dual;

commit;