BEGIN
  INSERT INTO PIX.TBPIX_TIPO_LIMITE (IDTIPO_LIMITE, NMTIPO_LIMITE) VALUES (5, 'Automatico');
  INSERT INTO PIX.TBPIX_TIPO_LIMITE (IDTIPO_LIMITE, NMTIPO_LIMITE) VALUES (6, 'Transferência dispositivo não cadastrado'); 
  INSERT INTO PIX.TBPIX_PERIODO (IDPERIODO, NMPERIODO) VALUES (3, 'Diário'); 
COMMIT;
END;
