BEGIN

  DELETE FROM CREDITO.TBCRED_INTEGRACAO_PAYLOAD;
  DELETE FROM CREDITO.TBCRED_INTEGRACAO_ESTORNO;
  DELETE FROM CREDITO.TBCRED_INTEGRACAO_PAGAMENTO;
  DELETE FROM CREDITO.TBCRED_INTEGRACAO_CONTRATO;

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE_application_error(-20500, SQLERRM);
END;
