BEGIN

DELETE
FROM  CECRED.TBCADAST_COLABORADOR 
WHERE CDUSURED IS NULL OR CDUSURED LIKE 'C%';

COMMIT;

EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20000, 'ERRO ' || SQLERRM);
END;