BEGIN
  UPDATE CECRED.CRAPEPR EPR
     SET EPR.IDQUAPRC = 1
   WHERE EPR.CDCOOPER = 7
     AND EPR.NRDCONTA = 99731509 
     AND EPR.NRCTREMP = 95129;
  
  UPDATE CECRED.CRAWEPR EPR
     SET EPR.IDQUAPRO = 1
   WHERE EPR.CDCOOPER = 7
     AND EPR.NRDCONTA = 99731509 
     AND EPR.NRCTREMP = 95129;
     
  COMMIT;
     
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE_application_error(-20500, SQLERRM);      
END;
