BEGIN

  UPDATE CECRED.CRAPBPR
  SET    CDSITGRV = 0,
         NRGRAVAM = null
  WHERE  CDCOOPER = 2
  AND    NRDCONTA = 813567
  AND    NRCTRPRO = 568985
  AND    IDSEQBEM IN (1,2);
  
  COMMIT;
		
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20000, 'ERRO ' || SQLERRM);
END;