BEGIN

INSERT INTO CECRED.CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR)
VALUES ('BUSCA_RESUMO_PRESTAMISTA_PJ', 'SEGU0004', 'PC_BUSCA_RESUMO_SEGURO_PJ', 'pr_cdcooper,pr_vlpremio,pr_nmsocio,pr_vlcobertura,pr_pecobertura',(SELECT NRSEQRDR FROM CECRED.CRAPRDR WHERE NMPROGRA = 'SEGU0004'));

COMMIT;
END;
