BEGIN

INSERT INTO CECRED.CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR)
VALUES ('EFETIVA_SEGURO_PRESTAMISTA_PJ', 'SEGU0004', 'PC_EFETIVA_SEGURO_PRESTAMISTA_PJ', 'pr_cdcooper,pr_nrdconta,pr_nrctremp',(SELECT NRSEQRDR FROM CECRED.CRAPRDR WHERE NMPROGRA = 'SEGU0004'));

COMMIT;
END;
