BEGIN

  INSERT INTO cecred.tbgen_layout_campo
    (IDLAYOUT, TPREGISTRO, NRSEQUENCIA_CAMPO, NMCAMPO, TPDADO, DSFORMATO, NRPOSICAO_INICIAL, QTDPOSICOES, DSOBSERVACAO)
  VALUES
    (16, '05', 4, 'DTINICIOINADIMPLENCI', 'D', 'RRRRMMDD', 108, 8, 'DATA DE INICIO DE INADIMPLENCIA ACEITA PELO FUNDO');

  COMMIT;

EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20500, SQLERRM);
END;