BEGIN
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 49501;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 52593;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 160244;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 160523;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 161689;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 164689;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 214359;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 218292;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 347448;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 325615;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 329360;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 209516;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 280686;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 55473;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 308014;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 61309;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 147225;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 299704;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 303989;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 55127;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 43486;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 44010;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 44376;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 45063;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 229171;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 76774;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 76980;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 77026;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 88398;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 89082;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 199479;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 199534;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 199632;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 89203;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 107233;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 202270;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 210286;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 211372;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 92305;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 219988;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 77730;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 77932;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 78153;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 45260;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 233651;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 239379;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 78940;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 106617;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 118014;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 273449;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 122621;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 282353;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 96241;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 130167;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 132438;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 134113;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 82367;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 96865;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 313738;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 328385;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 332571;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 164570;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 164818;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 340175;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 343188;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 168996;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 74190;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 74384;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 74962;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 192288;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 75653;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 87771;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 199160;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 199380;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 168416;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 169597;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 197818;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 198505;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 147682;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 172120;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 149586;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 174725;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 128373;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 153974;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 131188;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 132186;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 214492;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 184542;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 218441;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 162192;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 333806;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 335744;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 340441;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 340533;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 276257;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 312398;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 343999;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 233799;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 316304;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 316720;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 287786;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 320793;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 348445;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 292137;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 321311;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 294322;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 360038;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 249116;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 249225;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 252806;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 254267;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 360834;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 361096;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 361097;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 259940;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 326398;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 262703;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 262836;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 262857;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 262914;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 263049;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 328034;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 263188;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 263659;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 264372;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 362062;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 362476;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 271589;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 367468;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 364513;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 369502;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 365388;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 365533;
  DELETE FROM gestaoderisco.tbrisco_grupo_economico_integrante WHERE cdgrupo_economico = 365808;
  COMMIT;
  UPDATE cecred.tbrisco_operacoes a SET a.dhtransmissao = NULL WHERE a.cdcooper = 10 AND a.nrdconta = 63509 AND a.nrctremp = 56753 AND a.tpctrato = 90;
  UPDATE cecred.tbrisco_operacoes a SET a.dhtransmissao = NULL WHERE a.cdcooper = 10 AND a.nrdconta = 16670213 AND a.nrctremp = 56716 AND a.tpctrato = 90;
  UPDATE cecred.tbrisco_operacoes a SET a.dhtransmissao = NULL WHERE a.cdcooper = 10 AND a.nrdconta = 170500 AND a.nrctremp = 56742 AND a.tpctrato = 90;
  UPDATE cecred.tbrisco_operacoes a SET a.dhtransmissao = NULL WHERE a.cdcooper = 1 AND a.nrdconta = 11819600 AND a.nrctremp = 8254366 AND a.tpctrato = 90;
  UPDATE cecred.tbrisco_operacoes a SET a.dhtransmissao = NULL WHERE a.cdcooper = 1 AND a.nrdconta = 16013247 AND a.nrctremp = 8296165 AND a.tpctrato = 90;
  UPDATE cecred.tbrisco_operacoes a SET a.dhtransmissao = NULL WHERE a.cdcooper = 13 AND a.nrdconta = 583464 AND a.nrctremp = 366117 AND a.tpctrato = 90;
  UPDATE cecred.tbrisco_operacoes a SET a.dhtransmissao = NULL WHERE a.cdcooper = 14 AND a.nrdconta = 16768884 AND a.nrctremp = 167961 AND a.tpctrato = 90;
  UPDATE cecred.tbrisco_operacoes a SET a.dhtransmissao = NULL WHERE a.cdcooper = 14 AND a.nrdconta = 178888 AND a.nrctremp = 167142 AND a.tpctrato = 90;
  UPDATE cecred.tbrisco_operacoes a SET a.dhtransmissao = NULL WHERE a.cdcooper = 13 AND a.nrdconta = 581810 AND a.nrctremp = 365991 AND a.tpctrato = 90;
  COMMIT;
  UPDATE cecred.tbrisco_operacoes SET dhtransmissao = null WHERE cdcooper = 1 AND nrdconta = 17979366 AND nrctremp = 17979366;
  UPDATE cecred.tbrisco_operacoes SET dhtransmissao = null WHERE cdcooper = 1 AND nrdconta = 11760389 AND nrctremp = 11760389;
  commit;
END;
