begin

	UPDATE CECRED.TBEPR_CONSIGNADO_PAGAMENTO A
	SET A.INSTATUS = 2
	WHERE A.CDCOOPER = 11
	AND A.NRDCONTA = 540528
	AND A.NRCTREMP = 168390
	AND A.NRPAREPR = 4
	AND A.INORGPGT = 1 
	AND A.INSTATUS = 3;

	commit;

end;