BEGIN

  FOR rw_coop IN ((SELECT cdcooper
                     FROM crapcop c
                    WHERE c.flgativo = 1)) LOOP
  
    INSERT INTO crapace
      (NMDATELA, CDDOPCAO, CDOPERAD, NMROTINA, CDCOOPER, NRMODULO, IDEVENTO, IDAMBACE)
    VALUES
      ('ATENDA', 'LO', 'f0033479', 'PRESTACOES', rw_coop.cdcooper, 1, 0, 2);
    INSERT INTO crapace
      (NMDATELA, CDDOPCAO, CDOPERAD, NMROTINA, CDCOOPER, NRMODULO, IDEVENTO, IDAMBACE)
    VALUES
      ('ATENDA', 'LO', 'f0033406', 'PRESTACOES', rw_coop.cdcooper, 1, 0, 2);
    INSERT INTO crapace
      (NMDATELA, CDDOPCAO, CDOPERAD, NMROTINA, CDCOOPER, NRMODULO, IDEVENTO, IDAMBACE)
    VALUES
      ('ATENDA', 'LO', 'f0030513', 'PRESTACOES', rw_coop.cdcooper, 1, 0, 2);
    INSERT INTO crapace
      (NMDATELA, CDDOPCAO, CDOPERAD, NMROTINA, CDCOOPER, NRMODULO, IDEVENTO, IDAMBACE)
    VALUES
      ('ATENDA', 'LO', 'f0033754', 'PRESTACOES', rw_coop.cdcooper, 1, 0, 2);
  
  END LOOP;

  COMMIT;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_application_error(-20500, SQLERRM);
    ROLLBACK;
END;
