BEGIN
  
  UPDATE CECRED.CRAPJUR t
    SET t.nmextttl = 'ABSOLUTA COBRANCA ESPECIALIZADA EIRELI'
  WHERE t.nrdconta = 14643855
    AND t.cdcooper = 1;
  
  UPDATE CECRED.CRAPASS a
    SET a.nmprimtl = 'ABSOLUTA COBRANCA ESPECIALIZADA EIRELI'
  WHERE a.nrdconta = 14643855
    and a.cdcooper = 1;
    
  COMMIT;
  
EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20000, 'ERRO: ' || SQLERRM);
END;
