BEGIN
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('67004','Saque Conta Corrente','Saque');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('67005','Saque Poupança','Saque');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('302010','Saque Poupança','Saque');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('302020','Saque Cartão Crédito','Saque');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('302050','Saque Salário','Saque');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('302000','Saque CC','Saque');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('325000','Saque Cartão Crédito','Saque');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('12000','Saque Frete','Saque');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('302060','Saque Frete','Saque');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('361000','Saque ZUUM','Saque');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('302070','Saque Parceiro','Saque');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('302090','Saque S/ Cartão','Saque');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('302080','Saque Moeda Estrangeira','Saque');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('301000','Saldo CC com Cartão','Saldo em Tela');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('318000','Saldo CC sem Cartão','Saldo em Tela');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('301050','Saldo CC com Cartão Salário','Saldo em Tela');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('301010','Saldo Poupança','Saldo em Tela');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('301070','Saldo INSS','Saldo em Tela');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('368106','Consulta de Saldo Aplicação','Saldo em Tela');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('368107','Consulta de Saldo Produto','Saldo em Tela');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('67001','Saldo Conta Corrente','Saldo Impresso');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('67002','Saldo Poupança','Saldo Impresso');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('321000','Saldo CC com Cartão - Impresso','Saldo Impresso');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('322000','Saldo CC sem Cartão - Impresso','Saldo Impresso');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('323000','Saldo CC com Cartão Salário - Impresso','Saldo Impresso');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('315000','Identificação Cliente','Consulta Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('311000','Consulta Favorecido Depósito','Consulta Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('324000','Consulta Informação Saque','Consulta Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('301060','Consulta Saldo','Saldo em Tela');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('311010','Consulta de Poupança','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('311040','Consulta de Conta INSS','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('311050','Consulta de Conta Salário','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('311066','Consulta de Contas para Ativar - Cartão Frete','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('311067','Consulta de Dependentes – Cartão','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('329001','Consulta de Agências e Contas Relacionadas','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('329002','Consulta de Informação para Recarga','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('350000','Consulta Pgto. de Conta em dinheiro C/ cód. de barras','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('350100','Consulta Pgto. de Conta em dinheiro S/ cód. de barras','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('329003','Consulta Inf. de Bancos e Tarifas (Autorizador)','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('319000','Consulta Depósito Cheque','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('371000','Consulta Texto Informativo','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('372001','Consulta Tarifas Disponíveis','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('372002','Consulta Tarifas Contratadas','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('373101','Consulta Lista de Investimentos Disponíveis','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('373102','Consulta Lista de Investimentos para Resgate','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('373201','Consulta Papéis de Investimento Disponíveis','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('373202','Consulta Papéis de Invest. Disp. para Resgate Valor','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('373203','Consulta Papéis de Invest. Disp. para Resgate Operação','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('374000','Consulta Contracheques','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('375000','Consulta Dados Cartão','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('378001','Consulta Concessionárias Conv. P/ Inc. Déb. Auto.','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('378002','Consulta Concessionárias Conv. P/ Exc. Déb. Auto.','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('369520','Consulta Pagamento DDA','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('376100','Consulta Transferências Agendadas','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('367000','Consulta Favorecidos','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('367010','Consulta Finalidades de Transferência','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('366001','Consulta Telefones Cadastrados','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('371001','Consulta Texto Informativo para Impressão','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('380010','Consulta Produtos de Pagamento para Reimpressão','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('380011','Consulta Produtos de Transferência P/ Reimpressão','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('380020','Consulta Comprovantes de Pagamento P/ Reimpressão','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('380021','Consulta Comprovantes de Transferência P/ Reimpressão','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('375002','Consulta Dados do Cartão','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('375003','Consulta Dados de Preparação do Cartão','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('315100','Autenticação','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('920000','Consulta Valores de Recarga e Transporte','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('920700','Consulta Produtos de Recarga e Transporte','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('329100','Consulta de Taxas','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('311060','Consulta Acerto de Contas Dinheiro (ATMR)','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('390000','Consulta Saque','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('350210','Consulta de Pagamentos Agendados','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('350200','Consulta Agendamento Conta/Título C/ cód. barras','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('311090','Consulta Títulos de Capitalização','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('380000','Consulta BIN','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('301100','Consulta de Saldo - Visa','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('304942','TED agendada (Netuno)','Depósito de Cédulas sem envelope');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('326100','Consulta Período Extrato - BANRISUL','Consulta de Dados');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('304010','Depósito Dinheiro Poupança','Depósito de Cédulas sem envelope');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('304000','Depósito Dinheiro CC','Depósito de Cédulas sem envelope');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('304900','Depósito Dinheiro CC - Cartão Poupança','Depósito de Cédulas sem envelope');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('304901','Depósito Dinheiro Poupança - Cartão Poupança','Depósito de Cédulas sem envelope');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('304910','Depósito Dinheiro CC - Sem Cartão','Depósito de Cédulas sem envelope');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('304911','Depósito Dinheiro Poupança - Sem Cartão','Depósito de Cédulas sem envelope');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('330000','Depósito Multibanco','Depósito de Cédulas sem envelope');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('360000','Depósito Vivo ZUUM','Depósito de Cédulas sem envelope');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('304940','Depósito Offline','Depósito de Cédulas sem envelope');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('305010','Compra Títulos de Capitalização','Depósito de Cédulas sem envelope');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('304500','Depósito Cheque CC','Depósito de Cheques sem envelope');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('304510','Depósito Cheque Poupança','Depósito de Cheques sem envelope');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('304902','Depósito Cheque CC – Cartão Poupança','Depósito de Cheques sem envelope');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('304903','Depósito Cheque Poupança - Cartão Poupança','Depósito de Cheques sem envelope');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('304912','Depósito Cheque CC - Sem Cartão','Depósito de Cheques sem envelope');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('304913','Depósito Cheque Poupança - Sem Cartão','Depósito de Cheques sem envelope');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('304506','Depósito Cheque C/ Imagem','Depósito de Cheques sem envelope');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('317000','Pagamento Contas Débito','Pagamento de Contas');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('317010','Pagamento Contas Cartão Poupança','Pagamento de Contas');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('317040','Pagamento Contas Cartão Benefício','Pagamento de Contas');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('317500','Pagamento Contas Cheque','Pagamento de Contas');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('317050','Pagamento de Conta em Dinheiro C/cód. barras e C/cartão','Pagamento de Contas');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('317060','Pagamento de Conta em dinheiro C/cód. barras e S/cartão','Pagamento de Contas');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('337050','Pagamento de Conta em Dinheiro S/cód. barras e C/cartão','Pagamento de Contas');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('337060','Pagamento de Conta em Dinheiro S/cód. barras e S/cartão','Pagamento de Contas');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('317020','Pagamento Agendado - Código de Barras e Déb. em CC','Pagamento de Contas');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('320000','Transferência entre Contas - Débito Conta Corrente','Transferência');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('320010','Transferência entre Contas - Débito Cartão Poupança','Transferência');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('320040','Transferência entre Contas - Débito Cartão INSS','Transferência');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('320900','Transferência entre Contas - Débito CC P/ CC','Transferência');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('320901','Transferência entre Contas - Débito CC P/ Poupança','Transferência');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('320902','Transferência entre Contas - Débito Poupança P/ CC','Transferência');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('320903','Transferência entre Contas - Débito Poupança P/ Poupança','Transferência');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('320904','Transferência entre Contas - Débito Conta Salário P/ CC','Transferência');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('320060','Transferência entre Contas - Cartão Frete P/ cartão dep.','Transferência');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('320061','Transferência entre Contas – Cartão Frete P/ Contas Banc','Transferência');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('369908','Alteração de Transferência Agendada','Transferência');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('369909','Cancelamento de Transferência Agendada','Transferência');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('369907','Transferência C/ Déb. CC P/ CP Agendada Data de Provento','Transferência');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('369905','Transferência C/ Débito CC para CP Agendada Eventual','Transferência');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('369906','Transferência C/ Débito CC para CP Agendada Mensal','Transferência');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('320920','Transferência de dinheiro CC','Transferência');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('326001','Extrato Saldo e Últimos Movimentos PF com Cartão','Extrato');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('326002','Extrato Semanal PF com Cartão','Extrato');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('326003','Extrato Quinzenal PF com Cartão','Extrato');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('326011','Extrato Saldo e Últimos Movimentos PJ C/ Cartão','Extrato');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('326021','Extrato Saldo e Últimos Movimentos S/ Cartão','Extrato');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('326007','Extrato Mensal PF C/ Cartão','Extrato');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('326017','Extrato Informe de Rendimentos','Extrato');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('326016','Extrato Contracheques','Extrato');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('326015','Extrato Tarifas','Extrato');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('326013','Extrato Produto','Extrato');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('326014','Extrato Aplicação','Extrato');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('326027','Extrato Mensal S/ Cartão','Extrato');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('326030','Extrato Histórico PF Com Cartão','Extrato');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('326018','Extrato Semanal PJ com cartão','Extrato');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('326019','Extrato Quinzenal PJ com cartão','Extrato');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('326020','Extrato Mensal PJ com cartão','Extrato');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('326031','Extrato Histórico PJ Com Cartão','Extrato');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('326005','Extrato Semanal sem cartão','Extrato');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('326006','Extrato Quinzenal sem cartão','Extrato');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('326032','Extrato Histórico sem cartão','Extrato');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('304001','Depósito Dinheiro - CC Varejista','Depósito Varejista');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('304002','Depósito Varejista com Cartão','Depósito Varejista');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('304003','Depósito Varejista sem Cartão','Depósito Varejista');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('910800','Recarga Pré-pago','Recarga com Cartão');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('331000','Recarga - Débito Cartão CC','Recarga com Cartão');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('331010','Recarga - Débito Cartão Poupança','Recarga com Cartão');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('331040','Recarga - Débito Cartão INSS','Recarga com Cartão');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('337000','Pagamento S/Cód. Barras e Débito em CC','Pagamento sem Código de Barras');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('337010','Pagamento S/Cód. Barras e Débito Poupança','Pagamento sem Código de Barras');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('337040','Pagamento S/Cód. Barras e Débito INSS','Pagamento sem Código de Barras');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('369521','Pagamento DDA COM cartão CC','Pagamento sem Código de Barras');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('369522','Pagamento DDA COM cartão INSS','Pagamento sem Código de Barras');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('369523','Pagamento DDA COM cartão Poupança','Pagamento sem Código de Barras');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('340327','Consulta Limites Empréstimo Emergencial','Empréstimo Emergencial');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('340317','Simulação Empréstimo Emergencial','Empréstimo Emergencial');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('341307','Empréstimo Emergencial','Empréstimo Emergencial');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('342000','Simulação Empréstimo Emergencial - Impresso','Empréstimo Emergencial');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('340328','Consulta Limites Empréstimo Sazonal','Empréstimo Sazonal');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('340318','Simulação Empréstimo Sazonal','Empréstimo Sazonal');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('341308','Empréstimo Sazonal','Empréstimo Sazonal');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('343000','Simulação Empréstimo Sazonal - Impresso','Empréstimo Sazonal');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('340329','Consulta Limites Empréstimo Parcelado','Empréstimo Parcelado');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('340319','Simulação Empréstimo Parcelado','Empréstimo Parcelado');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('341309','Empréstimo Parcelado','Empréstimo Parcelado');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('344000','Simulação Empréstimo Parcelado - Impresso','Empréstimo Parcelado');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('340339','Consulta Parcelas Empréstimo','Empréstimo Parcelado');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('341310','Empréstimo Saque Extra','Empréstimo Parcelado');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('340330','Consulta de Limites de Saque Extra (Empréstimo)','Empréstimo Parcelado');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('340340','Consulta de Parc. de Saque Extra (Empréstimo)','Empréstimo Parcelado');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('306500','Recolhimento de cheques','Administrativa');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('305000','Reabastecimento','Administrativa');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('306000','Recolhimento','Administrativa');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('310000','Fechamento','Administrativa');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('338000','Registro de Incidentes','Administrativa');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('306550','Recolhimento de Cartões','Administrativa');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('306600','Recolhimento de Folhas de Cheque','Administrativa');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('306650','Bobinas','Administrativa');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('306700','Ribbon','Administrativa');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('306750','Tonner Magnético','Administrativa');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('305600','Abastecimento de Folhas de Cheque','Administrativa');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('305550','Abastecimento de Cartões','Administrativa');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('305650','Abastecimento de Bobinas','Administrativa');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('305500','Abastecimento de Moedas','Administrativa');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('305700','Abastecimento de Ribbon','Administrativa');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('305750','Abastecimento de Tonner Magnético','Administrativa');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('306800','Recolhimento de Moedas','Administrativa');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('320910','TED com Débito Conta Corrente para Conta Corrente','TED');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('320911','TED com Débito Conta Corrente para Poupança','TED');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('320912','TED com Débito Poupança para Conta Corrente','TED');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('320913','TED com Débito Poupança para Poupança','TED');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('372100','Pacote de Tarifas Adesão','Pacote');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('372200','Pacote de Tarifas Cancelamento','Pacote');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('366100','Adesão a Serviço de Pacote de SMS','Pacote');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('366200','Cancelamento de Serviço de Pacote de SMS','Pacote');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('371100','Consulta Adesão Pacote SMS','Pacote');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('371101','Consulta Cancelamento Pacote SMS','Pacote');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('373301','Simula Investimento - Contratação','Simulação');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('373302','Simula Investimento - Resgate','Simulação');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('345000','Simulação de Investimento','Simulação');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('373303','Simula Investimento - Resgate por Operação','Simulação');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('373400','Aplicação em Investimento','Aplicação');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('373501','Resgate de Aplicação de Investimento por Valor','Resgate');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('373502','Resgate de Aplicação de Investimento por Operação','Resgate');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('376002','Cadastro de Senha de Internet','Cadastro Senha');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('377002','Alteração de Senha da Internet','Cadastro Senha');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('376003','Alteração da Senha da Internet','Cadastro Senha');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('377000','Impressão de cheques','Impressão Cheque');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('375200','Cancela Cartão','Cancelamento Cartão');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('375100','Grava Cartão','Gravação de Cartão');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('327000','Solicitação de Saque Topázio','Solicitação Saque');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('378100','Inclusão Débito Automático','Débito automático');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('378200','Exclusão Débito Automático','Débito automático');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('369510','Liquidação de dívidas com Débito em Conta Corrente','Liquidação de dívidas');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('380001','Reimpressão de Comprovante de Pagamento','Reimpressão de Comprovante');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('380002','Reimpressão de Comprovante de Transferência','Reimpressão de Comprovante');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('920800','Recarga Cartão Transporte','Pessoa Física');
    INSERT INTO TAA.TBTAA_SEP_OPERACAO VALUES('311070','Consulta Acerto de Contas Dinheiro (ATMD)','Consulta');

    COMMIT;
END;