BEGIN
  UPDATE TBDOMIC_LIQTRANS_LANCTO
     SET INSITUACAO = 1
   WHERE IDARQUIVO IN (SELECT IDARQUIVO
                         FROM TBDOMIC_LIQTRANS_ARQUIVO
                        WHERE TRUNC(DHRECEBIMENTO) = TRUNC(SYSDATE - 1))
     AND INSITUACAO = 0;
  COMMIT;
END;
