DECLARE
  -- Local variables here
  CURSOR cr_crapcop IS
	  SELECT cdcooper
		  FROM crapcop c
		 WHERE c.flgativo = 1
		   AND c.cdcooper <> 3;
			 
BEGIN
	FOR coop IN cr_crapcop LOOP
  
		INSERT INTO crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, FLGBNAND, FLGINTER)
		VALUES (100, 'VISA INFINITE BLACK', 1, 'SÃO PAULO', 'Rua Bela Cintra, 967, 8º andar - cjto 82', 'Consolação', 'SP', 01415907, '', 'VISA', 23, 0, 0, 0, 2011, 7, 'UNICRED', 'VISA INFINITE', 'cartoes@ailos.coop.br', coop.cdcooper, 0, 0, 1, 111111, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0);
    
    INSERT INTO tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
    VALUES (coop.cdcooper, 100, 500.00, 100000.00, '3,7,11,19,22', 0);

    INSERT INTO tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
    VALUES (coop.cdcooper, 100, 500.00, 100000.00, '3,7,11,19,22', 1);		
		
		INSERT INTO crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, FLGBNAND, FLGINTER)
		VALUES (101, 'VISA CLASSIC', 1, 'SÃO PAULO', 'Rua Bela Cintra, 967, 8º andar - cjto 82', 'Consolação', 'SP', 01415907, '', 'VISA', 23, 0, 0, 0, 2011, 7, 'UNICRED', 'VISA CLASSIC', 'cartoes@ailos.coop.br', coop.cdcooper, 0, 0, 1, 222222, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0);  

    INSERT INTO tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
    VALUES (coop.cdcooper, 101, 500.00, 100000.00, '3,7,11,19,22', 0);

    INSERT INTO tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
    VALUES (coop.cdcooper, 101, 500.00, 100000.00, '3,7,11,19,22', 1);

		INSERT INTO crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, FLGBNAND, FLGINTER)
		VALUES (102, 'VISA GOLD', 1, 'SÃO PAULO', 'Rua Bela Cintra, 967, 8º andar - cjto 82', 'Consolação', 'SP', 01415907, '', 'VISA', 23, 0, 0, 0, 2011, 7, 'UNICRED', 'VISA GOLD', 'cartoes@ailos.coop.br', coop.cdcooper, 0, 0, 1, 333333, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0);  

    INSERT INTO tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
    VALUES (coop.cdcooper, 102, 500.00, 100000.00, '3,7,11,19,22', 0);

    INSERT INTO tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
    VALUES (coop.cdcooper, 102, 500.00, 100000.00, '3,7,11,19,22', 1);
		
		INSERT INTO crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, FLGBNAND, FLGINTER)
		VALUES (103, 'VISA PLATINUM', 1, 'SÃO PAULO', 'Rua Bela Cintra, 967, 8º andar - cjto 82', 'Consolação', 'SP', 01415907, '', 'VISA', 23, 0, 0, 0, 2011, 7, 'UNICRED', 'VISA PLATINUM', 'cartoes@ailos.coop.br', coop.cdcooper, 0, 0, 1, 444444, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0);    

    INSERT INTO tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
    VALUES (coop.cdcooper, 103, 500.00, 100000.00, '3,7,11,19,22', 0);

    INSERT INTO tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
    VALUES (coop.cdcooper, 103, 500.00, 100000.00, '3,7,11,19,22', 1);
		
		INSERT INTO crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, FLGBNAND, FLGINTER)
		VALUES (104, 'VISA INFINITE PEROLADO', 1, 'SÃO PAULO', 'Rua Bela Cintra, 967, 8º andar - cjto 82', 'Consolação', 'SP', 01415907, '', 'VISA', 23, 0, 0, 0, 2011, 7, 'UNICRED', 'VISA PEROLADO', 'cartoes@ailos.coop.br', coop.cdcooper, 0, 0, 1, 555555, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0);

    INSERT INTO tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
    VALUES (coop.cdcooper, 104, 500.00, 100000.00, '3,7,11,19,22', 0);

    INSERT INTO tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
    VALUES (coop.cdcooper, 104, 500.00, 100000.00, '3,7,11,19,22', 1);
		
		INSERT INTO crapadc (CDADMCRD, NMADMCRD, INSITADC, NMCIDADE, DSENDERE, NMBAIRRO, CDUFENDE, NRCEPEND, NMPESCTO, NMBANDEI, QTCARNOM, NRCTACOR, NRDIGCTA, NRRAZCTA, CDAGECTA, CDDIGAGE, NMAGECTA, NMRESADM, DSDEMAIL, CDCOOPER, INANUIDA, FLGHABCJ, TPCTAHAB, NRCTAMAE, CDCLASSE, FLGCCHIP, FLOUTROS, FLGDEBIT, FLGCRDIT, FLGSAQSS, FLGCRDAD, FLGCOMPI, FLGRECOP, FLGCCIEG, FLGPPDIF, VLANUIDD, FLGBNAND, FLGINTER)
		VALUES (105, 'VISA ELECTRON', 1, 'SÃO PAULO', 'Rua Bela Cintra, 967, 8º andar - cjto 82', 'Consolação', 'SP', 01415907, '', 'VISA', 23, 0, 0, 0, 2011, 7, 'UNICRED', 'VISA ELECTRON', 'cartoes@ailos.coop.br', coop.cdcooper, 0, 0, 1, 666666, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0);  

    INSERT INTO tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
    VALUES (coop.cdcooper, 105, 500.00, 100000.00, '3,7,11,19,22', 0);

    INSERT INTO tbcrd_config_categoria (CDCOOPER, CDADMCRD, VLLIMITE_MINIMO, VLLIMITE_MAXIMO, DSDIAS_DEBITO, TPLIMCRD)
    VALUES (coop.cdcooper, 105, 500.00, 100000.00, '3,7,11,19,22', 1);	
		
  END LOOP;	
	
	COMMIT;
END;