BEGIN
  DELETE 
    FROM CREDITO.TBEPR_PARCELAS_CRED_IMOB PARC
   WHERE IDPARCELA = 301;
   
  UPDATE CREDITO.TBEPR_PARCELAS_CRED_IMOB PARC
     SET NRCTREMP = 4924277
   WHERE IDPARCELA = 401;
   
  UPDATE CREDITO.TBEPR_PARCELAS_CRED_IMOB PARC
     SET NRCTREMP = 4997509
   WHERE IDPARCELA = 404;
   
  COMMIT; 
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
END; 
