DECLARE

  VR_NRSEQRDR CRAPRDR.NRSEQRDR%TYPE := 0;
  
  CURSOR CR_CRAPRDR IS
    SELECT NRSEQRDR 
      FROM CRAPRDR 
     WHERE NMPROGRA = 'TCARGA';
     
  RW_CRAPRDR CR_CRAPRDR%ROWTYPE; 
BEGIN
   OPEN CR_CRAPRDR;
   FETCH CR_CRAPRDR INTO RW_CRAPRDR;
   IF CR_CRAPRDR%NOTFOUND THEN    
     INSERT INTO CRAPRDR(NMPROGRA,DTSOLICI) VALUES ('TCARGA',SYSDATE) RETURNING CRAPRDR.NRSEQRDR INTO VR_NRSEQRDR;
   ELSE 
     VR_NRSEQRDR := RW_CRAPRDR.NRSEQRDR;
   END IF;
   CLOSE CR_CRAPRDR; 

  INSERT INTO CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR) VALUES ('VERIFICAAMBIENTE', 'TELA_TCARGA', 'pc_verifica_ambiente', NULL, vr_nrseqrdr);
  
  INSERT INTO CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR) VALUES ('VERIFICAEXECUCAO', 'TELA_TCARGA', 'pc_verifica_execucao', NULL, vr_nrseqrdr);
  
  INSERT INTO CRAPACA (NMDEACAO, NMPACKAG, NMPROCED, LSTPARAM, NRSEQRDR) VALUES ('SOLICITACARGA', 'TELA_TCARGA', 'pc_solicita_teste_carga', 'pr_cooperativas,pr_mensagens,pr_quantidade,pr_secoes,pr_datamsg,pr_valorde,pr_valorate', vr_nrseqrdr);

  COMMIT;

EXCEPTION
  WHEN OTHERS THEN NULL;
END;