declare
begin
	MERGE INTO PIX.TBPIX_HORARIO_PERIODO_COOPERADO t1
	USING (SELECT crapsnh.CDCOOPER, crapsnh.NRDCONTA FROM crapsnh crapsnh WHERE TPDSENHA = 1 AND CDSITSNH = 1 
	and not exists (SELECT H.CDCOOPER, H.NRDCONTA FROM PIX.TBPIX_HORARIO_PERIODO_COOPERADO H
	WHERE H.CDCOOPER = crapsnh.CDCOOPER AND H.NRDCONTA = crapsnh.NRDCONTA) GROUP BY crapsnh.CDCOOPER, crapsnh.NRDCONTA) t2
	ON (t1.CDCOOPER = t2.CDCOOPER AND t1.NRDCONTA = t2.NRDCONTA)
	WHEN NOT MATCHED THEN
		INSERT (t1.CDCOOPER, t1.NRDCONTA, t1.DHREGISTRO, t1.DHEFETIVACAO, t1.CDSITUACAO, t1.IDHORARIO_PERIODO)
		VALUES(t2.CDCOOPER, t2.NRDCONTA, sysdate, sysdate, 1, 1);
	commit;
end; 