DECLARE
BEGIN
	UPDATE CECRED.TBGEN_NOTIF_MSG_CADASTRO SET DSHTML_MENSAGEM = '#NomeCooperado, <br><br>O ajuste de limite Pix que você solicitou foi realizado com sucesso. <br><br>Novos limites: <br><br>DIURNO <br>Período: R$ #LimiteDiurno <br>Transação: R$ #PorTransacaoLimiteDiurno <br><br>NOTURNO <br>Período: R$ #LimiteNoturno <br>Transação: R$ #PorTransacaoLimiteNoturno <br><br>Para mais informações sobre Limites Pix, acesse a seção de dúvidas.' WHERE CDMENSAGEM = 9280 AND CDORIGEM_MENSAGEM = 13 AND DSTITULO_MENSAGEM = 'Alteração de limites Pix';
	UPDATE CECRED.TBGEN_NOTIF_MSG_CADASTRO SET DSHTML_MENSAGEM = '#NomeCooperado, <br><br>O ajuste de limite Pix Saque e Pix Troco que você solicitou foi realizado com sucesso. <br><br>Novos limites: <br><br>DIURNO <br>Período: R$ #LimiteDiurno <br>Transação: R$ #PorTransacaoLimiteDiurno <br><br>NOTURNO <br>Período: R$ #LimiteNoturno <br>Transação: R$ #PorTransacaoLimiteNoturno <br><br>Para mais informações sobre Limites Pix, acesse a seção de dúvidas.' WHERE CDMENSAGEM = 9281 AND CDORIGEM_MENSAGEM = 13 AND DSTITULO_MENSAGEM = 'Alteração de limites Pix Saque/Troco';
	UPDATE CECRED.TBGEN_NOTIF_MSG_CADASTRO SET DSHTML_MENSAGEM = '#NomeCooperado, <br><br>O ajuste de limite Pix que você solicitou foi realizado com sucesso. <br><br>Dados da Conta: <br><br>Nome: #NomeContaCadastrada <br>Banco: #BancoContaCadastrada <br>Agência: #AgenciaContaCadastrada <br>Conta: #NumeroContaCadastrada <br>Novos limites: <br><br>DIURNO <br>Período: R$ #LimiteDiurno <br>Transação: R$ #PorTransacaoLimiteDiurno <br><br>NOTURNO <br>Período: R$ #LimiteNoturno <br>Transação: R$ #PorTransacaoLimiteNoturno <br><br>Para mais informações sobre Limites Pix, acesse a seção de dúvidas.' WHERE CDMENSAGEM = 9282 AND CDORIGEM_MENSAGEM = 13 AND DSTITULO_MENSAGEM = 'Alteração de limites Pix de uma conta cadastrada';
	UPDATE CECRED.TBGEN_NOTIF_MSG_CADASTRO SET DSHTML_MENSAGEM = '#nomeCooperado, <br><br>O aumento de limite máximo do Pix que você solicitou foi realizado com sucesso. <br><br>Novo limite máximo: R$#novoLimite. <br><br>Para mais informações sobre Limites Pix, acesse a seção de dúvidas.' WHERE CDMENSAGEM = 9283 AND CDORIGEM_MENSAGEM = 13 AND DSTITULO_MENSAGEM = 'Aumento de limite máximo do Pix';
	UPDATE CECRED.TBGEN_NOTIF_MSG_CADASTRO SET DSHTML_MENSAGEM = '#nomeCooperado, <br><br>O cadastro da conta que você solicitou foi realizado com sucesso. Você já pode gerenciar de forma personalizada os limites Pix dessa conta. <br><br>Dados da Conta: <br><br>Nome: #nomeContaCadastrada <br>Banco: #bancoContaCadastrada <br>Agência: #agenciaContaCadastrada <br>Conta: #numeroContaCadastrada <br><br>Para mais informações sobre Limites Pix, acesse a seção de dúvidas.' WHERE CDMENSAGEM = 9284 AND CDORIGEM_MENSAGEM = 13 AND DSTITULO_MENSAGEM = 'Efetivação de uma conta cadastrada';
	UPDATE CECRED.TBGEN_NOTIF_MSG_CADASTRO SET DSHTML_MENSAGEM = '#nomeCooperado, <br><br>A alteração de horário do período noturno que você solicitou foi realizada com sucesso. <br><br>Novo horário do período noturno: <br><br>Início: #horarioInicio <br>Fim: #horarioFim <br><br>Para mais informações sobre Limites Pix, acesse a seção de dúvidas.' WHERE CDMENSAGEM = 9285 AND CDORIGEM_MENSAGEM = 13 AND DSTITULO_MENSAGEM = 'Efetivação de novo horário noturno';
COMMIT;
END;