declare
begin
	INSERT INTO PIX.TBPIX_PERIODO (IDPERIODO, NMPERIODO) VALUES(1, 'Diurno');
	INSERT INTO PIX.TBPIX_PERIODO (IDPERIODO, NMPERIODO) VALUES(2, 'Noturno');


	INSERT INTO PIX.TBPIX_TIPO_LIMITE (IDTIPO_LIMITE, NMTIPO_LIMITE) VALUES(1, 'Transferencia');
	INSERT INTO PIX.TBPIX_TIPO_LIMITE (IDTIPO_LIMITE, NMTIPO_LIMITE) VALUES(2, 'Saque Troco');
	INSERT INTO PIX.TBPIX_TIPO_LIMITE (IDTIPO_LIMITE, NMTIPO_LIMITE) VALUES(3, 'Conta Cadastrada');


	INSERT INTO PIX.TBPIX_HORARIO_PERIODO (IDHORARIO_PERIODO, IDPERIODO, DHREGISTRO, FLPADRAO, DHINATIVACAO, NRHORA_INICIO, NRHORA_FIM)
	VALUES(1, 2, SYSDATE, 1, NULL, 20, 6);

	INSERT INTO PIX.TBPIX_HORARIO_PERIODO (IDHORARIO_PERIODO, IDPERIODO, DHREGISTRO, FLPADRAO, DHINATIVACAO, NRHORA_INICIO, NRHORA_FIM)
	VALUES(2, 2, SYSDATE, 0, NULL, 22, 6);
	commit;
end;
