BEGIN  
  /************************************/
  /*  INSERT DOMINIO CANAL E STATUS REVISÃO   */
  /************************************/
  INSERT INTO TBCADAST_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO) VALUES ('TBCADAST_CANAL', 1, 'IB');
  INSERT INTO TBCADAST_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO) VALUES ('TBCADAST_CANAL', 2, 'Mobile');
  INSERT INTO TBCADAST_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO) VALUES ('TBCADAST_STATUSREVISAO', 1, 'Confirmado');
  INSERT INTO TBCADAST_DOMINIO_CAMPO (NMDOMINIO, CDDOMINIO, DSCODIGO) VALUES ('TBCADAST_STATUSREVISAO', 2, 'Não confirmado'); 
  
  COMMIT;
END;
