begin
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABdAAA2GnAAK';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABjAAB+QiAAg';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABdAAA2jvAAM';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABbAAB0PiAAd';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABeAABVNWAAN';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABcAAA9+JAAi';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABbAAOIVGAAK';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABiAACFGEAAI';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABeAABU4oAAK';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABkAAB3ySAAh';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABiAABQ35AAM';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABeAAEGZqAAR';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABbAAB1ktAAJ';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABbAAAVHrAAZ';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABeAABUSZAAL';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABiAABQsIAAV';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABfAAB32+AAU';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABbAAOHH5AAC';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABiAABUiKAAR';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABbAAAVxcAAV';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABkAAAVk5AAd';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABeAAApb4AAB';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABbAADmTTAAa';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABcAAH5WWAAj';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABgAAD6HwAAY';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABgAABwiIAAg';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABbAABAZTAAC';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABkAAASrpAAX';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABjAABQ6AAAR';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABdAACMLmAAI';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABgAAB0KEAAP';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABbAAOHnhAAP';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABkAADCGrAAN';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABgAABwrnAAV';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABdAACMYYAAK';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABcAACGISAAZ';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABgAAD7F7AAf';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABfAACxKfAAE';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABjAAASE3AAU';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABgAABwsqAAe';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABeAAAopHAAl';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABdAABbJRAAX';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABkAAAVRFAAO';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABkAAAVURAAY';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABdAAEa3rAAK';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABgAABxyZAAa';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABkAAAWAcAAB';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABkAAAWAcAAG';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABbAAB2KLAAP';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABbAAAV9XAAT';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABkAAAS+vAAS';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABeAABVBNAAQ';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABdAABaQeAAr';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABiAAA4CPAAU';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABiAACFz8AAP';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABbAAB0SwAAP';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABfAAB4GlAAH';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABfAAB209AAT';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABiAAAS5EAAU';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABgAAD6CgAAF';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABgAAD6KhAAP';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABdAABai+AAE';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABfAABRtmAAF';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABfAABRtmAAI';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABiAABQgCAAI';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABhAABeq9AAN';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABbAABBqtAAJ';
	update crapcob set dsdinstr = ' ' where rowid = 'AAAS/0ABbAAOIKTAAI';
	commit;
  EXCEPTION
    WHEN others THEN
	  CECRED.pc_internal_exception;
	  rollback;
end;