/* 
Solicitação: INC0014558
Objetivo   : Corrigir o valor da coluna CRAPCEM.DSDEMAIL de todos o associados que contém algum caracter inválido
             para endereço de email nesta coluna.
             Há casos que o sistema está permitindo a entrada de alguns caracteres inválidos ao registrar o endereço de email.
Autor      : Edmar
*/

update CRAPCEM set DSDEMAIL = 'contabilidade@alljabercompany.com.br' where PROGRESS_RECID = 541148;
update CRAPCEM set DSDEMAIL = 'marcos.gandolfo@uol.com.br' where PROGRESS_RECID = 56750;
update CRAPCEM set DSDEMAIL = 'jjoaok@gmail.com' where PROGRESS_RECID = 220060;
update CRAPCEM set DSDEMAIL = 'wellington_bnu@hotmail.com' where PROGRESS_RECID = 211051;
update CRAPCEM set DSDEMAIL = 'lete.contabil@gmail.com' where PROGRESS_RECID = 53493;
update CRAPCEM set DSDEMAIL = 'schuminha@gmail.com' where PROGRESS_RECID = 20781;
update CRAPCEM set DSDEMAIL = 'vera@wtscobrana.com.br' where PROGRESS_RECID = 4036;
update CRAPCEM set DSDEMAIL = 'jjoaol@gmail.com' where PROGRESS_RECID = 220084;
update CRAPCEM set DSDEMAIL = 'dalmerinda@yahoo.com.br' where PROGRESS_RECID = 218827;
update CRAPCEM set DSDEMAIL = 'sheronwcampinas@gmail.combr' where PROGRESS_RECID = 207750;
update CRAPCEM set DSDEMAIL = 'gracielalorenz@gmail.com' where PROGRESS_RECID = 218822;
update CRAPCEM set DSDEMAIL = 'rodrigo@wegeinternational.de' where PROGRESS_RECID = 186014;
update CRAPCEM set DSDEMAIL = 'rosebrian46@hotmail.com' where PROGRESS_RECID = 5458;
update CRAPCEM set DSDEMAIL = 'cris.amaral@gmail.com' where PROGRESS_RECID = 35658;
update CRAPCEM set DSDEMAIL = 'stececarneirojardinagem@hotmail.com' where PROGRESS_RECID = 36011;
update CRAPCEM set DSDEMAIL = 'ahptrasnporte@hotmail.com' where PROGRESS_RECID = 187454;
update CRAPCEM set DSDEMAIL = 'contabilidade@alljabercompany.com.br' where PROGRESS_RECID = 541149;
update CRAPCEM set DSDEMAIL = 'tintasneiumann@yahoo.com.br' where PROGRESS_RECID = 13240;
update CRAPCEM set DSDEMAIL = 'patricktreiss@bol.com.br' where PROGRESS_RECID = 111489;
update CRAPCEM set DSDEMAIL = 'dayany04@hotmailcom' where PROGRESS_RECID = 66901;
update CRAPCEM set DSDEMAIL = 'cecrisacred@cecrisacred.coopbr' where PROGRESS_RECID = 132513;
update CRAPCEM set DSDEMAIL = 'lucaselias007@hotmail.com' where PROGRESS_RECID = 132571;
update CRAPCEM set DSDEMAIL = 'bruna_100gatinha@hotmail.com' where PROGRESS_RECID = 46161;
update CRAPCEM set DSDEMAIL = 'elicleptomsilva19@gmail.com' where PROGRESS_RECID = 46716;
update CRAPCEM set DSDEMAIL = 'daniellaodail@hotmail.com' where PROGRESS_RECID = 94354;
update CRAPCEM set DSDEMAIL = 'paulopleno@live.com' where PROGRESS_RECID = 94486;
update CRAPCEM set DSDEMAIL = 'rgi_b@hotmail.com' where PROGRESS_RECID = 61328;
update CRAPCEM set DSDEMAIL = 'anny_ponchirolli@hotmail.com' where PROGRESS_RECID = 83265;
update CRAPCEM set DSDEMAIL = 'eneidess@yahoo.combr' where PROGRESS_RECID = 40719;
update CRAPCEM set DSDEMAIL = 'jake206pim@gmail.com' where PROGRESS_RECID = 76203;
update CRAPCEM set DSDEMAIL = 'airto.monteiro@hotmail.com' where PROGRESS_RECID = 76965;
update CRAPCEM set DSDEMAIL = 'juarez_filho@cargill.com' where PROGRESS_RECID = 7530;
update CRAPCEM set DSDEMAIL = 'giovanichavesviacredi@gmail.com' where PROGRESS_RECID = 8791;
update CRAPCEM set DSDEMAIL = 'gustavo.lopes.15@hotmail.com' where PROGRESS_RECID = 103349;
update CRAPCEM set DSDEMAIL = 'deciosilva@hotmail.com' where PROGRESS_RECID = 264051;
update CRAPCEM set DSDEMAIL = 'alceu@grameyer.com.b' where PROGRESS_RECID = 248019;
update CRAPCEM set DSDEMAIL = 'christianlkoch@hotmail.com' where PROGRESS_RECID = 225006;
update CRAPCEM set DSDEMAIL = 'amsvendas@yahoocom.br' where PROGRESS_RECID = 180290;
update CRAPCEM set DSDEMAIL = 'db_jeh@hotmail.com' where PROGRESS_RECID = 235774;
update CRAPCEM set DSDEMAIL = 'dilceu.noll@hotmail.com' where PROGRESS_RECID = 199860;
update CRAPCEM set DSDEMAIL = 'paulin_hai_tj@hotmail.com' where PROGRESS_RECID = 159174;
update CRAPCEM set DSDEMAIL = 'selma.fraga@fns.emosc.orgbr' where PROGRESS_RECID = 151131;
update CRAPCEM set DSDEMAIL = 'diogoharoldo.reinert@gail.com' where PROGRESS_RECID = 544013;
update CRAPCEM set DSDEMAIL = 'diogoharoldo.reinert@gail.com' where PROGRESS_RECID = 544014;
update CRAPCEM set DSDEMAIL = 'sidinei.fontoura@hotmail.com' where PROGRESS_RECID = 69924;
update CRAPCEM set DSDEMAIL = 'joelcio_100eu@hotmail.com' where PROGRESS_RECID = 70844;
update CRAPCEM set DSDEMAIL = 'luiz.mertens.cavaillier@gail.com' where PROGRESS_RECID = 57498;
update CRAPCEM set DSDEMAIL = 'valmir@mnh.com.br' where PROGRESS_RECID = 58139;
update CRAPCEM set DSDEMAIL = 'douglasdeleon@hotmail.com' where PROGRESS_RECID = 191407;
update CRAPCEM set DSDEMAIL = 'johannespaulo@gmail.com' where PROGRESS_RECID = 213580;
update CRAPCEM set DSDEMAIL = 'daialoka@hotmail.com' where PROGRESS_RECID = 50841;
update CRAPCEM set DSDEMAIL = 'luana.m.nasc@hotmail.com' where PROGRESS_RECID = 64192;
update CRAPCEM set DSDEMAIL = 'crisfab@hotmail.com' where PROGRESS_RECID = 89534;
update CRAPCEM set DSDEMAIL = 'leonardo@sci10.combr' where PROGRESS_RECID = 89942;
update CRAPCEM set DSDEMAIL = 'MSNadry_ser@terra.com.br' where PROGRESS_RECID = 13958;
update CRAPCEM set DSDEMAIL = 'edianemonteiro.927@gmail.com' where PROGRESS_RECID = 216831;
update CRAPCEM set DSDEMAIL = 'jairborba@hotmail.com' where PROGRESS_RECID = 220455;
update CRAPCEM set DSDEMAIL = 'autopecaslassen@boll.combr' where PROGRESS_RECID = 122937;
update CRAPCEM set DSDEMAIL = 'jeanci92@outlookcom' where PROGRESS_RECID = 123622;
update CRAPCEM set DSDEMAIL = 'luciane_d@gmail.com' where PROGRESS_RECID = 181732;
update CRAPCEM set DSDEMAIL = 'destakpintura@hotmail.com' where PROGRESS_RECID = 203677;
update CRAPCEM set DSDEMAIL = 'eng.filipepozzo@gmail.com' where PROGRESS_RECID = 261004;
update CRAPCEM set DSDEMAIL = 'haltaengenharia@hotmail.com' where PROGRESS_RECID = 252864;
update CRAPCEM set DSDEMAIL = 'guinchosfortaleza@gmail.com' where PROGRESS_RECID = 258223;
update CRAPCEM set DSDEMAIL = 'vitorbronsani@hotmailcom' where PROGRESS_RECID = 548317;
update CRAPCEM set DSDEMAIL = 'tatah.vitor@gmail.com' where PROGRESS_RECID = 127220;
update CRAPCEM set DSDEMAIL = 'alvarohostert@gail.com' where PROGRESS_RECID = 26205;
update CRAPCEM set DSDEMAIL = 'gilson@facil.artbr' where PROGRESS_RECID = 67516;
update CRAPCEM set DSDEMAIL = 'jeanvanessa@hotamil.com' where PROGRESS_RECID = 69505;
update CRAPCEM set DSDEMAIL = 'worldsports@brturbo' where PROGRESS_RECID = 19458;
update CRAPCEM set DSDEMAIL = 'vitor.botega@fiesc.net.br' where PROGRESS_RECID = 137720;
update CRAPCEM set DSDEMAIL = 'feristow@yahoo.com.br' where PROGRESS_RECID = 241448;
update CRAPCEM set DSDEMAIL = 'silvana.cetebra@hotmail.com' where PROGRESS_RECID = 207425;
update CRAPCEM set DSDEMAIL = 'mauriciopoltranieri@hotmailcom' where PROGRESS_RECID = 208009;
update CRAPCEM set DSDEMAIL = 'burghardtsimone@yahoo.com.br' where PROGRESS_RECID = 265814;
update CRAPCEM set DSDEMAIL = 'carlostriangulo@gmail.comrecado' where PROGRESS_RECID = 121998;
update CRAPCEM set DSDEMAIL = 'ricardischuster.80@gmailcom' where PROGRESS_RECID = 122151;
update CRAPCEM set DSDEMAIL = 'beibi.tavares@gmail.com' where PROGRESS_RECID = 75123;
update CRAPCEM set DSDEMAIL = 'gabriel040795@hotmail.com' where PROGRESS_RECID = 100926;
update CRAPCEM set DSDEMAIL = 'supervisao.join@terra.com.br' where PROGRESS_RECID = 101347;
update CRAPCEM set DSDEMAIL = 'elfie27@hotmail.com' where PROGRESS_RECID = 162605;
update CRAPCEM set DSDEMAIL = 'alexandrocrocetti@hotmail.com' where PROGRESS_RECID = 230571;
update CRAPCEM set DSDEMAIL = 'ana@biocal.ind.br' where PROGRESS_RECID = 228604;
update CRAPCEM set DSDEMAIL = 'rosani.avila@hotmail.com' where PROGRESS_RECID = 244042;
update CRAPCEM set DSDEMAIL = 'wigoldkleinschmidt@gmail.com' where PROGRESS_RECID = 237476;
update CRAPCEM set DSDEMAIL = 'luzidei@waylogistics.com.br' where PROGRESS_RECID = 244184;
update CRAPCEM set DSDEMAIL = 'atendimento@imoveiskessler.com.br' where PROGRESS_RECID = 238004;
update CRAPCEM set DSDEMAIL = 'rafa_mateus.10@hotmail.com' where PROGRESS_RECID = 177155;
update CRAPCEM set DSDEMAIL = 'debrassifabiano@gmail.com' where PROGRESS_RECID = 174401;
update CRAPCEM set DSDEMAIL = 'mayara.odorizzi@hotmail.com' where PROGRESS_RECID = 169947;
update CRAPCEM set DSDEMAIL = 'leandrovendrami@msn.com' where PROGRESS_RECID = 170750;
update CRAPCEM set DSDEMAIL = 'graficatimbo@graficatimbo.com.br' where PROGRESS_RECID = 236618;
update CRAPCEM set DSDEMAIL = 'nuna.ass@hotmail.com' where PROGRESS_RECID = 234303;
update CRAPCEM set DSDEMAIL = 'arthur@brandili.com.br' where PROGRESS_RECID = 22535;
update CRAPCEM set DSDEMAIL = 'rafael.machado@amctextil.com.br' where PROGRESS_RECID = 523843;
update CRAPCEM set DSDEMAIL = 'fernandopeschelrn@yahoo.combr' where PROGRESS_RECID = 165345;
update CRAPCEM set DSDEMAIL = 'trans.minatto@brturbo.combr' where PROGRESS_RECID = 153776;
update CRAPCEM set DSDEMAIL = 'CFRUET@HERINGNET.COMBR' where PROGRESS_RECID = 106;
update CRAPCEM set DSDEMAIL = 'comercial3@pollyformaturas.com.br' where PROGRESS_RECID = 174020;
update CRAPCEM set DSDEMAIL = 'taiane.scavin@hotmail.com' where PROGRESS_RECID = 555536;
update CRAPCEM set DSDEMAIL = 'dmp@cecrisa.com.br' where PROGRESS_RECID = 131590;
update CRAPCEM set DSDEMAIL = 'eliane-anezia@hotmail.com' where PROGRESS_RECID = 269246;
update CRAPCEM set DSDEMAIL = 'marcelinokreuch@hotmail.com' where PROGRESS_RECID = 269821;
update CRAPCEM set DSDEMAIL = 'dinoradr@yahoo.combr' where PROGRESS_RECID = 272506;
update CRAPCEM set DSDEMAIL = 'rafaelhermann@ig.com.br' where PROGRESS_RECID = 269725;
update CRAPCEM set DSDEMAIL = 'lucas@cukafilmes.combr' where PROGRESS_RECID = 272487;
update CRAPCEM set DSDEMAIL = 'johnnypatrick767@gmailcom' where PROGRESS_RECID = 277523;
update CRAPCEM set DSDEMAIL = 'lavajatolima@gmail.com' where PROGRESS_RECID = 272453;
update CRAPCEM set DSDEMAIL = 'katia@escoblu.com' where PROGRESS_RECID = 277412;
update CRAPCEM set DSDEMAIL = 'diego@bmasistemas.com.br' where PROGRESS_RECID = 273612;
update CRAPCEM set DSDEMAIL = 'heo.kleba@hotmail.com' where PROGRESS_RECID = 283330;
update CRAPCEM set DSDEMAIL = 'lusale@desbrava.com.br' where PROGRESS_RECID = 291957;
update CRAPCEM set DSDEMAIL = 'alex@confiancecondomnios.com.br' where PROGRESS_RECID = 290265;
update CRAPCEM set DSDEMAIL = 'jurdico@arbengenharia.com.br' where PROGRESS_RECID = 281961;
update CRAPCEM set DSDEMAIL = 'magdaadami@yahoo.com.br' where PROGRESS_RECID = 287213;
update CRAPCEM set DSDEMAIL = 'graa__nascimento@outlook.com' where PROGRESS_RECID = 292031;
update CRAPCEM set DSDEMAIL = 'tfcolocao@hotmail.com' where PROGRESS_RECID = 284153;
update CRAPCEM set DSDEMAIL = 'rdnutrioanimal@hotmail.com' where PROGRESS_RECID = 291142;
update CRAPCEM set DSDEMAIL = 'rdnutrioanimal@hotmail.com' where PROGRESS_RECID = 291822;
update CRAPCEM set DSDEMAIL = 'willianniquelatti@gmail.com' where PROGRESS_RECID = 285143;
update CRAPCEM set DSDEMAIL = 'adriana@benetex.ind.br' where PROGRESS_RECID = 288429;
update CRAPCEM set DSDEMAIL = 'erika.pslo@hotmail.co' where PROGRESS_RECID = 286163;
update CRAPCEM set DSDEMAIL = 'vilma2012@hotmail.combr' where PROGRESS_RECID = 288542;
update CRAPCEM set DSDEMAIL = 'marcyy04@gmail.com' where PROGRESS_RECID = 348201;
update CRAPCEM set DSDEMAIL = 'charles@ferrarilogistica.combr' where PROGRESS_RECID = 355069;
update CRAPCEM set DSDEMAIL = 'lete.contabil@gmail.com' where PROGRESS_RECID = 525395;
update CRAPCEM set DSDEMAIL = 'lete.contabil@gmail.com' where PROGRESS_RECID = 525397;
update CRAPCEM set DSDEMAIL = 'danielcredifiesc@sqlambda.com' where PROGRESS_RECID = 501845;
update CRAPCEM set DSDEMAIL = 'gabriel@confiancecondomnios.com.br' where PROGRESS_RECID = 361564;
update CRAPCEM set DSDEMAIL = 'hidrafer.mc@hotmail.com' where PROGRESS_RECID = 355313;
update CRAPCEM set DSDEMAIL = 'mariliasilva02@bol.combr' where PROGRESS_RECID = 366013;
update CRAPCEM set DSDEMAIL = 'scotti@nanovetores.com.br' where PROGRESS_RECID = 359496;
update CRAPCEM set DSDEMAIL = 'luizsim@hotmailcom' where PROGRESS_RECID = 361474;
update CRAPCEM set DSDEMAIL = 'wagner@dhablioprototipos.com.br' where PROGRESS_RECID = 352904;
update CRAPCEM set DSDEMAIL = 'taiane.scavin@hotmail.com' where PROGRESS_RECID = 353430;
update CRAPCEM set DSDEMAIL = 'arielmax.bk@gmail.com' where PROGRESS_RECID = 361787;
update CRAPCEM set DSDEMAIL = 'matheus_luis_c@hotmailcom' where PROGRESS_RECID = 351830;
update CRAPCEM set DSDEMAIL = 'valmir@networkinfo.com.br' where PROGRESS_RECID = 358436;
update CRAPCEM set DSDEMAIL = 'edigdesigner@gmail.com' where PROGRESS_RECID = 369512;
update CRAPCEM set DSDEMAIL = 'raquel.tietjen@buhlergroup.com' where PROGRESS_RECID = 376191;
update CRAPCEM set DSDEMAIL = 'cleusa.pamplona@hotmail.com' where PROGRESS_RECID = 367390;
update CRAPCEM set DSDEMAIL = 'wanderleiferreiradesouza@gmail.co' where PROGRESS_RECID = 376643;
update CRAPCEM set DSDEMAIL = 'felipe@spessattocom' where PROGRESS_RECID = 374306;
update CRAPCEM set DSDEMAIL = 'allan_machado91@hotmailcom' where PROGRESS_RECID = 390544;
update CRAPCEM set DSDEMAIL = 'rh@racitecempreendimentoscombr' where PROGRESS_RECID = 387981;
update CRAPCEM set DSDEMAIL = 'contabilidadehercules@hotmail.com' where PROGRESS_RECID = 380590;
update CRAPCEM set DSDEMAIL = 'marlene_gs@outlook.com' where PROGRESS_RECID = 390227;
update CRAPCEM set DSDEMAIL = 'rosaneangela@gmail.com' where PROGRESS_RECID = 388115;
update CRAPCEM set DSDEMAIL = 'rh@racitecempreendimentos.combr' where PROGRESS_RECID = 387874;
update CRAPCEM set DSDEMAIL = 'giljunior19@hotmail.com' where PROGRESS_RECID = 382639;
update CRAPCEM set DSDEMAIL = 'leonardo@bascel.combr' where PROGRESS_RECID = 388697;
update CRAPCEM set DSDEMAIL = 'cleiton.anselmo7@gmail.com' where PROGRESS_RECID = 385283;
update CRAPCEM set DSDEMAIL = 'bkestiva@gmailcom' where PROGRESS_RECID = 389090;
update CRAPCEM set DSDEMAIL = 'soaresaldair1994@gmail.com' where PROGRESS_RECID = 390936;
update CRAPCEM set DSDEMAIL = 'fehmalaguttyy@gmail.com' where PROGRESS_RECID = 410279;
update CRAPCEM set DSDEMAIL = 'rafael.machado@amctextil.com.br' where PROGRESS_RECID = 404910;
update CRAPCEM set DSDEMAIL = 'mecanicann2017@gmail.com' where PROGRESS_RECID = 404863;
update CRAPCEM set DSDEMAIL = 'zita861@hotmail.com' where PROGRESS_RECID = 402797;
update CRAPCEM set DSDEMAIL = 'danieladallorsoletta@gmail.com' where PROGRESS_RECID = 415604;
update CRAPCEM set DSDEMAIL = 'danielcredifiesc@sqlambda.com' where PROGRESS_RECID = 397364;
update CRAPCEM set DSDEMAIL = 'marcos@sulphones.combr' where PROGRESS_RECID = 391360;
update CRAPCEM set DSDEMAIL = 'carlos_sorac_53@hotmail.com' where PROGRESS_RECID = 402610;
update CRAPCEM set DSDEMAIL = 'sueki_odonto@hotmail.com' where PROGRESS_RECID = 416417;
update CRAPCEM set DSDEMAIL = 'darciovolkmann59@gmailcom' where PROGRESS_RECID = 417279;
update CRAPCEM set DSDEMAIL = 'leaozinhocei@gmail.co' where PROGRESS_RECID = 401463;
update CRAPCEM set DSDEMAIL = 'marialpamplona@hotmail.com' where PROGRESS_RECID = 397031;
update CRAPCEM set DSDEMAIL = 'matheusrodrigues-s@hotmail.com' where PROGRESS_RECID = 399303;
update CRAPCEM set DSDEMAIL = 'cantinhodobichopetshop@hotmail.com' where PROGRESS_RECID = 407823;
update CRAPCEM set DSDEMAIL = 'andreimotta2014@outolk.com' where PROGRESS_RECID = 405083;
update CRAPCEM set DSDEMAIL = 'nathielly@catolicasc.orgbr' where PROGRESS_RECID = 403118;
update CRAPCEM set DSDEMAIL = 'rafa144_itj@yahoo.com.br' where PROGRESS_RECID = 396362;
update CRAPCEM set DSDEMAIL = 'luian_junio@outlook.co.br' where PROGRESS_RECID = 416818;
update CRAPCEM set DSDEMAIL = 'posto.toretti@hotmailcom' where PROGRESS_RECID = 420382;
update CRAPCEM set DSDEMAIL = 'seffcelesccredelesc@gmail.com' where PROGRESS_RECID = 421781;
update CRAPCEM set DSDEMAIL = 'antoniocmarkus@gmail.com' where PROGRESS_RECID = 422381;
update CRAPCEM set DSDEMAIL = 'danielen@cvg.ind.br' where PROGRESS_RECID = 423480;
update CRAPCEM set DSDEMAIL = 'contato@mkoser.com.brcategorias' where PROGRESS_RECID = 425149;
update CRAPCEM set DSDEMAIL = 'danielarnold@sqlambda.com' where PROGRESS_RECID = 428147;
update CRAPCEM set DSDEMAIL = 'godrigo99@hotmail.comacoes' where PROGRESS_RECID = 431969;
update CRAPCEM set DSDEMAIL = 'daisepereira@hotmail.com' where PROGRESS_RECID = 430696;
update CRAPCEM set DSDEMAIL = 'felipesehnem07@gmail.co' where PROGRESS_RECID = 439255;
update CRAPCEM set DSDEMAIL = 'nicalexmaico@gmail.com' where PROGRESS_RECID = 430243;
update CRAPCEM set DSDEMAIL = 'yagogall@icloud.com' where PROGRESS_RECID = 433210;
update CRAPCEM set DSDEMAIL = 'dr872654@gmail.com' where PROGRESS_RECID = 436084;
update CRAPCEM set DSDEMAIL = 'ni.alinerosa@gmail.com' where PROGRESS_RECID = 431160;
update CRAPCEM set DSDEMAIL = 'cristiano.risantos@gmail.com' where PROGRESS_RECID = 428676;
update CRAPCEM set DSDEMAIL = 'juniorvieiralost@hotmailcom' where PROGRESS_RECID = 447209;
update CRAPCEM set DSDEMAIL = 'marcoscar38@gmail.com' where PROGRESS_RECID = 442421;
update CRAPCEM set DSDEMAIL = 'vitorgondim0107@gmail.com' where PROGRESS_RECID = 451195;
update CRAPCEM set DSDEMAIL = 'janafilhosmarhotel@hotmail.com' where PROGRESS_RECID = 445855;
update CRAPCEM set DSDEMAIL = 'emanuellymorgana.andre@outlook.com.br' where PROGRESS_RECID = 448855;
update CRAPCEM set DSDEMAIL = 'mazilialinda59@gmail.com' where PROGRESS_RECID = 437142;
update CRAPCEM set DSDEMAIL = 'antoniojpaula@yahoo.com.br' where PROGRESS_RECID = 445789;
update CRAPCEM set DSDEMAIL = 'vidracaria_oliveira@yahoo.combr' where PROGRESS_RECID = 447352;
update CRAPCEM set DSDEMAIL = 'transpspenglersc@terra.com.br' where PROGRESS_RECID = 448331;
update CRAPCEM set DSDEMAIL = 'joseglazarotto@gmailcom' where PROGRESS_RECID = 448290;
update CRAPCEM set DSDEMAIL = 'teste@teste.com.br' where PROGRESS_RECID = 442075;
update CRAPCEM set DSDEMAIL = 'renatohafermann@gmail.co' where PROGRESS_RECID = 446822;
update CRAPCEM set DSDEMAIL = 'edcampos05@hotmailcom' where PROGRESS_RECID = 445049;
update CRAPCEM set DSDEMAIL = 'elainebrand@terra.com.br' where PROGRESS_RECID = 450479;
update CRAPCEM set DSDEMAIL = 'alinegarcia35@gmail.com' where PROGRESS_RECID = 447403;
update CRAPCEM set DSDEMAIL = 'deisesarturi2006@yahoo.com.br' where PROGRESS_RECID = 453283;
update CRAPCEM set DSDEMAIL = 'seffcelesccredelesc@gmail.com' where PROGRESS_RECID = 464318;
update CRAPCEM set DSDEMAIL = 'luiz.mertens.cavaillier@gail.com' where PROGRESS_RECID = 461274;
update CRAPCEM set DSDEMAIL = 'marcos@sulphones.combr' where PROGRESS_RECID = 502523;
update CRAPCEM set DSDEMAIL = 'dayany04@hotmailcom' where PROGRESS_RECID = 454584;
update CRAPCEM set DSDEMAIL = 'dayany04@hotmailcom' where PROGRESS_RECID = 454586;
update CRAPCEM set DSDEMAIL = 'dayany04@hotmailcom' where PROGRESS_RECID = 454588;
update CRAPCEM set DSDEMAIL = 'leandrovendrami@msn.com' where PROGRESS_RECID = 485599;
update CRAPCEM set DSDEMAIL = 'juniorvieiralost@hotmailcom' where PROGRESS_RECID = 484351;
update CRAPCEM set DSDEMAIL = 'rafaelhermann@ig.com.br' where PROGRESS_RECID = 478707;
update CRAPCEM set DSDEMAIL = 'marcelinokreuch@hotmail.com' where PROGRESS_RECID = 481261;
update CRAPCEM set DSDEMAIL = 'silvana.cetebra@hotmail.com' where PROGRESS_RECID = 476321;
update CRAPCEM set DSDEMAIL = 'marcos.gandolfo@uol.com.br' where PROGRESS_RECID = 474827;
update CRAPCEM set DSDEMAIL = 'paulin_hai_tj@hotmail.com' where PROGRESS_RECID = 470716;
update CRAPCEM set DSDEMAIL = 'wigoldkleinschmidt@gmail.com' where PROGRESS_RECID = 506462;
update CRAPCEM set DSDEMAIL = 'sueki_odonto@hotmail.com' where PROGRESS_RECID = 506553;
update CRAPCEM set DSDEMAIL = 'marialpamplona@hotmail.com' where PROGRESS_RECID = 504386;
update CRAPCEM set DSDEMAIL = 'dilceu.noll@hotmail.com' where PROGRESS_RECID = 511138;
update CRAPCEM set DSDEMAIL = 'dilceu.noll@hotmail.com' where PROGRESS_RECID = 511139;
update CRAPCEM set DSDEMAIL = 'dilceu.noll@hotmail.com' where PROGRESS_RECID = 511140;
update CRAPCEM set DSDEMAIL = 'charles@ferrarilogistica.combr' where PROGRESS_RECID = 509644;
update CRAPCEM set DSDEMAIL = 'arthur@brandili.com.br' where PROGRESS_RECID = 492474;
update CRAPCEM set DSDEMAIL = 'teste@teste.com.br' where PROGRESS_RECID = 498608;
update CRAPCEM set DSDEMAIL = 'mariliasilva02@bol.combr' where PROGRESS_RECID = 497070;
update CRAPCEM set DSDEMAIL = 'matheusrodrigues-s@hotmail.com' where PROGRESS_RECID = 497487;
update CRAPCEM set DSDEMAIL = 'nuna.ass@hotmail.com' where PROGRESS_RECID = 491491;
update CRAPCEM set DSDEMAIL = 'joelcio_100eu@hotmail.com' where PROGRESS_RECID = 491619;
update CRAPCEM set DSDEMAIL = 'joelcio_100eu@hotmail.com' where PROGRESS_RECID = 491620;
update CRAPCEM set DSDEMAIL = 'joelcio_100eu@hotmail.com' where PROGRESS_RECID = 491621;
update CRAPCEM set DSDEMAIL = 'jeanci92@outlookcom' where PROGRESS_RECID = 495921;
update CRAPCEM set DSDEMAIL = 'cecrisacred@cecrisacred.coopbr' where PROGRESS_RECID = 532549;
update CRAPCEM set DSDEMAIL = 'cecrisacred@cecrisacred.coopbr' where PROGRESS_RECID = 532551;
update CRAPCEM set DSDEMAIL = 'cecrisacred@cecrisacred.coopbr' where PROGRESS_RECID = 532553;
update CRAPCEM set DSDEMAIL = 'cecrisacred@cecrisacred.coopbr' where PROGRESS_RECID = 532555;
update CRAPCEM set DSDEMAIL = 'cecrisacred@cecrisacred.coopbr' where PROGRESS_RECID = 532557;
update CRAPCEM set DSDEMAIL = 'cecrisacred@cecrisacred.coopbr' where PROGRESS_RECID = 532559;
update CRAPCEM set DSDEMAIL = 'cecrisacred@cecrisacred.coopbr' where PROGRESS_RECID = 532561;
update CRAPCEM set DSDEMAIL = 'cecrisacred@cecrisacred.coopbr' where PROGRESS_RECID = 532563;
update CRAPCEM set DSDEMAIL = 'cecrisacred@cecrisacred.coopbr' where PROGRESS_RECID = 532565;
update CRAPCEM set DSDEMAIL = 'destakpintura@hotmail.com' where PROGRESS_RECID = 534909;
update CRAPCEM set DSDEMAIL = 'cleusa.pamplona@hotmail.com' where PROGRESS_RECID = 533125;
update CRAPCEM set DSDEMAIL = 'MSNadry_ser@terra.com.br' where PROGRESS_RECID = 529351;
update CRAPCEM set DSDEMAIL = 'vera@wtscobrana.com.br' where PROGRESS_RECID = 512770;
update CRAPCEM set DSDEMAIL = 'ademir2702@gmail.co' where PROGRESS_RECID = 569151;
update CRAPCEM set DSDEMAIL = 'haltaengenharia@hotmail.com' where PROGRESS_RECID = 537319;
update CRAPCEM set DSDEMAIL = 'nobertozanchet@hotmail.com' where PROGRESS_RECID = 553233;
update CRAPCEM set DSDEMAIL = 'metre_leno@yahoo.com.br' where PROGRESS_RECID = 570674;
update CRAPCEM set DSDEMAIL = 'katiafisio21@gmail.com' where PROGRESS_RECID = 570856;
update CRAPCEM set DSDEMAIL = 'prih.prih123@hotmailcom' where PROGRESS_RECID = 570162;
update CRAPCEM set DSDEMAIL = 'camiilamiguel@hotmailcom' where PROGRESS_RECID = 568766;
update CRAPCEM set DSDEMAIL = 'eduardoconnect.br@gmail.com' where PROGRESS_RECID = 565544;
update CRAPCEM set DSDEMAIL = 'wandeleypaes@yahoo.combr' where PROGRESS_RECID = 561087;
update CRAPCEM set DSDEMAIL = 'marcoscar38@gmail.com' where PROGRESS_RECID = 559105;
update CRAPCEM set DSDEMAIL = 'emerdiasbrustolin@gmail.com' where PROGRESS_RECID = 571754;
update CRAPCEM set DSDEMAIL = 'leticiaitj@hotmail.com' where PROGRESS_RECID = 576468;
update CRAPCEM set DSDEMAIL = 'stillofitnessilhota@hotmail.co' where PROGRESS_RECID = 581206;
update CRAPCEM set DSDEMAIL = 'sabrina@abilityambiental.com.br' where PROGRESS_RECID = 582641;
update CRAPCEM set DSDEMAIL = 'leomar.estofador@hotmail.com' where PROGRESS_RECID = 594081;
update CRAPCEM set DSDEMAIL = 'seffcelesccecred@gmail.com' where PROGRESS_RECID = 581729;
update CRAPCEM set DSDEMAIL = 'contato@farolcontabilidadecom.br' where PROGRESS_RECID = 594706;
update CRAPCEM set DSDEMAIL = 'contato@farolcontabilidadecom' where PROGRESS_RECID = 594732;
update CRAPCEM set DSDEMAIL = 'bremenzenter@viacredi.coopbr' where PROGRESS_RECID = 594192;
update CRAPCEM set DSDEMAIL = 'ana_.darc@hotmail.com' where PROGRESS_RECID = 581221;
update CRAPCEM set DSDEMAIL = 'minellajuliana@gmailcom' where PROGRESS_RECID = 593518;
update CRAPCEM set DSDEMAIL = 'seffcelesccecred@gmail.com' where PROGRESS_RECID = 581728;
update CRAPCEM set DSDEMAIL = 'secolo23@hotmail.co' where PROGRESS_RECID = 606195;
update CRAPCEM set DSDEMAIL = 'alisonstringari20@gmail.com' where PROGRESS_RECID = 600532;
update CRAPCEM set DSDEMAIL = 'priscilamoda@gmailcom' where PROGRESS_RECID = 606561;
update CRAPCEM set DSDEMAIL = 'vanessabryan2017@outlook.com' where PROGRESS_RECID = 605076;
update CRAPCEM set DSDEMAIL = 'mailtosolucoeseletricasjk@gmail.com' where PROGRESS_RECID = 601182;
update CRAPCEM set DSDEMAIL = 'loka7@gmail.com' where PROGRESS_RECID = 613159;
update CRAPCEM set DSDEMAIL = 'marcelomeiarota@gmail.com' where PROGRESS_RECID = 606297;
update CRAPCEM set DSDEMAIL = 'zaira@zaiatransportes.combr' where PROGRESS_RECID = 613399;
update CRAPCEM set DSDEMAIL = 'mailtomarcia.kuka@hotmail.com' where PROGRESS_RECID = 604654;
update CRAPCEM set DSDEMAIL = 'huachhakodesh07@gmailcom' where PROGRESS_RECID = 610127;
update CRAPCEM set DSDEMAIL = 'tomelindecor@hotmail.com' where PROGRESS_RECID = 612516;
update CRAPCEM set DSDEMAIL = 'fiscal3@alfacontabilidade.cnt.br' where PROGRESS_RECID = 598817;
update CRAPCEM set DSDEMAIL = 'nessagm91@gmail.com' where PROGRESS_RECID = 611437;
update CRAPCEM set DSDEMAIL = 'jardeldsouza@hotmail.com' where PROGRESS_RECID = 612280;
update CRAPCEM set DSDEMAIL = 'lucasenrico170@gmail.com' where PROGRESS_RECID = 637352;
update CRAPCEM set DSDEMAIL = 'ronnysalazar1992@gmail.com' where PROGRESS_RECID = 636505;
update CRAPCEM set DSDEMAIL = 'gbrideliz@gmail.com' where PROGRESS_RECID = 621748;
update CRAPCEM set DSDEMAIL = 'geovanefotoaerea@yahoocom.br' where PROGRESS_RECID = 619341;
update CRAPCEM set DSDEMAIL = 'inglidbomfim18@gmail.com' where PROGRESS_RECID = 621365;
update CRAPCEM set DSDEMAIL = 'clinicafitcim@hotmail.com' where PROGRESS_RECID = 618068;
update CRAPCEM set DSDEMAIL = 'gomidesgian@gmail.com' where PROGRESS_RECID = 630073;
update CRAPCEM set DSDEMAIL = 'gutotransportesblu@gmail.com' where PROGRESS_RECID = 632341;
update CRAPCEM set DSDEMAIL = 'aliatan.matheusg@gmail.com' where PROGRESS_RECID = 642347;
update CRAPCEM set DSDEMAIL = 'sanches197525@gmail.com' where PROGRESS_RECID = 628081;
update CRAPCEM set DSDEMAIL = 'henriqueantunes981@gmailcom' where PROGRESS_RECID = 630802;
update CRAPCEM set DSDEMAIL = 'ivairsa@hotmail.com' where PROGRESS_RECID = 636791;
update CRAPCEM set DSDEMAIL = 'fabianoborgo@hotmail.co' where PROGRESS_RECID = 639461;
update CRAPCEM set DSDEMAIL = 'simonereiter354@gmail.com' where PROGRESS_RECID = 639813;
update CRAPCEM set DSDEMAIL = 'isa.correa@latan.com' where PROGRESS_RECID = 641846;
update CRAPCEM set DSDEMAIL = 'luis-enriquemertens@hotmail.com' where PROGRESS_RECID = 641928;
update CRAPCEM set DSDEMAIL = 'sheronwcampinas@gmail.combr' where PROGRESS_RECID = 643147;
update CRAPCEM set DSDEMAIL = 'ruthhl@outlook.com' where PROGRESS_RECID = 632623;
update CRAPCEM set DSDEMAIL = 'luis.grandeluis@yahoo.com.br' where PROGRESS_RECID = 636522;
update CRAPCEM set DSDEMAIL = 'ticoeteco.aleixo@gmail.com' where PROGRESS_RECID = 627022;
update CRAPCEM set DSDEMAIL = 'jonathan.fortunato920513@gmail.com' where PROGRESS_RECID = 647015;
update CRAPCEM set DSDEMAIL = 'alexandre@pedronilog.com.br' where PROGRESS_RECID = 652126;
update CRAPCEM set DSDEMAIL = 'goncalvesalberes3@gmail.com' where PROGRESS_RECID = 651973;
update CRAPCEM set DSDEMAIL = 'jeanci92@outlookcom' where PROGRESS_RECID = 654049;
update CRAPCEM set DSDEMAIL = 'espacoreviver@live.com' where PROGRESS_RECID = 654674;
update CRAPCEM set DSDEMAIL = 'rayssapereiradeamarijo@hotmail.com' where PROGRESS_RECID = 646565;
update CRAPCEM set DSDEMAIL = 'tcss1979@gmail.com' where PROGRESS_RECID = 657907;
update CRAPCEM set DSDEMAIL = 'uvii.0202@gmail.com' where PROGRESS_RECID = 656001;
update CRAPCEM set DSDEMAIL = 'marialpamplona@hotmail.com' where PROGRESS_RECID = 656292;
update CRAPCEM set DSDEMAIL = 'caiocesaroliver1989@gmail.com' where PROGRESS_RECID = 657244;
update CRAPCEM set DSDEMAIL = 'renatosramos1201@gmail.cp' where PROGRESS_RECID = 647415;
update CRAPCEM set DSDEMAIL = 'naopossui@naopossui.com.br' where PROGRESS_RECID = 654331;
update CRAPCEM set DSDEMAIL = 'rfexpressronaldo@gmail.com' where PROGRESS_RECID = 655311;
update CRAPCEM set DSDEMAIL = 'wlademirsilva2018@gmail.combr' where PROGRESS_RECID = 656355;
update CRAPCEM set DSDEMAIL = 'vinigsouza.bnu@gmail.com' where PROGRESS_RECID = 662847;
update CRAPCEM set DSDEMAIL = 'junior_8537@hotmail.com' where PROGRESS_RECID = 671311;
update CRAPCEM set DSDEMAIL = 'sandramelloo@homailcom' where PROGRESS_RECID = 675538;
update CRAPCEM set DSDEMAIL = 'clfcarlos@hotmailcom' where PROGRESS_RECID = 676640;
update CRAPCEM set DSDEMAIL = 'brunynhaeguga@hotmail.com' where PROGRESS_RECID = 660457;
update CRAPCEM set DSDEMAIL = 'rafael.32.lima@gmail.com' where PROGRESS_RECID = 668390;
update CRAPCEM set DSDEMAIL = 'karoline.luciani@hotail.com' where PROGRESS_RECID = 662405;
update CRAPCEM set DSDEMAIL = 'thaizerodriguezz@hotails.com' where PROGRESS_RECID = 663444;
update CRAPCEM set DSDEMAIL = 'eloirsilva58@gmail.com' where PROGRESS_RECID = 660386;
update CRAPCEM set DSDEMAIL = 'silveriotalita55@gmailcom' where PROGRESS_RECID = 663464;
update CRAPCEM set DSDEMAIL = 'nvns00@hotmail.co' where PROGRESS_RECID = 667909;
update CRAPCEM set DSDEMAIL = 'lumalhas.sc@bol.com.br' where PROGRESS_RECID = 665152;
update CRAPCEM set DSDEMAIL = 'tatianestigar@hotmailcom' where PROGRESS_RECID = 699576;
update CRAPCEM set DSDEMAIL = 'julianamhfelipe@gmail.co' where PROGRESS_RECID = 673350;
update CRAPCEM set DSDEMAIL = 'maicon.vanchei.oliveira@gmailcom' where PROGRESS_RECID = 707284;
update CRAPCEM set DSDEMAIL = 'rotulos.guilherme@hotmail.com' where PROGRESS_RECID = 674146;
update CRAPCEM set DSDEMAIL = 'vanessacandidosbs@gmail.com' where PROGRESS_RECID = 677928;
update CRAPCEM set DSDEMAIL = 'everaldoalves70@yahoo.com.br' where PROGRESS_RECID = 673913;
update CRAPCEM set DSDEMAIL = 'sil2220.moraes@hotmail.com' where PROGRESS_RECID = 684031;
update CRAPCEM set DSDEMAIL = 'mary.303840@gmail.co' where PROGRESS_RECID = 701785;
update CRAPCEM set DSDEMAIL = 'rotulos.guilherme@hotmail.com' where PROGRESS_RECID = 674147;
update CRAPCEM set DSDEMAIL = 'rotulos.guilherme@hotmail.com' where PROGRESS_RECID = 674148;
update CRAPCEM set DSDEMAIL = 'rotulos.guilherme@hotmail.com' where PROGRESS_RECID = 674149;
update CRAPCEM set DSDEMAIL = 'rotulos.guilherme@hotmail.com' where PROGRESS_RECID = 674150;
update CRAPCEM set DSDEMAIL = 'andressaklemzak31@gmail.com' where PROGRESS_RECID = 704107;
update CRAPCEM set DSDEMAIL = 'mostowskidouglas45@gmail.co' where PROGRESS_RECID = 677918;
update CRAPCEM set DSDEMAIL = 'operacional@zimmartransportes.com.br' where PROGRESS_RECID = 712186;
update CRAPCEM set DSDEMAIL = 'rafaelystaniski26@hotmail.co' where PROGRESS_RECID = 712010;
update CRAPCEM set DSDEMAIL = 'seffcelescailos@gmail.com' where PROGRESS_RECID = 707643;
update CRAPCEM set DSDEMAIL = 'seffcelescailos@gmail.com' where PROGRESS_RECID = 707644;
update CRAPCEM set DSDEMAIL = 'janealexandre09@gmailcom.br' where PROGRESS_RECID = 711707;
update CRAPCEM set DSDEMAIL = 'objetivocontabil@brturbo.com.br' where PROGRESS_RECID = 711543;
update CRAPCEM set DSDEMAIL = 'comprasaraquarinox@gmail.com' where PROGRESS_RECID = 712778;
update CRAPCEM set DSDEMAIL = 'jlki@ig.com.br' where PROGRESS_RECID = 712591;
update CRAPCEM set DSDEMAIL = 'maicon.vanchei.oliveira@gmailcom' where PROGRESS_RECID = 707283;
update CRAPCEM set DSDEMAIL = 'jmosolucoes@outlookcom' where PROGRESS_RECID = 700800;
update CRAPCEM set DSDEMAIL = 'jorge.xv@terra.com.br' where PROGRESS_RECID = 711495;
update CRAPCEM set DSDEMAIL = 'jorge.xv@terra.com.br' where PROGRESS_RECID = 711494;   


/*
Objetivo   : Corrigir o valor da coluna CRAPCEM.DSDEMAIL para os casos em que o email está definido com mais de um "@"
*/

update CRAPCEM set DSDEMAIL = 'lilo.automoveis@hotmail.com'	 where PROGRESS_RECID = 	113896	;
update CRAPCEM set DSDEMAIL = 'nilson@imobiliariasegura.com.br'	 where PROGRESS_RECID = 	220415	;
update CRAPCEM set DSDEMAIL = 'nilson@imobiliariasegura.com.br'	 where PROGRESS_RECID = 	220405	;
update CRAPCEM set DSDEMAIL = 'pereirasilvano@hotmail.com'	 where PROGRESS_RECID = 	210974	;
update CRAPCEM set DSDEMAIL = 'kaka@seatshomealvorada.com.br'	 where PROGRESS_RECID = 	84176	;
update CRAPCEM set DSDEMAIL = 'rosangelamellies@gmail.com'	 where PROGRESS_RECID = 	45750	;
update CRAPCEM set DSDEMAIL = 'giovanella@valorpesquisas.com.br'	 where PROGRESS_RECID = 	124858	;
update CRAPCEM set DSDEMAIL = 'poffoi@terra.com.br'	 where PROGRESS_RECID = 	16615	;
update CRAPCEM set DSDEMAIL = 'nadinemachado78@gmail.com'	 where PROGRESS_RECID = 	241939	;
update CRAPCEM set DSDEMAIL = 'financeiro@slpeacos.ind.br'	 where PROGRESS_RECID = 	183097	;
update CRAPCEM set DSDEMAIL = 'consultoriovoneia@hotmail.com'	 where PROGRESS_RECID = 	284204	;
update CRAPCEM set DSDEMAIL = 'financeiro@damaiasoftcomfort.com.br'	 where PROGRESS_RECID = 	285749	;
update CRAPCEM set DSDEMAIL = 'taizeregina@gmail.com'	 where PROGRESS_RECID = 	354766	;
update CRAPCEM set DSDEMAIL = 'adivetransporte@hotmail.com'	 where PROGRESS_RECID = 	376240	;
update CRAPCEM set DSDEMAIL = 'atendimento@kuppasearaujo.com.br'	 where PROGRESS_RECID = 	407948	;
update CRAPCEM set DSDEMAIL = 'rogerio@lycrimalhas.com.br'	 where PROGRESS_RECID = 	411690	;
update CRAPCEM set DSDEMAIL = 'feliciogleiciane2@gmail.com'	 where PROGRESS_RECID = 	400670	;
update CRAPCEM set DSDEMAIL = 'fesdourado@gmail.com'	 where PROGRESS_RECID = 	398794	;
update CRAPCEM set DSDEMAIL = 'haverrott@gmail.com'	 where PROGRESS_RECID = 	393061	;
update CRAPCEM set DSDEMAIL = 'jorgemachado7176@gmail.com'	 where PROGRESS_RECID = 	443336	;
update CRAPCEM set DSDEMAIL = 'nilson@imobiliariasegura.com.br'	 where PROGRESS_RECID = 	517933	;
update CRAPCEM set DSDEMAIL = 'nilson@imobiliariasegura.com.br'	 where PROGRESS_RECID = 	521336	;
update CRAPCEM set DSDEMAIL = 'nilson@imobiliariasegura.com.br'	 where PROGRESS_RECID = 	521340	;
update CRAPCEM set DSDEMAIL = 'ronara.197@gmail.com'	 where PROGRESS_RECID = 	591416	;
update CRAPCEM set DSDEMAIL = 'patricia.maas@objetobr.com.br'	 where PROGRESS_RECID = 	591923	;
update CRAPCEM set DSDEMAIL = 'patricia.maas@objetobr.com.br'	 where PROGRESS_RECID = 	591920	;
update CRAPCEM set DSDEMAIL = 'luana_bonacolsi@hotmail.com'	 where PROGRESS_RECID = 	624592	;
update CRAPCEM set DSDEMAIL = 'rosangelamellies@gmail.com'	 where PROGRESS_RECID = 	645187	;


/*
OBJETIVO: Tratar os casos em que tem dois emails definidos corretamente em um único registro.
Está sendo criado um segundo registro para a mesma conta/cooperativa, considerando o segundo email definido 
na coluna DSDEMAIL e alterando o registro já existente, para manter registrado na coluna DSDEMAIL 
apenas o primeiro endereço de email definido nesta.

*/

/* Tratando caso para conta 7439 / cooperativa 6 */
INSERT INTO CRAPCEM VALUES (1, 
                            7439,
                            'alisboa@previsc.com',
                            (select max(CDDEMAIL)+1 from CRAPCEM where NRDCONTA = 7439 AND CDCOOPER = 6),
                            '26/04/2011',
                            83180,
                            6,
                            1,
                            'A',
                            ' ',
                            ' ',
                            NULL,
                            to_date('24/04/2019 22:41:00', 'DD/MM/RRRR HH24:MI:SS'),
                            NULL);


update CRAPCEM C
set c.dsdemail = 'drikalisboa@hotmail.com'   
where c.progress_recid = 133980; 

/*Tratando caso para conta 1984314 / cooperativa 1 */
INSERT INTO CRAPCEM VALUES (1, 
                            1984314,
                            'vanderlei@selgron.com.br',
                            (select max(CDDEMAIL)+1 from CRAPCEM where NRDCONTA = 1984314 AND CDCOOPER = 1),
                            '26/04/2011',
                            83057,
                            1,
                            1,
                            'A',
                            ' ',
                            ' ',
                            NULL,
                            to_date('24/04/2019 22:41:00', 'DD/MM/RRRR HH24:MI:SS'),
                            NULL);
                            
update CRAPCEM C
set c.dsdemail = 'v.tomio@ig.com.br'   
where c.progress_recid = 12536;  

/*Tratando caso para conta 1856120 / cooperativa 1 */
INSERT INTO CRAPCEM VALUES (1, 
                            1856120,
                            'dj_canisso@yahoo.com',
                            (select max(CDDEMAIL)+1 from CRAPCEM where NRDCONTA = 1856120 AND CDCOOPER = 1),
                            '26/04/2011',
                            83048,
                            1,
                            1,
                            'A',
                            ' ',
                            ' ',
                            NULL,
                            to_date('24/04/2019 22:41:00', 'DD/MM/RRRR HH24:MI:SS'),
                            NULL);
                            
update CRAPCEM C
set c.dsdemail = 'danilo.21@bol.com.br'   
where c.progress_recid = 8911;    

/*Tratando caso para conta 2120810 / cooperativa 1 */
INSERT INTO CRAPCEM VALUES (3016, 
                            2120810,
                            'estoque@leiloeiro.com.br',
                            (select max(CDDEMAIL)+1 from CRAPCEM where NRDCONTA = 2120810 AND CDCOOPER = 1),
                            '07/01/2016',
                            40785,
                            1,
                            1,
                            'A',
                            ' ',
                            ' ',
                            NULL,
                            to_date('24/04/2019 22:41:00', 'DD/MM/RRRR HH24:MI:SS'),
                            NULL);
                            
update CRAPCEM C
set c.dsdemail = 'andrebrtk@gmail.com'   
where c.progress_recid = 269677;



COMMIT;
