
insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (1, 1, 'Crédito Pessoal', 4, 12, 2, 1, '<CLOB>', 30);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (17, 1, 'Crédito Pessoal', 4, 12, 2, 1, '<CLOB>', 30);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (16, 1, 'Crédito Pessoal', 4, 12, 2, 1, 'Crédito digital! Basta você informar o valor do crédito e o prazo desejado para pagamento, então será apresentado na sua tela, o valor da parcela e a taxa de juros para a sua solicitação. Se você gostar da opção, poderá solicitar o crédito. Você poderá acompanhar o status da sua solicitação e assim que ela for aprovada poderá contratar o crédito na hora. ', 
30);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (15, 1, 'Crédito Pessoal', 4, 12, 2, 1, '<CLOB>', 30);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (14, 1, 'Crédito Pessoal', 4, 12, 2, 1, '<CLOB>', 30);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (13, 1, 'Crédito Pessoal', 4, 12, 2, 1, '<CLOB>', 30);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (12, 1, 'Crédito Pessoal', 4, 12, 2, 1, '<CLOB>', 30);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (11, 1, 'Crédito Pessoal', 4, 12, 2, 1, '<CLOB>', 30);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (10, 1, 'Crédito Pessoal', 4, 12, 2, 1, '<CLOB>', 30);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (9, 1, 'Crédito Pessoal', 4, 12, 2, 1, '<CLOB>', 30);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (8, 1, 'Crédito Pessoal', 4, 12, 2, 1, '<CLOB>', 30);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (7, 1, 'Crédito Pessoal', 4, 12, 2, 1, '<CLOB>', 30);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (6, 1, 'Crédito Pessoal', 4, 12, 2, 1, '<CLOB>', 30);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (5, 1, 'Crédito Pessoal', 4, 12, 2, 1, '<CLOB>', 30);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (4, 1, 'Crédito Pessoal', 4, 12, 2, 1, '<CLOB>', 30);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (3, 1, 'Crédito Pessoal', 4, 12, 2, 1, '<CLOB>', 30);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (2, 1, 'Crédito Pessoal', 4, 12, 2, 1, '<CLOB>', 30);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (1, 2, 'Crédito Empreendedor', 4, 6, 10, 24, '<CLOB>', 15);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (2, 2, 'Crédito Empreendedor', 4, 6, 10, 24, '<CLOB>', 15);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (3, 2, 'Crédito Empreendedor', 4, 6, 10, 24, '<CLOB>', 15);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (4, 2, 'Crédito Empreendedor', 4, 6, 10, 24, '<CLOB>', 15);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (5, 2, 'Crédito Empreendedor', 4, 6, 10, 24, '<CLOB>', 15);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (6, 2, 'Crédito Empreendedor', 4, 6, 10, 24, '<CLOB>', 15);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (7, 2, 'Crédito Empreendedor', 4, 6, 10, 24, '<CLOB>', 15);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (8, 2, 'Crédito Empreendedor', 4, 6, 10, 24, '<CLOB>', 15);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (9, 2, 'Crédito Empreendedor', 4, 6, 10, 24, '<CLOB>', 15);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (10, 2, 'Crédito Empreendedor', 4, 6, 10, 24, '<CLOB>', 15);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (11, 2, 'Crédito Empreendedor', 4, 6, 10, 24, '<CLOB>', 15);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (12, 2, 'Crédito Empreendedor', 4, 6, 10, 24, '<CLOB>', 15);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (13, 2, 'Crédito Empreendedor', 4, 6, 10, 24, '<CLOB>', 15);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (14, 2, 'Crédito Empreendedor', 4, 6, 10, 24, '<CLOB>', 15);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (15, 2, 'Crédito Empreendedor', 4, 6, 10, 24, '<CLOB>', 15);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (16, 2, 'Crédito Empreendedor', 4, 6, 10, 24, 'Crédito digital! Basta você informar o valor do crédito e o prazo desejado para pagamento, então será apresentado na sua tela, o valor da parcela e a taxa de juros para a sua solicitação. Se você gostar da opção, poderá solicitar o crédito. Você poderá acompanhar o status da sua solicitação e assim que ela for aprovada poderá contratar o crédito na hora. '
, 15);

insert into tbepr_segmento (CDCOOPER, IDSEGMENTO, DSSEGMENTO, QTSIMULACOES_PADRAO, NRVARIACAO_PARC, NRMAX_PROPOSTA, NRINTERVALO_PROPOSTA, DSSEGMENTO_DETALHADA, QTDIAS_VALIDADE)
values (17, 2, 'Crédito Empreendedor', 4, 6, 10, 24, '<CLOB>', 15);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (1, 1, 11, 'Credito Pessoal', 7080, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (2, 1, 11, 'Credito Pessoal', 7080, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (3, 1, 11, 'Credito Pessoal', 7080, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (4, 1, 11, 'Credito Pessoal', 7080, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (5, 1, 11, 'Credito Pessoal', 7080, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (6, 1, 11, 'Credito Pessoal', 7080, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (7, 1, 11, 'Credito Pessoal', 7080, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (8, 1, 11, 'Credito Pessoal', 7080, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (9, 1, 11, 'Credito Pessoal', 7080, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (10, 1, 11, 'Credito Pessoal', 7080, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (11, 1, 11, 'Credito Pessoal', 7080, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (12, 1, 11, 'Credito Pessoal', 7080, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (13, 1, 11, 'Credito Pessoal', 7080, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (14, 1, 11, 'Credito Pessoal', 7080, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (15, 1, 11, 'Credito Pessoal', 7080, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (16, 1, 11, 'Credito Pessoal', 7080, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (17, 1, 11, 'Credito Pessoal', 7080, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (1, 2, 21, 'Credito Empreendedor', 7081, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (2, 2, 21, 'Credito Empreendedor', 7081, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (3, 2, 21, 'Credito Empreendedor', 7081, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (4, 2, 21, 'Credito Empreendedor', 7081, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (5, 2, 21, 'Credito Empreendedor', 7081, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (6, 2, 21, 'Credito Empreendedor', 7081, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (7, 2, 21, 'Credito Empreendedor', 7081, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (8, 2, 21, 'Credito Empreendedor', 7081, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (9, 2, 21, 'Credito Empreendedor', 7081, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (10, 2, 21, 'Credito Empreendedor', 7081, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (11, 2, 21, 'Credito Empreendedor', 7081, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (12, 2, 21, 'Credito Empreendedor', 7081, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (13, 2, 21, 'Credito Empreendedor', 7081, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (14, 2, 21, 'Credito Empreendedor', 7081, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (15, 2, 21, 'Credito Empreendedor', 7081, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (16, 2, 21, 'Credito Empreendedor', 7081, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_subsegmento (CDCOOPER, IDSEGMENTO, IDSUBSEGMENTO, DSSUBSEGMENTO, CDLINHA_CREDITO, FLGGARANTIA, TPGARANTIA, PEMAX_AUTORIZADO, PEEXCEDENTE, VLMAX_PROPOSTA, CDFINALIDADE)
values (17, 2, 21, 'Credito Empreendedor', 7081, 0, 0, 0.00, 0.00, 0.00, 77);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (1, 1, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (1, 1, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (2, 1, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (2, 1, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (3, 1, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (3, 1, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (4, 1, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (4, 1, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (5, 1, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (5, 1, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (6, 1, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (6, 1, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (7, 1, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (7, 1, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (8, 1, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (8, 1, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (9, 1, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (9, 1, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (10, 1, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (10, 1, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (11, 1, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (11, 1, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (12, 1, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (12, 1, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (13, 1, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (13, 1, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (14, 1, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (14, 1, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (15, 1, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (15, 1, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (16, 1, 3, 2, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (16, 1, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (17, 1, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (17, 1, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (1, 2, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (1, 2, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (2, 2, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (2, 2, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (3, 2, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (3, 2, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (4, 2, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (4, 2, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (5, 2, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (5, 2, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (6, 2, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (6, 2, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (7, 2, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (7, 2, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (8, 2, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (8, 2, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (9, 2, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (9, 2, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (10, 2, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (10, 2, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (11, 2, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (11, 2, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (12, 2, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (12, 2, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (13, 2, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (13, 2, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (14, 2, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (14, 2, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (15, 2, 3, 0, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (15, 2, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (16, 2, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (16, 2, 3, 2, 30000.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (17, 2, 10, 0, 0.00);

insert into tbepr_segmento_canais_perm (CDCOOPER, IDSEGMENTO, CDCANAL, TPPERMISSAO, VLMAX_AUTORIZADO)
values (17, 2, 3, 0, 30000.00);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (1, 1, 1);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (2, 1, 1);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (3, 1, 1);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (4, 1, 1);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (5, 1, 1);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (6, 1, 1);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (7, 1, 1);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (8, 1, 1);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (9, 1, 1);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (10, 1, 1);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (11, 1, 1);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (12, 1, 1);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (13, 1, 1);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (14, 1, 1);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (15, 1, 1);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (16, 1, 1);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (17, 1, 1);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (1, 2, 2);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (2, 2, 2);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (3, 2, 2);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (4, 2, 2);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (5, 2, 2);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (6, 2, 2);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (7, 2, 2);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (8, 2, 2);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (9, 2, 2);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (10, 2, 2);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (11, 2, 2);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (12, 2, 2);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (13, 2, 2);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (14, 2, 2);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (15, 2, 2);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (16, 2, 2);

insert into tbepr_segmento_tppessoa_perm (CDCOOPER, IDSEGMENTO, TPPESSOA)
values (17, 2, 2);

commit;
