begin
  insert into tbgen_fipe_marca_tmp values (102,3,gene0007.fn_caract_acento('AGRALE'));
  insert into tbgen_fipe_marca_tmp values (206,3,gene0007.fn_caract_acento('BEPOBUS'));
  insert into tbgen_fipe_marca_tmp values (103,3,gene0007.fn_caract_acento('CHEVROLET'));
  insert into tbgen_fipe_marca_tmp values (121,3,gene0007.fn_caract_acento('CICCOBUS'));
  insert into tbgen_fipe_marca_tmp values (197,3,gene0007.fn_caract_acento('DAF'));
  insert into tbgen_fipe_marca_tmp values (179,3,gene0007.fn_caract_acento('EFFA-JMC'));
  insert into tbgen_fipe_marca_tmp values (104,3,gene0007.fn_caract_acento('FIAT'));
  insert into tbgen_fipe_marca_tmp values (105,3,gene0007.fn_caract_acento('FORD'));
  insert into tbgen_fipe_marca_tmp values (191,3,gene0007.fn_caract_acento('FOTON'));
  insert into tbgen_fipe_marca_tmp values (106,3,gene0007.fn_caract_acento('GMC'));
  insert into tbgen_fipe_marca_tmp values (181,3,gene0007.fn_caract_acento('HYUNDAI'));
  insert into tbgen_fipe_marca_tmp values (122,3,gene0007.fn_caract_acento('IVECO'));
  insert into tbgen_fipe_marca_tmp values (184,3,gene0007.fn_caract_acento('MAN'));
  insert into tbgen_fipe_marca_tmp values (108,3,gene0007.fn_caract_acento('MARCOPOLO'));
  insert into tbgen_fipe_marca_tmp values (196,3,gene0007.fn_caract_acento('MASCARELLO'));
  insert into tbgen_fipe_marca_tmp values (194,3,gene0007.fn_caract_acento('MAXIBUS'));
  insert into tbgen_fipe_marca_tmp values (109,3,gene0007.fn_caract_acento('MERCEDES-BENZ'));
  insert into tbgen_fipe_marca_tmp values (110,3,gene0007.fn_caract_acento('NAVISTAR'));
  insert into tbgen_fipe_marca_tmp values (111,3,gene0007.fn_caract_acento('NEOBUS'));
  insert into tbgen_fipe_marca_tmp values (112,3,gene0007.fn_caract_acento('PUMA-ALFA'));
  insert into tbgen_fipe_marca_tmp values (113,3,gene0007.fn_caract_acento('SAAB-SCANIA'));
  insert into tbgen_fipe_marca_tmp values (114,3,gene0007.fn_caract_acento('SCANIA'));
  insert into tbgen_fipe_marca_tmp values (193,3,gene0007.fn_caract_acento('SHACMAN'));
  insert into tbgen_fipe_marca_tmp values (166,3,gene0007.fn_caract_acento('SINOTRUK'));
  insert into tbgen_fipe_marca_tmp values (115,3,gene0007.fn_caract_acento('VOLKSWAGEN'));
  insert into tbgen_fipe_marca_tmp values (116,3,gene0007.fn_caract_acento('VOLVO'));
  insert into tbgen_fipe_marca_tmp values (144,3,gene0007.fn_caract_acento('WALKBUS'));
  insert into tbgen_fipe_marca_tmp values (1,1,gene0007.fn_caract_acento('Acura'));
  insert into tbgen_fipe_marca_tmp values (2,1,gene0007.fn_caract_acento('Agrale'));
  insert into tbgen_fipe_marca_tmp values (3,1,gene0007.fn_caract_acento('Alfa Romeo'));
  insert into tbgen_fipe_marca_tmp values (4,1,gene0007.fn_caract_acento('AM Gen'));
  insert into tbgen_fipe_marca_tmp values (5,1,gene0007.fn_caract_acento('Asia Motors'));
  insert into tbgen_fipe_marca_tmp values (189,1,gene0007.fn_caract_acento('ASTON MARTIN'));
  insert into tbgen_fipe_marca_tmp values (6,1,gene0007.fn_caract_acento('Audi'));
  insert into tbgen_fipe_marca_tmp values (207,1,gene0007.fn_caract_acento('Baby'));
  insert into tbgen_fipe_marca_tmp values (7,1,gene0007.fn_caract_acento('BMW'));
  insert into tbgen_fipe_marca_tmp values (8,1,gene0007.fn_caract_acento('BRM'));
  insert into tbgen_fipe_marca_tmp values (123,1,gene0007.fn_caract_acento('Bugre'));
  insert into tbgen_fipe_marca_tmp values (10,1,gene0007.fn_caract_acento('Cadillac'));
  insert into tbgen_fipe_marca_tmp values (11,1,gene0007.fn_caract_acento('CBT Jipe'));
  insert into tbgen_fipe_marca_tmp values (136,1,gene0007.fn_caract_acento('CHANA'));
  insert into tbgen_fipe_marca_tmp values (182,1,gene0007.fn_caract_acento('CHANGAN'));
  insert into tbgen_fipe_marca_tmp values (161,1,gene0007.fn_caract_acento('CHERY'));
  insert into tbgen_fipe_marca_tmp values (12,1,gene0007.fn_caract_acento('Chrysler'));
  insert into tbgen_fipe_marca_tmp values (13,1,gene0007.fn_caract_acento('Citroën'));
  insert into tbgen_fipe_marca_tmp values (14,1,gene0007.fn_caract_acento('Cross Lander'));
  insert into tbgen_fipe_marca_tmp values (15,1,gene0007.fn_caract_acento('Daewoo'));
  insert into tbgen_fipe_marca_tmp values (16,1,gene0007.fn_caract_acento('Daihatsu'));
  insert into tbgen_fipe_marca_tmp values (17,1,gene0007.fn_caract_acento('Dodge'));
  insert into tbgen_fipe_marca_tmp values (147,1,gene0007.fn_caract_acento('EFFA'));
  insert into tbgen_fipe_marca_tmp values (18,1,gene0007.fn_caract_acento('Engesa'));
  insert into tbgen_fipe_marca_tmp values (19,1,gene0007.fn_caract_acento('Envemo'));
  insert into tbgen_fipe_marca_tmp values (20,1,gene0007.fn_caract_acento('Ferrari'));
  insert into tbgen_fipe_marca_tmp values (21,1,gene0007.fn_caract_acento('Fiat'));
  insert into tbgen_fipe_marca_tmp values (149,1,gene0007.fn_caract_acento('Fibravan'));
  insert into tbgen_fipe_marca_tmp values (22,1,gene0007.fn_caract_acento('Ford'));
  insert into tbgen_fipe_marca_tmp values (190,1,gene0007.fn_caract_acento('FOTON'));
  insert into tbgen_fipe_marca_tmp values (170,1,gene0007.fn_caract_acento('Fyber'));
  insert into tbgen_fipe_marca_tmp values (199,1,gene0007.fn_caract_acento('GEELY'));
  insert into tbgen_fipe_marca_tmp values (23,1,gene0007.fn_caract_acento('GM - Chevrolet'));
  insert into tbgen_fipe_marca_tmp values (153,1,gene0007.fn_caract_acento('GREAT WALL'));
  insert into tbgen_fipe_marca_tmp values (24,1,gene0007.fn_caract_acento('Gurgel'));
  insert into tbgen_fipe_marca_tmp values (152,1,gene0007.fn_caract_acento('HAFEI'));
  insert into tbgen_fipe_marca_tmp values (25,1,gene0007.fn_caract_acento('Honda'));
  insert into tbgen_fipe_marca_tmp values (26,1,gene0007.fn_caract_acento('Hyundai'));
  insert into tbgen_fipe_marca_tmp values (27,1,gene0007.fn_caract_acento('Isuzu'));
  insert into tbgen_fipe_marca_tmp values (208,1,gene0007.fn_caract_acento('IVECO'));
  insert into tbgen_fipe_marca_tmp values (177,1,gene0007.fn_caract_acento('JAC'));
  insert into tbgen_fipe_marca_tmp values (28,1,gene0007.fn_caract_acento('Jaguar'));
  insert into tbgen_fipe_marca_tmp values (29,1,gene0007.fn_caract_acento('Jeep'));
  insert into tbgen_fipe_marca_tmp values (154,1,gene0007.fn_caract_acento('JINBEI'));
  insert into tbgen_fipe_marca_tmp values (30,1,gene0007.fn_caract_acento('JPX'));
  insert into tbgen_fipe_marca_tmp values (31,1,gene0007.fn_caract_acento('Kia Motors'));
  insert into tbgen_fipe_marca_tmp values (32,1,gene0007.fn_caract_acento('Lada'));
  insert into tbgen_fipe_marca_tmp values (171,1,gene0007.fn_caract_acento('LAMBORGHINI'));
  insert into tbgen_fipe_marca_tmp values (33,1,gene0007.fn_caract_acento('Land Rover'));
  insert into tbgen_fipe_marca_tmp values (34,1,gene0007.fn_caract_acento('Lexus'));
  insert into tbgen_fipe_marca_tmp values (168,1,gene0007.fn_caract_acento('LIFAN'));
  insert into tbgen_fipe_marca_tmp values (127,1,gene0007.fn_caract_acento('LOBINI'));
  insert into tbgen_fipe_marca_tmp values (35,1,gene0007.fn_caract_acento('Lotus'));
  insert into tbgen_fipe_marca_tmp values (140,1,gene0007.fn_caract_acento('Mahindra'));
  insert into tbgen_fipe_marca_tmp values (36,1,gene0007.fn_caract_acento('Maserati'));
  insert into tbgen_fipe_marca_tmp values (37,1,gene0007.fn_caract_acento('Matra'));
  insert into tbgen_fipe_marca_tmp values (38,1,gene0007.fn_caract_acento('Mazda'));
  insert into tbgen_fipe_marca_tmp values (211,1,gene0007.fn_caract_acento('Mclaren'));
  insert into tbgen_fipe_marca_tmp values (39,1,gene0007.fn_caract_acento('Mercedes-Benz'));
  insert into tbgen_fipe_marca_tmp values (40,1,gene0007.fn_caract_acento('Mercury'));
  insert into tbgen_fipe_marca_tmp values (167,1,gene0007.fn_caract_acento('MG'));
  insert into tbgen_fipe_marca_tmp values (156,1,gene0007.fn_caract_acento('MINI'));
  insert into tbgen_fipe_marca_tmp values (41,1,gene0007.fn_caract_acento('Mitsubishi'));
  insert into tbgen_fipe_marca_tmp values (42,1,gene0007.fn_caract_acento('Miura'));
  insert into tbgen_fipe_marca_tmp values (43,1,gene0007.fn_caract_acento('Nissan'));
  insert into tbgen_fipe_marca_tmp values (44,1,gene0007.fn_caract_acento('Peugeot'));
  insert into tbgen_fipe_marca_tmp values (45,1,gene0007.fn_caract_acento('Plymouth'));
  insert into tbgen_fipe_marca_tmp values (46,1,gene0007.fn_caract_acento('Pontiac'));
  insert into tbgen_fipe_marca_tmp values (47,1,gene0007.fn_caract_acento('Porsche'));
  insert into tbgen_fipe_marca_tmp values (185,1,gene0007.fn_caract_acento('RAM'));
  insert into tbgen_fipe_marca_tmp values (186,1,gene0007.fn_caract_acento('RELY'));
  insert into tbgen_fipe_marca_tmp values (48,1,gene0007.fn_caract_acento('Renault'));
  insert into tbgen_fipe_marca_tmp values (195,1,gene0007.fn_caract_acento('Rolls-Royce'));
  insert into tbgen_fipe_marca_tmp values (49,1,gene0007.fn_caract_acento('Rover'));
  insert into tbgen_fipe_marca_tmp values (50,1,gene0007.fn_caract_acento('Saab'));
  insert into tbgen_fipe_marca_tmp values (51,1,gene0007.fn_caract_acento('Saturn'));
  insert into tbgen_fipe_marca_tmp values (52,1,gene0007.fn_caract_acento('Seat'));
  insert into tbgen_fipe_marca_tmp values (183,1,gene0007.fn_caract_acento('SHINERAY'));
  insert into tbgen_fipe_marca_tmp values (157,1,gene0007.fn_caract_acento('smart'));
  insert into tbgen_fipe_marca_tmp values (125,1,gene0007.fn_caract_acento('SSANGYONG'));
  insert into tbgen_fipe_marca_tmp values (54,1,gene0007.fn_caract_acento('Subaru'));
  insert into tbgen_fipe_marca_tmp values (55,1,gene0007.fn_caract_acento('Suzuki'));
  insert into tbgen_fipe_marca_tmp values (165,1,gene0007.fn_caract_acento('TAC'));
  insert into tbgen_fipe_marca_tmp values (56,1,gene0007.fn_caract_acento('Toyota'));
  insert into tbgen_fipe_marca_tmp values (57,1,gene0007.fn_caract_acento('Troller'));
  insert into tbgen_fipe_marca_tmp values (58,1,gene0007.fn_caract_acento('Volvo'));
  insert into tbgen_fipe_marca_tmp values (59,1,gene0007.fn_caract_acento('VW - VolksWagen'));
  insert into tbgen_fipe_marca_tmp values (163,1,gene0007.fn_caract_acento('Wake'));
  insert into tbgen_fipe_marca_tmp values (120,1,gene0007.fn_caract_acento('Walk'));
  insert into tbgen_fipe_marca_tmp values (60,2,gene0007.fn_caract_acento('ADLY'));
  insert into tbgen_fipe_marca_tmp values (61,2,gene0007.fn_caract_acento('AGRALE'));
  insert into tbgen_fipe_marca_tmp values (131,2,gene0007.fn_caract_acento('AMAZONAS'));
  insert into tbgen_fipe_marca_tmp values (62,2,gene0007.fn_caract_acento('APRILIA'));
  insert into tbgen_fipe_marca_tmp values (63,2,gene0007.fn_caract_acento('ATALA'));
  insert into tbgen_fipe_marca_tmp values (64,2,gene0007.fn_caract_acento('BAJAJ'));
  insert into tbgen_fipe_marca_tmp values (205,2,gene0007.fn_caract_acento('BEE'));
  insert into tbgen_fipe_marca_tmp values (162,2,gene0007.fn_caract_acento('Benelli'));
  insert into tbgen_fipe_marca_tmp values (65,2,gene0007.fn_caract_acento('BETA'));
  insert into tbgen_fipe_marca_tmp values (66,2,gene0007.fn_caract_acento('BIMOTA'));
  insert into tbgen_fipe_marca_tmp values (67,2,gene0007.fn_caract_acento('BMW'));
  insert into tbgen_fipe_marca_tmp values (68,2,gene0007.fn_caract_acento('BRANDY'));
  insert into tbgen_fipe_marca_tmp values (130,2,gene0007.fn_caract_acento('BRAVA'));
  insert into tbgen_fipe_marca_tmp values (150,2,gene0007.fn_caract_acento('BRP'));
  insert into tbgen_fipe_marca_tmp values (117,2,gene0007.fn_caract_acento('BUELL'));
  insert into tbgen_fipe_marca_tmp values (155,2,gene0007.fn_caract_acento('BUENO'));
  insert into tbgen_fipe_marca_tmp values (69,2,gene0007.fn_caract_acento('byCristo'));
  insert into tbgen_fipe_marca_tmp values (70,2,gene0007.fn_caract_acento('CAGIVA'));
  insert into tbgen_fipe_marca_tmp values (71,2,gene0007.fn_caract_acento('CALOI'));
  insert into tbgen_fipe_marca_tmp values (72,2,gene0007.fn_caract_acento('DAELIM'));
  insert into tbgen_fipe_marca_tmp values (145,2,gene0007.fn_caract_acento('DAFRA'));
  insert into tbgen_fipe_marca_tmp values (137,2,gene0007.fn_caract_acento('DAYANG'));
  insert into tbgen_fipe_marca_tmp values (142,2,gene0007.fn_caract_acento('DAYUN'));
  insert into tbgen_fipe_marca_tmp values (73,2,gene0007.fn_caract_acento('DERBI'));
  insert into tbgen_fipe_marca_tmp values (74,2,gene0007.fn_caract_acento('DUCATI'));
  insert into tbgen_fipe_marca_tmp values (75,2,gene0007.fn_caract_acento('EMME'));
  insert into tbgen_fipe_marca_tmp values (132,2,gene0007.fn_caract_acento('FOX'));
  insert into tbgen_fipe_marca_tmp values (209,2,gene0007.fn_caract_acento('FUSCO MOTOSEGURA'));
  insert into tbgen_fipe_marca_tmp values (128,2,gene0007.fn_caract_acento('FYM'));
  insert into tbgen_fipe_marca_tmp values (143,2,gene0007.fn_caract_acento('GARINNI'));
  insert into tbgen_fipe_marca_tmp values (76,2,gene0007.fn_caract_acento('GAS GAS'));
  insert into tbgen_fipe_marca_tmp values (133,2,gene0007.fn_caract_acento('GREEN'));
  insert into tbgen_fipe_marca_tmp values (138,2,gene0007.fn_caract_acento('HAOBAO'));
  insert into tbgen_fipe_marca_tmp values (203,2,gene0007.fn_caract_acento('HAOJUE'));
  insert into tbgen_fipe_marca_tmp values (77,2,gene0007.fn_caract_acento('HARLEY-DAVIDSON'));
  insert into tbgen_fipe_marca_tmp values (78,2,gene0007.fn_caract_acento('HARTFORD'));
  insert into tbgen_fipe_marca_tmp values (79,2,gene0007.fn_caract_acento('HERO'));
  insert into tbgen_fipe_marca_tmp values (80,2,gene0007.fn_caract_acento('HONDA'));
  insert into tbgen_fipe_marca_tmp values (81,2,gene0007.fn_caract_acento('HUSABERG'));
  insert into tbgen_fipe_marca_tmp values (82,2,gene0007.fn_caract_acento('HUSQVARNA'));
  insert into tbgen_fipe_marca_tmp values (202,2,gene0007.fn_caract_acento('INDIAN'));
  insert into tbgen_fipe_marca_tmp values (158,2,gene0007.fn_caract_acento('IROS'));
  insert into tbgen_fipe_marca_tmp values (141,2,gene0007.fn_caract_acento('JIAPENG VOLCANO'));
  insert into tbgen_fipe_marca_tmp values (174,2,gene0007.fn_caract_acento('JOHNNYPAG'));
  insert into tbgen_fipe_marca_tmp values (151,2,gene0007.fn_caract_acento('JONNY'));
  insert into tbgen_fipe_marca_tmp values (129,2,gene0007.fn_caract_acento('KAHENA'));
  insert into tbgen_fipe_marca_tmp values (118,2,gene0007.fn_caract_acento('KASINSKI'));
  insert into tbgen_fipe_marca_tmp values (85,2,gene0007.fn_caract_acento('KAWASAKI'));
  insert into tbgen_fipe_marca_tmp values (87,2,gene0007.fn_caract_acento('KTM'));
  insert into tbgen_fipe_marca_tmp values (204,2,gene0007.fn_caract_acento('KYMCO'));
  insert into tbgen_fipe_marca_tmp values (159,2,gene0007.fn_caract_acento('LANDUM'));
  insert into tbgen_fipe_marca_tmp values (88,2,gene0007.fn_caract_acento('L AQUILA'));
  insert into tbgen_fipe_marca_tmp values (89,2,gene0007.fn_caract_acento('LAVRALE'));
  insert into tbgen_fipe_marca_tmp values (139,2,gene0007.fn_caract_acento('LERIVO'));
  insert into tbgen_fipe_marca_tmp values (178,2,gene0007.fn_caract_acento('LIFAN'));
  insert into tbgen_fipe_marca_tmp values (148,2,gene0007.fn_caract_acento('Lon-V'));
  insert into tbgen_fipe_marca_tmp values (175,2,gene0007.fn_caract_acento('MAGRÃO TRICICLOS'));
  insert into tbgen_fipe_marca_tmp values (146,2,gene0007.fn_caract_acento('Malaguti'));
  insert into tbgen_fipe_marca_tmp values (126,2,gene0007.fn_caract_acento('MIZA'));
  insert into tbgen_fipe_marca_tmp values (90,2,gene0007.fn_caract_acento('MOTO GUZZI'));
  insert into tbgen_fipe_marca_tmp values (201,2,gene0007.fn_caract_acento('MOTOCAR'));
  insert into tbgen_fipe_marca_tmp values (200,2,gene0007.fn_caract_acento('MOTORINO'));
  insert into tbgen_fipe_marca_tmp values (160,2,gene0007.fn_caract_acento('MRX'));
  insert into tbgen_fipe_marca_tmp values (91,2,gene0007.fn_caract_acento('MV AGUSTA'));
  insert into tbgen_fipe_marca_tmp values (92,2,gene0007.fn_caract_acento('MVK'));
  insert into tbgen_fipe_marca_tmp values (93,2,gene0007.fn_caract_acento('ORCA'));
  insert into tbgen_fipe_marca_tmp values (164,2,gene0007.fn_caract_acento('PEGASSI'));
  insert into tbgen_fipe_marca_tmp values (94,2,gene0007.fn_caract_acento('PEUGEOT'));
  insert into tbgen_fipe_marca_tmp values (95,2,gene0007.fn_caract_acento('PIAGGIO'));
  insert into tbgen_fipe_marca_tmp values (210,2,gene0007.fn_caract_acento('POLARIS'));
  insert into tbgen_fipe_marca_tmp values (173,2,gene0007.fn_caract_acento('REGAL RAPTOR'));
  insert into tbgen_fipe_marca_tmp values (198,2,gene0007.fn_caract_acento('RIGUETE'));
  insert into tbgen_fipe_marca_tmp values (192,2,gene0007.fn_caract_acento('Royal Enfield'));
  insert into tbgen_fipe_marca_tmp values (96,2,gene0007.fn_caract_acento('SANYANG'));
  insert into tbgen_fipe_marca_tmp values (134,2,gene0007.fn_caract_acento('SHINERAY'));
  insert into tbgen_fipe_marca_tmp values (97,2,gene0007.fn_caract_acento('SIAMOTO'));
  insert into tbgen_fipe_marca_tmp values (98,2,gene0007.fn_caract_acento('SUNDOWN'));
  insert into tbgen_fipe_marca_tmp values (99,2,gene0007.fn_caract_acento('SUZUKI'));
  insert into tbgen_fipe_marca_tmp values (176,2,gene0007.fn_caract_acento('TARGOS'));
  insert into tbgen_fipe_marca_tmp values (187,2,gene0007.fn_caract_acento('TIGER'));
  insert into tbgen_fipe_marca_tmp values (119,2,gene0007.fn_caract_acento('TRAXX'));
  insert into tbgen_fipe_marca_tmp values (100,2,gene0007.fn_caract_acento('TRIUMPH'));
  insert into tbgen_fipe_marca_tmp values (180,2,gene0007.fn_caract_acento('VENTO'));
  insert into tbgen_fipe_marca_tmp values (135,2,gene0007.fn_caract_acento('WUYANG'));
  insert into tbgen_fipe_marca_tmp values (101,2,gene0007.fn_caract_acento('YAMAHA'));

  commit;
end;
/