insert into crapPRG (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
values ('CRED', 'CERISC', 'Parâmetros Central de Risco', ' ', ' ', ' ', 50, 10830, 1, 0, 0, 0, 0, 0, 1, 17, null);

insert into crapPRG (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
values ('CRED', 'CERISC', 'Parâmetros Central de Risco', ' ', ' ', ' ', 50, 10830, 1, 0, 0, 0, 0, 0, 1, 9, null);

insert into crapPRG (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
values ('CRED', 'CERISC', 'Parâmetros Central de Risco', ' ', ' ', ' ', 50, 10830, 1, 0, 0, 0, 0, 0, 1, 11, null);

insert into crapPRG (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
values ('CRED', 'CERISC', 'Parâmetros Central de Risco', ' ', ' ', ' ', 50, 10830, 1, 0, 0, 0, 0, 0, 1, 14, null);

insert into crapPRG (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
values ('CRED', 'CERISC', 'Parâmetros Central de Risco', ' ', ' ', ' ', 50, 10830, 1, 0, 0, 0, 0, 0, 1, 10, null);

insert into crapPRG (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
values ('CRED', 'CERISC', 'Parâmetros Central de Risco', ' ', ' ', ' ', 50, 10830, 1, 0, 0, 0, 0, 0, 1, 8, null);

insert into crapPRG (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
values ('CRED', 'CERISC', 'Parâmetros Central de Risco', ' ', ' ', ' ', 50, 10830, 1, 0, 0, 0, 0, 0, 1, 1, null);

insert into crapPRG (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
values ('CRED', 'CERISC', 'Parâmetros Central de Risco', ' ', ' ', ' ', 50, 10830, 1, 0, 0, 0, 0, 0, 1, 16, null);

insert into crapPRG (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
values ('CRED', 'CERISC', 'Parâmetros Central de Risco', ' ', ' ', ' ', 50, 10830, 1, 0, 0, 0, 0, 0, 1, 15, null);

insert into crapPRG (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
values ('CRED', 'CERISC', 'Parâmetros Central de Risco', ' ', ' ', ' ', 50, 10830, 1, 0, 0, 0, 0, 0, 1, 13, null);

insert into crapPRG (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
values ('CRED', 'CERISC', 'Parâmetros Central de Risco', ' ', ' ', ' ', 50, 10830, 1, 0, 0, 0, 0, 0, 1, 12, null);

insert into crapPRG (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
values ('CRED', 'CERISC', 'Parâmetros Central de Risco', ' ', ' ', ' ', 50, 10830, 1, 0, 0, 0, 0, 0, 1, 3, null);

insert into crapPRG (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
values ('CRED', 'CERISC', 'Parâmetros Central de Risco', ' ', ' ', ' ', 50, 10830, 1, 0, 0, 0, 0, 0, 1, 4, null);

insert into crapPRG (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
values ('CRED', 'CERISC', 'Parâmetros Central de Risco', ' ', ' ', ' ', 50, 10830, 1, 0, 0, 0, 0, 0, 1, 2, null);

insert into crapPRG (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
values ('CRED', 'CERISC', 'Parâmetros Central de Risco', ' ', ' ', ' ', 50, 10830, 1, 0, 0, 0, 0, 0, 1, 7, null);

insert into crapPRG (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
values ('CRED', 'CERISC', 'Parâmetros Central de Risco', ' ', ' ', ' ', 50, 10830, 1, 0, 0, 0, 0, 0, 1, 6, null);

insert into crapPRG (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER, QTMINMED)
values ('CRED', 'CERISC', 'Parâmetros Central de Risco', ' ', ' ', ' ', 50, 10830, 1, 0, 0, 0, 0, 0, 1, 5, null);

COMMIT;