BEGIN

EXECUTE IMMEDIATE 'ALTER TRIGGER CECRED.TRG_CRAPBAN_ATLZ_CRM DISABLE';

COMMIT; 
  
INSERT INTO CECRED.CRAPBAN (CDOPERAD, DTMVTOLT, CDBCCXLT, NMRESBCC, NMEXTBCC, NRISPBIF, FLGDISPB, DTINISPB, DTALTSTR)
              VALUES('1', TO_DATE('28/11/2022','dd/mm/yyyy'), 455, 'FENIX DTVM LTDA.', 'FENIX DTVM LTDA.', 38429045, 1, TO_DATE('05/12/2022','dd/mm/yyyy'), TO_DATE('28/11/2022','dd/mm/yyyy'));

INSERT INTO CECRED.CRAPBAN (CDOPERAD, DTMVTOLT, CDBCCXLT, NMRESBCC, NMEXTBCC, NRISPBIF, FLGDISPB, DTINISPB, DTALTSTR)
              VALUES('1', TO_DATE('07/12/2022','dd/mm/yyyy'), 507, 'GERENCIANET CFI', 'GERENCIANET CFI', 37229413, 1, TO_DATE('12/12/2022','dd/mm/yyyy'), TO_DATE('07/12/2022','dd/mm/yyyy'));

INSERT INTO CECRED.CRAPBAN (CDOPERAD, DTMVTOLT, CDBCCXLT, NMRESBCC, NMEXTBCC, NRISPBIF, FLGDISPB, DTINISPB, DTALTSTR)
              VALUES('1', TO_DATE('17/11/2022','dd/mm/yyyy'), 510, 'FFCRED SCD S.A.', 'FFCRED SCD S.A.', 39738065, 1, TO_DATE('30/11/2022','dd/mm/yyyy'), TO_DATE('17/11/2022','dd/mm/yyyy'));

INSERT INTO CECRED.CRAPBAN (CDOPERAD, DTMVTOLT, CDBCCXLT, NMRESBCC, NMEXTBCC, NRISPBIF, FLGDISPB, DTINISPB, DTALTSTR)
              VALUES('1', TO_DATE('25/11/2022','dd/mm/yyyy'), 513, 'ATF CREDIT SCD S.A.', 'ATF CREDIT SCD S.A.', 44728700, 1, TO_DATE('02/12/2022','dd/mm/yyyy'), TO_DATE('25/11/2022','dd/mm/yyyy'));

INSERT INTO CECRED.CRAPBAN (CDOPERAD, DTMVTOLT, CDBCCXLT, NMRESBCC, NMEXTBCC, NRISPBIF, FLGDISPB, DTINISPB, DTALTSTR)
              VALUES('1', TO_DATE('06/12/2022','dd/mm/yyyy'), 519, 'LIONS TRUST DTVM', 'LIONS TRUST DTVM', 40768766, 1, TO_DATE('12/12/2022','dd/mm/yyyy'), TO_DATE('06/12/2022','dd/mm/yyyy'));
  
INSERT INTO CECRED.CRAPBAN (CDOPERAD, DTMVTOLT, CDBCCXLT, NMRESBCC, NMEXTBCC, NRISPBIF, FLGDISPB, DTINISPB, DTALTSTR)
              VALUES('1', TO_DATE('28/11/2022','dd/mm/yyyy'), 525, 'INTERCAM CC LTDA', 'INTERCAM CC LTDA', 34265629, 1, TO_DATE('05/12/2022','dd/mm/yyyy'), TO_DATE('28/11/2022','dd/mm/yyyy'));
  
INSERT INTO CECRED.CRAPBAN (CDOPERAD, DTMVTOLT, CDBCCXLT, NMRESBCC, NMEXTBCC, NRISPBIF, FLGDISPB, DTINISPB, DTALTSTR)
              VALUES('1', TO_DATE('08/11/2022','dd/mm/yyyy'), 529, 'PINBANK IP', 'PINBANK IP', 17079937, 1, TO_DATE('16/11/2022','dd/mm/yyyy'), TO_DATE('08/11/2022','dd/mm/yyyy'));
  

COMMIT; 

UPDATE CECRED.CRAPBAN BANCO
                  SET BANCO.NMRESBCC = 'GERENCIANET IP',
                      BANCO.NMEXTBCC = 'GERENCIANET IP'                  
                WHERE BANCO.CDBCCXLT = 364; 
         
       
UPDATE CECRED.CRAPBAN BANCO
                  SET BANCO.NMRESBCC = 'ACESSO SOLUCOES DE PAGAMENTO S.A. - INSTITUICAO DE',
                      BANCO.NMEXTBCC = 'ACESSO SOLUCOES DE PAGAMENTO S.A. - INSTITUICAO DE'                  
                WHERE BANCO.CDBCCXLT = 332;
         
COMMIT;

END;  
