DECLARE
  VN_EXISTE NUMBER := 0;
BEGIN
  BEGIN
    SELECT COUNT(1)
      INTO VN_EXISTE
      FROM ALL_TAB_COLS T 
     WHERE T.TABLE_NAME = 'HT_CONTRATACAO_CESTAS' 
       AND T.OWNER = 'TARIFAS' 
       AND T.COLUMN_NAME = 'CDEMPRESA';
  EXCEPTION
    WHEN OTHERS THEN
      VN_EXISTE := 0;
  END;
  --
  IF VN_EXISTE > 0 THEN
     --
     EXECUTE IMMEDIATE 'COMMENT ON COLUMN TARIFAS.HT_CONTRATACAO_CESTAS.CDEMPRESA IS ''Codigo da Cooperativa enviado pelo Topaz. #CLASSIFICACAO_DADO:I'' ';
     --
  END IF;
  --
  COMMIT;
  --
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK; 
END;
/