INSERT INTO cecred.craptab VALUES ('CRED','GENERI', 0, 'HRPBANCOOBAPI', 0, '64800', 1,'');
INSERT INTO cecred.craptab VALUES ('CRED','GENERI', 0, 'HRPBANCOOBAPI', 0, '64800', 2,'');
INSERT INTO cecred.craptab VALUES ('CRED','GENERI', 0, 'HRPBANCOOBAPI', 0, '64800', 3,'');
INSERT INTO cecred.craptab VALUES ('CRED','GENERI', 0, 'HRPBANCOOBAPI', 0, '64800', 4,'');
INSERT INTO cecred.craptab VALUES ('CRED','GENERI', 0, 'HRPBANCOOBAPI', 0, '64800', 5,'');
INSERT INTO cecred.craptab VALUES ('CRED','GENERI', 0, 'HRPBANCOOBAPI', 0, '64800', 6,'');
INSERT INTO cecred.craptab VALUES ('CRED','GENERI', 0, 'HRPBANCOOBAPI', 0, '64800', 7,'');
INSERT INTO cecred.craptab VALUES ('CRED','GENERI', 0, 'HRPBANCOOBAPI', 0, '64800', 8,'');
INSERT INTO cecred.craptab VALUES ('CRED','GENERI', 0, 'HRPBANCOOBAPI', 0, '64800', 9,'');
INSERT INTO cecred.craptab VALUES ('CRED','GENERI', 0, 'HRPBANCOOBAPI', 0, '64800', 10,'');
INSERT INTO cecred.craptab VALUES ('CRED','GENERI', 0, 'HRPBANCOOBAPI', 0, '64800', 11,'');
INSERT INTO cecred.craptab VALUES ('CRED','GENERI', 0, 'HRPBANCOOBAPI', 0, '64800', 12,'');
INSERT INTO cecred.craptab VALUES ('CRED','GENERI', 0, 'HRPBANCOOBAPI', 0, '64800', 13,'');
INSERT INTO cecred.craptab VALUES ('CRED','GENERI', 0, 'HRPBANCOOBAPI', 0, '64800', 14,'');
INSERT INTO cecred.craptab VALUES ('CRED','GENERI', 0, 'HRPBANCOOBAPI', 0, '64800', 15,'');
INSERT INTO cecred.craptab VALUES ('CRED','GENERI', 0, 'HRPBANCOOBAPI', 0, '64800', 16,'');
INSERT INTO cecred.craptab VALUES ('CRED','GENERI', 0, 'HRPBANCOOBAPI', 0, '64800', 17,'');

COMMIT;
