begin

	UPDATE CRAPTTL SET NMEXTTTL = 'VILSON WITTHOEFT' WHERE CDCOOPER = 1 AND NRDCONTA = 1849336 AND IDSEQTTL = 2;
	UPDATE CRAPTTL SET NMEXTTTL = 'VILSON WITTHOEFT' WHERE CDCOOPER = 1 AND NRDCONTA = 2628643 AND IDSEQTTL = 1;
	UPDATE CRAPTTL SET NMEXTTTL = 'EDUARDO HENRIQUE VIEIRA' WHERE CDCOOPER = 9 AND NRDCONTA = 295302 AND IDSEQTTL = 1;
	
	UPDATE CRAPASS SET NMPRIMTL = 'EDUARDO HENRIQUE VIEIRA' WHERE CDCOOPER = 9 AND NRDCONTA = 295302;
	UPDATE CRAPASS SET NMPRIMTL = 'VILSON WITTHOEFT' WHERE CDCOOPER = 1 AND NRDCONTA = 2628643;	
	
    commit;

end;


