BEGIN
  INSERT INTO CECRED.CRAPPRM (NMSISTEM,CDCOOPER,CDACESSO,DSTEXPRM,DSVLRPRM)
  VALUES ('CRED' , 0 , 'TESTE_CARGA_SPB', 'Quantidade entrada teste carga', '0' );
     
  COMMIT;
 
EXCEPTION
  WHEN OTHERS THEN
  NULL;
END;