BEGIN
   UPDATE TBCONV_REMESSA_PAGFOR REM
      SET REM.CDSTATUS_RETORNO = 1 
    WHERE REM.IDREMESSA = 101967;

 

   UPDATE TBCONV_REGISTRO_REMESSA_PAGFOR REG
      SET REG.NMARQUIVO_INCLUSAO = NULL,
          CDSTATUS_PROCESSAMENTO = 1,
          DSPROCESSAMENTO = NULL,
          DHINCLUSAO_PROCESSAMENTO = NULL,
          DHRETORNO_PROCESSAMENTO = NULL,
          NMARQUIVO_RETORNO = NULL,
          NRNSUBCB = NULL
    WHERE REG.IDSICREDI = 3553034;

 

   UPDATE CRAPPRO
      SET DSCOMPROVANTE_PARCEIRO = NULL, 
          CDAGEARR = NULL, 
          NMAGEARR = NULL, 
          CDAGENCI = NULL, 
      NMAGENCI = NULL 
    WHERE PROGRESS_RECID = 268512191;

 

   COMMIT;
END;