UPDATE CRAPPRM P
   SET P.DSVLRPRM = '20/09/2021#2'
 WHERE (CDACESSO LIKE 'CTRL_CRPS688_EXEC' OR
        CDACESSO LIKE 'CTRL_CRPS724_EXEC' OR
        CDACESSO LIKE 'CTRL_CRPS750_EXEC')
   AND CDCOOPER = 9
   AND P.NMSISTEM = 'CRED';
COMMIT;
