
BEGIN

insert into INTERNETBANKING.TBIB_ITENS_MENU_MULTCONTAS (IDITEM_MENU_MULTCONTAS ,CDITEM_MENU , CDCOOPER , NRDCONTA ,DHCADASTRO ) values ((select max(iditem_menu_multcontas) + 1 from INTERNETBANKING.TBIB_ITENS_MENU_MULTCONTAS) ,82 , null , null , sysdate);
insert into INTERNETBANKING.TBIB_ITENS_MENU_MULTCONTAS (IDITEM_MENU_MULTCONTAS ,CDITEM_MENU , CDCOOPER , NRDCONTA ,DHCADASTRO ) values ((select max(iditem_menu_multcontas) + 1 from INTERNETBANKING.TBIB_ITENS_MENU_MULTCONTAS) ,83 , null , null , sysdate);
insert into INTERNETBANKING.TBIB_ITENS_MENU_MULTCONTAS (IDITEM_MENU_MULTCONTAS ,CDITEM_MENU , CDCOOPER , NRDCONTA ,DHCADASTRO ) values ((select max(iditem_menu_multcontas) + 1 from INTERNETBANKING.TBIB_ITENS_MENU_MULTCONTAS) ,84 , null , null , sysdate);
insert into INTERNETBANKING.TBIB_ITENS_MENU_MULTCONTAS (IDITEM_MENU_MULTCONTAS ,CDITEM_MENU , CDCOOPER , NRDCONTA ,DHCADASTRO ) values ((select max(iditem_menu_multcontas) + 1 from INTERNETBANKING.TBIB_ITENS_MENU_MULTCONTAS) ,87 , null , null , sysdate);
insert into INTERNETBANKING.TBIB_ITENS_MENU_MULTCONTAS (IDITEM_MENU_MULTCONTAS ,CDITEM_MENU , CDCOOPER , NRDCONTA ,DHCADASTRO ) values ((select max(iditem_menu_multcontas) + 1 from INTERNETBANKING.TBIB_ITENS_MENU_MULTCONTAS) ,90 , null , null , sysdate);
insert into INTERNETBANKING.TBIB_ITENS_MENU_MULTCONTAS (IDITEM_MENU_MULTCONTAS ,CDITEM_MENU , CDCOOPER , NRDCONTA ,DHCADASTRO ) values ((select max(iditem_menu_multcontas) + 1 from INTERNETBANKING.TBIB_ITENS_MENU_MULTCONTAS) ,137 , null , null , sysdate);
insert into INTERNETBANKING.TBIB_ITENS_MENU_MULTCONTAS (IDITEM_MENU_MULTCONTAS ,CDITEM_MENU , CDCOOPER , NRDCONTA ,DHCADASTRO ) values ((select max(iditem_menu_multcontas) + 1 from INTERNETBANKING.TBIB_ITENS_MENU_MULTCONTAS) ,138 , null , null , sysdate);
insert into INTERNETBANKING.TBIB_ITENS_MENU_MULTCONTAS (IDITEM_MENU_MULTCONTAS ,CDITEM_MENU , CDCOOPER , NRDCONTA ,DHCADASTRO ) values ((select max(iditem_menu_multcontas) + 1 from INTERNETBANKING.TBIB_ITENS_MENU_MULTCONTAS) ,139 , null , null , sysdate);
insert into INTERNETBANKING.TBIB_ITENS_MENU_MULTCONTAS (IDITEM_MENU_MULTCONTAS ,CDITEM_MENU , CDCOOPER , NRDCONTA ,DHCADASTRO ) values ((select max(iditem_menu_multcontas) + 1 from INTERNETBANKING.TBIB_ITENS_MENU_MULTCONTAS) ,140 , null , null , sysdate);

 COMMIT;
                  
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
END;
