BEGIN

INSERT INTO CREDITO.TBCRED_REPASSADOR_CREDITO
  (NMREPASSADOR, DSREPASSADOR)
VALUES
  ('BNDES', 'Banco Nacional de Desenvolvimento Econômico e Social');
  
INSERT INTO CREDITO.TBCRED_REPASSADOR_CREDITO
  (NMREPASSADOR, DSREPASSADOR)
VALUES
  ('Finep', 'Financiadora de Estudos e Projetos');

INSERT INTO CREDITO.TBCRED_REPASSADOR_PRODUTO
  (IDPRODUTO_REPASSE, IDREPASSADOR_CREDITO, NMPRODUTOREPASSE)
VALUES
  (24000, 1, 'BNDES Automático');
  
INSERT INTO CREDITO.TBCRED_REPASSADOR_SUBPRODUTO
  (IDREPASSADOR_CREDITO,IDPRODUTO_REPASSE,DSLINHAREPASSE,CDCONDOPERACIONAL,DSCONDOPERACIONAL)
VALUES
  (1, 24000, 'Crédito Pequenas Empresas', 393, 'PO2020/01');  

COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
END;    
