BEGIN

UPDATE CRAPASS
SET NMPRIMTL = 'IVONEI ANTONIO RODRIGUES DE LARA'
where CDCOOPER = 14
AND NRDCONTA = 76279;


UPDATE CRAPTTL
SET NMEXTTTL = 'IVONEI ANTONIO RODRIGUES DE LARA'
  , NMTALTTL = 'IVONEI A R DE LARA'
where CDCOOPER = 14
AND NRDCONTA = 76279;
	 
  COMMIT;
  
END;