---  delete  CECRED.TBSEG_PRST_MOT_RECUSA ;
Begin

INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('1', 'Número de vidas não permitido para contratação do produto');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('2', 'Preenchimento indevido dos beneficiários para Cesta Básica, tendo em vista que esta apólice não prevê tais coberturas.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('3', 'Declaração Pessoal de Saúde com rasura.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('4', 'O percentual de comissão estar inválido');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('5', 'Declaração Pessoal de Saúde do cônjuge não preenchida.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('6', 'Ultrapassa Limite de Retenção R$ 2.000.000,01');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('7', 'Proposta sem pagamento 1º prêmio.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('8', 'Identidade /data de expedição do proponente/cônjuge não informado');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('9', 'Dados bancários inválidos/não informados/com rasura');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('10', 'CNPJ inválido/não informado.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('11', 'CPF do proponente com rasura/inválido/não informado.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('12', 'CPF do cônjuge inválido/não informado/com rasura');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('13', 'Capital segurado não informado');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('14', 'Capital segurado contratado divergente para o prêmio pago');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('15', 'Declaração Pessoal de Saúde do cônjuge preenchida com caneta/grafia divergente da Declaração Pessoal de Saúde do titular.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('16', 'Data de nascimento com rasura.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('17', 'Declaração Pessoal de Saúde do cônjuge não preenchida');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('18', 'Proposta com numeração inválida- SICREDI');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('19', 'Data de nascimento inválida/não informada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('20', 'Cobertura adicional divergente da proposta de adesão');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('21', 'Capital segurado com rasura.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('22', 'Proposta sem assinatura do proponente.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('23', 'Capital acima do limite permitido pela Cia.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('24', 'Categoria do INSS do proponente não informada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('25', 'Valor do prêmio divergente para coberturas contratadas');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('26', 'Data de assinatura da proposta superior a data do relógio protocolo');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('27', 'Prêmio mensal abaixo do mínimo.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('28', 'Data de assinatura da proposta com rasura');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('29', 'Número da identidade não informada/com rasura');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('30', 'Código de corretor não informado/rasura');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('31', 'Pré-existência informada na Declaração Pessoal de Saúde do conjugue.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('32', 'Conta poupança não pode ser utilizada para forma de pagamento débito em conta.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('33', 'Fora da Política de Aceitação');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('34', 'Idade do cônjuge superior ao limite do produto');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('35', 'Cônjuge aposentado por invalidez');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('36', 'Forma de pagamento, débito em conta corrente em Banco não conveniado.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('37', 'Código do corretor cancelado');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('38', 'Proposta de Adesão VE com rasura');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('39', 'Valor do prêmio informado na proposta não compatível com a periodicidade escolhida.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('40', 'Proposta com preenchimento incompleto.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('41', 'Proposta sem assinatura do corretor');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('42', 'Bateria de vendas incompleta/não informada/com rasura.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('43', 'Ramo de atividade - Risco excluído - VE');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('44', 'Proposta sem recibo de pagamento 1º prêmio');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('45', 'Correspondência de retificação anexada a proposta, com assinatura divergente da proposta.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('46', 'Estado civil do proponente, divergente para o grau de parentesco informado no Beneficiário (companheira).');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('47', 'Valor do prêmio com rasura.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('48', 'Cálculo do prêmio, divergente para o ramo de atividade');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('49', 'Coberturas adicionais, não podem ser contratados sozinho no Invida Mulher.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('50', 'A proposta em referência será recusada, em função da pré-existência informada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('51', 'Assinatura da proposta divergente da assinatura para autorização de débito em conta corrente.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('52', 'Dados do cônjuge preenchido indevidamente/incompleto.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('53', 'Prêmio SAF com valor incorreto');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('54', 'Correspondência anexada a proposta com divergência');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('55', 'O produto Vida Empresarial não está associado para o DG informado');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('56', 'Valor do prêmio divergente em função da idade informada');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('57', 'Data da assinatura com mais de 60 dias em relação ao relógio protocolo.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('58', 'Dados do cônjuge não informado.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('59', 'Forma de pagamento informada, inválida');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('60', 'Declaração Pessoal de Saúde não preenchida/assinada/incompleta');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('61', 'Autorização de débito em conta corrente, não foi assinada pelo correntista.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('62', 'Ramo de atividade não informado');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('63', 'Declaração Pessoal de Saúde preenchida com caneta divergente da assinatura.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('64', 'Endereço incompleto ou não informado');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('65', 'Débito em conta corrente Pessoa Jurídica.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('66', 'Débito em conta corrente de terceiros');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('67', 'Beneficiário informado na proposta, pessoa jurídica');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('68', 'Proposta extraviada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('69', 'Idade do proponente acima do limite permitido na cláusula contratual.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('70', 'Idade abaixo do limite permitido pela política de aceitação.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('71', 'Prêmio ou capital incorreto/não informado');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('72', 'Prêmio abaixo do mínimo estabelecido pela apólice - (CARNÊ)');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('73', 'Percentual dos beneficiários acima de 100%.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('74', 'Falta assinatura do cônjuge.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('75', 'Risco agravado.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('76', 'Motivo da aposentadoria não informado.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('77', 'Falta assinatura titular c/corrente');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('78', 'Aposentado por invalidez');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('79', 'Aposentadoria sem especificação');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('80', 'Falta Assinatura e RG dos pais, tutor ou curador, idade entre (14 a 18 anos incompletos).');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('81', 'Recusa a pedido.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('82', 'CEI não cadastrado ou inválido.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('83', 'Não recebimento DPS do(s) Sócio(s).');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('84', 'Proponente menor de idade');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('85', 'Segurado não alfabetizado - falta assinatura das testemunhas.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('86', 'Falta Carimbo CCG ou do Encarregado da CIA');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('87', 'Cartão proposta não confere com o CNPJ informado');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('88', 'Rasura Cobertura Campo SAF');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('89', 'Solicitação cobertura de SAF sem pagamento');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('90', 'Proposta com os dados ilegíveis/rasura');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('91', 'CEI - Informações disponíveis, junto ao SITE da Caixa, são insuficientes para comprovar regularidade junto ao FGTS).');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('92', 'Rasura campo número de Funcionários/Sócios');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('93', 'Divergência nas assinaturas.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('94', 'Proposta assinada por procuração');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('95', 'Não possui um certificado no SICREDI Previdência.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('96', 'Nº da cooperativa e unidade não informados');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('97', 'Dia do vencimento não informado');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('98', 'Apólice não disponível para comercialização');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('99', 'Faz-se necessário o envio de documentos/informações complementares, conforme carta de análise médica em anexo.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('100', 'Carta de autorização da cobertura IFPD não encaminhada junto a proposta.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('101', 'Testemunha(s) constante(s) na proposta de seguro em desacordo com normativa CO021907.CSS');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('102', 'Preenchimento indevido dos dados do cônjuge, tendo em vista que a apólice não permite inclusão facultativa de cônjuge.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('103', 'Idade acima do limite permitido pela política de aceitação.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('104', 'Profissão/Atividade - risco recusado');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('105', 'Valor do Prêmio não informado');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('106', 'Idade acima do limite para aumento do capital');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('107', 'Local e data de assinatura da Declaração Pessoal de Saúde, não preenchidos.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('108', 'Data de nascimento do proponente/cônjuge não informada ');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('109', 'Nacionalidade do proponente não informada');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('110', 'Local e data de assinatura da proposta, não preenchidos');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('111', 'Designação de beneficiário(s) em desacordo com a legislação - Código Civil Brasileiro.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('112', 'Dados do Angariador inválidos/não informados/com rasura');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('113', 'Não recebida a via da proposta da Seguradora');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('114', 'Capital segurado inválido para idade do proponente');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('115', 'Declaração Pessoal de Saúde com preenchido incompleto');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('116', 'Valor do prêmio divergente para o capital segurado contratado');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('117', 'Local, data e assinatura da Declaração Pessoal de Saúde e proposta não preenchidos.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('118', 'Preenchimento indevido dos beneficiários para Auxílio Despesa, tendo em vista que esta apólice não prevê tais coberturas.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('119', 'Preenchimento de Declaração Pessoal de Saúde com grafias diferentes.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('120', 'Não associado ao SICREDI');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('121', 'Módulos excedentes, acima de 11');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('122', 'Proposta assinada por procuração não específica para este fim');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('123', 'Corretor não cadastrado');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('124', 'Proposta fora do novo padrão');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('125', 'Formulário inválido (logomarca Icatu Hartford)');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('126', 'Proposta sem data de assinatura');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('127', 'NÃO ATENDIMENTO AS SOLICITAÇÕES MÉDICAS!');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('128', 'Capital segurado inferior ao limite permitido para inclusão na apólice.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('129', 'Preenchimento indevido da cobertura DDDG.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('130', 'Declaração Pessoal de Saúde preenchida por digitação e proposta sem local e data de assinatura.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('131', 'Entrevista telefônica por profissional de saúde para a aceitação do seguro, não realizada');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('132', 'Entrevista telefônica por profissional de saúde para a aceitação do seguro, não realizada, local e data de assinatura da proposta, não preenchidos.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('133', 'A soma dos capitais ultrapassa o limite da apólice.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('134', 'Capital acima do limite da apólice.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('135', 'Idade do proponente é inferior a idade permitida pelo produto.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('136', 'Proposta sem data de assinatura');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('137', 'Código do corretor cancelado');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('138', 'Declaração Pessoal de Saúde preenchida com caneta divergente da assinatura.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('139', 'Nº de apólice incorreto na proposta.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('140', 'Local, data e Declaração Pessoal de Saúde não preenchidos.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('141', 'Assinatura do proponente com rasura');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('142', 'Valor do prêmio inválido.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('143', 'Proposta com irregularidades.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('144', 'Entrevista telefônica por profissional de saúde para a aceitação do seguro, não realizada. Capital acima do limite para contratação do Unique.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('145', 'Recusada por substituição de nova proposta no produto correto.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('146', 'Entrevista telefônica por profissional de saúde não realizada e o corretor informado se encontra Bloqueado/Cancelado.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('147', 'O corretor informado se encontra Bloqueado/Cancelado.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('148', 'Local e data de assinatura da Declaração pessoal de Saúde e proposta, não preenchidos. Informar o motivo pelo qual não se encontra em plena atividade profissional.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('149', 'Capital Segurado inválido');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('150', 'Corretor não cadastrado.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('151', 'Proposta com irregularidades no preenchimento.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('152', 'Recusa a pedido conforme carta enviada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('153', 'DPS com preenchimento incompleto, item 31 até 35.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('154', 'DPS com preenchimento incompleto.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('155', 'Entrevista telefônica por profissional de saúde para a aceitação do seguro, não realizada, local e data de assinatura da proposta, não preenchidos.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('156', 'Proposta sem Declaração Pessoal de Saúde');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('157', 'Proposta recusada, recebemos nova proposta assinada e datada para regularizar pendência anterior.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('159', 'DPS ter sido preenchida à máquina. Enviar relatório fornecido pelo seu médico, sobre a sua condição atual de saúde.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('160', 'Cobertura básica não informada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('161', 'Cobertura de IFPD divergente da cobertura básica.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('162', 'Recusa a pedido.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('163', 'Pendência não regularizada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('164', 'DPS preenchida a máquina. Informar o motivo pelo qual não se encontra em plena atividade profissional, item 1 da DPS.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('165', 'DPS preenchida a máquina.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('166', 'Valor do capital segurado, abaixo do mínimo permitido para o produto Unique.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('167', 'DPS preenchida a máquina. Enviar relatório médico informando desde quando é portador de hipertensão arterial, acrescentando dados médicos sobre os tratamentos que realiza atualmente, se existem complicações em órgãos alvos e resultado dos últimos exames realizados.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('168', 'Capital e prêmio da cobertura DIT não informados.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('169', 'Não regularizou pendência médica. Prêmio invalido.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('170', 'Capital e prêmio da cobertura de DIT não informado.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('171', 'Proposta sem data de assinatura. Recusa médica até a realização da Cirurgia de Tendão.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('172', 'Data da assinatura com mais de 60 dias em relação ao relógio protocolo.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('173', 'Atividade - risco recusado');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('174', 'Valor do prêmio inválido referente a idade na data da assinatura.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('175', 'Proposta sem data de assinatura. Encaminhar juntamente com uma nova proposta devidamente preenchida, datada e assinada, os exames de ECG e Teste Ergométrico.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('176', 'Data de assinatura da proposta posterior a data de protocolo.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('178', 'Valor do prêmio incorreto e com rasura.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('179', 'Proposta sem Assinatura, local e data.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('180', 'DPS não preenchida.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('181', 'Valor da cobertura de DIT inválida.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('182', 'DPS não preenchida e Proposta sem data da assinatura');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('183', 'As condições atualmente apresentadas por V.Sa., não estão dentro dos critérios de aceitação de risco, estipuladas por esta Sociedade Seguradora.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('184', 'Valor do prêmio da cobertura SAF inválido');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('185', 'Conta corrente não preenchida ou invalida.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('186', 'Declaração Pessoal de Saúde digitada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('187', 'Recebemos nova proposta para regularizar pendência de CPF');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('188', 'Cobertura marcada indevidamente.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('189', 'Conta corrente não preenchida.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('190', 'Proposta sem local e data da assinatura.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('191', 'Valor do prêmio inválido, envio de exames, Teste Ergométrico; ECG devido relato de Arritmia Cardíaca; Coleta de uma Urina I; e US Renal e Pélvica.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('192', 'Capital da cobertura de DIT não informado.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('193', 'DPS não enviada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('194', 'Profissão fora da política de aceitação para contratação da cobertura de DIT');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('195', 'Coberturas contratadas diferente das cadastrada para o modulo 1472.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('196', 'As condições atualmente apresentadas por V.Sa. referente a prática esportiva, não estão dentro das condições de aceitação de risco estipuladas por esta Sociedade Seguradora.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('197', 'Conforme contrato, devido ao capital do DIT ser superior a R$ 6.000,00 é obrigatório comprovar o rendimento por meio da Declaração do Imposto de Renda ou Decore.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('198', 'SAF com valor incorreto.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('199', 'Profissão/Atividade -risco recusado para cobertura DIT');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('200', 'Modalidade esportiva fora da política de aceitação.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('201', 'A profissão/atividade atualmente apresentada por V.Sa., não estão dentro das condições técnicas de aceitação de risco estipuladas por esta Sociedade Seguradora.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('202', 'Preenchimento indevido da DPS do cônjuge, tendo em vista que essa apólice não abrange cobertura de cônjuge.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('203', 'Preenchimento de capital em campo divergente da cobertura marcada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('204', 'Declaração do Proponente/Associado sem assinatura.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('205', 'Capital acima do limite, para contratação do Global.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('206', 'Aposentados por invalidez (doença ou acidente) não podem contratar cobertura de IFPD (Invalidez Funcional Permanente Total por Doença).');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('207', 'Falecimento do proponente.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('208', 'Cobertura principal não contratada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('209', 'O capital contratado do DIT não pode ser superior a renda mensal.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('210', 'É obrigatória a contratação da garantia básica - morte.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('211', 'Item 01 da DPS não preenchido.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('212', 'As condições atualmente apresentadas por V.Sa., não estão dentro dos critérios de aceitação de risco, estipuladas por esta Sociedade Seguradora.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('213', 'Capital segurado contratado inferior ao limite mínimo da apólice.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('214', 'Data de vencimento do boleto não informada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('215', 'Tele Entrevista não realizada e valor do prêmio inválido.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('216', 'Valor do prêmio inválido e proposta sem data de assinatura.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('217', 'Data da assinatura com mais de 60 dias em relação ao relógio protocolo / Valor do prêmio inválido.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('218', 'Proposta sem data da assinatura / DPS do titular não preenchida');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('219', 'Quantidade de módulos contratados encontra-se acima do limite máximo permitido para essa proposta.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('220', 'Preenchimento indevido dos dados do cônjuge, tendo em vista que não optou pela inclusão do cônjuge.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('221', 'Apólice não cadastrada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('222', 'Capital segurado e prêmio divergentes para o módulo informado na proposta.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('223', 'Data de assinatura da proposta posterior a data de protocolo');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('224', 'Data de assinatura da proposta posterior a data de protocolo./DPS sem assinatura e data.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('225', 'Data da assinatura com mais de 60 dias em relação ao relógio protocolo.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('226', 'Apólice não abrange Assistência Veículo de Passeio.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('227', 'Nº do Módulo incorreto para o prêmio informado.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('228', 'Coberturas incorretas para o módulo informado.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('229', 'A soma dos capitais da garantia DIT ultrapassa o limite da apólice.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('230', 'Declaração Pessoal de Saúde sem assinatura.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('231', 'Capital abaixo do limite permitido pela Cia.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('232', 'Data da assinatura posterior a data do protocolo/ valor do prêmio inválido.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('233', 'Valor do prêmio inválido para o módulo informado.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('234', 'Idade acima do limite da apólice.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('235', 'Proposta sem data da assinatura e DPS rasurada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('236', 'Valor do prêmio inválido/Declaração do Imposto de Renda ou Decore não enviada (devido ao valor do DIT),');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('237', 'Capital do DIT abaixo do limite da apólice.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('238', 'Declaração Pessoal de Saúde com preenchimento incorreto.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('239', 'Assinatura da DPS divergente da assinatura da proposta');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('241', 'Cobertura de SAF obrigatória para o produto contratado.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('242', 'DPS não preenchida / Valor do prêmio inválido.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('243', 'Cor de caneta da DPS diferente da assinatura / Valor do prêmio inválido.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('244', 'Valor do capital segurado para a cobertura de SAF está acima do permitido para essa apólice.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('245', 'As condições de saúde atualmente apresentadas por V.Sa., não estão dentro das condições médicas de aceitação de risco estipuladas por esta Sociedade Seguradora para contratação da cobertura DIT.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('246', 'Capital inválido para idade informada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('247', 'Assinatura da proposta divergente do documento de identificação.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('248', 'Proposta sem assinatura do proponente.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('249', 'Capital inválido para a quantidade de módulos contratado');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('250', 'A soma dos capitais ultrapassa o limite da apólice.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('251', 'A soma dos capitais da cobertura de DIT ultrapassa a renda mensal.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('252', 'Valores dos prêmios das coberturas informados incorretamente / Profissão não informada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('253', 'A soma dos capitais da cobertura DIT ultrapassa a renda mensal.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('254', 'As condições de saúde e atividade (hobby) atualmente apresentados por V.Sa., não estão dentro das condições de aceitação de risco estipuladas por esta Sociedade Seguradora.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('255', 'A atividade (hobby) atualmente apresentada por V.Sa., não se encontra dentro das condições de aceitação de risco estipuladas por esta Sociedade Seguradora.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('256', 'Capital e prêmio inválidos.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('257', 'As condições de saúde atualmente apresentadas por V.Sa., não estão dentro das condições médicas de aceitação de risco estipuladas por esta Sociedade Seguradora para contratação da cobertura DG.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('258', 'Valores dos prêmios de todas as coberturas encontram-se inválidos para o módulo contratado.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('259', 'Proposta rasurada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('261', 'Preenchimento indevido dos dados do cônjuge, tendo em vista que optou pelo plano individual / Proposta sem loca, data e assinatura na declaração do proponente.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('262', 'Profissão/ atividade do cônjuge fora da política de aceitação; valor do prêmio inválido.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('263', 'A soma dos capitais da cobertura de DIT ultrapassa o limite da apólice.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('264', 'DATA DA ASSINATURA COM MAIS DE 60 DIAS EM RELAÇÃO AO RELÓGIO PROTOCOLO/ VALOR DO PRÊMIO INVÁLIDO.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('265', 'VALOR DO PRÊMIO INVÁLIDO/ FICHA FINANCEIRA NÃO ENVIADA.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('266', 'Proposta assinada por procuração sem recebimento da procuração');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('267', 'Cor de caneta da DPS diferente da assinatura.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('268', 'Profissão/Atividade -risco recusado para cobertura DIT e IFPD');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('269', 'A soma dos capitais ultrapassa o limite da apólice.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('270', ' Capital do DIT acima da renda informada / Ficha Financeira não enviada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('271', 'Valor do prêmio inválido para o módulo contratado./Dados cadastrais e DPS do cônjuge não preenchidos.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('272', 'Proposta sem local e data da assinatura/Valor do prêmio inválido');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('273', 'Capital segurado da cobertura de DIT inferior ao limite permitido para essa apólice, não podendo ultrapassar o valor da renda mensal.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('274', 'Possui a proposta Profissional Liberal nº 930094702655. A soma dos capitais da cobertura DIT ultrapassa o limite da apólice.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('275', 'Valor do capital da cobertura PIE inválido/Data da assinatura com mais de 60 dias em relação ao relógio protocolo.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('276', 'Recusa a pedido devido a preenchimento incorreto na proposta.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('277', 'Proposta sem a DPS/ Módulo não informado / Código corretor não informado.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('278', 'Contratação através CEI com mais de um Sócio/Administrador');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('279', 'Proposta incompleta (faltando página).');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('280', 'DPS COM PREENCHIMENTO INCOMPLETO / CAPITAL E PRÊMIO NÃO INFORMADOS');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('281', 'Declaração Pessoal de Saúde preenchida com caneta e grafia divergentes da assinatura.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('282', 'Preenchimento indevido dos dados do cônjuge, tendo em vista que o módulo escolhido não abrange cobertura de cônjuge.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('283', 'A soma dos capitais da cobertura DIT ultrapassa o valor da renda mensal.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('285', 'DPS preenchida com caneta divergente da assinatura. / Valor do prêmio inválido.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('286', 'Proposta sem data da assinatura./DPS não preenchida.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('287', 'As condições apresentadas na tele entrevista não estão dentro das condições técnicas de aceitação de risco estipuladas por esta Sociedade Seguradora.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('288', 'Declaração Pessoal de Saúde com data da assinatura com mais de 60 dias com relação ao relógio protocolo.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('289', 'Proposta com preenchimento indevido da DPS do cônjuge, tendo em vista que não optou pela contratação das coberturas de cônjuge.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('290', 'DPS RASURADA.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('291', 'Falta laudo médico (CID) conforme solicitação em anexo.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('292', 'Beneficiário não informado/ incompleto');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('293', 'Beneficiário com rasura');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('294', 'Proposta/Formulário antigo');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('295', 'Proposta assinada por procuração sem recebimento da procuração.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('296', 'Capital da cobertura DIT acima da renda mensal.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('297', 'O título foi pago com valor diferente do Valor da Parcela.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('298', 'Assinatura na proposta divergente da curadora responsável');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('299', 'A soma dos capitais ultrapassa o limite para a cobertura de DIT.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('300', 'Idade abaixo do limite da apólice.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('301', 'DPS não preenchida./Profissão não esclarecida.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('302', 'Nome da assinatura divergente do nome do proponente.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('303', 'As condições de saúde atualmente apresentadas pelo cônjuge da V.Sa., não estão dentro das condições médicas de aceitação de risco estipuladas por esta Sociedade Seguradora.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('304', 'Valor do prêmio e do capital inválidos para essa apólice.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('305', '- Cobertura de IPAM somente disponível para médicos e dentistas, não sendo permitido para outras profissões.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('306', 'A profissão/atividade atualmente apresentada por V Sa. não se encontra dentro das condições técnicas de aceitação de risco estipuladas por esta Sociedade Seguradora para contratação de DIT e IPA.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('307', 'Idade acima do limite do produto.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('308', 'As condições atualmente apresentadas pelo cônjuge, não estão dentro dos critérios de aceitação de risco estipulados por esta Sociedade Seguradora.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('309', 'Capital da cobertura DIT maior que a renda mensal.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('310', 'As condições de saúde atualmente apresentadas por V.Sa., não estão dentro das condições médicas de aceitação de risco estipuladas por esta Sociedade Seguradora para contratação das coberturas de DIT e IFPD.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('311', 'Proposta sem data da assinatura/DPS sem assinatura.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('312', 'Profissão fora da política de aceitação para contratação da cobertura de IPA');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('314', 'Profissão fora da política de aceitação para contratação da cobertura de IPA e DIT.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('315', 'Proposta inválida, cópia.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('316', 'Razões técnicas.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('317', 'As condições técnicas apresentadas por VSa. não se encontra dentro das condições de aceitação de risco estipuladas por esta Sociedade Seguradora.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('318', 'Profissão fora da política de aceitação para contratação da cobertura de IPA, IEA e DIT');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('319', 'DPS não preenchida de próprio punho (digitada).');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('321', 'Nova proposta assinada e datada recusada, regularizada e aceita a proposta anterior.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('322', 'Proposta sem assinatura das testemunhas. Tratando-se de proponente analfabeto ou impossibilitado de assinar, deve-se colocar a digital do polegar direito e junto, a assinatura de duas testemunhas, devidamente qualificadas, com cópia do RG e CPF.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('323', 'As condições de saúde atualmente apresentadas pelo cônjuge, não estão dentro das condições de aceitação de risco estipuladas por esta Sociedade Seguradora.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('324', 'Profissão fora da política de aceitação para contratação da cobertura de DIT com LER/DORT/LTC');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('325', 'entrevista');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('326', 'A atividade (hobby) atualmente apresentada por V.Sa., não se encontra dentro das condições de aceitação de risco estipuladas por esta Sociedade Seguradora para contratação da cobertura DIT.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('327', 'Valor da renda mensal incompatível para a contratação das garantias Morte e IFPD em relação ao valor de capital informado.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('328', 'Declaração Pessoal de Saúde não preenchida.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('329', 'Coberturas de IEA e IPA não marcadas na proposta, porém são obrigatórias para a contração desse seguro. ');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('331', 'A profissão/atividade atualmente apresentada por VSa. não se encontra dentro das condições técnicas de aceitação de risco estipuladas por esta Sociedade Seguradora, para contratação da cobertura de DIT e IPA Majorada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('332', 'A soma dos capitais ultrapassa o limite para as coberturas de DIT e IPA.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('333', 'As condições de saúde atualmente apresentadas por V.Sa., não estão dentro das condições médicas de aceitação de risco estipuladas por esta Sociedade Seguradora para contratação da cobertura de IPA.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('334', 'Proposta em Duplicidade');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('335', 'As condições atualmente apresentadas por V.Sa., não estão dentro das condições técnicas de aceitação de risco estipuladas por esta Sociedade Seguradora para contratação da cobertura de IPA.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('336', 'Desistência da contratação do seguro.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('337', 'A soma dos capitais ultrapassa o limite para a cobertura de DG.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('338', 'Declaração Pessoal de Saúde ilegível e assinatura sobreposta.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('339', 'A soma dos capitais ultrapassa o limite do produto.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('340', 'Cobertura de SAF obrigatória para a apólice contratada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('341', 'A profissão/atividade atualmente apresentada por VSa. não se encontra dentro das condições técnicas de aceitação de risco estipuladas por esta Sociedade Seguradora para contratação da cobertura de DIT com LER/DORT/LTC.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('342', 'Declaração Pessoal de Saúde com grafias diferentes.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('343', 'Assinatura a rogo. Faz-se necessário a assinatura da testemunha informando o número do CPF.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('344', 'Capital da cobertura DG acima de 200% em relação ao capital da cobertura Morte.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('345', 'Capital da cobertura DIT acima de 10% em relação a cobertura IEA.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('346', 'O produto Essencial Vida foi alterado e, por esse motivo, não foi possível aceitarmos a sua proposta. Para mais informações, procure seu corretor.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('347', 'Capital da cobertura DG acima do limite para inclusão na apólice.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('348', 'Fora da política de aceitação de risco estipulado por esta Sociedade Seguradora, conforme informações declaradas.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('349', 'Idade abaixo do limite do produto, para contratação das assistências Fratura Óssea e Despesas Médicas Hospitalares.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('350', 'As condições atualmente apresentadas por V.Sa., não estão dentro dos critérios de aceitação de risco, estipuladas por esta Sociedade Seguradora.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('351', 'Assinatura Inválida');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('352', 'Capital acima do limite permitido para a cobertura de Doenças Graves no modelo de proposta utilizada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('353', 'Capital acima do limite permitido para a cobertura de DIT no modelo de proposta utilizada.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('354', 'Favor detalhar o item 1 da DPS informando a frequência de uso do medicamento, e o item 3 com as informações referentes ao Tumor (Teste Unicred).');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('355', 'Capital da cobertura DIT acima de 10% em relação ao capital da cobertura IEA.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('356', 'Capital da cobertura DG acima de 200% em relação ao capital da cobertura Morte.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('357', 'O produto Profissional Liberal foi alterado e, por esse motivo, não foi possível aceitarmos a sua proposta. Para mais informações, procure seu corretor.');
INSERT INTO CECRED.TBSEG_PRST_MOT_RECUSA (IDMOTIVO, DSMOTIVO) VALUES ('358', 'Proposta assinada não enviada');


 COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    dbms_output.put_line('Erro ao inserir registros na crapprm - '||sqlerrm);
END;

