
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('AB','Tipo de Operação Inválido');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('AC','Tipo de Serviço Inválido');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('AE','Tipo/Número de Inscrição Inválido');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('AG','Número Agência Cooperativa Inválida');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('AH','Numero Sequencial do Registro de Lote Inválido');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('AI','Código Segmento Inválido');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('AJ','Tipo de Movimento Inválido');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('AL','Código Banco Favorecido Inválido');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('AM','Agência Mantedora da Conta Inválida');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('AO','Nome do Favorecido Não Informado');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('AP','Data Lançamento Inválida');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('AQ','Tipo/Quantidade de Moeda Inválido');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('AR','Valor do Lnaçamento Inválido');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('AT','Tipo/Número de Inscrição do Favorecido Inválido');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('AZ','Código Banco Inválido');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('A1','Dígito Agência Cooperativa Inválida');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('A2','Número Agência Favorecido Inválido');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('A3','Dígito Agência Favorecido Inválido');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('C1','Número Conta Corrente Inválido');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('C2','Dígito Conta Corrente Inválido');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('DG','Data Geração do Arquivo Inválida');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('HH','Lote de Serviço Inválido');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('HJ','Tipo de Registro Inválido');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('HK','Código Remessa/Retorno Inválida');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('HL','Versão Layout Inválida');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('NA','Conta Corrente/DV/Conta de Pagamento do Favorecido Inválido');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('NE','Nome da empresa não Informado');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('NS','Número Sequencial do Arquivo Inválido');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('TA','Quantidade/Totais do lote inválidos');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('VT','Valor total das Operações Inválido');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('YD','Código/Finalidade da Ocorrência Inválido');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('YE','Complemento/Histórico da Transação não informado');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('BD','Inclusão Efetuada com Sucesso');
Insert into CECRED.TBTRANSF_ERROS_CNAB
   (TPERROCNAB, DSERROCNAB)
 Values
('EV','Erro no processamento');
COMMIT;
