begin
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (1,'DEBITO CHEQUE');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (2,'CREDITO COBRANCA');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (3,'CREDITO COBRANCA 2');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (4,'CREDITO COBRANCA 3');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (5,'CREDITO COBRANCA 4');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (6,'CREDITO COBRANCA 5');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (7,'CREDITO COBRANCA 6');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (8,'DEB BLOQ DE CHEQUE EM CUSTODIA');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (9,'DEB CHEQUE PROPRIA COOPERATIVA');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (10,'CREDITO DE TRANSFERENCIA VIA INTERNET');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (11,'TRANSFERENCIA INTERCOOPERATIVA');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (12,'TRANSFERENCIA COOPERATIVA');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (13,'DEB CHEQUE PRACA E FORA PRACA');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (14,'FOLHA DE PAGAMENTO');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (15,'CREDITO TED');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (16,'CREDITO DOC');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (17,'ACERTO CHEQUE EXTRA CAIXA');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (18,'DEBITO TED');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (19,'MOVIMENTACOES AILOS');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (20,'CHEQUE COMPENSADO');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (21,'MOVIMENTACOES CONTA');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (22,'DEPOSITO CHEQUE');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (23,'CREDITO DESCONTO CHEQUE');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (24,'BORDERO DE TITULO');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (25,'CRED TED BB / CRED VIA BB');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (26,'SAQUE CARTAO');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (27, 'PAGAMENTO INTERNET-BOLETO/CONVENIO');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (28, 'DEVOLUCOES');
  insert into tbjur_prm_quebra_sigilo(cdestsig, nmestsig) values (29, 'AJUSTES COOPERATIVA');

  update craphis set cdestsig = 1 where cdhistor = 21;
  update craphis set cdestsig = 2 where cdhistor = 266;
  update craphis set cdestsig = 3 where cdhistor = 971;
  update craphis set cdestsig = 4 where cdhistor = 977;
  update craphis set cdestsig = 5 where cdhistor = 987;
  update craphis set cdestsig = 6 where cdhistor = 1089;
  update craphis set cdestsig = 7 where cdhistor = 654;
  update craphis set cdestsig = 8 where cdhistor = 881;
  update craphis set cdestsig = 9 where cdhistor = 386;
  update craphis set cdestsig = 10 where cdhistor = 537;
  update craphis set cdestsig = 10 where cdhistor = 538;
  update craphis set cdestsig = 10 where cdhistor = 539;
  update craphis set cdestsig = 11 where cdhistor = 1009;
  update craphis set cdestsig = 11 where cdhistor = 1014;
  update craphis set cdestsig = 11 where cdhistor = 1011;
  update craphis set cdestsig = 11 where cdhistor = 1015;
  update craphis set cdestsig = 12 where cdhistor = 302;
  update craphis set cdestsig = 12 where cdhistor = 771;
  update craphis set cdestsig = 12 where cdhistor = 303;
  update craphis set cdestsig = 13 where cdhistor = 3;
  update craphis set cdestsig = 13 where cdhistor = 4;
  update craphis set cdestsig = 13 where cdhistor = 372;
  update craphis set cdestsig = 14 where cdhistor = 889;
  update craphis set cdestsig = 15 where cdhistor IN (578, 799);
  update craphis set cdestsig = 16 where cdhistor = 548;
  update craphis set cdestsig = 16 where cdhistor = 575;
  update craphis set cdestsig = 17 where cdhistor = 521;
  update craphis set cdestsig = 18 where cdhistor = 503;
  update craphis set cdestsig = 18 where cdhistor = 555;
  update craphis set cdestsig = 19 where cdhistor in (351,399,47,15,79,501,530,597,377,613,630,320,354,658,535,504);
  update craphis set cdestsig = 19 where cdhisrec IN (102,104,105,106,107,110);
  update craphis set cdestsig = 20 where cdhistor = 524;
  update craphis set cdestsig = 20 where cdhistor = 27;
  update craphis set cdestsig = 20 where cdhistor = 1873;
  update craphis set cdestsig = 21 where cdhistor = 570;
  update craphis set cdestsig = 21 where cdhistor = 22;
  update craphis set cdestsig = 21 where cdhistor = 614;
  update craphis set cdestsig = 21 where cdhistor = 1030;
  update craphis set cdestsig = 21 where cdhistor = 271;
  update craphis set cdestsig = 21 where cdhistor = 1;
  update craphis set cdestsig = 21 where cdhistor in (1791,662,1404,1560,1577,1895,1558,600,1260,2123,1566);
  update craphis set cdestsig = 22 where cdhistor in (3, 2433);
  update craphis set cdestsig = 22 where cdhistor = 4;
  update craphis set cdestsig = 23 where cdhistor = 270;
  update craphis set cdestsig = 24 where cdhistor = 686;
  update craphis set cdestsig = 25 where cdhistor = 651;
  update craphis set cdestsig = 25 where cdhistor = 1875;
  update craphis set cdestsig = 26 where cdhistor = 316;
  update craphis set cdestsig = 27 where cdhistor IN (508, 856);
  update craphis set cdestsig = 28 where cdhistor = 465;
  UPDATE craphis set cdestsig = 29 where cdhistor = 362;
  
  UPDATE craphis c
     SET c.cdestsig = 28
   WHERE c.cdestsig IS NULL
     AND c.cdhistor IN (578,170,1908,1909,1897,1892,169,170,314,646,651,573,887,918,1290,1405,2175,2176,2179,2740,110);

  commit;
end;