BEGIN
  UPDATE CECRED.CRAPASS A
    SET flgrestr = 1
  WHERE A.CDCOOPER = 1
    AND A.NRDCONTA IN (17716756, 84413603);
    
  commit;
  
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20000, 'ERRO: ' || SQLERRM);
END;
