begin
   
  UPDATE cecred.tbdomic_liqtrans_pdv PDV SET
       pdv.cdocorrencia_retorno = NULL,
       pdv.dsocorrencia_retorno = NULL,
       pdv.dhretorno            = NULL,
       pdv.dserro  = NULL
  WHERE pdv.idcentraliza IN (SELECT idcentraliza
                            FROM tbdomic_liqtrans_centraliza
                           WHERE idlancto IN (SELECT idlancto
                                                FROM tbdomic_liqtrans_lancto
                            WHERE IDARQUIVO IN (923724,923725,923751,923752,923764,923765,923780,923781,923799,923800,923819,923820,923831,
                            923832,923846,923847,923860,923861,923888, 923889,923910,923911) ));

  commit; 
                              
  update cecred.tbdomic_liqtrans_lancto l
  set insituacao = 0
  where  IDARQUIVO IN (923724,923725,923751,923752,923764,923765,923780,923781,923799,923800,
  923819,923820,923831,923832,923846,923847,923860,923861,923888,923889,923910,923911);

  commit;
  
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923724'; 
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923725'; 
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923751'; 
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923752'; 
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923764'; 
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923765'; 
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923780'; 
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923781'; 
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923799'; 
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923800'; 
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923819'; 
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923820'; 
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923831'; 
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923832'; 
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923846'; 
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923847'; 
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923860'; 
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923861'; 
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923888'; 
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923889'; 
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923910'; 
  UPDATE CECRED.TBDOMIC_LIQTRANS_ARQUIVO SET NMARQUIVO_GERADO = null, DHARQUIVO_GERADO = null , NMARQUIVO_RETORNO = null, DHARQUIVO_RETORNO = NULL WHERE IDARQUIVO = '923911';    
    commit;
  
  update cecred.craplau lau set 
  lau.insitlau = 1,
  lau.dtdebito = NULL,
  lau.dscritic = NULL
  where substr(lau.cdseqtel, 1, 21) in (
  select pdv.NRLIQUIDACAO from tbdomic_liqtrans_pdv pdv
  where pdv.idcentraliza IN (SELECT idcentraliza
                            FROM tbdomic_liqtrans_centraliza
                           WHERE idlancto IN (SELECT idlancto
                                                FROM tbdomic_liqtrans_lancto
                            WHERE IDARQUIVO IN (923724,923725,923751,923752,923764,923765,923780,923781,923799,923800,923819,923820,923831,
                            923832,923846,923847,923860,923861,923888, 923889,923910,923911))));
                            
  commit;
end; 
