BEGIN

	INSERT INTO credito.tbcred_pronampe_retremessa
		(NRREMESSA, TPREGISTRO, CDRETORNO, DTPROCESSAMENTO, IDCONTRATO, VLFINANCIADO, DTRECUPERACAO, VLRECUPERADO, DTCANCELAMENTO, DTDEVOLUCAO, CDPENDENCIAOP, CDSITUACAOOP, DTULTSALDOOP, DTVENCIMENTOOP, DTINIPENDENCIAOP, CDENCERRAMENTOOP, DTENCERRAMENTOOP, CDIMPUGNACAOOP, DTIMPUGNACAOOP, CDMOVIMENTACAOFI, DTMOVIMENTACAOFI, DTFATOGERADORFI, VLNOMIFATOGERFI, VLATUALMONETARFI, VLISSQNFI, VLLIQUIDOMOVFI, NRCAUSADORMOVFI)
	VALUES
		(419, '03', '0', to_date('14-03-2024 08:00:27', 'dd-mm-yyyy hh24:mi:ss'), 5115817, 0.00, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

    INSERT INTO credito.tbcred_pronampe_retremessa
		(NRREMESSA, TPREGISTRO, CDRETORNO, DTPROCESSAMENTO, IDCONTRATO, VLFINANCIADO, DTRECUPERACAO, VLRECUPERADO, DTCANCELAMENTO, DTDEVOLUCAO, CDPENDENCIAOP, CDSITUACAOOP, DTULTSALDOOP, DTVENCIMENTOOP, DTINIPENDENCIAOP, CDENCERRAMENTOOP, DTENCERRAMENTOOP, CDIMPUGNACAOOP, DTIMPUGNACAOOP, CDMOVIMENTACAOFI, DTMOVIMENTACAOFI, DTFATOGERADORFI, VLNOMIFATOGERFI, VLATUALMONETARFI, VLISSQNFI, VLLIQUIDOMOVFI, NRCAUSADORMOVFI)
	VALUES
		(419, '03', '0', to_date('14-03-2024 08:00:27', 'dd-mm-yyyy hh24:mi:ss'), 5115813, 0.00, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

    INSERT INTO credito.tbcred_pronampe_retremessa
		(NRREMESSA, TPREGISTRO, CDRETORNO, DTPROCESSAMENTO, IDCONTRATO, VLFINANCIADO, DTRECUPERACAO, VLRECUPERADO, DTCANCELAMENTO, DTDEVOLUCAO, CDPENDENCIAOP, CDSITUACAOOP, DTULTSALDOOP, DTVENCIMENTOOP, DTINIPENDENCIAOP, CDENCERRAMENTOOP, DTENCERRAMENTOOP, CDIMPUGNACAOOP, DTIMPUGNACAOOP, CDMOVIMENTACAOFI, DTMOVIMENTACAOFI, DTFATOGERADORFI, VLNOMIFATOGERFI, VLATUALMONETARFI, VLISSQNFI, VLLIQUIDOMOVFI, NRCAUSADORMOVFI)
	VALUES
		(419, '03', '0', to_date('14-03-2024 08:00:27', 'dd-mm-yyyy hh24:mi:ss'), 5115811, 0.00, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

	INSERT INTO credito.tbcred_pronampe_retremessa
		(NRREMESSA, TPREGISTRO, CDRETORNO, DTPROCESSAMENTO, IDCONTRATO, VLFINANCIADO, DTRECUPERACAO, VLRECUPERADO, DTCANCELAMENTO, DTDEVOLUCAO, CDPENDENCIAOP, CDSITUACAOOP, DTULTSALDOOP, DTVENCIMENTOOP, DTINIPENDENCIAOP, CDENCERRAMENTOOP, DTENCERRAMENTOOP, CDIMPUGNACAOOP, DTIMPUGNACAOOP, CDMOVIMENTACAOFI, DTMOVIMENTACAOFI, DTFATOGERADORFI, VLNOMIFATOGERFI, VLATUALMONETARFI, VLISSQNFI, VLLIQUIDOMOVFI, NRCAUSADORMOVFI)
	VALUES
		(419, '03', '0', to_date('14-03-2024 08:00:27', 'dd-mm-yyyy hh24:mi:ss'), 5115812, 0.00, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);	

	INSERT INTO credito.tbcred_pronampe_retremessa
		(NRREMESSA, TPREGISTRO, CDRETORNO, DTPROCESSAMENTO, IDCONTRATO, VLFINANCIADO, DTRECUPERACAO, VLRECUPERADO, DTCANCELAMENTO, DTDEVOLUCAO, CDPENDENCIAOP, CDSITUACAOOP, DTULTSALDOOP, DTVENCIMENTOOP, DTINIPENDENCIAOP, CDENCERRAMENTOOP, DTENCERRAMENTOOP, CDIMPUGNACAOOP, DTIMPUGNACAOOP, CDMOVIMENTACAOFI, DTMOVIMENTACAOFI, DTFATOGERADORFI, VLNOMIFATOGERFI, VLATUALMONETARFI, VLISSQNFI, VLLIQUIDOMOVFI, NRCAUSADORMOVFI)
	VALUES
		(419, '03', '0', to_date('14-03-2024 08:00:27', 'dd-mm-yyyy hh24:mi:ss'), 5115820, 0.00, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);	

	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		ROLLBACK;
END;