BEGIN
  DELETE FROM CECRED.crapprm prm
   WHERE prm.NMSISTEM = 'CRED'
     AND prm.CDCOOPER = 0
     AND prm.CDACESSO IN ('MLC_CRPS551', 'MLC_CRPS713');
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    SISTEMA.excecaoInterna(pr_compleme => 'PRJ0024441');
    ROLLBACK;
    RAISE;
END;