BEGIN
     insert into cecred.crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
     values ('CRED', 'DIVINSS', 'RELATORIO DE BENEFICIOS DIVERGENTES (INSS - SICREDI)', ' ', ' ', ' ', 999, 1211, 1, 827, 0, 0, 0, 0, 1, 1);

     insert into cecred.crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
     values ('CRED', 'DIVINSS', 'RELATORIO DE BENEFICIOS DIVERGENTES (INSS - SICREDI)', ' ', ' ', ' ', 999, 1211, 1, 827, 0, 0, 0, 0, 1, 2);

     insert into cecred.crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
     values ('CRED', 'DIVINSS', 'RELATORIO DE BENEFICIOS DIVERGENTES (INSS - SICREDI)', ' ', ' ', ' ', 999, 1211, 1, 827, 0, 0, 0, 0, 1, 3);

     insert into cecred.crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
     values ('CRED', 'DIVINSS', 'RELATORIO DE BENEFICIOS DIVERGENTES (INSS - SICREDI)', ' ', ' ', ' ', 999, 1211, 1, 827, 0, 0, 0, 0, 1, 4);

     insert into cecred.crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
     values ('CRED', 'DIVINSS', 'RELATORIO DE BENEFICIOS DIVERGENTES (INSS - SICREDI)', ' ', ' ', ' ', 999, 1211, 1, 827, 0, 0, 0, 0, 1, 5);

     insert into cecred.crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
     values ('CRED', 'DIVINSS', 'RELATORIO DE BENEFICIOS DIVERGENTES (INSS - SICREDI)', ' ', ' ', ' ', 999, 1211, 1, 827, 0, 0, 0, 0, 1, 6);

     insert into cecred.crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
     values ('CRED', 'DIVINSS', 'RELATORIO DE BENEFICIOS DIVERGENTES (INSS - SICREDI)', ' ', ' ', ' ', 999, 1211, 1, 827, 0, 0, 0, 0, 1, 7);

     insert into cecred.crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
     values ('CRED', 'DIVINSS', 'RELATORIO DE BENEFICIOS DIVERGENTES (INSS - SICREDI)', ' ', ' ', ' ', 999, 1211, 1, 827, 0, 0, 0, 0, 1, 8);

     insert into cecred.crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
     values ('CRED', 'DIVINSS', 'RELATORIO DE BENEFICIOS DIVERGENTES (INSS - SICREDI)', ' ', ' ', ' ', 999, 1211, 1, 827, 0, 0, 0, 0, 1, 9);

     insert into cecred.crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
     values ('CRED', 'DIVINSS', 'RELATORIO DE BENEFICIOS DIVERGENTES (INSS - SICREDI)', ' ', ' ', ' ', 999, 1211, 1, 827, 0, 0, 0, 0, 1, 10);

     insert into cecred.crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
     values ('CRED', 'DIVINSS', 'RELATORIO DE BENEFICIOS DIVERGENTES (INSS - SICREDI)', ' ', ' ', ' ', 999, 1211, 1, 827, 0, 0, 0, 0, 1, 11);

     insert into cecred.crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
     values ('CRED', 'DIVINSS', 'RELATORIO DE BENEFICIOS DIVERGENTES (INSS - SICREDI)', ' ', ' ', ' ', 999, 1211, 1, 827, 0, 0, 0, 0, 1, 12);

     insert into cecred.crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
     values ('CRED', 'DIVINSS', 'RELATORIO DE BENEFICIOS DIVERGENTES (INSS - SICREDI)', ' ', ' ', ' ', 999, 1211, 1, 827, 0, 0, 0, 0, 1, 13);

     insert into cecred.crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
     values ('CRED', 'DIVINSS', 'RELATORIO DE BENEFICIOS DIVERGENTES (INSS - SICREDI)', ' ', ' ', ' ', 999, 1211, 1, 827, 0, 0, 0, 0, 1, 14);

     insert into cecred.crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
     values ('CRED', 'DIVINSS', 'RELATORIO DE BENEFICIOS DIVERGENTES (INSS - SICREDI)', ' ', ' ', ' ', 999, 1211, 1, 827, 0, 0, 0, 0, 1, 15);

     insert into cecred.crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
     values ('CRED', 'DIVINSS', 'RELATORIO DE BENEFICIOS DIVERGENTES (INSS - SICREDI)', ' ', ' ', ' ', 999, 1211, 1, 827, 0, 0, 0, 0, 1, 16);

     insert into cecred.crapprg (NMSISTEM, CDPROGRA, DSPROGRA##1, DSPROGRA##2, DSPROGRA##3, DSPROGRA##4, NRSOLICI, NRORDPRG, INCTRPRG, CDRELATO##1, CDRELATO##2, CDRELATO##3, CDRELATO##4, CDRELATO##5, INLIBPRG, CDCOOPER)
     values ('CRED', 'DIVINSS', 'RELATORIO DE BENEFICIOS DIVERGENTES (INSS - SICREDI)', ' ', ' ', ' ', 999, 1211, 1, 827, 0, 0, 0, 0, 1, 17);

     insert into cecred.craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL)
     values (827, 1, 999, 'INSS - RELATORIO BENEFICIOS DIVERGENTES', 1, 'BENEFICIOS INSS', '132col', 0, 1, 'Diario', 1, 1, 1, ' ');

     insert into cecred.craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL)
     values (827, 1, 999, 'INSS - RELATORIO BENEFICIOS DIVERGENTES', 1, 'BENEFICIOS INSS', '132col', 0, 2, 'Diario', 1, 1, 1, ' ');

     insert into cecred.craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL)
     values (827, 1, 999, 'INSS - RELATORIO BENEFICIOS DIVERGENTES', 1, 'BENEFICIOS INSS', '132col', 0, 3, 'Diario', 1, 1, 1, ' ');

     insert into cecred.craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL)
     values (827, 1, 999, 'INSS - RELATORIO BENEFICIOS DIVERGENTES', 1, 'BENEFICIOS INSS', '132col', 0, 4, 'Diario', 1, 1, 1, ' ');

     insert into cecred.craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL)
     values (827, 1, 999, 'INSS - RELATORIO BENEFICIOS DIVERGENTES', 1, 'BENEFICIOS INSS', '132col', 0, 5, 'Diario', 1, 1, 1, ' ');

     insert into cecred.craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL)
     values (827, 1, 999, 'INSS - RELATORIO BENEFICIOS DIVERGENTES', 1, 'BENEFICIOS INSS', '132col', 0, 6, 'Diario', 1, 1, 1, ' ');

     insert into cecred.craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL)
     values (827, 1, 999, 'INSS - RELATORIO BENEFICIOS DIVERGENTES', 1, 'BENEFICIOS INSS', '132col', 0, 7, 'Diario', 1, 1, 1, ' ');

     insert into cecred.craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL)
     values (827, 1, 999, 'INSS - RELATORIO BENEFICIOS DIVERGENTES', 1, 'BENEFICIOS INSS', '132col', 0, 8, 'Diario', 1, 1, 1, ' ');

     insert into cecred.craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL)
     values (827, 1, 999, 'INSS - RELATORIO BENEFICIOS DIVERGENTES', 1, 'BENEFICIOS INSS', '132col', 0, 9, 'Diario', 1, 1, 1, ' ');

     insert into cecred.craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL)
     values (827, 1, 999, 'INSS - RELATORIO BENEFICIOS DIVERGENTES', 1, 'BENEFICIOS INSS', '132col', 0, 10, 'Diario', 1, 1, 1, ' ');

     insert into cecred.craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL)
     values (827, 1, 999, 'INSS - RELATORIO BENEFICIOS DIVERGENTES', 1, 'BENEFICIOS INSS', '132col', 0, 11, 'Diario', 1, 1, 1, ' ');

     insert into cecred.craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL)
     values (827, 1, 999, 'INSS - RELATORIO BENEFICIOS DIVERGENTES', 1, 'BENEFICIOS INSS', '132col', 0, 12, 'Diario', 1, 1, 1, ' ');

     insert into cecred.craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL)
     values (827, 1, 999, 'INSS - RELATORIO BENEFICIOS DIVERGENTES', 1, 'BENEFICIOS INSS', '132col', 0, 13, 'Diario', 1, 1, 1, ' ');

     insert into cecred.craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL)
     values (827, 1, 999, 'INSS - RELATORIO BENEFICIOS DIVERGENTES', 1, 'BENEFICIOS INSS', '132col', 0, 14, 'Diario', 1, 1, 1, ' ');

     insert into cecred.craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL)
     values (827, 1, 999, 'INSS - RELATORIO BENEFICIOS DIVERGENTES', 1, 'BENEFICIOS INSS', '132col', 0, 15, 'Diario', 1, 1, 1, ' ');

     insert into cecred.craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL)
     values (827, 1, 999, 'INSS - RELATORIO BENEFICIOS DIVERGENTES', 1, 'BENEFICIOS INSS', '132col', 0, 16, 'Diario', 1, 1, 1, ' ');

     insert into cecred.craprel (CDRELATO, NRVIADEF, NRVIAMAX, NMRELATO, NRMODULO, NMDESTIN, NMFORMUL, INDAUDIT, CDCOOPER, PERIODIC, TPRELATO, INIMPREL, INGERPDF, DSDEMAIL)
     values (827, 1, 999, 'INSS - RELATORIO BENEFICIOS DIVERGENTES', 1, 'BENEFICIOS INSS', '132col', 0, 17, 'Diario', 1, 1, 1, ' ');

     COMMIT;
END;
